"""Accurate interview knowledge for devops track."""
from __future__ import annotations

from . import entry


def devops_topics() -> dict:
    E = entry
    T: dict = {}

    def add(name: str, *args):
        T[name] = E(*args)

    # --- Priority: Docker / containers ---
    add(
        "container image",
        "A container image is an immutable layered filesystem + config/metadata used to create containers.",
        "It packages an app with its runtime dependencies so it runs consistently across environments.",
        ["layers/digest", "base image", "entrypoint/cmd", "OCI format", "registry"],
        "Build produces layered tars hashed by content; run instantiates a writable container layer on top. Pull fetches by name:tag or digest from a registry.",
        "Fat images slow deploys and widen CVE surface; distroless/minimal images trade debug ease for security. Pin digests for reproducibility.",
        "Unexpected versions: you pulled :latest. Scan and pin digests. Debug with docker history and dive.",
        "docker build -t api:1.2 .\ndocker image ls\ndocker pull ghcr.io/org/api@sha256:…",
        "1) Define a standard base image. 2) Build in CI and push digests. 3) Scan on push. 4) Deploy by digest.",
    )
    add(
        "Dockerfile layer",
        "Dockerfile layers cache filesystem diffs from each instruction; ordering affects build-cache hit rates.",
        "Good layering makes rebuilds fast when only app code changes.",
        ["instruction → layer", "cache busting", "COPY package manifests first", "multi-stage", ".dockerignore"],
        "Docker executes instructions sequentially, reusing cached layers until an input changes. Put dependency install before COPY of source so code edits don't reinstall deps.",
        "Over-splitting layers can hurt pull size less than you'd think (squash exists elsewhere); clarity + cache locality matter most.",
        "Cache never hits: check changing ARG/COPY order and build context noise—use .dockerignore.",
        "COPY package.json package-lock.json ./\nRUN npm ci\nCOPY . .\nRUN npm run build",
        "1) Order Dockerfile for cache. 2) Add .dockerignore. 3) Use BuildKit cache in CI. 4) Measure build times.",
    )
    add(
        "multi-stage build",
        "Multi-stage Docker builds compile in a fat builder stage and copy artifacts into a slim runtime stage.",
        "It keeps final images small without shipping compilers/dev deps.",
        ["AS builder", "COPY --from", "runtime base", "secrets not in final", "cache mounts"],
        "First stage installs toolchains and builds; final stage starts FROM a minimal image and COPY --from=builder the binary/assets only.",
        "More stages add complexity; worthwhile when build tools dwarf runtime. Ensure glibc/musl compatibility for binaries.",
        "Missing files in final image: wrong COPY path/stage name. Debug by running the builder stage interactively.",
        "FROM golang:1.22 AS build\nWORKDIR /src\nCOPY . .\nRUN CGO_ENABLED=0 go build -o /out/api\nFROM gcr.io/distroless/static\nCOPY --from=build /out/api /api\nENTRYPOINT [\"/api\"]",
        "1) Split build vs runtime. 2) Copy only artifacts. 3) Scan final image. 4) Pin both bases by digest.",
    )
    add(
        "Docker Compose service",
        "A Compose service defines a containerized dependency (build/image, ports, env, networks, volumes) for local/dev stacks.",
        "It runs multi-container apps with one declarative file instead of ad-hoc docker run scripts.",
        ["services", "networks/DNS by service name", "volumes", "depends_on", "env_file"],
        "compose up creates network, starts services, and DNS-resolves service names. depends_on waits for start (not readiness unless healthchecks configured).",
        "Compose is not a production orchestrator—use Swarm/k8s for prod HA. Healthchecks matter for ordering.",
        "Cannot reach db: wrong network, hostname, or published vs internal ports. Use compose logs and exec.",
        "services:\n  api:\n    build: .\n    ports: [\"8080:8080\"]\n    environment: { DATABASE_URL: postgres://db:5432/app }\n  db:\n    image: postgres:16\n    volumes: [\"pg:/var/lib/postgresql/data\"]",
        "1) Model each process as a service. 2) Use internal DNS names. 3) Add healthchecks. 4) Keep secrets out of compose committed files.",
    )
    add(
        "bridge network",
        "A Docker bridge network is a software bridge connecting containers so they can communicate via private IPs and embedded DNS.",
        "User-defined bridges provide service-name DNS; the default bridge is more limited.",
        ["user-defined bridge", "embedded DNS", "published ports", "isolation", "external networks"],
        "Containers on the same user-defined network resolve each other by name. Publishing ports maps host→container for external access.",
        "Host networking skips isolation (Linux) for performance/special cases. Overlay networks span Swarm/k8s nodes differently.",
        "Name resolution fails on default bridge—attach a user-defined network. Port conflicts on host publishes.",
        "docker network create appnet\ndocker run -d --network appnet --name redis redis:7",
        "1) Create explicit networks per app. 2) Avoid legacy links. 3) Publish only needed ports. 4) Document inter-service hostnames.",
    )
    add(
        "image registry",
        "An image registry stores and serves container images (Docker Hub, ECR, GHCR, GCR) by repository and tag/digest.",
        "It is the distribution point between CI builds and runtime pulls.",
        ["repository", "tag vs digest", "auth/IAM", "immutability", "retention/GC"],
        "CI pushes image; clusters pull with credentials. Prefer digest pins in prod manifests. Retention policies garbage-collect old tags.",
        "Public registries risk rate limits; private registries add auth/ops. Mutable tags (:latest) undermine provenance.",
        "Pull denials: auth, IAM, or network policy. Verify digests match what CI pushed.",
        "docker tag api:1.2 123.dkr.ecr.region.amazonaws.com/api:1.2\ndocker push 123.dkr.ecr.region.amazonaws.com/api:1.2",
        "1) Use a private registry. 2) Push immutable tags+digests. 3) Restrict pull access. 4) Set retention and scanning.",
    )
    add(
        "volume",
        "A Docker/k8s volume provides durable or shared filesystem storage that outlives a container’s writable layer.",
        "It persists databases and uploads without baking data into images.",
        ["named volume", "bind mount", "persistence", "permissions/UID", "backup"],
        "Declare a volume and mount at a path; engine manages named volumes, bind mounts map host paths. Data remains after container removal for named volumes.",
        "Bind mounts are convenient locally but fragile in prod. Backing storage performance/IOPS matter for DBs.",
        "Permission errors: container user vs volume ownership. Lost data: volume not mounted or wrong name.",
        "docker volume create pgdata\ndocker run -v pgdata:/var/lib/postgresql/data postgres:16",
        "1) Use named volumes for stateful local deps. 2) Plan backups. 3) Align UIDs. 4) In k8s use PVCs.",
    )

    # --- Priority: Kubernetes ---
    add(
        "Kubernetes",
        "Kubernetes orchestrates containers by reconciling declared desired state for workloads, networking, and storage across a cluster.",
        "It standardizes deploy/scale/self-heal so you are not managing pets by SSH.",
        ["Pod/Deployment/Service", "control plane", "kubelet", "declarative API", "RBAC"],
        "You apply objects; controllers reconcile actual toward desired. Deployments manage Pods; Services route to Pods; kubelet runs probes.",
        "K8s complexity is real—managed control planes help. Not every app needs k8s; Compose/ECS can be enough early.",
        "CrashLoopBackOff: kubectl describe/logs. Pending: scheduling/resources/taints. Use events.",
        "kubectl apply -f deploy.yaml\nkubectl get pods -o wide\nkubectl rollout status deploy/api",
        "1) Start with Deployment+Service. 2) Add probes/resources. 3) GitOps manifests. 4) Enforce RBAC least privilege.",
    )
    add(
        "Pod",
        "A Pod is the smallest deployable unit in Kubernetes: one or more containers sharing network namespace and volumes.",
        "It colocates tightly coupled containers (app + sidecar) with a shared IP and storage volumes.",
        ["shared network/IPC", "containers", "restartPolicy", "ephemeral", "labels"],
        "Scheduler places the Pod on a node; kubelet starts containers. Pods are mortal—controllers recreate them. Prefer Deployments over naked Pods.",
        "Multi-container Pods couple lifecycle; prefer separate Pods unless sidecar pattern is required.",
        "Pending: resources/taints/PVC. ImagePullBackOff: registry auth/tag. Describe the Pod.",
        "kubectl run api --image=ghcr.io/org/api:1.2 --restart=Never\nkubectl describe pod api",
        "1) Run apps via Deployment. 2) Set resources. 3) Add readiness/liveness. 4) Label for Services.",
    )
    add(
        "Deployment",
        "A Deployment declares a desired replica count and Pod template, owning ReplicaSets for rolling updates.",
        "It provides declarative rollouts/rollbacks for stateless workloads.",
        ["replicas", "ReplicaSet", "rollingUpdate", "revision history", "maxUnavailable/maxSurge"],
        "Changing the Pod template creates a new ReplicaSet and rolls Pods gradually. kubectl rollout undo reverts to a prior revision.",
        "StatefulSets fit sticky identity/storage. DaemonSets fit per-node agents. Jobs fit finite tasks.",
        "Rollout stuck: readiness failing or progressDeadline. Check rollout status and events.",
        "kubectl set image deploy/api api=ghcr.io/org/api:1.3\nkubectl rollout undo deploy/api",
        "1) Manage apps with Deployments. 2) Tune rolling parameters. 3) Gate on readiness. 4) Alert on stuck rollouts.",
    )
    add(
        "Service",
        "A Kubernetes Service provides a stable virtual IP/DNS name load-balancing to matching Pods via selectors.",
        "Pods are ephemeral; Services give clients a consistent endpoint.",
        ["ClusterIP", "NodePort/LoadBalancer", "selectors/labels", "endpoints", "kube-proxy/dataplane"],
        "Service selects Pods by labels; Endpoints/EndpointSlices track ready Pods. ClusterIP is internal; LoadBalancer provisions external IP in cloud.",
        "ClusterIP is default for east-west. Exposing everything publicly increases attack surface.",
        "No endpoints: label mismatch or not Ready. Debug with kubectl get endpoints and describe.",
        "apiVersion: v1\nkind: Service\nmetadata: { name: api }\nspec:\n  selector: { app: api }\n  ports: [{ port: 80, targetPort: 8080 }]",
        "1) Label Pods consistently. 2) Add Service per app. 3) Use Ingress/Gateway for HTTP. 4) Monitor empty endpoints.",
    )
    add(
        "ClusterIP",
        "ClusterIP is the default Service type: a virtual IP reachable only inside the cluster.",
        "It exposes services safely for internal traffic without a public address.",
        ["internal VIP", "DNS name", "iptables/IPVS/eBPF", "east-west traffic"],
        "kube-proxy or dataplane DNAT ClusterIP:port to a ready Pod. DNS name service.namespace.svc.cluster.local resolves to ClusterIP.",
        "Need external access? Use Ingress/LoadBalancer/NodePort carefully. Headless Services (None) return Pod IPs for stateful patterns.",
        "Timeouts: NetworkPolicy, wrong port, or no ready endpoints.",
        "kubectl get svc api -o wide\nkubectl run tmp --rm -it --image=busybox -- wget -qO- http://api",
        "1) Default to ClusterIP. 2) Front with Ingress for HTTP. 3) Restrict with NetworkPolicy. 4) Test DNS from a debug Pod.",
    )
    add(
        "ConfigMap",
        "A ConfigMap stores non-secret configuration as key/value data injectable as env vars or files.",
        "It separates config from images so the same artifact runs in multiple environments.",
        ["data keys", "envFrom", "volume mount", "immutable ConfigMaps", "not for secrets"],
        "Create ConfigMap; reference in Pod spec. Mounted files update depending on kubelet sync; env vars typically need Pod restart.",
        "Secrets belong in Secret/KMS—not ConfigMaps. Huge configs better as files than thousands of env vars.",
        "App sees old config: env vars not hot-reloaded—roll Pods. Typo in key names.",
        "kubectl create configmap api-config --from-literal=LOG_LEVEL=info",
        "1) Move env into ConfigMaps. 2) Mount files for complex config. 3) Roll Deployments on change. 4) Keep secrets elsewhere.",
    )
    add(
        "secret",
        "A Kubernetes Secret stores sensitive key/values (base64 in etcd by default) for credentials and keys.",
        "It keeps passwords/tokens out of images and ConfigMaps.",
        ["Opaque/TLS types", "mount vs env", "RBAC", "encryption at rest", "external secret managers"],
        "Create Secret; mount as volume or env. Enable encryption at rest and tight RBAC. Prefer CSI/external managers for strong security.",
        "Secrets in env can leak via process dumps; file mounts with restricted perms are often better. Still not as strong as vaults alone.",
        "Pull failures: wrong key or RBAC. Audit who can get secrets.",
        "kubectl create secret generic db --from-literal=password='…'",
        "1) Enable encryption at rest. 2) Restrict Secret RBAC. 3) Prefer external KMS/SealedSecrets/ESO. 4) Rotate regularly.",
    )
    add(
        "readiness probe",
        "A readiness probe tells Kubernetes when a container is ready to receive traffic; failing removes Pod from Service endpoints.",
        "It prevents routing to Pods still starting or overloaded.",
        ["httpGet/tcpSocket/exec", "initialDelaySeconds", "failureThreshold", "vs liveness", "endpoints"],
        "kubelet probes periodically; on failure, Endpoints controller drops the Pod from Services until success returns.",
        "Liveness restarts; readiness only cuts traffic. Misusing liveness for readiness causes restart storms.",
        "Flapping readiness: check dependencies and timeouts. Align probe path with real health.",
        "readinessProbe:\n  httpGet: { path: /readyz, port: 8080 }\n  periodSeconds: 5",
        "1) Implement /readyz checking critical deps. 2) Configure readiness on Deployments. 3) Keep liveness separate. 4) Alert on not-ready replicas.",
    )
    add(
        "resource request",
        "A CPU/memory request is the guaranteed amount used by the scheduler for placement decisions.",
        "It enables predictable packing and avoids scheduling onto nodes that cannot meet guarantees.",
        ["requests vs limits", "millicores", "QoS classes", "bin packing", "overcommit"],
        "Scheduler sums requests to find a fit. Burstable QoS occurs when requests < limits. Set requests from measured usage.",
        "Requests too high waste capacity; too low cause noisy-neighbor contention. HPA often scales on utilization vs requests.",
        "Pending Pods: cluster lacks enough allocatable resources—scale nodes or shrink requests.",
        "resources:\n  requests: { cpu: \"100m\", memory: \"256Mi\" }\n  limits: { cpu: \"500m\", memory: \"512Mi\" }",
        "1) Measure p95 usage. 2) Set requests near steady-state. 3) Set memory limits carefully. 4) Review pending pods.",
    )
    add(
        "resource limits",
        "Limits cap the maximum CPU/memory a container may use; memory beyond limit OOMs the container.",
        "They protect nodes from a single runaway Pod.",
        ["memory OOMKill", "CPU throttling", "limit ≥ request", "QoS Guaranteed", "cgroups"],
        "cgroups enforce limits. CPU limit throttles; memory limit kills on exceed. Prefer accurate requests; limits especially for memory.",
        "Tight CPU limits create latency via throttling. Unbounded memory risks node instability.",
        "OOMKilled: raise memory or fix leak. Throttling: kubectl top / metrics-server; loosen CPU limit.",
        "kubectl describe pod … | grep -A5 Limits",
        "1) Always set memory limits for apps. 2) Use CPU limits judiciously. 3) Alert on throttling/OOM. 4) Load test.",
    )
    add(
        "HPA",
        "Horizontal Pod Autoscaler adjusts Deployment replicas based on metrics (CPU, memory, or custom).",
        "It matches capacity to load without manual scaling.",
        ["target utilization", "metrics-server", "min/max replicas", "cooldown/stabilization", "custom metrics"],
        "HPA controller compares current metrics to targets and scales replicas up/down within bounds, respecting stabilization windows.",
        "Without meaningful metrics, HPA oscillates. Scale-to-zero needs KEDA/serverless patterns.",
        "Not scaling: missing metrics-server or requests unset (utilization undefined). Check hpa describe.",
        "kubectl autoscale deploy/api --cpu-percent=70 --min=2 --max=10",
        "1) Set resource requests. 2) Install metrics-server. 3) Define min/max. 4) Load test scale behavior.",
    )
    add(
        "DaemonSet",
        "A DaemonSet runs a copy of a Pod on all (or selected) nodes—typical for agents/log collectors.",
        "It ensures node-level agents are present without manual per-node installs.",
        ["per-node Pod", "nodeSelector/affinity", "updates", "tolerations", "hostPath caution"],
        "Controller creates a Pod per matching node. Updates roll node agents. Tolerations allow scheduling on tainted nodes.",
        "Not for replicated app servers—use Deployments. hostPath has security implications.",
        "Missing nodes: taints without tolerations or selectors too narrow.",
        "kubectl get ds -A\nkubectl describe ds fluent-bit",
        "1) Deploy node agents as DaemonSets. 2) Add needed tolerations. 3) Restrict host mounts. 4) Monitor Ready nodes.",
    )
    add(
        "Job",
        "A Job runs Pods to completion for batch/finite tasks, retrying until backoffLimit or success.",
        "It models migrations, reports, and one-shot work better than long-running Deployments.",
        ["completions", "parallelism", "backoffLimit", "ttlAfterFinished", "CronJob"],
        "Job creates Pods until successful completions count is met. Failures retry. CronJob creates Jobs on a schedule.",
        "For continuous work use Deployments. Huge parallelism needs queue-based workers carefully.",
        "Jobs stuck: inspect Pod logs and backoff. Clean finished Jobs with TTL.",
        "kubectl create job migrate --from=cronjob/migrate\nkubectl logs job/migrate",
        "1) Put migrations in Jobs. 2) Set backoffLimit. 3) Add TTL cleanup. 4) Alert on failed Jobs.",
    )
    add(
        "PersistentVolume",
        "A PersistentVolume (PV/PVC) abstracts durable storage for Pods, binding claims to volumes provisioned statically or dynamically.",
        "It keeps data beyond Pod restarts for stateful workloads.",
        ["PVC", "StorageClass", "access modes", "reclaim policy", "binding"],
        "Pod mounts a PVC; provisioner creates a PV via StorageClass. AccessModes (RWO/RWX) constrain attach topology.",
        "RWO disks cannot multi-attach across nodes casually—use StatefulSets carefully. Snapshots/backups still required.",
        "Pending PVC: no matching StorageClass/capacity. Multi-attach errors on RWO.",
        "kubectl get pvc,pv\nkubectl describe pvc data",
        "1) Choose StorageClass. 2) Use PVCs in StatefulSets. 3) Plan backups. 4) Test restore.",
    )
    add(
        "NetworkPolicy",
        "NetworkPolicies restrict Pod ingress/egress traffic to allowed peers/ports (CNI-enforced).",
        "They implement least-privilege networking inside the cluster.",
        ["podSelector", "ingress/egress rules", "namespaceSelector", "default deny", "CNI support"],
        "On apply, CNI allows only matching traffic. Start with default-deny then open necessary paths.",
        "Without a supporting CNI, policies are no-ops—verify. Over-tight policies break DNS unless egress to kube-dns allowed.",
        "Timeouts after enabling: check DNS egress and labeled peers. Use network tools from ephemeral Pods.",
        "policyTypes: [Ingress, Egress]\npodSelector: { matchLabels: { app: api } }",
        "1) Confirm CNI supports policies. 2) Default deny in sensitive NS. 3) Allow DNS. 4) Expand gradually with tests.",
    )
    add(
        "RBAC",
        "Kubernetes RBAC authorizes users/service accounts via roles and bindings to API verbs on resources.",
        "It enforces least privilege on the control plane API.",
        ["Role/ClusterRole", "RoleBinding", "ServiceAccount", "verbs/resources", "aggregation"],
        "Subject authenticates; authorizer checks bindings for requested verb/resource/namespace. Prefer Role over ClusterRole when possible.",
        "Wildcards and cluster-admin are convenient and dangerous. Audit regularly.",
        "Forbidden errors: missing binding. Impersonation surprises: check SA used by Pods.",
        "kubectl auth can-i list pods --as=system:serviceaccount:dev:api",
        "1) Dedicated SA per app. 2) Minimal Roles. 3) Ban cluster-admin for apps. 4) Audit periodically.",
    )
    add(
        "taint/toleration",
        "Taints mark nodes so Pods won’t schedule unless they tolerate the taint; used for dedicated nodes and eviction effects.",
        "They reserve nodes for special workloads (GPU, system) and control NoSchedule/NoExecute behavior.",
        ["NoSchedule", "PreferNoSchedule", "NoExecute", "tolerationSeconds", "dedicated pools"],
        "Add taint to node; only Pods with matching toleration schedule. NoExecute can evict running non-tolerating Pods.",
        "Over-tainting leaves Pods pending. Prefer affinity for soft preferences sometimes.",
        "Pending with untolerated taint: add toleration or untaint. Describe Pod events.",
        "kubectl taint nodes node1 dedicated=ml:NoSchedule\n# Pod: tolerations: [{ key: dedicated, value: ml, effect: NoSchedule }]",
        "1) Taint special node pools. 2) Add matching tolerations only to intended workloads. 3) Document pool purpose.",
    )
    add(
        "control plane",
        "The Kubernetes control plane (API server, etcd, scheduler, controllers) manages cluster state and reconciliation.",
        "Worker nodes run workloads; control plane makes the decisions and stores desired state.",
        ["kube-apiserver", "etcd", "scheduler", "controller-manager", "HA etcd"],
        "kubectl talks to API server; objects persist in etcd; controllers/scheduler act on changes. Managed k8s hosts this for you.",
        "Self-managing control planes is operationally heavy—prefer managed unless required.",
        "API latency/etcd issues affect all ops—monitor control plane SLOs separately.",
        "kubectl get --raw='/readyz?verbose'",
        "1) Use managed control plane if possible. 2) Monitor API/etcd health. 3) Limit API QPS from controllers. 4) Backup etcd if self-managed.",
    )
    add(
        "CrashLoopBackOff",
        "CrashLoopBackOff means a container repeatedly exits and kubelet backs off restart attempts.",
        "It signals the process cannot stay up—config, dependency, or crash bug.",
        ["restartPolicy", "exit code", "backoff", "liveness misconfig", "logs/events"],
        "kubelet restarts crashed containers with exponential backoff. Inspect previous logs and describe events to find root cause.",
        "Aggressive liveness probes can create crash loops on slow starts—tune or use startupProbe.",
        "kubectl logs --previous and describe. Check command/args/env and failing migrations.",
        "kubectl describe pod api-xxx\nkubectl logs api-xxx --previous",
        "1) Standardize log capture. 2) Add startupProbe. 3) Fail fast with clear exit errors. 4) Alert on crash loops.",
    )
    add(
        "CRD/operator",
        "CustomResourceDefinitions extend the Kubernetes API; operators are controllers that reconcile those custom resources.",
        "They encode operational knowledge (databases, certificates) as declarative APIs.",
        ["CRD schema", "controller reconcile", "status subresource", "finalizers", "Operator pattern"],
        "Install CRD; users apply CRs; operator watches and creates underlying Deployments/PVCs/etc., updating status.",
        "Operators add power and failure modes—prefer mature ones. Poor operators fight humans.",
        "Stuck CRs: finalizers or operator down. Check operator logs.",
        "kubectl get crds\nkubectl explain mydb.spec",
        "1) Adopt operators cautiously. 2) Monitor operator health. 3) Pin operator versions. 4) Document CR runbooks.",
    )

    # --- Priority: Linux ---
    add(
        "Linux filesystem hierarchy",
        "The Linux FHS places configs in /etc, variable data in /var, homes in /home, temp in /tmp, and kernel/process APIs in /proc.",
        "Knowing the layout speeds debugging and keeps packaging predictable.",
        ["/etc config", "/var logs/state", "/home", "/tmp ephemeral", "/proc /sys"],
        "Apps read config from /etc, write logs/spools under /var, and expose runtime info via /proc. Containers often remount these intentionally.",
        "Distros vary slightly; containers may be minimal without full FHS. Don't store critical state only in /tmp.",
        "Disk full in /var: rotate logs. Missing configs: wrong path or ConfigMap mount.",
        "ls /etc /var /home /tmp /proc | head\ndu -sh /var/* 2>/dev/null | sort -h | tail",
        "1) Follow FHS in packaging. 2) Mount /var for stateful hosts. 3) Monitor /var disk. 4) Treat /proc as API not disk.",
    )
    add(
        "file permissions",
        "Linux file permissions use user/group/other bits (rwx) plus ownership; modes like 644/755 are common.",
        "They enforce least privilege on files and executables.",
        ["owner/group/other", "chmod/chown", "umask", "directories need x", "capabilities/ACL"],
        "Permission checks use effective uid/gid. Directories require execute to traverse. umask sets default create masks.",
        "ACLs add finer control; root bypasses most checks. In containers, UIDs map to host—align volumes.",
        "EACCES: wrong owner/mode. Diagnose with namei -l and id.",
        "ls -l file\nchmod 640 file; chown app:app file\nnamei -l /var/app/data",
        "1) Run services as non-root. 2) Tighten modes. 3) Align volume UIDs. 4) Audit world-writable paths.",
    )
    add(
        "filesystem inode",
        "An inode stores a file’s metadata (size, perms, pointers to data blocks); directories map names→inode numbers.",
        "Inode exhaustion can prevent new files even when disk space remains.",
        ["metadata vs data", "df -i", "hard links", "small-file workloads"],
        "Creating a file allocates an inode and directory entry. Many tiny files can exhaust inodes on ext filesystems.",
        "Some filesystems scale inodes differently; object stores avoid inode limits.",
        "‘No space’ with free bytes: df -i. Clean temp/small-file piles.",
        "df -h; df -i",
        "1) Monitor inode usage. 2) Avoid millions of tiny files in one FS. 3) Separate volumes for such workloads.",
    )
    add(
        "process",
        "A Linux process is a running program with PID, memory map, FDs, and threads scheduled by the kernel.",
        "Process tools (ps, top, /proc) are primary for host debugging.",
        ["PID/PPID", "states R/S/D/Z", "signals", "nice", "cgroups"],
        "Fork/exec create processes; they block on I/O (S), run (R), uninterruptible wait (D), or zombie (Z) until waited. Signals control lifecycle.",
        "Containers isolate processes via namespaces/cgroups but share a kernel.",
        "Zombies: parent not reaping. D-state: disk/NFS issues. Use ps and /proc.",
        "ps aux --sort=-%cpu | head\ncat /proc/$(pgrep -n sshd)/status | head",
        "1) Supervise with systemd/k8s. 2) Handle signals for graceful shutdown. 3) Alert on zombies/D-state spikes.",
    )
    add(
        "systemd",
        "systemd is the Linux init system managing services via unit files, dependencies, and journals.",
        "It replaces ad-hoc init scripts with declarative start/stop/restart and logging.",
        ["unit files", "WantedBy/After", "systemctl", "journald", "restart policies"],
        "systemctl start enables execution per unit; dependencies order boot. Logs go to journalctl. Restart=on-failure for crash recovery.",
        "Not all distros/containers use systemd. For containers prefer foreground processes under orchestrators.",
        "Failed units: systemctl status and journalctl -u. Remember daemon-reload after unit edits.",
        "systemctl status nginx\njournalctl -u nginx -n 100 --no-pager\nsudo systemctl daemon-reload",
        "1) Package apps as units. 2) Set Restart and limits. 3) Ship journal/log shipping. 4) Reload after changes.",
    )
    add(
        "signal",
        "Unix signals notify processes asynchronously (SIGTERM, SIGKILL, SIGINT) for shutdown and control.",
        "Graceful shutdown depends on handling SIGTERM before SIGKILL.",
        ["SIGTERM vs SIGKILL", "SIGINT", "SIGHUP reload", "handlers", "PID 1 in containers"],
        "Kernel delivers signals; processes handle or default-terminate. Orchestrators send SIGTERM then wait then SIGKILL. In containers, PID 1 must reap and handle signals (tini).",
        "SIGKILL cannot be caught—use only as last resort. Ignoring SIGTERM causes slow kills and data risk.",
        "App ignores shutdown: trap signals or use init. Check docker stop grace period.",
        "kill -TERM <pid>\n# in shell scripts: trap 'cleanup' TERM INT",
        "1) Handle SIGTERM in apps. 2) Use proper init in containers. 3) Tune terminationGracePeriodSeconds. 4) Test rolling stops.",
    )
    add(
        "swap",
        "Swap extends RAM onto disk; when memory pressure hits, pages move to swap, slowing access dramatically.",
        "It can prevent OOM at the cost of latency; many prod systems reduce or disable swap.",
        ["si/so", "swappiness", "latency risk", "OOM vs thrash"],
        "Kernel evicts cold pages to swap devices under pressure. High swap I/O (si/so) means thrashing.",
        "Databases often prefer OOM over surprise swap latency. Containers may have swap disabled.",
        "Latency spikes with free RAM seeming OK: check swap in/out. vmstat/si so.",
        "free -h; vmstat 1 5\nsudo sysctl vm.swappiness",
        "1) Decide swap policy per workload. 2) Alert on swap activity. 3) Size memory correctly. 4) Avoid swap for latency-critical DBs.",
    )
    add(
        "load average",
        "Load average is the exponential moving average of runnable (+ uninterruptible) tasks—rough system demand signal.",
        "It helps spot CPU saturation or disk wait piles, interpreted relative to CPU count.",
        ["1/5/15 minute avgs", "run queue", "compare to nproc", "D-state contribution"],
        "uptime reports load; compare to core count. High load with low CPU may be disk/network D-state tasks.",
        "Load alone lacks causality—pair with CPU%, iowait, and latency SLIs.",
        "Investigate with top/vmstat/iostat when load >> cores.",
        "uptime; nproc\nvmstat 1 5",
        "1) Chart load vs CPUs. 2) Correlate with latency. 3) Split CPU vs IO causes. 4) Scale or fix bottlenecks.",
    )
    add(
        "memory pressure",
        "Memory pressure means free memory is low and the kernel is reclaiming caches/swap or approaching OOM.",
        "It degrades performance and can kill processes via OOM killer.",
        ["available memory", "reclaim", "OOM killer", "cgroup limits", "working set"],
        "Watch MemAvailable, cgroup usage vs limit, and OOM events. Reduce caches, fix leaks, or raise limits/scale.",
        "Over-provisioning wastes money; under-provisioning causes kills. Measure working set under load.",
        "OOMKilled containers: kubectl describe / dmesg. Host pressure: free -h and psi if available.",
        "free -h\ncat /proc/pressure/memory 2>/dev/null",
        "1) Set container memory limits. 2) Alert on pressure/OOM. 3) Fix leaks. 4) Load test memory.",
    )
    add(
        "memory leak",
        "A memory leak retains unused memory (references or native allocs) until RSS grows without bound.",
        "It eventually causes OOM, thrashing, or eviction.",
        ["retained references", "native leaks", "heap profiles", "RSS vs heap", "restart mitigation"],
        "Profile heap to find retained paths; watch RSS growth slope. Restarts mitigate but don't fix.",
        "Unbounded caches look like leaks—cap them. Language GC heaps vs native (off-heap) differ.",
        "Capture heap dump under load; compare baselines. Check cgroup OOM events.",
        "# Node example mindset: clinic heap / --inspect heap snapshot\n# Go: pprof heap",
        "1) Cap caches. 2) Continuous RSS graphs. 3) Profile before paging. 4) Fix root cause, not only restart.",
    )
    add(
        "high CPU",
        "High CPU means processes saturate cores, increasing latency and load average.",
        "It signals hot loops, tight polls, or insufficient capacity.",
        ["user vs system CPU", "hot threads", "profiling", "throttling", "noisy neighbors"],
        "Identify top PIDs (top/pidstat), profile (perf/pprof), fix algorithmic hotspots or scale out. Distinguish GC/system time.",
        "CPU limits in containers throttle before node saturation. Scale horizontally when work is parallel.",
        "Correlate with deploy times. Use flame graphs for sustained highs.",
        "top -H -p <pid>\nperf top -p <pid>  # if available",
        "1) Alert on CPU saturation. 2) Profile hot paths. 3) Fix or scale. 4) Review limit throttling.",
    )
    add(
        "Bash strict mode",
        "Bash strict mode commonly means set -euo pipefail (and often IFS) to fail fast on errors, unset vars, and pipeline failures.",
        "It prevents scripts from continuing after silent failures.",
        ["set -e", "set -u", "pipefail", "IFS", "trap ERR"],
        "Enable at script top; handle expected nonzero exits explicitly. Use traps for cleanup.",
        "Strict mode can be surprising with pipelines/greps—set allowances carefully.",
        "Script exits early: check which command failed with -x tracing.",
        "#!/usr/bin/env bash\nset -euo pipefail\nIFS=$'\\n\\t'",
        "1) Template all scripts with strict mode. 2) CI-lint shell. 3) Add -x in debug. 4) Prefer Python for complex logic.",
    )
    add(
        "shell pipeline",
        "A shell pipeline connects stdout of one command to stdin of the next with | for compositional text processing.",
        "It enables powerful one-liners without temp files.",
        ["stdout→stdin", "exit codes + pipefail", "buffers", "xargs"],
        "Commands run concurrently connected by pipes. Without pipefail, pipeline status is last command only.",
        "Huge streams need care; prefer awk/SQL for heavy joins. Quoting matters.",
        "Wrong results: encoding/sort locale. Debug stages separately.",
        "cat access.log | awk '{print $1}' | sort | uniq -c | sort -nr | head",
        "1) Use pipefail. 2) Quote variables. 3) Break complex pipes into scripts. 4) Test on sample logs.",
    )

    # --- Priority: CI/CD ---
    add(
        "continuous integration",
        "CI automatically builds and tests every change to keep the main branch integrable and green.",
        "It catches breakages early and reduces merge hell.",
        ["pipeline on PR", "fast feedback", "required checks", "artifacts", "cache"],
        "Push/PR triggers workflows: checkout, build, test, lint. Failures block merge. Cache dependencies by lockfile hash.",
        "Slow/flaky CI reduces trust—invest in stability. CD builds on CI artifacts.",
        "Flakes: quarantine with owners. Cache misses: verify keys.",
        "on: [pull_request]\njobs:\n  build:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: npm ci && npm test",
        "1) Require CI on protected branches. 2) Keep under ~10–15 min. 3) Kill flakes. 4) Cache deps.",
    )
    add(
        "continuous delivery",
        "Continuous delivery keeps software releasable so deploying to prod is a routine, automated, low-risk action.",
        "It shortens lead time from commit to production value.",
        ["releasable main", "automated deploy", "approvals/environments", "rollback", "progressive delivery"],
        "CI produces artifacts; CD pipelines deploy to staging/prod with gates. Feature flags and canaries reduce risk.",
        "Continuous deployment auto-goes to prod; continuous delivery ensures you could. Choose based on risk appetite.",
        "Failed deploys: artifact mismatch, config drift, health checks. Keep one-click rollback.",
        "# promote the same image digest staging → prod",
        "1) Deploy same artifact across envs. 2) Automate smoke tests. 3) Add rollback. 4) Measure lead time.",
    )
    add(
        "workflow",
        "A GitHub Actions workflow is a YAML-defined automation triggered by events, containing jobs and steps.",
        "It encodes CI/CD and repo automation as code.",
        ["on: triggers", "jobs", "steps", "runners", "permissions"],
        "Event triggers workflow; jobs run on runners (possibly parallel); steps execute actions/commands. Least-privilege permissions recommended.",
        "Reusable workflows reduce duplication. Self-hosted runners need hardening.",
        "Pending jobs: runner labels/availability. Secrets: check environments.",
        "name: ci\non: { pull_request: { branches: [main] } }\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps: [{ uses: actions/checkout@v4 }, { run: make test }]",
        "1) Put workflows in .github/workflows. 2) Pin action versions. 3) Restrict permissions. 4) Require for merges.",
    )
    add(
        "runner",
        "A runner is the machine/VM that executes CI jobs (GitHub-hosted or self-hosted).",
        "Job capacity and isolation depend on runner pools.",
        ["hosted vs self-hosted", "labels", "ephemeral runners", "scaling", "security"],
        "Orchestrator assigns jobs to matching-labeled runners; they checkout and execute steps. Ephemeral runners reduce persistence risk.",
        "Self-hosted is cheaper/heavier and must be locked down. Hosted is simpler with limits.",
        "Queueing: scale runners or reduce job time. Dirty workspaces: prefer clean ephemeral.",
        "runs-on: ubuntu-latest\n# or: [self-hosted, linux, x64, gpu]",
        "1) Prefer hosted until scale demands. 2) Harden self-hosted. 3) Use ephemeral where possible. 4) Monitor queue time.",
    )
    add(
        "reusable workflow",
        "Reusable workflows are callable workflow YAMLs that centralize shared CI/CD logic across repos.",
        "They reduce copy-paste drift in org pipelines.",
        ["workflow_call", "inputs/outputs", "secrets: inherit", "versioning"],
        "Caller uses jobs.<id>.uses: org/repo/.github/workflows/x.yml@ref with inputs. Pin refs for stability.",
        "Over-centralizing creates bottlenecks—version carefully. Actions vs reusable workflows solve different reuse levels.",
        "Breakages cascade—canary the reusable workflow version.",
        "jobs:\n  ci:\n    uses: org/platform/.github/workflows/node-ci.yml@v3\n    with: { node-version: '20' }",
        "1) Extract common CI. 2) Version tags. 3) Document inputs. 4) Roll forward deliberately.",
    )
    add(
        "pipeline artifact",
        "Pipeline artifacts are build outputs (binaries, images, reports) stored for later jobs/deploys.",
        "They ensure the same bits tested are the bits deployed.",
        ["upload/download", "image digests", "retention", "provenance", "immutable artifacts"],
        "Build job uploads artifact or pushes image digest; deploy job consumes that exact artifact—not a rebuild.",
        "Rebuilding per environment risks drift. Retain enough history for rollback audits.",
        "Missing artifacts: expired retention or wrong names. Verify digests.",
        "- uses: actions/upload-artifact@v4\n  with: { name: web-dist, path: dist/ }",
        "1) Publish artifacts once. 2) Deploy by digest. 3) Set retention. 4) Sign critical artifacts.",
    )
    add(
        "build cache",
        "CI build caches store dependencies/intermediate build outputs keyed by lockfiles to speed pipelines.",
        "They cut wall-clock time and registry load.",
        ["cache keys", "lockfile hash", "layer cache", "remote cache", "invalidation"],
        "On hit, restore cache before install/build; on miss, populate. Key by OS + lockfile hash. Docker BuildKit cache exports similarly.",
        "Stale caches can hide bugs—periodically clean. Never cache secrets.",
        "Low hit rate: unstable keys or matrix sprawl. Inspect key computation.",
        "- uses: actions/cache@v4\n  with:\n    path: ~/.npm\n    key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}",
        "1) Cache package dirs. 2) Key by lockfiles. 3) Enable BuildKit cache. 4) Monitor hit rates.",
    )
    add(
        "merge",
        "Merging integrates a completed branch into the target (often via PR squash/merge/rebase strategies).",
        "Controlled merges protect main while integrating reviewed work.",
        ["PR checks", "squash vs merge commit", "CODEOWNERS", "required reviews", "linear history"],
        "CI green + approvals → merge strategy updates main. Branch protection enforces rules.",
        "Squash simplifies history; merge commits preserve branch topology. Pick one org standard.",
        "Blocked merges: failing checks or rulesets. Resolve conflicts locally first.",
        "gh pr merge --squash\ngit pull --ff-only",
        "1) Protect main. 2) Require CI+reviews. 3) Standardize merge style. 4) Delete merged branches.",
    )

    # Continue remaining devops topics with accurate (slightly denser) entries
    rest = {
        "Auto Scaling": (
            "Auto Scaling adds/removes instances based on metrics so capacity tracks demand.",
            "It improves availability and cost efficiency versus static fleets.",
            ["scaling policies", "metrics/thresholds", "cooldown", "health checks", "min/desired/max"],
            "Cloud service watches metrics (CPU/ALB requests); when thresholds breach, it launches/terminates instances in the group and registers with the load balancer.",
            "Reactive scaling lags spikes; schedule + predictive help. Misconfigured health checks churn instances.",
            "Flapping: widen thresholds/cooldowns. Not scaling: IAM, metrics gaps, or wrong ASG attachment.",
            "aws autoscaling describe-auto-scaling-groups --query 'AutoScalingGroups[].AutoScalingGroupName'",
            "1) Put instances behind LB in an ASG. 2) Scale on meaningful SLI proxies. 3) Set min≥2 for HA. 4) Load test.",
        ),
        "CloudWatch": (
            "CloudWatch is AWS’s monitoring service for metrics, logs, and alarms on AWS resources and custom app metrics.",
            "It provides the basic observability plane for AWS-native stacks.",
            ["metrics", "alarms", "log groups", "dashboards", "retention"],
            "Agents/services emit metrics/logs; you alarm on thresholds and route to SNS. Custom metrics via PutMetricData/EMF.",
            "Prometheus may fit multi-cloud/k8s better; CloudWatch is integrated and simple for AWS.",
            "Missing metrics: namespaces/dimensions wrong or no permissions. High cost: verbose logs—sample/filter.",
            "aws cloudwatch put-metric-alarm --alarm-name high-cpu --metric-name CPUUtilization --namespace AWS/EC2 --threshold 80 --comparison-operator GreaterThanThreshold --evaluation-periods 2 --statistic Average --period 60 --dimensions Name=InstanceId,Value=i-…",
            "1) Define golden signals. 2) Create alarms to paging. 3) Centralize logs. 4) Cap retention.",
        ),
        "EC2": (
            "EC2 provides resizable virtual machines (instances) in AWS with chosen AMI, size, network, and storage.",
            "It is the general-purpose compute building block for lift-and-shift and custom runtimes.",
            ["AMI", "instance types", "EBS", "security groups", "IMDSv2"],
            "Launch from AMI into a subnet with SG/IAM role; user data bootstraps. Prefer SSM over SSH when possible.",
            "Lambda/Fargate reduce ops for many apps; EC2 wins for specialized kernels/GPUs/long processes.",
            "Unreachable: SG/NACL/route. Use instance connect/SSM. Check status checks.",
            "aws ec2 describe-instances --filters Name=tag:Name,Values=api --query 'Reservations[].Instances[].InstanceId'",
            "1) Standardize AMIs. 2) Use IAM roles not keys. 3) Force IMDSv2. 4) Autoscale when needed.",
        ),
        "ELB/ALB": (
            "Elastic Load Balancing (ALB/NLB/CLB) distributes traffic across targets; ALB is L7 HTTP-aware.",
            "It enables HA, TLS termination, and path-based routing.",
            ["listeners", "target groups", "health checks", "TLS certs", "idle timeout"],
            "Client hits listener; ALB routes by rules to healthy targets in target groups. Health checks remove bad targets.",
            "NLB for L4/extreme performance; ALB for HTTP routing. Mis-healthchecks cause outages.",
            "5xx: bad targets or timeouts. Check target health and SG between ALB and instances.",
            "aws elbv2 describe-target-health --target-group-arn …",
            "1) Place ALB public/private intentionally. 2) Tune health checks. 3) Attach ASG. 4) Alert on unhealthy hosts.",
        ),
        "IAM user": (
            "An IAM user is a long-lived AWS identity with access keys/passwords—generally discouraged for apps vs roles.",
            "Users exist for humans/break-glass; workloads should use roles.",
            ["access keys", "policies", "MFA", "least privilege", "prefer roles"],
            "Attach policies to user/group; humans use console with MFA; avoid embedding access keys in servers.",
            "Roles with temporary creds are safer for apps. SSO federation beats many IAM users.",
            "Leaked keys: deactivate immediately, cloudtrail review. Rotate and prefer roles.",
            "aws iam list-access-keys --user-name alice",
            "1) Human users via SSO. 2) MFA everywhere. 3) No static keys on servers. 4) Audit unused credentials.",
        ),
        "Internet Gateway": (
            "An Internet Gateway (IGW) is a VPC component that enables bidirectional Internet connectivity for resources with public IPs.",
            "Without an IGW and correct routes, public subnets cannot reach/be reached from the Internet.",
            ["VPC attachment", "public routes 0.0.0.0/0", "public IP/EIP", "vs NAT Gateway"],
            "Attach IGW to VPC; route public subnet 0.0.0.0/0 to IGW; assign public IPs. Private subnets use NAT for egress only.",
            "NAT Gateway provides outbound-only for private subnets. Don't put data stores in public subnets casually.",
            "No Internet: missing IGW route, public IP, or NACL/SG. Trace route tables.",
            "aws ec2 describe-route-tables --filters Name=vpc-id,Values=vpc-…",
            "1) Attach one IGW per VPC. 2) Route only public subnets to IGW. 3) Prefer private+NAT for apps. 4) Lock SGs.",
        ),
        "NAT": (
            "A NAT Gateway/instance allows private-subnet egress to the Internet without accepting inbound connections.",
            "It lets private instances pull packages/APIs while remaining non-public.",
            ["private route to NAT", "EIP", "AZ HA", "conntrack limits", "cost"],
            "Private subnet route 0.0.0.0/0 → NAT in a public subnet; NAT SNAT outbound. Use per-AZ NATs for HA.",
            "NAT costs money and can bottleneck; VPC endpoints reduce need for AWS API egress.",
            "Egress fails: wrong route, SG, or NAT down. Check CloudWatch NAT metrics.",
            "# route: 0.0.0.0/0 → nat-gateway-id for private subnet",
            "1) Place NAT in public subnet. 2) Point private routes to it. 3) Multi-AZ for prod. 4) Prefer endpoints for AWS APIs.",
        ),
        "RDS": (
            "RDS is AWS managed relational databases (Postgres/MySQL/etc.) handling patching, backups, and Multi-AZ failover options.",
            "It reduces undifferentiated DB operations versus self-managed EC2 databases.",
            ["engine versions", "Multi-AZ", "automated backups", "parameter groups", "security groups"],
            "Provision instance/cluster in private subnets; apps connect via endpoint; Multi-AZ sync standby for failover; backups enable PITR.",
            "Aurora vs RDS trade cost/features. Superuser access limited vs self-managed.",
            "Connectivity: SG/DNS. Failover: DNS tip; use retries. Storage full alerts.",
            "aws rds describe-db-instances --query 'DBInstances[].Endpoint'",
            "1) Private subnets only. 2) Enable Multi-AZ for prod. 3) Automate parameter changes carefully. 4) Test failover.",
        ),
        "Route 53": (
            "Route 53 is AWS DNS: public/private hosted zones, health checks, and routing policies (weighted/failover/latency).",
            "It controls how names resolve for users and internal services.",
            ["hosted zones", "records", "TTL", "alias to AWS targets", "routing policies"],
            "Create zone/records; set TTL; Alias records point to ALB/CloudFront without IPv4 management. Health checks drive failover policies.",
            "External DNS can work too; Route 53 integrates with AWS targets. Low TTL helps failover but increases queries.",
            "Stale DNS after cutover: TTL caches. Compare dig results globally.",
            "aws route53 list-resource-record-sets --hosted-zone-id Z…",
            "1) Manage zones as code. 2) Plan TTLs before migrations. 3) Use health-checked failover. 4) Monitor query fails.",
        ),
        "S3": (
            "S3 is durable object storage for blobs with buckets, keys, versioning, and IAM policies.",
            "It stores backups, static assets, data lakes, and artifacts cheaply at scale.",
            ["bucket/key", "versioning", "SSE encryption", "IAM/bucket policies", "lifecycle"],
            "PutObject stores by key; GET retrieves. Use least-privilege IAM, block public access by default, lifecycle to IA/Glacier.",
            "Not a POSIX filesystem—no partial append semantics like disks. Cross-region replication for DR.",
            "AccessDenied: policy/KMS. Unexpected public: audit ACLs/policies.",
            "aws s3 cp file.zip s3://my-bucket/path/file.zip",
            "1) Block public access. 2) Encrypt. 3) Version critical buckets. 4) Lifecycle + monitoring.",
        ),
        "VPC": (
            "A VPC is an isolated virtual network in AWS with CIDRs, subnets, route tables, and gateways.",
            "It is the foundation for placing compute and controlling network paths.",
            ["CIDR", "subnets", "route tables", "IGW/NAT", "endpoints"],
            "Create VPC+subnets across AZs; attach IGW/NAT; place resources; use SGs/NACLs. Endpoints reach AWS APIs privately.",
            "Overlapping CIDRs break peering/VPN. Plan ranges early.",
            "No connectivity: routes/SG/NACL/DNS. Use Reachability Analyzer.",
            "aws ec2 describe-vpcs --query 'Vpcs[].CidrBlock'",
            "1) Plan non-overlapping CIDRs. 2) Multi-AZ subnets. 3) Private apps. 4) Codify in Terraform.",
        ),
        "public subnet": (
            "A public subnet has a route to an Internet Gateway and typically assigns public IPs to instances.",
            "It hosts Internet-facing load balancers/bastions—not databases.",
            ["IGW route", "auto-assign public IP", "vs private subnet", "minimize blast radius"],
            "Route table 0.0.0.0/0 → IGW. Prefer placing only LBs/NAT there; apps in private subnets.",
            "Public EC2 increases attack surface—prefer private + LB.",
            "Instances lack Internet: missing public IP or IGW route.",
            "# public subnet route: destination 0.0.0.0/0 → igw-…",
            "1) Mark subnets clearly. 2) Only edge components public. 3) Strict SGs. 4) Monitor exposed ports.",
        ),
        "security group": (
            "A security group is a stateful virtual firewall around AWS ENIs allowing explicit inbound/outbound rules.",
            "It is the primary microservice network control in AWS.",
            ["allow rules only", "stateful", "by SG reference", "least privilege", "vs NACL"],
            "Attach SG to ENI; add least-privilege ports from specific CIDRs/SGs. Responses allowed automatically (stateful).",
            "NACLs are stateless subnet-level. Prefer SG references over wide CIDRs.",
            "Timeouts: missing ingress on server or egress on client. Diff rules in console/IaC.",
            "aws ec2 authorize-security-group-ingress --group-id sg-… --protocol tcp --port 5432 --source-group sg-app",
            "1) Default deny inbound. 2) Reference SGs. 3) Manage via IaC. 4) Regular rule audits.",
        ),
        "region": (
            "An AWS Region is a geographic area of isolated Availability Zones; choose for latency, data residency, and DR.",
            "Resources are regional; cross-region needs explicit replication.",
            ["AZ isolation", "data residency", "latency", "cross-region DR", "service availability"],
            "Deploy into a region; use multiple AZs for HA. Replicate to another region for DR if required.",
            "Multi-region is powerful and costly/complex. Start multi-AZ single region.",
            "Wrong region in CLI: configure profile. Service missing in region: check docs.",
            "aws configure get region\naws ec2 describe-availability-zones",
            "1) Pick primary region. 2) Multi-AZ. 3) Document DR region strategy. 4) Pin region in IaC.",
        ),
        "IaaS": (
            "IaaS provides virtualized compute/storage/network building blocks you configure (VMs, disks, VPCs).",
            "It maximizes control versus PaaS/SaaS while shifting more ops onto you.",
            ["VMs", "you manage OS/runtime", "vs PaaS/FaaS", "shared responsibility"],
            "Provision VMs/networks; you patch OS and run apps. Cloud still manages hardware/hypervisor.",
            "PaaS faster for apps; IaaS for custom networking/OS. Mix via containers on IaaS.",
            "Ownership gaps cause vulnerabilities—clarify patch duties.",
            "# EC2+EBS+VPC is classic IaaS",
            "1) Decide IaaS vs PaaS per component. 2) Automate patching. 3) Codify infra. 4) Apply CIS baselines.",
        ),
        "Infrastructure as Code": (
            "IaC defines infrastructure in versioned declarative code (Terraform/CloudFormation) applied repeatedly.",
            "It makes environments reproducible and reviewable.",
            ["declarative desired state", "plan/apply", "state", "modules", "drift"],
            "Write configs; plan shows diff; apply mutates cloud APIs; state tracks ownership.",
            "ClickOps drifts from code—import or recreate. Huge monoliths of IaC hurt; modularize.",
            "State conflicts: use remote state locking. Unexpected destroys: careful plan review.",
            "terraform plan\nterraform apply",
            "1) Put all prod infra in IaC. 2) PR reviews for plans. 3) Remote state+lock. 4) CI plan on PR.",
        ),
    }
    for name, args in rest.items():
        add(name, *args)

    more = {
        "idempotence": (
            "Idempotence means applying an operation multiple times yields the same result without unintended duplicates.",
            "It makes automation safe to retry under failure.",
            ["same end state", "retries", "unique keys", "Terraform/Ansible mindset"],
            "Design APIs/automation so repeats are no-ops or reinforce desired state (create-if-not-exists).",
            "True perfect idempotence can be hard with side effects—use idempotency keys.",
            "Duplicates after retry: missing keys/constraints.",
            "# HTTP: PUT /users/42 with full body is more idempotent than POST /users",
            "1) Prefer declarative tools. 2) Add unique constraints. 3) Idempotency keys for payments. 4) Retry safely.",
        ),
        "inventory": (
            "Ansible inventory lists hosts/groups and variables defining automation targets.",
            "It scopes playbooks to the right machines.",
            ["hosts/groups", "static vs dynamic", "host vars", "group vars"],
            "Inventory provides connection info; playbooks select hosts. Dynamic inventory pulls from cloud APIs.",
            "Dynamic scales better for cloud churn; static is simple for labs.",
            "Wrong hosts changed: check group patterns and limits.",
            "ansible -i inventory.ini web -m ping",
            "1) Source inventory dynamically in cloud. 2) Separate env inventories. 3) Limit by group. 4) Audit vars.",
        ),
        "role": (
            "An Ansible role packages tasks, handlers, templates, and defaults into a reusable unit.",
            "It modularizes playbooks for shareable configuration.",
            ["tasks/handlers", "defaults/vars", "templates", "dependencies"],
            "Playbooks include roles; roles apply tasks idempotently and notify handlers on change.",
            "Roles vs collections: collections distribute broader content. Keep roles focused.",
            "Unexpected changes: var precedence. Use --check and diff.",
            "ansible-galaxy init roles/nginx",
            "1) Extract repeated tasks into roles. 2) Version roles. 3) Test with molecule if possible. 4) Pin versions.",
        ),
        "backup": (
            "Backups copy data so you can restore after loss/corruption; they must be tested.",
            "They are the last line of defense when replication isn't enough (logical bugs).",
            ["RPO/RTO", "full/incremental", "offsite", "restore tests", "encryption"],
            "Schedule backups; store offsite/immutable; periodically restore to verify. Align with RPO/RTO.",
            "Snapshots ≠ complete DR without application consistency. Replication doesn't protect against bad writes.",
            "Restore fails: missing credentials or incomplete sets—practice restores.",
            "aws backup start-backup-job …  # or pg_dump/pg_basebackup depending on system",
            "1) Define RPO/RTO. 2) Automate backups. 3) Quarterly restore drills. 4) Monitor job failures.",
        ),
        "RPO": (
            "RPO (Recovery Point Objective) is the maximum acceptable data loss measured in time.",
            "It drives backup frequency and replication design.",
            ["data-loss tolerance", "backup interval", "replication lag", "vs RTO"],
            "If RPO is 5 minutes, you need continuous or frequent backups/replication within that lag.",
            "Tighter RPO costs more. Business sets RPO; engineering implements.",
            "Missed RPO: lagging replicas or failed backups—alert on lag/age.",
            "# RPO 15m → backups or sync every ≤15m with margin",
            "1) Get business RPO. 2) Implement accordingly. 3) Alert on backup age/lag. 4) Document per system.",
        ),
        "canary deployment": (
            "Canary deployment releases a new version to a small traffic slice before full rollout.",
            "It limits blast radius while gathering real-user signal.",
            ["traffic split", "metrics gate", "automatic rollback", "progressive delivery"],
            "Deploy canary instances; shift 1–5% traffic; watch errors/latency; promote or abort.",
            "Requires good metrics and traffic splitting (mesh/LB). Feature flags are an alternative.",
            "False confidence: insufficient traffic. Bad metrics: wrong SLIs.",
            "# FLB weighted target groups or service mesh traffic split",
            "1) Define success SLIs. 2) Automate canary analysis. 3) Instant rollback path. 4) Start with low %.",
        ),
        "rollback": (
            "Rollback reverts to a prior known-good version/config after a bad deploy.",
            "It is the fastest mitigation when forward-fix would take too long.",
            ["previous artifact", "DB migrate compatibility", "fast path", "feature flags"],
            "Redeploy prior image/manifest revision; ensure schema is backward compatible or use expand/contract migrations.",
            "Some failures need forward fixes (bad data migrations). Practice rollbacks.",
            "Rollback broken: incompatible migrations—design expand/contract.",
            "kubectl rollout undo deploy/api\nhelm rollback myapp 1",
            "1) Keep prior artifacts. 2) Compatible migrations. 3) One-command rollback. 4) Game-day practice.",
        ),
        "rolling deployment": (
            "Rolling deployment replaces instances gradually with the new version while keeping service available.",
            "It avoids full downtime of big-bang replaces.",
            ["batch size", "readiness gates", "maxUnavailable", "surge"],
            "Take down/replace a subset, wait healthy, continue. Orchestrators encode surge/unavailable parameters.",
            "Canaries add safety; blue/green doubles capacity. Slow rolls prolong mixed versions.",
            "Stuck rolls: failing readiness. Pause and inspect.",
            "kubectl rollout status deploy/api",
            "1) Use readiness probes. 2) Tune surge/unavailable. 3) Monitor during roll. 4) Abort on SLI breach.",
        ),
        "health check": (
            "Health checks probe whether an instance should receive traffic or be replaced.",
            "They keep load balancers and orchestrators honest about readiness.",
            ["liveness vs readiness", "shallow vs deep", "timeouts", "dependency checks"],
            "LB/orchestrator calls HTTP/TCP endpoint; failures remove/restart targets. Keep checks cheap and accurate.",
            "Deep checks can cascade outages if they depend on downstreams—prefer shallow + separate ready.",
            "Flapping: loosen thresholds. Always-unhealthy: wrong path/port.",
            "curl -fsS http://127.0.0.1:8080/healthz",
            "1) Implement /healthz and /readyz. 2) Wire to LB/k8s. 3) Avoid expensive dependency fanout. 4) Alert on failing checks.",
        ),
        "GitOps": (
            "GitOps uses Git as the source of truth for desired cluster/app state, continuously reconciled by an agent.",
            "It provides auditability and consistent delivery.",
            ["desired state in Git", "reconciler (Argo/Flux)", "drift detection", "PR changes"],
            "Commit manifests; controller applies and reverts drift. Changes go through PR review.",
            "Secrets need sealing/ESO. Not every infra change fits pure GitOps.",
            "Out-of-sync: check controller logs and Git permissions.",
            "argocd app sync myapp  # conceptual",
            "1) Store manifests in Git. 2) Install reconciler. 3) Protect main. 4) Monitor sync status.",
        ),
        "OpenTofu": (
            "OpenTofu is an open-source Terraform fork for declarative infrastructure provisioning with HCL and providers.",
            "It provides community-governed IaC compatible with Terraform workflows.",
            ["providers", "state", "plan/apply", "modules", "lockfile"],
            "Write HCL; init providers; plan; apply; state tracks resources. Remote backends + locking for teams.",
            "Terraform Cloud vs OpenTofu/CLI trade support models. Pin provider versions.",
            "State lock stuck: release carefully after ensuring no apply running.",
            "tofu init && tofu plan",
            "1) Standardize on OpenTofu or Terraform. 2) Remote state. 3) CI plans. 4) Module versioning.",
        ),
        "plan": (
            "terraform/tofu plan computes the diff between desired config and state without applying.",
            "It is the safety review step before mutating cloud resources.",
            ["refresh", "diff add/change/destroy", "saved plan", "policy checks"],
            "plan refreshes state, walks graph, prints actions. Review destroys carefully; apply exact saved plan in CI.",
            "Plans can be stale if state changes underneath—lock and apply promptly.",
            "Unexpected destroys: renamed resources without moved blocks.",
            "terraform plan -out=tf.plan\nterraform show tf.plan",
            "1) Require plan artifacts in PRs. 2) Human review destroys. 3) Apply saved plans. 4) Use `moved` blocks.",
        ),
        "state": (
            "Terraform/OpenTofu state maps configuration addresses to real cloud resource IDs.",
            "Without state, tools cannot reliably update or destroy the right resources.",
            ["resource mapping", "remote backend", "sensitive values", "drift"],
            "After apply, state stores IDs/attributes. Remote state (S3+Dynamo, etc.) enables teams.",
            "Never hand-edit casually. Sensitive data in state needs encrypted backends.",
            "Orphan resources: state lost—import or adopt. Drift: refresh/plan.",
            "terraform state list",
            "1) Remote encrypted state. 2) Restrict access. 3) Backup state. 4) Avoid manual edits.",
        ),
        "state locking": (
            "State locking prevents concurrent applies from corrupting Terraform state.",
            "It serializes mutations across teammates/CI.",
            ["DynamoDB lock", "lock timeout", "force unlock caution"],
            "Backend acquires lock before plan/apply; others wait/fail. Force-unlock only if process is dead.",
            "Local state lacks safe team locking—don't use for prod teams.",
            "Stuck lock: verify no runner active then unlock.",
            "# S3 backend with dynamodb_table for locks",
            "1) Enable locking backend. 2) CI uses same backend. 3) Never unlock blindly. 4) Alert on long locks.",
        ),
        "remote state": (
            "Remote state stores Terraform state in shared durable storage (S3, GCS, Terraform Cloud).",
            "It enables collaboration and state locking.",
            ["backend config", "encryption", "versioning", "access control"],
            "Configure backend; terraform init migrates; team shares one state per workspace carefully.",
            "One state per environment/app boundary—avoid mega-states.",
            "AccessDenied: IAM on backend. Enable versioning for recovery.",
            "terraform {\n  backend \"s3\" {\n    bucket = \"tf-state\"\n    key = \"prod/app.tfstate\"\n    dynamodb_table = \"tf-locks\"\n  }\n}",
            "1) Create encrypted versioned bucket. 2) Configure backend. 3) Lock table. 4) Limit IAM read/write.",
        ),
        "module": (
            "A Terraform module is a reusable packaged set of resources with inputs/outputs.",
            "It standardizes patterns (VPC, ECS service) across environments.",
            ["source/version", "variables/outputs", "composition", "interfaces"],
            "Root module calls child modules with variables; outputs feed other modules. Pin module versions.",
            "Over-abstracted modules become opaque. Start concrete, extract later.",
            "Version drift: pin and renovate intentionally.",
            "module \"vpc\" {\n  source = \"git::https://…//modules/vpc?ref=v1.2.0\"\n  cidr = \"10.0.0.0/16\"\n}",
            "1) Extract repeated infra. 2) Semantic-version modules. 3) Document inputs. 4) Test examples.",
        ),
        "resource": (
            "A Terraform resource block declares one infrastructure object managed by a provider.",
            "Resources are the atomic units of IaC desired state.",
            ["type/name", "arguments", "dependencies", "lifecycle"],
            "Provider maps resource to API calls create/read/update/delete. Implicit deps via references; explicit depends_on rarely.",
            "Data sources read without owning. Avoid provisioners when possible.",
            "Replace cycles: understand force-new attributes.",
            "resource \"aws_s3_bucket\" \"logs\" {\n  bucket = \"my-logs-prod\"\n}",
            "1) One logical object per resource. 2) Use lifecycle guards. 3) Prefer managed attrs over local-exec. 4) Review force-new diffs.",
        ),
        "import": (
            "terraform import adopts an existing cloud object into state under a resource address.",
            "It brings ClickOps resources under IaC without recreate.",
            ["address", "id", "generate config", "drift after import"],
            "Write matching config; import ID into state; plan until clean. Newer workflows can generate config.",
            "Import doesn't change cloud—only state. Mis-import mismanages resources.",
            "Plans want destroy/recreate: attributes mismatch—align config.",
            "terraform import aws_s3_bucket.logs my-logs-prod",
            "1) Write config first. 2) Import. 3) Plan to zero. 4) Commit.",
        ),
        "drift": (
            "Drift is when real infrastructure differs from IaC desired state due to manual changes or out-of-band edits.",
            "It causes surprises on next apply and undermines audits.",
            ["manual change", "refresh/plan", "prevent ClickOps", "detection"],
            "Detect via periodic plans or drift tools; reconcile by apply or updating code. Lock down console permissions.",
            "Some drift is inevitable (autoscaled counts)—ignore_changes selectively.",
            "Unexpected diffs: find who changed via CloudTrail.",
            "terraform plan -detailed-exitcode",
            "1) Limit console IAM. 2) Nightly plans. 3) ignore_changes only when justified. 4) Educate on GitOps/IaC.",
        ),
        "chart": (
            "A Helm chart packages Kubernetes manifests with templates and default values for installable apps.",
            "It standardizes deploying complex software to clusters.",
            ["Chart.yaml", "templates", "values", "releases", "hooks"],
            "helm install renders templates with values and applies. Upgrades revise release; rollback uses revision history.",
            "Kustomize is alternative without templating engine. Charts can hide risky defaults—read values.",
            "Failed release: helm status/logs. Values typos common.",
            "helm install myapp ./chart -f values-prod.yaml",
            "1) Vendor charts carefully. 2) Pin versions. 3) Manage values in Git. 4) Test upgrades.",
        ),
        "values": (
            "Helm values are configuration inputs that parameterize chart templates per environment.",
            "They keep one chart reusable across stages.",
            ["values.yaml", "overrides -f/--set", "schema", "secrets separation"],
            "Defaults ship in chart; env overlays override. Avoid --set for complex structures; use files.",
            "Secrets in values need sealing/SOPS—not plain Git.",
            "Wrong env deployed: check which values file. helm get values.",
            "helm upgrade myapp ./chart -f values-prod.yaml",
            "1) Layer values per env. 2) Validate schema. 3) Encrypt secrets. 4) Diff before upgrade.",
        ),
        "PromQL": (
            "PromQL is Prometheus’s query language for selecting and aggregating time-series metrics.",
            "It powers alerts and dashboards on golden signals.",
            ["selectors", "rate/increase", "sum by", "recording rules", "cardinality"],
            "Select series by labels; apply rate on counters; aggregate with sum/avg by. Keep label cardinality bounded.",
            "High cardinality explodes memory. Prefer recording rules for heavy queries.",
            "Empty graphs: label mismatch or scrape gaps.",
            "sum(rate(http_requests_total{status=~\"5..\"}[5m])) by (service)",
            "1) Define SLI queries. 2) Build alerts. 3) Control labels. 4) Use recording rules.",
        ),
        "scrape model": (
            "Prometheus primarily scrapes metrics from targets’ HTTP endpoints on an interval (pull model).",
            "It decentralizes instrumentation and simplifies target discovery.",
            ["/metrics", "scrape_interval", "service discovery", "labels", "pushgateway rare"],
            "Prometheus discovers targets, scrapes exposition format, stores samples. Apps expose /metrics.",
            "Push is exceptional (batch jobs via Pushgateway). Short-lived pods need careful discovery.",
            "Missing targets: SD/relabel config. Check /targets page.",
            "scrape_configs:\n  - job_name: api\n    static_configs: [{ targets: [\"api:8080\"] }]",
            "1) Expose /metrics. 2) Configure scrape jobs. 3) Use k8s SD. 4) Monitor scrape health.",
        ),
        "metric": (
            "A metric is a numeric time series measuring system behavior (counters, gauges, histograms).",
            "Metrics enable SLIs, capacity planning, and alerting.",
            ["counter/gauge/histogram", "labels", "cardinality", "units"],
            "Instrument code; export; scrape/store; query. Prefer RED/USE golden signals.",
            "Logs/traces complement metrics. Too many labels kill Prometheus.",
            "Weird spikes: check resets on counters—use rate().",
            "http_requests_total{path=\"/pay\",code=\"200\"} 1",
            "1) Agree on golden metrics. 2) Instrument services. 3) Bound labels. 4) Alert on SLIs.",
        ),
        "dashboard": (
            "Dashboards visualize metrics/logs for situational awareness during operations and incidents.",
            "They compress many signals into human-scanable views.",
            ["golden signals", "templating", "less is more", "link to runbooks"],
            "Build from SLIs first; template by service; avoid vanity charts. Prefer RED panels for request services.",
            "Dashboard sprawl confuses—curate tier-1 views.",
            "Empty panels: datasource permissions or label drift.",
            "# Grafana: rate(errors)/rate(requests) as error ratio panel",
            "1) Create service overview dashboards. 2) Standard variables. 3) Link alerts→panels. 4) Review quarterly.",
        ),
        "trace": (
            "Distributed traces follow a request across services via span context (OpenTelemetry/Jaeger/Zipkin).",
            "They diagnose latency attribution in microservice calls.",
            ["trace/span IDs", "context propagation", "sampling", "baggage", "tail-based sampling"],
            "Each service creates spans; propagates headers; backend assembles traces. Sample to control cost.",
            "100% sampling is expensive. Metrics still needed for SLOs.",
            "Broken traces: missing propagation headers across hops.",
            "# propagate traceparent (W3C) across HTTP calls",
            "1) Adopt OpenTelemetry SDKs. 2) Propagate context. 3) Sample wisely. 4) Tie traces to exemplars.",
        ),
        "instrumentation": (
            "Instrumentation adds metrics/logs/traces to code so systems are observable.",
            "Without it, incidents are guesswork.",
            ["OpenTelemetry", "RED metrics", "structured logs", "span attributes"],
            "Add SDK/auto-instrumentation; export to backends; standardize attributes (service.name).",
            "Too much instrumentation noise/cost—focus on user journeys.",
            "Missing data: exporter config/endpoints. Verify with a known request.",
            "from opentelemetry import trace\ntracer = trace.get_tracer(__name__)",
            "1) Standardize OTel. 2) Auto-instrument frameworks. 3) Add custom spans for critical paths. 4) Review cardinality.",
        ),
        "SLI": (
            "An SLI (Service Level Indicator) is a quantitative measure of user-facing reliability (availability, latency).",
            "It makes reliability measurable rather than anecdotal.",
            ["good/total events", "availability", "latency percentiles", "correctness"],
            "Define event and good predicate; compute ratio over window. Example: non-5xx requests / total.",
            "Vanity metrics aren't SLIs. Choose indicators users feel.",
            "SLI flat wrong: bad event definition or sampling bias.",
            "availability = sum(rate(requests{code!~\"5..\"}[5m])) / sum(rate(requests[5m]))",
            "1) Pick 1–3 SLIs per critical journey. 2) Implement queries. 3) Chart burn. 4) Review with product.",
        ),
        "SLO": (
            "An SLO (Service Level Objective) sets a target on an SLI over a window (e.g., 99.9% monthly).",
            "It balances feature velocity vs reliability via error budgets.",
            ["target %", "window", "error budget", "burn alerts"],
            "Choose target from user needs/cost; track compliance; alert on budget burn rate, not raw blips.",
            "Too tight SLOs stall delivery; too loose hide pain. Iterate.",
            "Chronic miss: invest in reliability or renegotiate SLO.",
            "# 99.9% monthly → ~43 minutes downtime budget",
            "1) Set SLOs with stakeholders. 2) Track budget. 3) Multi-window burn alerts. 4) Freeze risky launches when budget exhausted.",
        ),
        "error budget": (
            "Error budget is the allowed unreliability derived from an SLO (1 - objective) over the window.",
            "It quantifies how much risk/failure you can spend on change.",
            ["budget = 1-SLO", "burn rate", "policy when exhausted", "release decisions"],
            "Measure consumed budget from SLI; high burn triggers pages; exhausted budget pauses risky deploys.",
            "Budgets only work with enforcement culture. Don't reset silently.",
            "Unexpected burn: partial outages or bad SLI. Investigate.",
            "# burn rate 2× means budget depletes in half the window",
            "1) Compute budget. 2) Alert on burn. 3) Write policy. 4) Review monthly.",
        ),
        "toil": (
            "Toil is manual, repetitive, automatable operational work that scales with service size (SRE definition).",
            "Reducing toil frees engineering time for durable improvements.",
            ["manual/repetitive", "automatable", "no enduring value", "scales with growth"],
            "Track toil; automate runbooks; create self-service platforms. Measure on-call ticket types.",
            "Some ops work is necessary engineering—not all ops is toil.",
            "Rising ticket volume of same type: automate that class.",
            "# example: automating certificate renewal removes recurring pager toil",
            "1) Categorize on-call work. 2) Prioritize top toil. 3) Automate. 4) Set toil budget goals.",
        ),
        "incident triage": (
            "Incident triage rapidly assesses impact, severity, and next diagnostic steps under time pressure.",
            "It structures chaos into roles, communication, and mitigation.",
            ["severity", "severity", "mitigate vs root-cause", "comms", "timeline"],
            "Declare incident; assign IC; assess user impact; mitigate (rollback/scale); communicate; later investigate deeply.",
            "Premature deep debugging delays mitigation. Blameless culture improves signal.",
            "Floundering: lack of IC/roles. Use checklists.",
            "# severity rubric: SEV1 user-wide outage → page immediately",
            "1) Write severity definitions. 2) Train IC role. 3) Mitigation runbooks. 4) Postmortems.",
        ),
        "postmortem": (
            "A blameless postmortem documents what happened, impact, root causes, and corrective actions after an incident.",
            "It turns outages into systemic learning.",
            ["timeline", "contributing factors", "action items", "blameless", "follow-up"],
            "Gather timeline/metrics; analyze contributing causes; assign owners/dates for fixes; share widely.",
            "Without follow-up tracking, postmortems are theater.",
            "Repeated incidents: actions not done or wrong causes.",
            "# template: summary, impact, timeline, root causes, actions",
            "1) Mandatory for SEV1/2. 2) Blameless facilitation. 3) Track actions to close. 4) Share learnings.",
        ),
        "least privilege": (
            "Least privilege grants only the permissions required for a task—nothing more.",
            "It limits blast radius of breaches and mistakes.",
            ["scoped roles", "time-bound access", "avoid wildcards", "regular audits"],
            "Start from deny; add needed verbs/resources; prefer short-lived credentials; review periodically.",
            "Over-tight permissions slow delivery—use break-glass with audit.",
            "AccessDenied storms after tightening: iterate with logs.",
            "# IAM: Resource-specific ARNs over \"*\"",
            "1) Replace * policies. 2) Role per service. 3) JIT elevation. 4) Quarterly access reviews.",
        ),
        "secrets manager": (
            "A secrets manager stores and rotates credentials centrally (AWS Secrets Manager, Vault) with audited access.",
            "It removes secrets from code, images, and developer laptops.",
            ["storage", "rotation", "IAM/policies", "dynamic secrets", "audit logs"],
            "App fetches secret at runtime with identity; manager rotates and versions; old versions invalidated.",
            "Env vars still leak—prefer runtime fetch + short cache. Pandemic of secret sprawl needs inventory.",
            "Fetch failures: IAM or network endpoint. Cache carefully.",
            "aws secretsmanager get-secret-value --secret-id prod/db",
            "1) Move secrets out of Git. 2) Grant identity-based access. 3) Enable rotation. 4) Audit usage.",
        ),
        "SAST": (
            "SAST (static application security testing) analyzes source/bytecode for vulnerabilities without running the app.",
            "It catches injection, secrets, and insecure patterns early in CI.",
            ["pattern/dataflow analysis", "false positives", "CI gating", "language coverage"],
            "Scanner parses code; reports findings; triage severities; fix or suppress with justification.",
            "Noise kills adoption—tune rules. DAST/SCA complement SAST.",
            "Missed vulns: unsupported frameworks. Keep analyzers updated.",
            "# e.g. semgrep --config p/owasp-top-ten",
            "1) Add SAST in CI. 2) Gate on high severity. 3) Triage weekly. 4) Train on common findings.",
        ),
        "SBOM": (
            "An SBOM (Software Bill of Materials) lists components/dependencies in an artifact for vulnerability and license tracking.",
            "It answers “what’s in this image/binary?” during CVEs.",
            ["CycloneDX/SPDX", "dependency inventory", "CVE correlation", "provenance"],
            "Generate SBOM at build; store beside artifact; scan against CVE DBs; alert on critical hits.",
            "SBOM without process is unused data—wire to response playbooks.",
            "Missing deps: generator config. Re-generate every build.",
            "syft packages docker:api:1.2 -o cyclonedx-json > sbom.json",
            "1) Generate SBOM in CI. 2) Sign/store. 3) Scan continuously. 4) On CVE, query SBOMs.",
        ),
        "container scanning": (
            "Container scanning analyzes images for known CVEs in OS packages and app dependencies.",
            "It reduces shipping critically vulnerable images.",
            ["CVE DB", "base image risk", "severity gates", "fix vs rebuild"],
            "Scan on build and periodically in registry; fail CI on severity thresholds; rebuild from patched bases.",
            "Scanners have false positives; accept risk formally. Patching base images is highest leverage.",
            "Same CVE after rebuild: pin moved or app deps. Check digests.",
            "trivy image ghcr.io/org/api:1.2",
            "1) Scan in CI. 2) Block criticals. 3) Automate base updates. 4) Rescan stored images.",
        ),
        "image signing/provenance": (
            "Image signing and provenance attest that an image was built by a trusted pipeline from known source (cosign/SLSA).",
            "It mitigates supply-chain tampering and untrusted tags.",
            ["sigstore/cosign", "attestations", "policy admission", "keyless OIDC"],
            "CI signs digest; cluster admission verifies signature/attestation before run.",
            "Key management is hard—keyless OIDC helps. Unsigned legacy images need migration.",
            "Admission rejects: missing signature or wrong identity—check CI settings.",
            "cosign sign ghcr.io/org/api@sha256:…\ncosign verify …",
            "1) Sign in CI. 2) Enforce verify in cluster. 3) Prefer digests. 4) Document trusted identities.",
        ),
        "firewall": (
            "A firewall filters packets/connections by policy (host iptables/nftables, cloud SG/NACL, network appliances).",
            "It reduces attack surface by allowing only needed paths.",
            ["allowlists", "stateful vs stateless", "egress control", "logging"],
            "Define deny-by-default; open required ports between tiers; log drops for forensics.",
            "Over-complex rulesets become outage sources—keep simple tiers.",
            "Silent drops: check counters/logs. Change windows matter.",
            "sudo iptables -L -n | head\n# prefer nftables/ufw/SG IaC in modern setups",
            "1) Default deny. 2) Codify rules. 3) Log drops. 4) Review quarterly.",
        ),
        "subnetting": (
            "Subnetting divides IP space into networks for routing, isolation, and blast-radius control.",
            "It structures VPCs and on-prem networks.",
            ["CIDR math", "public/private", "routing", "growth planning"],
            "Allocate prefixes per tier/AZ; size for growth; document in IPAM. Avoid overlaps with partners.",
            "Too-small subnets force painful renumbering; too-large waste space and widen broadcast domains (L2).",
            "Overlap incidents: IPAM audit. Wrong mask: connectivity half-works.",
            "python3 - <<'PY'\nimport ipaddress\nprint(list(ipaddress.ip_network('10.0.0.0/16').subnets(new_prefix=24))[:3])\nPY",
            "1) Create IPAM plan. 2) Standard subnet sizes. 3) Encode in Terraform. 4) Reserve spare capacity.",
        ),
        "DNS": (
            "DNS maps names to records (A/AAAA/CNAME) used by apps and users to locate services.",
            "Most distributed systems fail when DNS is wrong or cached stale.",
            ["resolvers", "TTL", "authoritative zones", "health-check routing"],
            "Clients query resolvers; answers cache for TTL; cutovers must respect caches. Split-horizon serves different answers internally.",
            "Service discovery may supplement DNS (k8s, Consul). Low TTL vs query load trade-off.",
            "Stale answers: TTL. SERVFAIL: upstream. Use dig +trace.",
            "dig +short api.internal A\ndig SOA example.com",
            "1) Manage zones as code. 2) Plan TTL for changes. 3) Monitor resolution errors. 4) Document private zones.",
        ),
        "DNS outage": (
            "A DNS outage is when resolution fails or returns wrong data, breaking service discovery even if backends are healthy.",
            "It presents as widespread timeouts with healthy hosts.",
            ["resolver failure", "zone misconfig", "TTL traps", "dependency on external DNS"],
            "Triage: dig from multiple resolvers; check authoritative; roll back zone changes; lower blast via cached IPs only temporarily.",
            "Hardcoding IPs is a brittle mitigation. Multi-resolver and health-checked failover help.",
            "App errors without backend CPU: suspect DNS. Check /etc/resolv.conf and ndots in k8s.",
            "dig @8.8.8.8 example.com\ndig @1.1.1.1 example.com",
            "1) Redundant DNS. 2) Change control for zones. 3) Runbooks for rollback. 4) Synthetic DNS checks.",
        ),
        "TLS certificate": (
            "A TLS certificate binds a public key to identities (DNS names) and is trusted via a CA chain.",
            "It enables authenticated encryption for HTTPS and mTLS.",
            ["X.509", "SAN names", "chain of trust", "expiry", "ACMEautomation"],
            "Issue cert; install on LB/server; clients validate chain+hostname+expiry. Automate renewal (ACME).",
            "Long-lived certs increase risk; short-lived need reliable automation.",
            "Browser errors: name mismatch, incomplete chain, expired. openssl s_client debugs.",
            "echo | openssl s_client -connect example.com:443 -servername example.com 2>/dev/null | openssl x509 -noout -dates -ext subjectAltName",
            "1) Automate issuance/renewal. 2) Alert on expiry. 3) Serve full chain. 4) Use SAN for all names.",
        ),
        "TCP": (
            "TCP provides reliable ordered byte streams—used by most admin protocols and HTTP.",
            "Understanding TCP helps debug timeouts, resets, and performance.",
            ["handshake", "retransmit", "ports", "vs UDP"],
            "Connect via handshake; transfer with acks; close with FIN/RST. Firewalls must allow SYN paths.",
            "UDP for latency-sensitive/loss-tolerant. TLS wraps TCP commonly.",
            "Resets: SG/RST from app. Use ss/tcpdump carefully.",
            "ss -tanpi | head",
            "1) Set timeouts. 2) Monitor retransmits. 3) Keepalive thoughtfully. 4) Document required ports.",
        ),
        "virtual machine": (
            "A VM virtualizes hardware so a full guest OS runs isolated on a hypervisor.",
            "Cloud instances are VMs with API lifecycle.",
            ["hypervisor", "guest OS", "images", "isolation vs containers"],
            "Boot from image; attach disks/NICs; patch guest. Stronger isolation than containers sharing a kernel.",
            "Heavier than containers; slower density. Use for different kernels/strong tenancy.",
            "Console/serial helps when networking broken.",
            "# cloud: launch instance from hardened image",
            "1) Golden images. 2) Autopatch. 3) Prefer containers for apps when suitable. 4) Monitor host contention.",
        ),
        "upstream/load balancing": (
            "In reverse proxies (nginx), upstreams define backend server pools and load-balancing policy.",
            "They distribute requests and remove unhealthy backends.",
            ["upstream block", "least_conn/round_robin", "health checks", "retries"],
            "Proxy passes to upstream servers; weights and health determine selection. Timeouts prevent wedged backends hanging workers.",
            "Service meshes move some of this into sidecars. Keep timeouts aligned end-to-end.",
            "502/504: all upstreams down or timeouts—check upstream health.",
            "upstream api {\n  server 10.0.0.1:8080;\n  server 10.0.0.2:8080;\n}",
            "1) Define upstream pools. 2) Configure health checks. 3) Align timeouts. 4) Observe error rates.",
        ),
        "reverse proxy": (
            "A reverse proxy terminates client connections and forwards to internal backends (nginx, Envoy, ALB).",
            "It centralizes TLS, routing, compression, and security controls.",
            ["TLS termination", "routing", "buffering", "headers", "WAF optional"],
            "Client→proxy→backend. Proxy adds X-Forwarded-* carefully; backends trust only known proxies.",
            "Extra hop adds latency but simplifies certs and policy. Misconfigured buffering hurts streaming.",
            "Bad gateways: upstream down. Redirect loops: scheme/headers wrong.",
            "proxy_pass http://api;\nproxy_set_header Host $host;\nproxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
            "1) Terminate TLS at proxy. 2) Standardize forwarded headers. 3) Health-check backends. 4) Rate-limit edges.",
        ),
    }
    for name, args in more.items():
        add(name, *args)

    assert len(T) >= 100, len(T)
    return T
