"""Accurate interview knowledge for foundations, devops, database tracks."""
from __future__ import annotations

from . import entry, curated


def foundations_topics() -> dict:
    E = entry
    return {
        "BFS": E(
            "BFS explores a graph level by level using a queue, visiting nodes in order of distance from the start.",
            "It finds shortest paths in unweighted graphs and systematically explores neighbors before going deeper.",
            ["queue frontier", "visited set", "level-order / distance", "unweighted shortest path", "connected components"],
            "Enqueue the start node and mark visited. While the queue is not empty, dequeue u, process neighbors of u, and enqueue each unseen neighbor while recording parent/distance. Layers expand until the goal is found or the frontier empties.",
            "BFS uses more memory than DFS for wide frontiers; DFS may find a deep solution sooner but not the shortest unweighted path. Dijkstra/A* replace BFS when edges have weights.",
            "If BFS never finishes, check missing visited marks (infinite graphs/cycles) or exploding branching. If distances look wrong, verify you only enqueue on first visit and that the graph edges are correct.",
            "from collections import deque\ndef bfs(graph, start):\n    q, seen, dist = deque([start]), {start}, {start: 0}\n    while q:\n        u = q.popleft()\n        for v in graph[u]:\n            if v not in seen:\n                seen.add(v); dist[v] = dist[u] + 1; q.append(v)\n    return dist",
            "1) Model the domain as an adjacency list. 2) Implement BFS with explicit visited. 3) Unit-test distance on a tiny graph. 4) Cap queue size / depth for production safety.",
        ),
        "Big-O complexity": E(
            "Big-O describes an upper bound on how an algorithm's cost grows with input size n (asymptotic worst-case growth class).",
            "It lets you compare algorithms independently of machine speed and reject designs that blow up as data scales.",
            ["O(1)/O(log n)/O(n)/O(n log n)/O(n²)", "worst vs average case", "time vs space", "dominant term", "amortized analysis"],
            "Count dominant operations as n grows, drop constants and lower-order terms, and classify the growth. Nested loops over n often yield O(n²); halving search space each step yields O(log n).",
            "Big-O ignores constants that matter at small n and real caches/IO. Prefer Big-Theta when you mean tight bound; use profiling for hot paths where constants dominate.",
            "If production latency grows unexpectedly, measure with increasing n, check for hidden O(n²) (nested scans, N+1 queries), and confirm you are not measuring fixed overhead.",
            "# binary search O(log n) vs linear O(n)\ndef find(a, x):\n    lo, hi = 0, len(a) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if a[mid] == x: return mid\n        if a[mid] < x: lo = mid + 1\n        else: hi = mid - 1\n    return -1",
            "1) State complexity in design docs for hot paths. 2) Add a scale test with 10× data. 3) Fail CI if p95 exceeds budget after growth.",
        ),
        "binary search": E(
            "Binary search finds a target in a sorted array by repeatedly discarding half of the remaining range.",
            "It turns O(n) scans into O(log n) lookups when data is ordered and random-access.",
            ["sorted invariant", "lo/hi mid", "overflow-safe mid", "lower/upper bound", "monotonic predicates"],
            "While lo ≤ hi, compute mid, compare a[mid] to the target, and move lo or hi to shrink the half that cannot contain the answer. Generalize to binary search on a monotonic predicate (search the answer space).",
            "Requires sorted (or monotonic) data; sorting first may dominate. Prefer hash sets for exact membership when order is irrelevant and memory allows.",
            "Off-by-one bugs show as infinite loops or missed edges—trace lo/hi on a 2-element array. Confirm sort order and stable lower_bound semantics for duplicates.",
            "def lower_bound(a, x):\n    lo, hi = 0, len(a)\n    while lo < hi:\n        mid = (lo + hi) // 2\n        if a[mid] < x: lo = mid + 1\n        else: hi = mid\n    return lo",
            "1) Ensure data is kept sorted or indexed. 2) Use library binary search when available. 3) Add tests for empty, one element, duplicates, and missing values.",
        ),
        "divide and conquer": E(
            "Divide and conquer splits a problem into independent subproblems, solves them, then combines results (e.g., mergesort, quicksort, binary search).",
            "It unlocks O(n log n) sorting and parallelizable workloads by reducing problem size recursively.",
            ["divide", "conquer/recurse", "combine", "recurrence / Master theorem", "base case"],
            "Define a base case, partition input, recurse on parts, then merge. Mergesort divides then merges in linear time per level across log n levels.",
            "Recursion depth and combine cost can dominate; sometimes iterative DP or greedy is simpler. Quicksort’s average is great but worst-case is O(n²) without care.",
            "Stack overflows imply missing base cases or unbalanced splits. Wrong results usually come from incorrect combine logic—test on tiny inputs.",
            "def mergesort(a):\n    if len(a) <= 1: return a\n    m = len(a)//2\n    L, R = mergesort(a[:m]), mergesort(a[m:])\n    return merge(L, R)",
            "1) Write the recurrence and expected complexity. 2) Implement with clear base cases. 3) Compare against a known-good sort on random arrays.",
        ),
        "dynamic programming": E(
            "Dynamic programming solves overlapping subproblems with optimal substructure by memoizing or tabulating sub-results.",
            "It avoids exponential recompute in problems like knapsack, edit distance, and path counting.",
            ["optimal substructure", "overlapping subproblems", "memoization vs tabulation", "state definition", "transition"],
            "Define state (what a subproblem answers), base cases, and transitions. Either recurse with a cache (top-down) or fill a table in dependency order (bottom-up).",
            "DP uses extra memory and needs a correct state; greedy is simpler when a local choice is provably safe. Sometimes Dijkstra/BFS replaces DP on graphs.",
            "Wrong answers usually mean an incomplete state (missing a dimension) or iteration order bugs. Profile memory for large tables; compress state when possible.",
            "# Fibonacci bottom-up O(n) time O(1) space\ndef fib(n):\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a",
            "1) Write state/transition on paper. 2) Implement memoized recursion for clarity. 3) Convert hot paths to iterative tables. 4) Add property tests vs brute force on small n.",
        ),
        "sorting algorithms": E(
            "Sorting algorithms reorder elements by a key; common ones are mergesort, quicksort, heapsort, and timsort (used by Python).",
            "Sorted data enables binary search, ordered reports, and efficient merges of streams.",
            ["comparison sorts", "stability", "in-place vs not", "O(n log n) lower bound", "adaptive sorts"],
            "Comparison sorts repeatedly compare keys; mergesort is stable O(n log n); quicksort partitions around a pivot; Python’s timsort exploits runs. Counting/radix sorts beat O(n log n) for restricted keys.",
            "Stability matters when sorting by multiple keys. In-place quicksort saves memory but is not stable. For nearly sorted data, adaptive sorts win.",
            "If order looks wrong, check comparator consistency (must be a total order). For performance regressions, measure n and check you accidentally used O(n²) sort.",
            "rows.sort(key=lambda r: (r['last'], r['first']))  # stable multi-key in Python",
            "1) Prefer language built-ins. 2) Document stability needs. 3) Benchmark on production-shaped data before custom sorts.",
        ),
        "HTTP methods": E(
            "HTTP methods (GET, POST, PUT, PATCH, DELETE, HEAD, OPTIONS) define the intent of a request on a resource.",
            "They standardize safe/idempotent semantics so caches, proxies, and clients behave correctly.",
            ["safe vs unsafe", "idempotent", "GET retrieve", "POST create/action", "PUT replace", "PATCH partial", "DELETE remove"],
            "Client sends method + URL + headers/body. Servers route by method. GET/HEAD should not change state; PUT/DELETE are idempotent; POST often creates or triggers non-idempotent work.",
            "Misusing POST for everything breaks caching and retry safety. PUT vs PATCH depends on whether the client sends a full replacement or a partial update.",
            "Debug with curl -v: check method, status, and whether intermediaries strip bodies. Retries causing duplicates usually mean non-idempotent POST without idempotency keys.",
            "curl -i -X GET https://api.example.com/users/42\ncurl -i -X POST https://api.example.com/users -H 'Content-Type: application/json' -d '{\"name\":\"Ada\"}'",
            "1) Define resource URLs and method semantics in an OpenAPI spec. 2) Enforce in framework routing. 3) Add contract tests for idempotency on PUT/DELETE.",
        ),
        "HTTP caching": E(
            "HTTP caching stores responses so repeat requests can be served from cache using headers like Cache-Control, ETag, and Last-Modified.",
            "It cuts latency and origin load for cacheable GET responses.",
            ["Cache-Control", "ETag / If-None-Match", "Last-Modified", "private vs public", "vary"],
            "Origin sets freshness (max-age) and validators. Caches serve fresh responses; on revalidation a 304 avoids transferring the body. Vary selects the correct variant for different request headers.",
            "Aggressive caching can serve stale personalized data—use private for user-specific responses. Fine-grained invalidation is hard; prefer short TTL + ETag for dynamic APIs.",
            "If users see stale content, inspect Cache-Control/Age, CDN rules, and Vary. If origin is overloaded, check that GETs are actually cacheable and not accidentally no-store.",
            "Cache-Control: public, max-age=60\nETag: \"abc123\"\n# client revalidate:\n# If-None-Match: \"abc123\" → 304 Not Modified",
            "1) Classify endpoints as public/private. 2) Set Cache-Control + ETag on GETs. 3) Purge CDN on deploy for HTML. 4) Monitor cache hit ratio.",
        ),
        "TLS": E(
            "TLS (Transport Layer Security) encrypts and authenticates network connections so HTTP becomes HTTPS.",
            "It protects confidentiality and integrity against eavesdropping and tampering on the path.",
            ["handshake", "certificates / PKI", "server auth", "symmetric session keys", "forward secrecy"],
            "Client and server negotiate a cipher suite, server presents a certificate chain, client verifies it to a trust store, then both derive session keys and encrypt application data.",
            "TLS adds CPU and latency (mitigated by session resumption/HTTP/2). Certificate mismanagement causes outages. mTLS adds client certificates for service identity.",
            "Handshake failures: check clock skew, chain completeness, SNI hostname, and TLS version. Use openssl s_client to inspect the presented chain.",
            "openssl s_client -connect example.com:443 -servername example.com </dev/null 2>/dev/null | openssl x509 -noout -dates -subject",
            "1) Terminate TLS at a trusted edge. 2) Automate cert renewal (ACM/Let’s Encrypt). 3) Redirect HTTP→HTTPS and enable HSTS. 4) Alert on expiry within 14 days.",
        ),
        "TCP": E(
            "TCP is a reliable, ordered, connection-oriented transport protocol that provides streams with retransmission and congestion control.",
            "It is the default for HTTP, databases, and most apps that need all bytes delivered in order.",
            ["ports", "sequence/ack", "retransmission", "flow control", "congestion control", "connection state"],
            "After the three-way handshake, peers exchange segments with sequence numbers; lost data is retransmitted; receive windows prevent overrun; congestion control paces sends.",
            "TCP latency suffers from head-of-line blocking; UDP/QUIC may fit real-time or loss-tolerant workloads. Connection setup cost matters for tiny RPCs.",
            "Timeouts and resets: check firewalls, SYN floods, and half-open states with ss/netstat. Throughput issues often involve window size, packet loss, or bufferbloat.",
            "ss -tan | head\n# ESTAB shows established TCP sessions with local/remote addresses",
            "1) Prefer TCP libraries/HTTP stacks over raw sockets. 2) Set sane timeouts and retries. 3) Monitor retransmits and connection error rates.",
        ),
        "TCP three-way handshake": E(
            "The TCP three-way handshake (SYN, SYN-ACK, ACK) synchronizes sequence numbers and establishes a connection before data transfer.",
            "It prevents half-open confusion and agrees initial sequence numbers for reliable delivery.",
            ["SYN", "SYN-ACK", "ACK", "ISN", "LISTEN/SYN-SENT/ESTABLISHED"],
            "Client sends SYN with its ISN; server replies SYN-ACK with its ISN and ack; client sends ACK. Both sides then mark the connection ESTABLISHED.",
            "Handshakes add one RTT before data (mitigated by TCP Fast Open / TLS 1.3 0-RTT carefully). UDP skips this but loses reliability.",
            "SYN floods fill backlog queues—tune somaxconn/syn cookies. Connection timeouts often mean packets dropped by security groups or wrong bind address.",
            "# capture handshake (needs privileges)\n# sudo tcpdump -ni any 'tcp[tcpflags] & (tcp-syn) != 0'",
            "1) Ensure listeners bind correctly. 2) Open firewall for SYN to the service port. 3) Alert on elevated SYN_RECV counts.",
        ),
        "DNS resolution": E(
            "DNS resolution maps human domain names to IP addresses (and other records) via a hierarchy of resolvers and authoritative servers.",
            "Without DNS, clients cannot find services by name; misconfigured DNS causes widespread outages.",
            ["stub resolver", "recursive resolver", "authoritative NS", "A/AAAA/CNAME/MX/TXT", "TTL"],
            "App asks OS stub → recursive resolver queries root/TLD/authoritative as needed → caches answers for TTL → returns A/AAAA (or follows CNAME).",
            "Low TTL speeds failover but increases query load; high TTL caches stale records after cutovers. CNAMEs at apex have restrictions.",
            "NXDOMAIN vs SERVFAIL vs timeouts point to different layers. Compare dig @8.8.8.8 vs corporate resolvers; check split-horizon DNS.",
            "dig +short example.com A\ndig example.com NS\ndig +trace example.com",
            "1) Document critical records and TTLs. 2) Dual-provision before cutover. 3) Lower TTL ahead of migrations. 4) Monitor resolution failure rates.",
        ),
        "commit": E(
            "A Git commit is an immutable snapshot of the project tree plus metadata (author, message, parent pointer(s)).",
            "Commits form history so teams can review, bisect, revert, and collaborate safely.",
            ["snapshot/tree", "parent hash", "message", "author/committer", "detached HEAD"],
            "Staging selects content; commit writes a new object referencing the tree and parent. Branches are movable pointers to commits.",
            "Small focused commits ease review; huge commits hide intent. Rewriting published history (force push) endangers collaborators.",
            "If a commit is missing files, check what was staged. Lost work often sits on another branch or reflog—use git reflog before panicking.",
            "git add -p && git commit -m \"fix: handle empty DNS responses\"\ngit log --oneline -5",
            "1) Agree on commit message conventions. 2) Prefer small commits. 3) Protect main from force-push. 4) Require review before merge.",
        ),
        "branching": E(
            "A Git branch is a movable pointer to a commit, letting you diverge history for features, fixes, or releases.",
            "Branches isolate in-progress work so main stays releasable.",
            ["branch pointer", "HEAD", "fast-forward", "feature vs release branches", "remote-tracking"],
            "Creating a branch names the current commit; new commits advance that pointer. Merging or rebasing integrates histories back.",
            "Long-lived branches drift and hurt merges; trunk-based development keeps branches short. Release branches trade isolation for merge cost.",
            "Diverged branches need merge/rebase. If you cannot find work, list branches and use reflog. Delete stale remote branches intentionally.",
            "git switch -c feature/dns-ttl\ngit push -u origin HEAD",
            "1) Use short-lived feature branches. 2) Name by ticket/intent. 3) Delete after merge. 4) Protect main with required checks.",
        ),
        "merge": E(
            "Git merge joins two histories, creating a merge commit when needed (or fast-forwarding when possible).",
            "It integrates completed work while preserving parallel history.",
            ["fast-forward", "3-way merge", "conflict markers", "merge commit", "ours/theirs"],
            "Git finds a common ancestor, diffs both sides, and combines changes. Conflicting hunks must be resolved manually, then committed.",
            "Merge preserves true history; rebase linearizes but rewrites commits. Prefer merge commits for shared branches if your team wants explicit integration points.",
            "Repeated conflicts mean overlapping long-lived branches—rebase/merge more often. Use git status and mergetool during conflicts.",
            "git switch main && git pull\ngit merge feature/dns-ttl\n# resolve conflicts, then: git commit",
            "1) Keep branches fresh with main. 2) Resolve conflicts with tests green. 3) Prefer squash or merge per team policy. 4) Never force-push shared merges casually.",
        ),
        "REST": E(
            "REST is an architectural style for networked APIs using resources identified by URLs, manipulated via HTTP methods and representations.",
            "It provides a uniform, cacheable, loosely coupled interface between clients and servers.",
            ["resources", "representations (JSON)", "stateless requests", "uniform interface", "HATEOAS (optional)"],
            "Design nouns as resources (/orders/42), use methods for actions, return appropriate status codes, and keep servers stateless—session lives in tokens/DB, not server memory per request.",
            "Pure REST can be chatty; GraphQL/RPC may fit complex client-driven queries. Over-rigid REST theater wastes time—be pragmatic about hypermedia.",
            "Ambiguous endpoints and verbs cause client bugs—document status codes and idempotency. Debug with HTTP traces and contract tests.",
            "GET /orders/42 → 200 {\"id\":42,\"status\":\"paid\"}\nPOST /orders → 201 Location: /orders/43",
            "1) Publish OpenAPI. 2) Standardize error shape. 3) Version carefully. 4) Add consumer-driven contract tests.",
        ),
        "cookies": E(
            "HTTP cookies are small name/value pairs the server sets via Set-Cookie and the browser stores and resends on later requests to the same site scope.",
            "They implement sessions and preferences without stuffing every URL with state.",
            ["Set-Cookie", "Domain/Path", "Secure/HttpOnly/SameSite", "session vs persistent", "cookie size limits"],
            "Server sends Set-Cookie; browser stores subject to attributes; matching requests include Cookie header. HttpOnly blocks JS access; SameSite mitigates CSRF; Secure requires HTTPS.",
            "Cookies are sent automatically—easy sessions, easy CSRF if SameSite/lax policies are wrong. Tokens in localStorage avoid CSRF but worsen XSS impact.",
            "Missing cookies: check Domain/Path/Secure and third-party blocking. Bloated headers: reduce cookie count/size.",
            "Set-Cookie: session=abc; Path=/; HttpOnly; Secure; SameSite=Lax",
            "1) Prefer HttpOnly Secure session cookies. 2) Set SameSite deliberately. 3) Rotate session IDs on login. 4) Document CSRF strategy.",
        ),
        "XSS": E(
            "Cross-site scripting (XSS) injects attacker-controlled script into pages viewed by other users, stealing sessions or performing actions as the victim.",
            "It breaks the browser’s trust that HTML/JS from your origin is safe.",
            ["stored vs reflected vs DOM XSS", "output encoding", "Content-Security-Policy", "HttpOnly cookies", "sanitize HTML"],
            "Untrusted input is reflected into HTML/JS/URL contexts without encoding. Fix by context-aware encoding, avoiding innerHTML with raw input, and CSP to limit script sources.",
            "Rich-text HTML requires careful sanitization allowlists. CSP helps but is not a substitute for encoding.",
            "Reproduce with a benign payload, find the sink (innerHTML, dangerous templating), and verify CSP reports. Check whether session cookies are HttpOnly.",
            "// Bad: el.innerHTML = userComment\n// Good: el.textContent = userComment",
            "1) Default-encode all untrusted output. 2) Add CSP with nonce/hash. 3) HttpOnly sessions. 4) Add security tests for reflective sinks.",
        ),
        "SQL injection": E(
            "SQL injection occurs when untrusted input is concatenated into SQL, letting attackers alter query structure.",
            "It can leak, modify, or delete data and sometimes escalate to OS commands via DB features.",
            ["parameterized queries", "ORMs", "least-privilege DB roles", "input validation", "error message leakage"],
            "Attacker supplies input that closes quotes and adds OR 1=1/-- etc. Prevent by binding parameters always; never string-build SQL with user data.",
            "Dynamic identifiers (table names) cannot be parameterized—use allowlists. ORMs help but raw SQL must still bind values.",
            "Hunt via code search for string-built SQL; test with benign payloads in staging. Review DB logs for unexpected statements.",
            "# Bad: f\"SELECT * FROM users WHERE id={user_id}\"\n# Good:\ncur.execute(\"SELECT * FROM users WHERE id=%s\", (user_id,))",
            "1) Ban string-interpolated SQL in lint/review. 2) Use parameterized APIs only. 3) DB user with minimal grants. 4) Add SAST and penetration checks.",
        ),
        "authentication": E(
            "Authentication verifies who a principal is (user/service), typically via passwords, tokens, certificates, or SSO.",
            "It is the gate before authorization; without it, identity-based access control is meaningless.",
            ["credentials", "sessions vs tokens", "MFA", "password hashing", "OAuth/OIDC"],
            "User presents credentials; server verifies (e.g., argon2id hash compare) and establishes a session cookie or issues JWTs. MFA adds a second factor. Federated login delegates identity to an IdP.",
            "JWTs are scalable but harder to revoke; server sessions reverse that trade-off. Never store recoverable passwords.",
            "Login failures: distinguish user-enumeration carefully, check clock skew for JWTs, cookie flags, and redirect URIs for OAuth.",
            "hash = argon2.hash(password)\nassert argon2.verify(hash, password)",
            "1) Use a vetted auth library. 2) Hash passwords with argon2/bcrypt. 3) Enforce MFA for privileged users. 4) Log auth events without secrets.",
        ),
        "array": E(
            "An array (or list) stores elements in a contiguous, indexable sequence supporting random access by position.",
            "It is the default collection for ordered data and the basis of many algorithms.",
            ["index access O(1)", "append amortized O(1)", "insert/delete middle O(n)", "cache locality", "dynamic resizing"],
            "Elements live in order; indexing jumps by size×index. Dynamic arrays resize geometrically when capacity is exceeded, amortizing copy cost.",
            "Linked lists win rare middle insert patterns but lose cache performance. For frequent keyed lookup, prefer hash maps.",
            "Off-by-one and mutation-during-iteration are common bugs—copy or iterate indices carefully.",
            "nums = [3, 1, 4]\nnums.append(1)\nprint(nums[0])  # 3",
            "1) Prefer arrays/lists as default. 2) Pre-size when length known. 3) Document mutability expectations in APIs.",
        ),
        "hash table": E(
            "A hash table maps keys to values using a hash function and buckets for average O(1) lookup, insert, and delete.",
            "It powers dictionaries, sets, caches, and indexes when you need keyed access.",
            ["hash function", "collision resolution", "load factor", "average O(1)", "key equality"],
            "Hash(key) selects a bucket; collisions use chaining or open addressing. On high load factor, the table resizes and rehashes.",
            "Worst-case can degrade without good hashing; keys must be immutable for stability. Ordered maps or trees if you need sorted keys.",
            "Unexpected misses: check equality/hash consistency. Hot keys and poor hashes cause uneven buckets—profile.",
            "index = {}\nfor word in words:\n    index.setdefault(word, 0)\n    index[word] += 1",
            "1) Use language dict/map. 2) Ensure keys are hashable. 3) Watch memory for large maps. 4) Consider LRU caches for bounded memory.",
        ),
        "hashing": E(
            "Hashing maps arbitrary data to a fixed-size digest for tables, integrity checks, or password storage (with slow KDFs).",
            "It enables fast equality checks and detects tampering when used cryptographically.",
            ["deterministic digest", "collision resistance (crypto)", "avalanche effect", "salt for passwords", "hash vs encryption"],
            "A hash function mixes input bits into a digest. For hash tables, speed matters; for security, use SHA-256/BLAKE3; for passwords, use argon2 with unique salts—not raw SHA.",
            "Hashes are one-way (ideally); encryption is reversible with a key. Checksums like CRC are not cryptographic.",
            "Collision or verification failures: confirm canonical encoding (UTF-8, newlines) and algorithm match on both sides.",
            "import hashlib\nhashlib.sha256(b\"hello\").hexdigest()",
            "1) Pick algorithm by purpose (table vs integrity vs passwords). 2) Version digests in protocols. 3) Never roll your own crypto.",
        ),
        "stack": E(
            "A stack is a LIFO collection: push and pop only at the top—used for call stacks, parsers, and undo.",
            "It models nested structure and depth-first control flow naturally.",
            ["LIFO", "push/pop/peek", "call stack", "balanced parentheses", "DFS explicit stack"],
            "Push adds to top; pop removes top. Recursion uses the machine call stack; you can simulate DFS with an explicit stack.",
            "Queues (FIFO) fit scheduling/BFS. Stacks do not give fair ordering of oldest items.",
            "Overflows imply unbounded nesting—cap depth. Wrong pop order usually means mismatched push/pop in parsing.",
            "def is_balanced(s):\n    st = []\n    pairs = {')':'(', ']':'[', '}':'{'}\n    for ch in s:\n        if ch in '([{': st.append(ch)\n        elif ch in pairs:\n            if not st or st.pop() != pairs[ch]: return False\n    return not st",
            "1) Use stacks for nested parsing/undo. 2) Bound depth. 3) Prefer clear iterative stacks when recursion depth is risky.",
        ),
        "heap": E(
            "A binary heap is a complete tree stored in an array that keeps the min (or max) at the root for O(log n) insert/remove and O(1) peek.",
            "It implements priority queues for schedulers, Dijkstra, and top-k problems.",
            ["complete binary tree", "heap property", "sift up/down", "priority queue", "O(log n) updates"],
            "Insert at end and sift up; remove root by swapping with last and sifting down. Array indexing uses parent/child formulas.",
            "Heaps do not keep full sorted order—only the extreme. For arbitrary delete/decrease-key, more advanced heaps or trees may help.",
            "Wrong order: verify comparator direction (min vs max). Ties may need secondary keys for stability.",
            "import heapq\nh = []\nheapq.heappush(h, (2, 'b'))\nheapq.heappush(h, (1, 'a'))\nheapq.heappop(h)  # (1, 'a')",
            "1) Use stdlib heap/priority queue. 2) Store (priority, tiebreaker, value). 3) Test empty-pop behavior.",
        ),
        "binary search tree": E(
            "A BST stores keys so left subtree < node < right, enabling average O(log n) search/insert/delete when balanced.",
            "It maintains sorted order for range queries unlike hash tables.",
            ["BST invariant", "inorder traversal", "balance (AVL/red-black)", "successor/predecessor", "range queries"],
            "Search compares and branches left/right. Insert walks to a leaf position. Unbalanced inserts degrade to O(n); balanced trees rotate to keep height logarithmic.",
            "Hash maps are faster for exact lookup without order. B-trees dominate disk-backed DB indexes.",
            "Failed finds after insert: check duplicates policy and comparator. Degenerate trees: switch to balanced trees or shuffle inserts.",
            "# inorder yields sorted keys\ndef inorder(n):\n    if not n: return []\n    return inorder(n.left) + [n.key] + inorder(n.right)",
            "1) Prefer language TreeMap / sorted containers when order matters. 2) Document comparator. 3) Avoid rolling your own production BST.",
        ),
        "trie": E(
            "A trie (prefix tree) stores strings by sharing character prefixes for fast prefix search and autocomplete.",
            "It answers “words with prefix P” efficiently compared to scanning a list.",
            ["node per character", "prefix sharing", "end-of-word mark", "alphabet size trade-off", "compressed/radix tries"],
            "Insert walks/creates nodes per character and marks terminal. Lookup follows characters; prefix search explores a subtree.",
            "Tries use more memory than hash sets for sparse alphabets; radix trees compress chains. For huge dictionaries, specialized structures or FM-indexes appear.",
            "Wrong misses: normalization (case/Unicode) mismatches. Memory blowups: compress or limit alphabet.",
            "class Node:\n    def __init__(self):\n        self.kids = {}; self.end = False",
            "1) Normalize input Unicode. 2) Use a trie for autocomplete/prefix features. 3) Cap dictionary size and measure memory.",
        ),
        "graph representation": E(
            "Graphs are stored as adjacency lists (usual) or matrices; lists map each vertex to neighbor edges.",
            "Representation choice drives memory and algorithm speed for BFS/DFS/shortest paths.",
            ["adjacency list vs matrix", "directed vs undirected", "weighted edges", "sparse vs dense", "implicit graphs"],
            "Build list: for each edge u→v, append v to adj[u] (and u to adj[v] if undirected). Matrices use O(n²) space and O(1) edge checks.",
            "Matrices suit dense graphs/Floyd-Warshall; lists suit sparse graphs. Choose immutable snapshots if concurrent mutation is hard.",
            "Missing edges or double edges: validate input. Index vs labeled nodes: keep a stable id map.",
            "graph = {0:[1,2], 1:[2], 2:[]}\n# edge list → adj\nfrom collections import defaultdict\nadj = defaultdict(list)\nfor u,v in edges: adj[u].append(v)",
            "1) Pick list vs matrix from density. 2) Encapsulate behind helpers. 3) Property-test round-trips from edge lists.",
        ),
        "recursion": E(
            "Recursion is a function solving a problem by calling itself on smaller inputs until a base case.",
            "It expresses trees, divide-and-conquer, and backtracking clearly.",
            ["base case", "recursive case", "call stack", "tail recursion", "stack overflow risk"],
            "Each call pushes a frame; base case returns; frames unwind combining results. Any recursion can be rewritten with an explicit stack.",
            "Deep recursion risks overflows—prefer iteration for deep linear chains. Memoize when subproblems overlap.",
            "Infinite recursion: missing/incorrect base case. Wrong results: check whether state is mutated across calls.",
            "def fact(n):\n    if n <= 1: return 1\n    return n * fact(n-1)",
            "1) Write base cases first. 2) Test depth limits. 3) Convert hot deep recursion to iterative form.",
        ),
        "process": E(
            "A process is an OS instance of a running program with its own address space, handles, and scheduling entity (plus threads).",
            "Processes isolate faults and security boundaries between programs.",
            ["PID", "address space", "file descriptors", "parent/child", "exit codes"],
            "OS creates a process (fork/exec or CreateProcess), loads the image, and schedules it. Threads share the address space; processes generally do not.",
            "Threads are lighter for shared-memory concurrency; processes give stronger isolation (browsers, workers).",
            "Zombies mean parents did not wait; leaks of FDs show as EMFILE. Use ps/lsof to inspect.",
            "ps -o pid,ppid,stat,cmd -p $$\nlsof -p $$ | head",
            "1) Prefer processes for isolation boundaries. 2) Handle SIGCHLD/wait. 3) Cap FD usage. 4) Supervise with systemd/k8s.",
        ),
        "mutex": E(
            "A mutex (mutual exclusion lock) ensures only one thread holds a critical section at a time.",
            "It prevents race conditions on shared mutable state.",
            ["lock/unlock", "critical section", "deadlock risk", "reentrancy", "priority inversion"],
            "Thread acquires mutex before touching shared data and releases after. If held, others block until unlock. Always unlock via finally/RAII.",
            "Coarse locks hurt scalability; lock-free structures are harder. Prefer message passing when possible.",
            "Deadlocks: lock ordering and timeouts. Contended locks: profile wait time and shrink critical sections.",
            "import threading\nlock = threading.Lock()\nwith lock:\n    shared += 1",
            "1) Identify shared mutable state. 2) Protect with clear lock scopes. 3) Document lock order. 4) Add race tests (TSan) where available.",
        ),
        "deadlock": E(
            "Deadlock is a permanent wait cycle where each party holds a resource another needs (Coffman: mutual exclusion, hold-and-wait, no preemption, circular wait).",
            "It freezes progress until process kill or timeout intervention.",
            ["circular wait", "lock ordering", "timeouts", "detection", "resource hierarchy"],
            "Prevent by acquiring locks in global order, using try-lock timeouts, or avoiding nested locks. Detect via wait-for graphs in DB engines.",
            "Fine-grained locking raises deadlock risk vs coarse locks. Sometimes queues eliminate shared locks.",
            "Symptoms: threads stuck, DB error 40P01. Capture lock graphs; reproduce with concurrency stress.",
            "-- Postgres\nSELECT * FROM pg_stat_activity WHERE wait_event_type = 'Lock';",
            "1) Define lock order. 2) Keep transactions short. 3) Use deadlock retries for DBs. 4) Alert on rising wait events.",
        ),
        "race condition": E(
            "A race condition means outcome depends on unsafe timing/interleaving of concurrent operations on shared state.",
            "It causes Heisenbugs: lost updates, duplicate charges, torn reads.",
            ["shared mutable state", "atomic operations", "happens-before", "check-then-act", "TOCTOU"],
            "Two threads read-modify-write without sync; both write stale values. Fix with mutexes, atomics, DB transactions/constraints, or single-threaded ownership.",
            "Over-synchronization hurts performance; under-synchronization corrupts data. Prefer immutability and actor models.",
            "Reproduce with stress tests and race detectors. Look for check-then-act on files/rows without locks or UNIQUE constraints.",
            "# Bad: if key not in cache: cache[key] = load()\n# Better: use a lock or concurrent map compute-if-absent",
            "1) Eliminate shared mutability where possible. 2) Add constraints at the DB. 3) Run concurrent tests. 4) Use race detectors in CI for C/C++/Go/Java.",
        ),
        "context switching": E(
            "Context switching is the OS saving one thread/process CPU state and restoring another so many tasks share cores.",
            "It enables multitasking but costs cycles and cache warmth.",
            ["save/restore registers", "kernel involvement", "cache/TLB effects", "voluntary vs involuntary", "run queues"],
            "Scheduler picks next task, saves old registers/PC, loads new ones, and resumes. Excessive switching thrashs caches.",
            "More threads than needed increase switch overhead. Blocking I/O models vs async change switch patterns.",
            "High system CPU with low useful work may mean thrashing—profile sched latency (perf, run queue).",
            "# Linux: context switches\nvmstat 1 5",
            "1) Size worker pools to cores×factor. 2) Avoid busy-wait. 3) Measure p99 latency under load.",
        ),
        "CPU scheduling": E(
            "CPU scheduling chooses which ready thread runs next on a core (CFS, priorities, real-time policies).",
            "It balances fairness, latency, and throughput for workloads sharing CPUs.",
            ["ready queue", "time slice", "priorities/nice", "preemption", "affinity"],
            "On timer interrupt or blocking, scheduler picks next task by policy. Interactive tasks get lower latency; batch can yield throughput.",
            "Priority inversion and starvation need inheritance or careful classes. Pinning helps latency-sensitive apps but reduces packing.",
            "Starvation or latency spikes: check nice values, cgroup CPU limits, and noisy neighbors.",
            "ps -eo pid,ni,cmd --sort=ni | head\n# cgroup CPU in containers often shows as throttling",
            "1) Set appropriate nice/cgroup limits. 2) Isolate latency-critical services. 3) Monitor throttling metrics.",
        ),
        "virtual memory": E(
            "Virtual memory gives each process a private virtual address space mapped to physical frames via page tables, with disk swap as backing.",
            "It isolates processes and lets programs use more memory than physical RAM (at a cost).",
            ["pages/frames", "page tables", "TLB", "page fault", "swap"],
            "CPU translates virtual→physical through page tables (cached in TLB). On miss/fault, OS loads a page or signals an error (segfault).",
            "Overcommit + swap can cause latency spikes; containers often disable swap. Huge pages reduce TLB pressure for big heaps.",
            "OOM kills and thrashing: watch si/so in vmstat and working set size. Segfaults: invalid pointers/mappings.",
            "free -h\nvmstat 1 3",
            "1) Size memory limits to working set. 2) Alert on swap activity. 3) Use huge pages only with measurement.",
        ),
        "paging": E(
            "Paging splits memory into fixed-size pages mapped to frames, simplifying allocation vs variable segments.",
            "It underpins virtual memory and protects processes from each other’s addresses.",
            ["page size", "page table levels", "page fault", "copy-on-write", "demand paging"],
            "OS allocates frames and fills page table entries. Demand paging loads pages on first access; COW shares pages until write.",
            "Large page tables cost memory; huge pages trade flexibility. Fragmentation is less than with pure segments.",
            "Major faults imply disk I/O—reduce working set or add RAM. Soft faults are cheaper remaps.",
            "# major/minor faults on Linux\nps -o min_flt,maj_flt,cmd -p $$",
            "1) Measure fault rates under load. 2) Pre-touch critical heaps if needed. 3) Align mmap sizes thoughtfully.",
        ),
        "filesystem": E(
            "A filesystem organizes bytes on storage into files, directories, permissions, and metadata (inodes).",
            "Programs persist data through files rather than raw disk blocks.",
            ["inode", "directory entries", "permissions", "mounts", "buffer cache"],
            "Path lookup walks directories to an inode; read/write goes through page cache unless O_DIRECT. Mounts attach trees to devices or remote shares.",
            "Different FS (ext4, XFS, ZFS) trade features/performance. Network FS add consistency quirks.",
            "ENOSPC, permission denied, and stale NFS handles are common—check df -i for inode exhaustion too.",
            "df -h; df -i\nls -la /var/log | head",
            "1) Monitor disk and inode usage. 2) Separate volumes for data/logs. 3) Back up critical mounts. 4) Document mount options.",
        ),
        "CPU registers": E(
            "CPU registers are tiny, fastest storage inside the core holding operands, addresses, and status during instruction execution.",
            "They make the instruction cycle possible; compilers allocate variables to registers when possible.",
            ["general-purpose regs", "PC/IP", "stack pointer", "flags", "ABI calling convention"],
            "Instructions read/write registers; spills go to stack memory when registers are exhausted. Interrupts save register state.",
            "More registers can improve speed but increase context-switch cost. You rarely manage them directly outside assembly.",
            "Debuggers show register state on crashes—use to diagnose calling-convention bugs in native code.",
            "# x86-64 example: rax holds return values in SysV ABI\n# (inspect via gdb: info registers)",
            "1) Prefer high-level languages. 2) For native hot paths, inspect compiler asm. 3) Follow ABI when writing assembly.",
        ),
        "CPU instruction cycle": E(
            "The instruction cycle is fetch → decode → execute (plus memory access/writeback in pipelined CPUs).",
            "It is how programs progress: each instruction advances architectural state.",
            ["fetch", "decode", "execute", "pipeline", "hazards"],
            "PC points to next instruction; CPU fetches bytes, decodes opcode, executes, then updates PC. Pipelines overlap stages for throughput.",
            "Branch mispredicts and cache misses stall pipelines—algorithmic locality matters more than micro-optimizing asm early.",
            "Perf counters reveal stalls; focus on cache misses and branches before rewriting algorithms.",
            "# Linux\nperf stat -e cycles,instructions,cache-misses ./app",
            "1) Write clear code first. 2) Profile before micro-optimizing. 3) Improve data locality for hot loops.",
        ),
        "CPU cache hierarchy": E(
            "CPUs use L1/L2/L3 caches to keep recently used lines closer than DRAM, exploiting locality.",
            "Cache-friendly layouts can yield order-of-magnitude speedups for tight loops.",
            ["cache line", "spatial/temporal locality", "inclusive/exclusive", "false sharing", "prefetch"],
            "On memory access, hardware checks L1→L2→L3→RAM. Lines are typically 64B. False sharing occurs when unrelated data share a line across cores.",
            "Bigger caches help but cost power/area. Structure-of-arrays can beat array-of-structures for scans.",
            "Perf cache-miss rates high: reorder loops, pack hot fields, align shared atomics to separate lines.",
            "# pad to avoid false sharing (conceptually)\n# struct { atomic_int counters[64]; }  # better: per-core counters",
            "1) Profile cache misses. 2) Keep hot data contiguous. 3) Avoid false sharing in concurrent counters.",
        ),
        "RAM and persistent storage": E(
            "RAM is volatile, fast working memory; persistent storage (SSD/HDD) keeps data across power loss but is slower.",
            "Software must treat RAM as temporary and explicitly persist durable state.",
            ["volatility", "latency/bandwidth gap", "page cache", "fsync durability", "wear (SSD)"],
            "Reads/writes hit RAM; OS page cache may delay disk. Durability requires fsync/journal commits. Databases manage this carefully (WAL).",
            "Memory-first designs are fast but crash-lose data without persistence strategies. Disk-bound systems need batching.",
            "Data loss after crash: missing fsync or write barriers. Slow disks: check iostat and queue depths.",
            "iostat -xz 1 3\n# ensure DB fsync settings match durability goals",
            "1) Classify data as ephemeral vs durable. 2) Use DB/fsync correctly. 3) Monitor disk latency. 4) Test crash recovery.",
        ),
        "binary representation": E(
            "Binary representation encodes values with bits (0/1); groups of 8 bits form a byte.",
            "All digital data—numbers, text, images—ultimately is bits interpreted by a schema.",
            ["bit/byte", "endianness", "signed vs unsigned", "bit operations", "masks"],
            "Positional powers of two form integers; formats define floating point and character encodings. Endianness decides byte order in memory/on wire.",
            "Humans prefer hex for compactness. Wrong endianness or signedness causes subtle protocol bugs.",
            "Mismatch dumps: print hex and confirm width/endian. Mask carefully to avoid sign extension bugs.",
            "n = 0b1101  # 13\nprint(hex(n), n.to_bytes(2, 'big'))",
            "1) Document binary layouts. 2) Use explicit endian helpers. 3) Add golden hex fixture tests.",
        ),
        "two's complement": E(
            "Two’s complement encodes signed integers so addition/subtraction use the same hardware as unsigned, with the high bit as sign.",
            "It is the universal signed integer representation in modern CPUs.",
            ["sign bit", "range −2^(n−1)..2^(n−1)−1", "overflow wrap", "negation via invert+1", "arithmetic shifts"],
            "To negate, invert bits and add one. Overflow wraps modulo 2^n in unchecked arithmetic—define checked ops when needed.",
            "Sign-magnitude is rarer; floating point is separate. Language “undefined behavior” on signed overflow in C/C++ differs from wrap in Java.",
            "Unexpected negatives: unsigned/signed mix or byte decoding errors. Check casts.",
            "print(int.from_bytes(b'\\xff\\xff', 'big', signed=True))  # -1 in 16-bit",
            "1) Prefer fixed-width types in protocols. 2) Test min/max edges. 3) Avoid mixing signed/unsigned carelessly.",
        ),
        "character encoding and Unicode": E(
            "Character encoding maps characters to bytes; Unicode assigns code points, usually serialized as UTF-8.",
            "It prevents mojibake and enables multilingual text.",
            ["code point", "UTF-8", "UTF-16", "BOM", "normalization (NFC/NFD)"],
            "UTF-8 uses 1–4 bytes per code point, ASCII-compatible. Decode bytes→str with known encoding; encode when writing. Normalize before comparing user-facing strings.",
            "Latin-1 mislabeled as UTF-8 causes errors. Some languages use UTF-16 internally (JS/Java) with surrogate pairs.",
            "Mojibake: wrong codec. Compare failures: normalize. Validate inputs reject invalid UTF-8.",
            "s = \"café\".encode(\"utf-8\")  # b'caf\\xc3\\xa9'\nprint(s.decode(\"utf-8\"))",
            "1) Standardize on UTF-8 everywhere. 2) Declare charset in HTTP/HTML. 3) Normalize for search keys. 4) Reject invalid byte sequences.",
        ),
        "OSI model": E(
            "The OSI model is a seven-layer conceptual stack (Physical→Application) for talking about networking responsibilities.",
            "It helps locate bugs (L3 routing vs L4 ports vs L7 HTTP) even though real stacks are closer to TCP/IP.",
            ["L2 switching", "L3 IP", "L4 TCP/UDP", "L7 application", "encapsulation"],
            "Each layer adds headers (encapsulation) going down and strips them going up. Troubleshooting maps symptoms to layers.",
            "OSI is pedagogical; do not force every product into seven boxes. TCP/IP four-layer model is often enough.",
            "Map failures: link lights (L1), ARP (L2), ping (L3), connect (L4), HTTP status (L7).",
            "# L3 vs L4 quick checks\nping -c1 8.8.8.8\nnc -vz example.com 443",
            "1) Teach on-call the layer map. 2) Capture at the right layer. 3) Document trust boundaries per layer.",
        ),
        "IPv4 subnetting": E(
            "IPv4 subnetting splits address space with a mask/CIDR prefix so hosts share a network and routers forward between networks.",
            "It structures addressing, controls broadcast domains, and enables routing policy.",
            ["CIDR prefix", "network/host bits", "gateway", "broadcast", "private ranges"],
            "A /24 keeps 8 host bits (256 addresses, fewer usable). Hosts use mask to decide local vs route-via-gateway. Plan ranges to avoid overlaps in VPCs/VPNs.",
            "Smaller subnets waste fewer addresses but add routes; flat large subnets increase blast radius.",
            "Overlap causes asymmetric routing—audit CIDRs. Wrong mask yields “destination unreachable” for local peers.",
            "# 10.0.1.0/24 → mask 255.255.255.0\nipcalc 10.0.1.0/24 2>/dev/null || python3 - <<'PY'\nimport ipaddress\nn=ipaddress.ip_network('10.0.1.0/24')\nprint(n.netmask, n.num_addresses)\nPY",
            "1) Plan non-overlapping CIDRs. 2) Document gateway/DNS. 3) Codify in Terraform. 4) Test connectivity matrices.",
        ),
        "MAC address": E(
            "A MAC address is a 48-bit link-layer identifier for a network interface used within a L2 broadcast domain.",
            "Switches forward frames by MAC; ARP maps IPv4→MAC on Ethernet.",
            ["48-bit EUI", "ARP/NDP", "switching vs routing", "spoofing", "local vs universal bits"],
            "Host ARP-requests for gateway MAC, then sends Ethernet frames with dest MAC. Routers strip L2 and forward IP to next hop L2.",
            "MACs are not global routing identifiers. Virtualization and privacy features randomize MACs.",
            "Duplicates confuse switches; check arp -an and CAM tables. Wireshark helps spot storms.",
            "ip link show\nip neigh show",
            "1) Avoid duplicate MACs in labs. 2) Secure ARP where needed. 3) Rely on IP/DNS for app config, not MAC.",
        ),
        "NAT": E(
            "Network Address Translation rewrites packet IP/ports so many private hosts share public IPs (or hide topology).",
            "It conserves IPv4 addresses and is standard at home/cloud edges.",
            ["SNAT/DNAT", "port mapping", "connection tracking", "hairpin", "IPv6 reduces need"],
            "Outbound SNAT replaces private source with public IP and tracks ports; inbound DNAT forwards public ports to private hosts. State lives in conntrack.",
            "NAT breaks true end-to-end addressing (hurts some P2P). Prefer IPv6 or private connectivity for service meshes when possible.",
            "Outbound fails: check default route, masquerade rules, and conntrack table full. Inbound fails: security groups + DNAT mismatch.",
            "# Linux MASQUERADE sketch\n# iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE",
            "1) Centralize NAT at edge. 2) Monitor conntrack. 3) Prefer private links for east-west. 4) Document public port forwards.",
        ),
        "socket": E(
            "A socket is an OS endpoint for network communication (IP:port + protocol) that apps read/write like a bidirectional channel.",
            "It is the API between programs and TCP/UDP.",
            ["bind/listen/accept", "connect", "TCP vs UDP sockets", "nonblocking/select", "SO_REUSEADDR"],
            "Servers bind+listen+accept; clients connect. Bytes stream on TCP sockets; datagrams on UDP. Close/shutdown manage half-close.",
            "Higher-level HTTP clients hide sockets—use them unless you need custom protocols.",
            "EADDRINUSE: port taken. Timeouts: set deadlines. TIME_WAIT piles: understand reuse options carefully.",
            "python3 - <<'PY'\nimport socket\ns=socket.create_connection(('example.com',80),5)\ns.sendall(b'HEAD / HTTP/1.1\\r\\nHost: example.com\\r\\n\\r\\n')\nprint(s.recv(200)); s.close()\nPY",
            "1) Prefer battle-tested client libraries. 2) Set timeouts. 3) Limit listen backlog. 4) Health-check accept loops.",
        ),
        "load balancer": E(
            "A load balancer distributes traffic across multiple backends to improve availability and scale.",
            "It avoids single-server bottlenecks and enables rolling updates.",
            ["L4 vs L7", "health checks", "algorithms (round-robin/least-conn)", "sticky sessions", "TLS termination"],
            "LB receives connections, picks a healthy backend by policy, and proxies. Health checks remove bad targets. L7 can route by path/host.",
            "Sticky sessions reduce stateless benefits. Over-complex L7 rules create outage risk—keep simple.",
            "502/504: backend dead or timeouts. Uneven load: check algorithm and slow instances. Verify health check paths.",
            "# nginx upstream sketch\n# upstream api { server 10.0.0.1; server 10.0.0.2; }",
            "1) Put LB in front of N≥2 healthy instances. 2) Tune health checks. 3) Drain on deploy. 4) Alert on unhealthy host count.",
        ),
        "horizontal scaling": E(
            "Horizontal scaling adds more instances to handle load, versus vertical scaling which grows one machine.",
            "It improves capacity and fault isolation when the app is designed to be stateless or sharded.",
            ["stateless services", "shared data store", "session externalization", "sharding", "autoscaling signals"],
            "Run N replicas behind a load balancer; externalize sessions/cache/DB. Autoscale on CPU/RPS/queue depth with cooldown.",
            "Not all systems scale linearly—DB write bottlenecks dominate. Vertical may be cheaper until a cliff.",
            "Scaling out without effect: find serial bottlenecks (global locks, single shard). Watch cold-start and cache stampede.",
            "# k8s\nkubectl scale deploy/api --replicas=5",
            "1) Make services stateless. 2) Put shared state in managed stores. 3) Autoscale on meaningful SLIs. 4) Load test the data tier.",
        ),
        "cache": E(
            "A cache stores recently or frequently used data closer/faster than the source of truth to cut latency and load.",
            "It accelerates reads when freshness requirements allow.",
            ["hit/miss", "TTL", "invalidation", "eviction (LRU)", "stampede"],
            "On read, check cache; on miss, load origin and populate. Invalidate or expire entries when data changes. Cap size with eviction policy.",
            "Stale reads vs complexity of invalidation. Write-through vs write-behind change durability/latency.",
            "Stampede: many misses thundering origin—use singleflight/locks. Memory growth: set maxmemory/eviction.",
            "value = redis.get(key) or db.load(key) and redis.setex(key, 60, value)",
            "1) Identify hot read paths. 2) Choose TTL/invalidation. 3) Cap memory. 4) Measure hit rate and origin load.",
        ),
        "message queue": E(
            "A message queue asynchronously decouples producers and consumers with durable or buffered messages (Kafka, SQS, RabbitMQ).",
            "It smooths load spikes and isolates failures between services.",
            ["producer/consumer", "at-least-once delivery", "ack/visibility", "dead-letter queue", "ordering keys"],
            "Producer enqueues; consumer pulls/processes/acks. Failures retry until DLQ. Design consumers idempotent because duplicates happen.",
            "Queues add operational complexity and eventual processing delay. Sync RPC is simpler for low-latency request/response.",
            "Lag growth: scale consumers or fix poison messages. Dupes: enforce idempotency keys.",
            "# SQS-style mental model\n# receive → process → delete/ack; on crash, visibility timeout returns message",
            "1) Pick queue tech for volume/ordering. 2) Make handlers idempotent. 3) Add DLQ + alerts on lag. 4) Load test retry storms.",
        ),
        "virtual machine": E(
            "A virtual machine emulates a computer so guest OS kernels run isolated on a hypervisor atop physical hosts.",
            "It consolidates hardware and isolates tenants more strongly than processes alone.",
            ["hypervisor", "guest OS", "images", "vCPU/memory", "snapshots"],
            "Hypervisor schedules vCPUs and mediates devices; guests think they own hardware. Images boot VMs; cloud APIs create them in minutes.",
            "VMs are heavier than containers; containers share a kernel. Use VMs for strong isolation/multi-OS; containers for app deploy density.",
            "Slow boots/noisy neighbors: check oversubscription and storage IOPS. Clock drift affects TLS/Kerberos.",
            "# cloud mental model: choose AMI/image → instance type → subnet/SG → ssh/ssm",
            "1) Standardize golden images. 2) Automate provisioning. 3) Patch via pipelines. 4) Monitor hypervisor-level metrics.",
        ),
        "compiler": E(
            "A compiler translates source code into a lower-level form (bytecode or machine code) with analysis and optimizations.",
            "It catches many errors early and produces efficient executables/artifacts.",
            ["lex/parse", "typecheck", "IR", "optimize", "codegen"],
            "Front end parses and checks; middle end optimizes IR; back end emits code. Interpreters execute more directly; JITs compile hot paths at runtime.",
            "Long compile times vs runtime performance. Dynamic languages trade safety for flexibility.",
            "Cryptic errors: reduce to minimal repro. ABI breaks: version modules carefully.",
            "gcc -O2 -Wall hello.c -o hello && ./hello",
            "1) Enable warnings as errors in CI. 2) Pin toolchain versions. 3) Cache builds. 4) Test across supported targets.",
        ),
        "garbage collection": E(
            "Garbage collection automatically reclaims heap objects no longer reachable, reducing manual free errors.",
            "It prevents many use-after-free bugs at the cost of pauses and CPU.",
            ["reachability", "generations", "mark-sweep/copying", "pause times", "allocation rate"],
            "Collector finds live objects from roots and reclaims the rest. Generational GCs exploit infant mortality. Tuning heap size affects frequency/pause.",
            "Manual memory can be tighter for embedded/hard realtime. RC (refcount) is predictable but cycles need handling.",
            "Latency spikes: profile GC pauses and allocation churn. Leaks still happen via unintended retained references.",
            "# Java example mindset: -Xmx, GC logs\n# Node: clinic/heap snapshots for retained paths",
            "1) Measure allocation hotspots. 2) Bound caches. 3) Tune heap with load tests. 4) Watch p99 during GC.",
        ),
        "stack memory": E(
            "Stack memory holds function frames (locals, return addresses) and grows/shrinks automatically with calls.",
            "It is fast and scoped to call lifetime, unlike heap allocations.",
            ["frame", "SP/BP", "automatic storage", "overflow", "vs heap"],
            "Call pushes frame; return pops. Large stack arrays risk overflow—use heap for big/variable lifetimes.",
            "Thread stacks are finite; deep recursion is dangerous. Heap is shared and needs management/GC.",
            "Stack overflow crashes: reduce depth or heap-allocate. Corruption: look for buffer overflows on stack buffers in native code.",
            "# prefer heap for large buffers\nbuf = bytearray(10_000_000)",
            "1) Keep stack frames small. 2) Bound recursion. 3) Enable stack protectors in native builds.",
        ),
        "scope and lifetime": E(
            "Scope is where a name is visible; lifetime is how long a value exists in memory.",
            "Confusing them causes use-after-free, leaks, and surprising closures.",
            ["lexical scope", "global/module", "stack lifetime", "heap lifetime", "closures capturing vars"],
            "Locals exist for the call; heap objects until unreachable; closures extend lifetimes by retaining references.",
            "Long lifetimes increase memory; too-short lifetimes cause dangling references in native languages.",
            "Leaks: retained closures/caches. Dangling: pointers outliving owners—use ownership types/GC.",
            "def make():\n    x = []\n    def add(v): x.append(v); return x\n    return add  # x lives with closure",
            "1) Prefer tight scopes. 2) Avoid unintended captures. 3) Clear references when done with large graphs.",
        ),
        "static typing": E(
            "Static typing checks types at compile/check time before runtime, catching whole classes of bugs early.",
            "It documents interfaces and enables better tooling/refactors.",
            ["compile-time checks", "type inference", "gradual typing", "generics", "soundness vs pragmatism"],
            "Annotate or infer types; compiler/typechecker rejects mismatches. Gradual systems (TypeScript/mypy) allow incremental adoption.",
            "Dynamic typing speeds prototyping but shifts errors to runtime. Overly complex types can slow teams.",
            "Type errors after refactor: fix at boundaries first. Escape hatches (any) hide bugs—minimize them.",
            "def area(w: float, h: float) -> float:\n    return w * h",
            "1) Enable typechecker in CI. 2) Type public APIs first. 3) Ban unchecked any in new code. 4) Generate types from OpenAPI when useful.",
        ),
        "value semantics": E(
            "Value semantics means variables behave like independent values (copies); mutating one does not affect another.",
            "It reduces aliasing bugs compared to shared references.",
            ["copy vs reference", "immutability", "defensive copy", "structural sharing", "equality by value"],
            "Languages copy small values; larger structures may be references. Immutable persistent structures give value-like safety with sharing.",
            "Reference semantics are cheaper for big objects but create alias surprises. Be explicit at API boundaries.",
            "Unexpected shared mutation: you passed a reference. Freeze/copy at boundaries.",
            "a = [1,2]; b = list(a); b.append(3)  # a unchanged",
            "1) Prefer immutable DTOs across threads. 2) Copy at trust boundaries. 3) Document mutability in APIs.",
        ),
        "encapsulation": E(
            "Encapsulation hides internal representation behind a stable interface so callers depend on behavior, not fields.",
            "It limits blast radius of changes and preserves invariants.",
            ["visibility", "invariants", "getters vs behavior", "modules/classes", "information hiding"],
            "Keep fields private; expose methods that maintain invariants. Modules export a minimal surface.",
            "Over-encapsulation can yield anemic getters; under-encapsulation couples everything to fields.",
            "Broken invariants: find leaked mutable references. Tighten interfaces and add tests for invariants.",
            "class BankAccount:\n    def __init__(self): self._balance = 0\n    def deposit(self, n): \n        assert n > 0; self._balance += n",
            "1) Make fields private by default. 2) Test invariants. 3) Review public API surface in PRs.",
        ),
        "inheritance": E(
            "Inheritance lets a class derive behavior/structure from a parent, forming an is-a hierarchy.",
            "It reuses code but can couple hierarchies if overused.",
            ["is-a", "override", "LSP", "abstract base", "composition alternative"],
            "Child receives parent members; overrides specialize. Prefer shallow hierarchies; call super carefully.",
            "Composition/interfaces often beat deep inheritance (fragile base class). Use inheritance for true behavioral subtypes.",
            "LSP violations: child breaks parent expectations—favor interfaces and composition.",
            "class Animal:\n    def speak(self): raise NotImplementedError\nclass Dog(Animal):\n    def speak(self): return 'woof'",
            "1) Prefer composition. 2) Keep hierarchies shallow. 3) Enforce LSP with subtype tests.",
        ),
        "polymorphism": E(
            "Polymorphism lets one interface handle many concrete types (runtime dispatch or generics).",
            "It enables extensibility without rewriting callers for each variant.",
            ["subtype polymorphism", "ad-hoc (overloading)", "parametric (generics)", "interfaces/traits", "dispatch"],
            "Callers depend on an interface; concrete types implement it. Generics parameterize algorithms over types statically.",
            "Too many runtime types hurt clarity; switch statements may be simpler for closed sets (prefer sum types when available).",
            "Wrong method called: check vtables/overrides. Prefer explicit interfaces over duck typing at boundaries.",
            "from typing import Protocol\nclass Writer(Protocol):\n    def write(self, s: str) -> None: ...",
            "1) Define interfaces at boundaries. 2) Keep closed sets explicit. 3) Use generics for containers/algorithms.",
        ),
        "interfaces and abstract classes": E(
            "Interfaces (and abstract classes) define required behaviors without committing to a full implementation.",
            "They enable polymorphism and test doubles while keeping modules decoupled.",
            ["contract", "multiple implementations", "dependency inversion", "abstract vs interface", "default methods"],
            "Declare methods a type must support; implementations provide behavior. Depend on abstractions in high-level modules.",
            "Abstract classes can share code but couple inheritance; interfaces are thinner. Avoid interface bloat.",
            "Missing methods fail compile/typecheck—good. Runtime surprises mean you used dynamic typing without checks.",
            "class Clock(Protocol):\n    def now(self) -> float: ...",
            "1) Introduce interfaces at volatile boundaries. 2) Keep them minimal. 3) Provide fakes for tests.",
        ),
        "SOLID principles": E(
            "SOLID is five OOP design heuristics: SRP, OCP, LSP, ISP, DIP—guiding maintainable module boundaries.",
            "They reduce brittle coupling as systems grow.",
            ["single responsibility", "open/closed", "Liskov", "interface segregation", "dependency inversion"],
            "Keep modules focused; extend via new types; don’t break subtypes; prefer small interfaces; depend on abstractions. Apply pragmatically, not dogmatically.",
            "Over-abstracting creates ceremony; under-applying creates spaghetti. Balance with YAGNI.",
            "Painful changes spanning many classes signal SRP/DIP issues—redraw boundaries.",
            "# DIP: high-level OrderService depends on PaymentGateway interface, not StripeClient directly",
            "1) Review PRs for boundary smells. 2) Extract interfaces when third parties appear. 3) Refactor when change cost rises.",
        ),
        "unit testing": E(
            "Unit tests verify a small unit (function/class) in isolation with fast, deterministic assertions.",
            "They catch regressions early and document expected behavior.",
            ["arrange-act-assert", "test doubles", "determinism", "coverage vs value", "fast feedback"],
            "Instantiate unit, stub dependencies, assert outputs/state. Keep tests independent and parallelizable.",
            "Over-mocking tests implementation not behavior. Integration tests catch wiring issues unit tests miss.",
            "Flakes: time/randomness/order dependence—freeze time and seed RNG. Fix by isolating side effects.",
            "def test_add():\n    assert add(2, 3) == 5",
            "1) Add tests around bugs. 2) Run in CI on every PR. 3) Keep unit suite < few minutes. 4) Pair with integration tests.",
        ),
        "mock": E(
            "A mock/stub/fake replaces a dependency so tests control inputs and assert interactions without real I/O.",
            "It keeps unit tests fast and focused when collaborators are slow or nondeterministic.",
            ["stub vs mock vs fake", "behavior verification", "over-mocking risk", "contract fidelity"],
            "Inject a test double implementing the interface; configure return values; optionally assert called with args.",
            "Too many mocks make tests brittle. Prefer fakes (in-memory DB) for richer behavior.",
            "Tests pass but prod fails: doubles drifted from real contracts—add contract tests.",
            "from unittest.mock import Mock\npayments = Mock(); payments.charge.return_value = 'ok'\nassert charge_order(payments, 10) == 'ok'\npayments.charge.assert_called_once()",
            "1) Mock at boundaries only. 2) Prefer fakes for storage. 3) Add a contract test against real sandbox periodically.",
        ),
        "continuous integration": E(
            "Continuous integration frequently merges work and runs automated builds/tests to detect integration failures early.",
            "It prevents long-lived branch hell and keeps main releasable.",
            ["frequent merges", "automated pipeline", "fast feedback", "broken main policy", "artifacts"],
            "Each commit/PR triggers build+test(+lint). Failures block merge. Main stays green; fix forward or revert quickly.",
            "Slow pipelines reduce compliance. Over-heavy CI wastes compute—parallelize and cache.",
            "Flaky tests erode trust—quarantine with owners. Cache poisoning: key caches by lockfiles.",
            "name: ci\non: [push, pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: npm test",
            "1) Require CI status on main. 2) Keep suite fast. 3) Ban flaky ignores without tickets. 4) Publish build artifacts.",
        ),
        "relational model": E(
            "The relational model stores data as relations (tables) of tuples (rows) with typed attributes, queried declaratively with SQL.",
            "It provides a clear algebra for joins/filters and underpins ACID databases.",
            ["tables/keys", "relations", "declarative SQL", "integrity constraints", "normalization"],
            "Define schemas with keys/FKs; query with relational operators (select/project/join). Engine picks plans.",
            "Document DBs fit flexible hierarchies; warehouses may denormalize for analytics. Relational shines for integrity-heavy OLTP.",
            "Unexpected join fanout: check keys/cardinality. Use EXPLAIN.",
            "SELECT u.name, o.total FROM users u JOIN orders o ON o.user_id = u.id;",
            "1) Model entities/keys first. 2) Add FKs where integrity matters. 3) Index join/filter columns. 4) Review with EXPLAIN.",
        ),
        "normalization": E(
            "Normalization organizes relational schemas to reduce redundancy and update anomalies (1NF/2NF/3NF/BCNF).",
            "It keeps each fact stored once so updates stay consistent.",
            ["1NF atomicity", "2NF full dependency on key", "3NF no transitive deps", "anomalies", "controlled denormalization"],
            "Identify keys and functional dependencies; decompose tables so non-keys depend only on keys. Denormalize later for read performance with clear sync rules.",
            "Over-normalization can force heavy joins; warehouses often denormalize. OLTP usually prefers higher normal forms.",
            "Update anomalies (same fact many places) signal under-normalization. Painful joins may justify materialized views.",
            "-- bad: orders(order_id, customer_name, customer_city)\n-- better: customers(id,name,city); orders(id, customer_id)",
            "1) Draw FDs. 2) Normalize OLTP schemas. 3) Denormalize only with measured need. 4) Document derived data refresh.",
        ),
        "SQL joins": E(
            "SQL joins combine rows from tables based on match conditions (INNER/LEFT/RIGHT/FULL).",
            "They reassemble normalized data into application-ready results.",
            ["INNER", "LEFT OUTER", "predicates", "join cardinality", "anti-join patterns"],
            "Engine matches rows on ON/USING. INNER keeps matches; LEFT keeps all left rows with NULLs on right when missing.",
            "Application-side joins cause N+1. Huge joins need indexes. CROSS JOIN explodes cardinality if unintentional.",
            "Unexpected NULLs: outer join. Row explosion: check many-to-many without bridging filters—validate counts.",
            "SELECT u.id, o.id FROM users u LEFT JOIN orders o ON o.user_id = u.id WHERE o.id IS NULL; -- users with no orders",
            "1) Index join keys. 2) Prefer SQL joins over app loops. 3) EXPLAIN large joins. 4) Test edge unmatched rows.",
        ),
        "database index": E(
            "A database index is an auxiliary structure (often B-tree) that speeds lookups/sorts/joins at write and storage cost.",
            "Without indexes, planners fall back to sequential scans that grow with table size.",
            ["B-tree", "selectivity", "covering indexes", "write amplification", "left-most prefix"],
            "CREATE INDEX builds a sorted structure on key columns. Planner chooses index vs seq scan via stats. Composites help leftmost prefixes.",
            "Too many indexes slow writes and bloat storage. Partial/expression indexes target specific workloads.",
            "Unused indexes waste writes—track usage. Wrong order in composites yields seq scans—verify with EXPLAIN.",
            "CREATE INDEX CONCURRENTLY idx_orders_user_created ON orders(user_id, created_at DESC);",
            "1) Index FK/filter/sort columns. 2) EXPLAIN slow queries. 3) Drop unused indexes. 4) Create concurrently in prod.",
        ),
        "ACID transactions": E(
            "ACID transactions group DB operations into atomic, consistent, isolated, durable units of work.",
            "They prevent partial updates and define concurrency correctness under failures.",
            ["atomicity", "consistency", "isolation levels", "durability/WAL", "commit/rollback"],
            "BEGIN work; on success COMMIT (WAL flush for durability); on error ROLLBACK. Isolation level controls what concurrent txns see.",
            "Strong isolation reduces anomalies but increases aborts/latency. Long transactions hold locks/bloat—keep them short.",
            "Partial writes after crash: check durability settings. Contention: shorten txns and retry serialization failures.",
            "BEGIN;\nUPDATE accounts SET bal = bal - 10 WHERE id = 1;\nUPDATE accounts SET bal = bal + 10 WHERE id = 2;\nCOMMIT;",
            "1) Put multi-row invariants in transactions. 2) Keep them short. 3) Set isolation deliberately. 4) Test crash/restart.",
        ),
        "symmetric encryption": E(
            "Symmetric encryption uses the same secret key to encrypt and decrypt (AES-GCM, ChaCha20-Poly1305).",
            "It provides confidentiality (and integrity with AEADs) for data at rest/in transit after keys are shared.",
            ["shared key", "AEAD", "nonce/IV uniqueness", "key rotation", "vs asymmetric"],
            "AEAD encrypts plaintext with key+nonce and produces ciphertext+tag. Never reuse nonces with the same key for GCM. Wrap keys with KMS.",
            "Key distribution is hard—use TLS/asymmetric to establish keys. Homegrown crypto fails; use vetted libraries.",
            "Auth failures: wrong key/nonce/AAD. Audits: ensure nonce uniqueness and rotation.",
            "# conceptual: ciphertext = AESGCM(key).encrypt(nonce, plaintext, aad)",
            "1) Use KMS-managed keys. 2) Prefer AEAD modes. 3) Rotate keys. 4) Encrypt sensitive columns/files deliberately.",
        ),
    }
