# High-quality backend interview knowledge cards.

def C(summary, problem, concepts, mechanics, tradeoffs, troubleshoot, example, integration):
    return {
        "summary": summary,
        "problem": problem,
        "concepts": concepts,
        "mechanics": mechanics,
        "tradeoffs": tradeoffs,
        "troubleshoot": troubleshoot,
        "example": example,
        "integration": integration,
    }


BACKEND = {
    "_general": C(
        "Backend interviews test HTTP semantics, data integrity, authn/z, and operational failure modes under load.",
        "Surface-level framework trivia without invariants (idempotency, timeouts, authz) fails real production scenarios.",
        ["API contracts", "consistency & idempotency", "observability", "failure isolation"],
        "State the invariant, describe the request path, name failure modes, and say how you detect/alert them.",
        "Prefer simple designs with clear ownership over distributed complexity you cannot operate.",
        "Ask for symptoms, SLOs, and recent changes before proposing rewrites.",
        "curl -i -X POST \"$API/orders\" -H \"Idempotency-Key: $(uuidgen)\" -H \"Authorization: Bearer $TOKEN\"",
        "1) Clarify invariants. 2) Implement smallest correct path. 3) Add tests/metrics. 4) Document runbooks. 5) Load-test critical flows.",
    ),
    "API integration test": C(
        "API integration tests exercise HTTP handlers against real-ish dependencies (DB/testcontainers) to verify contracts end-to-end.",
        "Unit-only suites miss wiring bugs in pipes, auth guards, and migrations.",
        ["test app bootstrap", "test DB", "fixtures", "assert status/body/headers"],
        "Boot Nest/Express app, seed data, call HTTP, assert response and side effects, reset DB between tests.",
        "Slower than unit tests but higher confidence; keep a focused suite, not full prod clones.",
        "On flake, isolate shared DB state and time dependence.",
        "const res = await request(app.getHttpServer()).post('/items').send({name:'a'}).expect(201);",
        "1) Add testcontainers/DB. 2) Write critical-path API tests. 3) Run on PR. 4) Keep unit tests for pure logic.",
    ),
    "API versioning": C(
        "API versioning evolves contracts without silently breaking existing clients—via URL, headers, or media types.",
        "Breaking field meanings in place strand old mobile apps that cannot force-upgrade instantly.",
        ["compatibility windows", "URI vs header versioning", "deprecation policy", "additive changes first"],
        "Prefer additive changes; when breaking, introduce v2, dual-run, migrate clients, then sunset with metrics.",
        "URL versions are obvious but noisy; header versions are clean but harder to explore. Avoid infinite parallel versions.",
        "If clients break, check which fields changed meaning and whether you shipped a silent break.",
        "# /v1/orders vs /v2/orders\nGET /v2/orders HTTP/1.1\nAccept: application/vnd.myapp.v2+json",
        "1) Publish compatibility policy. 2) Version only on breaks. 3) Dual-write/read as needed. 4) Track version usage. 5) Sunset with notice.",
    ),
    "Buffer": C(
        "Buffer is Node's fixed-size binary memory type for bytes from sockets, files, and crypto.",
        "Treating binary as UTF-8 strings corrupts data; unsafe Buffer alloc can leak memory contents.",
        ["Buffer.from", "alloc vs allocUnsafe", "encoding", "Uint8Array interop"],
        "Use Buffer.from/alloc for binary, set encodings explicitly, prefer Uint8Array APIs when portable.",
        "Buffers are fast but easy to misuse with encodings; streams often beat giant buffers for large payloads.",
        "If you see replacement characters, you decoded with the wrong encoding.",
        "const buf = Buffer.from('hello', 'utf8');\nbuf.toString('hex');",
        "1) Ban allocUnsafe without overwrite. 2) Explicit encodings. 3) Stream large payloads. 4) Add binary fixtures in tests.",
    ),
    "CPU-bound workload": C(
        "CPU-bound work saturates the Node event loop when run on the main thread, delaying all requests.",
        "Heavy JSON parse/crypto/image work in request handlers creates latency spikes under concurrency.",
        ["event loop blocking", "worker threads", "offload queues", "time budgets"],
        "Measure loop lag, move CPU to worker_threads/native addons/queues, and set timeouts/backpressure.",
        "Workers add complexity; for rare heavy jobs prefer async queues over in-request compute.",
        "If p99 latency rises with CPU, check event-loop delay metrics and profiles.",
        "import { Worker } from 'node:worker_threads';\nconst w = new Worker(new URL('./heavy.js', import.meta.url));",
        "1) Profile. 2) Move hot CPU off-loop. 3) Queue long jobs. 4) Alert on loop delay.",
    ),
    "DDD bounded context": C(
        "A bounded context is a linguistic and model boundary in DDD where terms have a specific meaning and a dedicated model.",
        "One enterprise-wide User model conflates meanings and creates brittle coupling across domains.",
        ["ubiquitous language", "context maps", "anti-corruption layer", "explicit boundaries"],
        "Split models by language/team ownership, translate at edges, and keep transactions within a context when possible.",
        "Too many contexts create distributed complexity; too few recreate the ball of mud.",
        "If teams argue over field meanings, you've crossed a context without a map.",
        "// orders.CustomerId vs crm.AccountId — different models, mapped at ACL",
        "1) Name contexts. 2) Draw context map. 3) Split schemas/modules. 4) Add ACLs. 5) Align teams to boundaries.",
    ),
    "DTO validation": C(
        "DTO validation checks inbound shapes at the API boundary so invalid data never reaches domain logic.",
        "Trusting client JSON enables mass assignment and subtle invariant breaks.",
        ["whitelist properties", "class-validator/zod", "transform pipes", "fail fast 400"],
        "Define DTOs/schemas, reject unknown fields, validate types/ranges, and return structured errors.",
        "Strict validation improves safety but needs careful versioning when clients lag.",
        "If bad payloads succeed, ensure ValidationPipe whitelist+forbidNonWhitelisted is on.",
        "@IsString() @MinLength(1) name: string;\n// ValidationPipe({ whitelist: true, forbidNonWhitelisted: true })",
        "1) Add schema validation globally. 2) Forbid unknown props. 3) Share error format. 4) Contract-test samples.",
    ),
    "ES modules": C(
        "ESM is Node's official module system with import/export, better static analysis, and asynchronous loading semantics.",
        "Dual CJS/ESM packages cause 'ERR_REQUIRE_ESM' and duplicated instances of singleton libs.",
        ["type:module", "import assertions/attributes", "interop with CJS", "package exports"],
        "Prefer ESM for new code, set package exports carefully, and avoid dual publishing pitfalls.",
        "ESM is future-proof but some tooling/CJS deps still friction; use documented interop patterns.",
        "If default import is undefined, check CJS interop and named export mismatch.",
        "// package.json\n{ \"type\": \"module\", \"exports\": { \".\": \"./dist/index.js\" } }",
        "1) Adopt ESM. 2) Fix exports map. 3) Resolve dual-package hazards. 4) Update loaders/tests.",
    ),
    "HTTP semantics": C(
        "HTTP semantics define methods, status codes, headers, and idempotency expectations clients rely on.",
        "Misusing GET for mutations or 200 for creates breaks caches and client logic.",
        ["safe/idempotent methods", "status classes", "cache headers", "content negotiation"],
        "Use method meaning correctly, pick precise statuses, document error bodies, and set cache headers deliberately.",
        "Pragmatic APIs sometimes bend REST purity—document deviations explicitly.",
        "If CDNs cache POSTs or miss GETs, review method safety and Cache-Control.",
        "POST /orders → 201 Created + Location\nPUT /orders/{id} → idempotent replace",
        "1) Document method semantics. 2) Standardize error envelope. 3) Add contract tests. 4) Review caching.",
    ),
    "JWT access token": C(
        "JWTs are signed bearer tokens carrying claims so APIs can authenticate without server session lookup each time.",
        "Long-lived JWTs in localStorage are hard to revoke and XSS-stealable; trusting unverified tokens is fatal.",
        ["header.payload.signature", "exp/iss/aud", "signature verify", "short TTL + refresh"],
        "Issue short-lived access tokens, verify signature/exp/aud, authorize from claims, and store refresh tokens carefully (often httpOnly).",
        "Stateless scale vs revocation difficulty; use blocklists or short TTL+refresh rotation for logout.",
        "If forged tokens work, you skipped verify or used a weak secret; rotate keys and validate aud/iss.",
        "const payload = await jose.jwtVerify(token, key, { issuer, audience });",
        "1) Short TTL access tokens. 2) Verify all claims. 3) Secure refresh storage. 4) Rotate keys. 5) Prefer opaque tokens if revocation is critical.",
    ),
    "N+1 query problem": C(
        "N+1 happens when code runs one query plus one query per row instead of a batched join/IN query.",
        "ORMs make N+1 easy via lazy relations, melting databases under list endpoints.",
        ["detect via query logs", "join/dataloader", "eager load", "batch size"],
        "Log SQL counts, eager-load or batch IDs, and add tests that fail when query count regresses.",
        "Joins can over-fetch; dataloaders batch well for graphs. Pick based on shape.",
        "APM showing thousands of similar SELECTs is classic N+1—fix the loop.",
        "// Bad: for (const u of users) await postsByUser(u.id)\n// Good: SELECT * FROM posts WHERE user_id = ANY($1)",
        "1) Enable query logging in tests. 2) Fix list endpoints. 3) Add query-count budgets. 4) Review ORM includes.",
    ),
    "NestJS": C(
        "NestJS is a structured Node framework using modules, DI, controllers, and providers inspired by Angular patterns.",
        "Unstructured Express apps become hard to test and navigate as teams grow.",
        ["modules", "DI container", "controllers/providers", "pipes/guards/interceptors"],
        "Organize by module, inject dependencies via constructors, push logic to services, and keep controllers thin.",
        "Structure helps large apps but can feel heavy for tiny scripts—don't over-module early.",
        "If DI fails (undefined provider), check module exports/imports and provider scope.",
        "@Injectable() class OrdersService {\n  constructor(private readonly repo: OrdersRepo) {}\n}",
        "1) Scaffold Nest module per domain. 2) Wire DI. 3) Add ValidationPipe. 4) Test with TestingModule. 5) Document module boundaries.",
    ),
    "Node streams": C(
        "Streams process data in chunks (Readable/Writable/Transform/Duplex) to bound memory for large I/O.",
        "Buffering entire uploads/downloads in memory OOMs under concurrency.",
        ["backpressure", "pipe/pipeline", "objectMode", "error propagation"],
        "Use stream.pipeline for error-safe piping, respect backpressure, and prefer streaming parsers for large payloads.",
        "Streams are efficient but harder APIs; for small JSON, buffers are fine.",
        "If memory grows, you likely buffered; ensure pipe and pause/resume work.",
        "import { pipeline } from 'node:stream/promises';\nawait pipeline(fs.createReadStream(src), gzip, fs.createWriteStream(dst));",
        "1) Stream uploads to object storage. 2) Use pipeline. 3) Handle errors. 4) Load-test large files.",
    ),
    "Node.js event loop": C(
        "Node's event loop multiplexes async I/O on a single JS thread, offloading some work to libuv's threadpool.",
        "Blocking the loop with sync CPU/fs calls stalls all requests.",
        ["phases (timers, poll, check)", "microtasks", "libuv threadpool", "loop delay metrics"],
        "Keep handlers non-blocking, tune UV_THREADPOOL_SIZE for fs/dns/crypto, and monitor event-loop lag.",
        "Single-threaded simplicity vs CPU scaling limits—use clustering/workers for CPU.",
        "High lag with low CPU may be sync FS; profile with clinic/0x.",
        "setImmediate(() => console.log('check phase'));\nawait fs.promises.readFile(path); // non-blocking API",
        "1) Ban sync FS in request path. 2) Monitor loop delay. 3) Offload CPU. 4) Tune threadpool if needed.",
    ),
    "OAuth 2.0": C(
        "OAuth 2.0 delegates authorization so clients obtain access tokens without handling user passwords directly.",
        "Wrong grant types (implicit for SPAs) and missing PKCE enable token theft.",
        ["authorization code + PKCE", "client types", "scopes", "refresh tokens"],
        "Use auth code with PKCE for public clients, limit scopes, rotate refresh tokens, and validate tokens on APIs.",
        "OAuth complexity vs building login yourself—prefer trusted IdPs. Don't invent crypto.",
        "If redirect attacks succeed, check redirect URI allowlists and state/PKCE params.",
        "// Authorize: /authorize?response_type=code&client_id=...&code_challenge=...\n// Token: exchange code + code_verifier",
        "1) Pick IdP. 2) Auth code+PKCE. 3) Tight redirect URIs. 4) Scope minimally. 5) Secure refresh rotation.",
    ),
    "ORM": C(
        "ORMs map tables to objects/query builders to speed CRUD while abstracting SQL dialects.",
        "Hiding SQL entirely invites N+1, unpredictable queries, and weak indexes.",
        ["unit of work", "lazy vs eager", "migrations", "raw SQL escape hatch"],
        "Use ORM for CRUD, explain critical queries, drop to SQL for complex reporting, and own migrations.",
        "Productivity vs control; hybrid approaches (Prisma + SQL) are common.",
        "If slow endpoints appear, EXPLAIN ORM SQL and check includes/joins.",
        "const users = await prisma.user.findMany({ include: { posts: true } });",
        "1) Adopt ORM with migrations. 2) Log SQL in staging. 3) Index hot paths. 4) Allow raw SQL where needed.",
    ),
    "OpenAPI": C(
        "OpenAPI describes HTTP APIs machine-readably for docs, client SDKs, and contract tests.",
        "Undocumented APIs drift and break consumers silently.",
        ["paths/schemas", "codegen", "request validation", "contract testing"],
        "Maintain spec as source or generate from code, publish docs, and fail CI on breaking changes.",
        "Spec-first vs code-first: choose based on consumer needs; keep them synced.",
        "If clients diverge, diff OpenAPI in CI and version breaks.",
        "openapi: 3.1.0\npaths:\n  /health:\n    get:\n      responses:\n        '200': { description: OK }",
        "1) Introduce OpenAPI. 2) Generate docs/clients. 3) Validate requests. 4) Breaking-change CI gate.",
    ),
    "PostgreSQL full-text search": C(
        "Postgres FTS uses tsvector/tsquery and GIN indexes for linguistic search inside the database.",
        "ILIKE '%term%' cannot use normal B-tree indexes efficiently at scale.",
        ["tsvector", "GIN", "ranking", "language configs"],
        "Maintain tsvector columns/triggers, GIN index them, query with to_tsquery, and rank with ts_rank.",
        "FTS is good enough for many apps; specialized search engines win for relevance/facets at larger scale.",
        "If searches sequential-scan, verify GIN and vector maintenance.",
        "CREATE INDEX ON articles USING GIN (to_tsvector('english', body));\nSELECT * FROM articles WHERE to_tsvector('english', body) @@ plainto_tsquery('english', $1);",
        "1) Add tsvector+GIN. 2) Rank results. 3) Measure. 4) Consider OpenSearch if relevance needs grow.",
    ),
    "RBAC": C(
        "Role-based access control grants permissions via roles assigned to subjects rather than per-user ACLs alone.",
        "Hard-coded role checks scattered in controllers drift and miss edge routes.",
        ["roles/permissions", "least privilege", "role explosion risk", "resource checks beyond roles"],
        "Centralize permission maps, enforce in guards, and combine with resource ownership checks for multi-tenant data.",
        "RBAC is simple until roles explode; ABAC/ReBAC may fit complex domains.",
        "If unauthorized access works, add integration tests per role and audit default-deny.",
        "@Roles('admin') @UseGuards(AuthGuard, RolesGuard)\n@Delete(':id') remove() {}",
        "1) Define permission matrix. 2) Enforce in guards. 3) Default deny. 4) Audit logs. 5) Test each role.",
    ),
    "REST resource design": C(
        "REST resource design models nouns as resources with HTTP methods acting on representations and hypermedia/relations as needed.",
        "RPC-ish endpoints (/doThing) proliferate and confuse caching/idempotency.",
        ["resources & collections", "status codes", "pagination filters", "idempotent methods"],
        "Name resources consistently, use plural collections, nest carefully, and document error shapes.",
        "Pure REST vs pragmatic RPC: choose clarity for clients; consistency beats dogma.",
        "If clients misuse methods, your docs/examples are unclear—tighten contract tests.",
        "GET /orders/{id}\nPOST /orders\nPATCH /orders/{id}",
        "1) Agree naming conventions. 2) Map verbs to methods. 3) Add OpenAPI. 4) Review nesting depth.",
    ),
    "RabbitMQ": C(
        "RabbitMQ is a message broker implementing AMQP with exchanges, queues, bindings, and ack semantics for async work.",
        "Sync chains between services create fragility; unacked consumers redeliver forever without poison handling.",
        ["exchange types", "acks/nacks", "prefetch", "DLQ"],
        "Publish to exchanges, consume with manual ack after success, set prefetch, and route failures to DLQ.",
        "Brokers decouple producers/consumers but add ops burden; managed queues trade control for simplicity.",
        "If messages pile up, check consumer errors, prefetch, and routing keys.",
        "channel.consume(queue, async (msg) => {\n  await handle(msg);\n  channel.ack(msg);\n});",
        "1) Define topology. 2) Idempotent consumers. 3) DLQ+alerts. 4) Load-test prefetch. 5) Document schemas.",
    ),
    "Redis TTL": C(
        "Redis TTL expires keys automatically—used for sessions, locks, and cache entries that must not live forever.",
        "Keys without TTL grow memory forever; locks without TTL deadlock holders that crash.",
        ["EX/PX", "EXPIRE", "TTL command", "volatile eviction policies"],
        "Set TTL on write (SET key val EX seconds), renew deliberately for sessions, and monitor evictions.",
        "Short TTL reduces staleness/memory but increases misses; sliding sessions need careful refresh.",
        "If memory high, find keys without TTL (SCAN) and add expires or eviction policy.",
        "SET session:123 '{...}' EX 3600\nSET lock:order:9 token NX EX 30",
        "1) Default TTL on cache keys. 2) TTL all locks. 3) Alert memory. 4) Document key prefixes.",
    ),
    "SSE": C(
        "Server-Sent Events stream one-way text events over HTTP from server to browser—simple live updates.",
        "Polling wastes load; full WebSockets are heavier when only server→client is needed.",
        ["text/event-stream", "Last-Event-ID resume", "auto reconnect", "proxy buffering issues"],
        "Send event-stream responses, write named events, include ids for resume, and disable proxy buffering.",
        "SSE is simple but unidirectional and has connection limits per browser; WS needed for bidirectional chat.",
        "If events delay, check nginx buffering and compression settings.",
        "res.writeHead(200, { 'Content-Type': 'text/event-stream' });\nres.write('id: 1\\ndata: hello\\n\\n');",
        "1) Pick SSE for one-way feeds. 2) Add event ids. 3) Configure proxies. 4) Heartbeat comments. 5) Auth the stream.",
    ),
    "SSRF": C(
        "Server-side request forgery tricks your server into requesting internal URLs (metadata, admin panels) on an attacker's behalf.",
        "URL-fetch features without allowlists expose cloud metadata (169.254.169.254) and intranet services.",
        ["allowlist schemes/hosts", "block link-local", "no follow to private IPs", "metadata hardening"],
        "Validate URLs, resolve DNS and deny private ranges, restrict protocols, and prefer allowlists over denylists.",
        "Allowlists are safer but less flexible for user webhooks—use egress proxies with policy.",
        "Test with internal IPs; if reachable, fix validation and IMDS hop limits.",
        "// Reject private/link-local after DNS resolve before fetch",
        "1) Inventory URL fetchers. 2) Allowlist. 3) Block private CIDRs. 4) Lock down cloud metadata. 5) Add security tests.",
    ),
    "URL shortener": C(
        "URL shorteners map compact codes to destination URLs with redirects, analytics, and abuse controls.",
        "Predictable IDs enable scraping; missing HTTPS/open-redirect checks enable phishing.",
        ["code generation", "301/302 semantics", "rate limits", "abuse detection"],
        "Generate unguessable codes, store mapping, redirect safely after validation, and monitor for malware URLs.",
        "Short TTLs vs permanent links; analytics storage can dominate cost.",
        "If collisions occur, increase code space and check uniqueness constraints.",
        "INSERT INTO links(code,url) VALUES($1,$2) ON CONFLICT DO NOTHING;\n// GET /:code → 302 Location: url",
        "1) Design code space. 2) Validate destinations. 3) Rate-limit creates. 4) Abuse scanning. 5) Cache redirects.",
    ),
    "WebSocket": C(
        "WebSockets provide full-duplex channels over a long-lived TCP connection after an HTTP upgrade.",
        "Using request/response for high-frequency bidirectional chat adds latency and load.",
        ["upgrade handshake", "frames", "heartbeats", "horizontal scale via pubsub"],
        "Authenticate on connect, heartbeat, handle reconnect, and fanout via Redis/NATS when multiple nodes.",
        "Stateful connections complicate load balancing; SSE/polling may suffice for simpler cases.",
        "If intermittent drops, check idle timeouts/proxies and ping intervals.",
        "const ws = new WebSocket(url);\nws.on('message', handle);\nsetInterval(() => ws.ping(), 30000);",
        "1) Auth connect. 2) Heartbeats. 3) Pub/sub for multi-instance. 4) Backpressure limits. 5) Reconnect protocol.",
    ),
    "at-least-once delivery": C(
        "At-least-once delivery means consumers may see duplicates after retries; handlers must be idempotent.",
        "Assuming exactly-once without a dedupe store double-charges or double-emails.",
        ["acks/retries", "idempotency keys", "dedupe stores", "poison messages"],
        "Acknowledge only after durable side effects, store processed keys, and send poison messages to DLQ.",
        "Exactly-once is rare/expensive; usually at-least-once + idempotency is the practical design.",
        "If duplicates appear, add idempotency table unique constraints.",
        "INSERT INTO processed_events(id) VALUES($1) ON CONFLICT DO NOTHING; -- skip if not inserted",
        "1) Make handlers idempotent. 2) Persist dedupe keys. 3) DLQ. 4) Metric retries/dupes.",
    ),
    "backpressure": C(
        "Backpressure signals producers to slow down when consumers/queues cannot keep up, preventing unbounded memory growth.",
        "Unbounded buffers under load OOM the process while appearing 'fine' until collapse.",
        ["high-water marks", "pause/resume streams", "queue length limits", "load shedding"],
        "Set max queue sizes, use stream backpressure, return 429/503 when overloaded, and autoscale on lag.",
        "Dropping/shedding hurts UX but saves the system; buffering hides problems until failure.",
        "Watch queue depth and RSS; if both climb, apply limits.",
        "if (queue.length > MAX) return res.status(503).json({ error: 'overloaded' });",
        "1) Define limits. 2) Shed load. 3) Alert on depth. 4) Load-test. 5) Document degraded modes.",
    ),
    "cache invalidation": C(
        "Cache invalidation removes or updates stale entries so readers see fresh data after writes.",
        "TTL-only caches serve stale critical data; manual deletes miss keys and leave ghosts.",
        ["TTL", "write-through/around", "tag-based purge", "event invalidation"],
        "Choose strategy per data: short TTL, explicit delete on write, or versioned keys after mutations.",
        "Invalidation complexity is famous; sometimes prefer short TTL over perfect coherence.",
        "If stale after write, log keys written vs invalidated and check race windows.",
        "await redis.del(`user:${id}`);\nawait redis.set(`user:${id}`, json, 'EX', 60);",
        "1) Classify data freshness needs. 2) Invalidate on write paths. 3) Version keys. 4) Monitor stale incidents.",
    ),
    "cache-aside": C(
        "Cache-aside (lazy loading) has the app read cache, on miss load DB then populate cache; writes update DB then invalidate cache.",
        "Write-through everywhere can slow writes; never caching thrashes DB.",
        ["get→miss→load→set", "invalidate on write", "stampede control", "TTL"],
        "Implement getOrLoad with single-flight, set TTL, and delete/update cache after successful writes.",
        "Simple and common; stampeding herd on expiry needs locking or probabilistic early expire.",
        "If DB spikes at TTL boundaries, add stampede protection.",
        "let v = await redis.get(key);\nif (!v) { v = await db.load(); await redis.set(key, v, 'EX', 60); }",
        "1) Wrap reads. 2) Invalidate writes. 3) Stampede guard. 4) Metrics hit ratio.",
    ),
    "chat backend": C(
        "Chat backends manage rooms, membership, message persistence, fanout, and presence with ordering guarantees.",
        "Naive broadcast without persistence loses history; missing authz leaks private rooms.",
        ["message ordering", "fanout", "presence", "moderation/abuse"],
        "Persist first (or reliably enqueue), fanout via pub/sub, authorize membership, and paginate history by cursor.",
        "Fanout-on-write scales differently than fanout-on-read; choose by room size distribution.",
        "If messages reorder, include monotonic server timestamps/ids and sort on client.",
        "await db.messages.insert(msg);\nawait pub.publish(`room:${id}`, msg);",
        "1) Schema messages. 2) Authz rooms. 3) Pub/sub fanout. 4) History API. 5) Rate-limit sends.",
    ),
    "circuit breaker": C(
        "Circuit breakers stop calling a failing dependency temporarily, failing fast and allowing recovery.",
        "Retry storms against a down dependency amplify outages.",
        ["closed/open/half-open", "error thresholds", "cooldown", "fallback"],
        "Trip open after error rate/latency thresholds, short-circuit calls, probe in half-open, and serve fallbacks.",
        "Breakers protect systems but hide dependency issues if alerts missing; tune thresholds carefully.",
        "If breaker flaps, raise windows or fix timeouts that are too aggressive.",
        "// pseudo: if failures/total > 50% in 30s → open for 20s",
        "1) Wrap critical clients. 2) Set thresholds. 3) Fallback behavior. 4) Alert on open. 5) Test chaos.",
    ),
    "connection pool": C(
        "Connection pools reuse DB/TCP connections to avoid handshake overhead and limit concurrent connections.",
        "Unbounded connections exhaust Postgres max_connections under traffic spikes.",
        ["pool size", "idle timeout", "checkout timeout", "pgbouncer"],
        "Size pools per instance relative to DB limits, fail fast on checkout timeout, and prefer transaction pooling for many tenants.",
        "Larger pools increase throughput until DB CPU/locks contend; measure.",
        "If 'too many connections', reduce app pools or add pgbouncer.",
        "// Prisma/Nest: set connection_limit in DATABASE_URL",
        "1) Calculate budgets. 2) Cap pools. 3) Add timeouts. 4) Monitor wait time. 5) Consider pgbouncer.",
    ),
    "contract testing": C(
        "Contract tests verify producer/consumer API expectations (schemas, status codes) without full E2E environments.",
        "Frontend/backend drift breaks production when only manual QA exists.",
        ["consumer-driven contracts", "OpenAPI diff", "pact-like flows", "CI gates"],
        "Publish contracts, validate both sides in CI, and break builds on incompatible changes.",
        "Contracts catch interface bugs early but not full business logic—still need some E2E.",
        "If false positives, version contracts and allow additive changes.",
        "// CI: oasdiff / openapi-diff against main; fail on breaking",
        "1) Choose contract format. 2) Generate/validate in CI. 3) Version breaks. 4) Notify consumers.",
    ),
    "controller": C(
        "Controllers adapt HTTP to application commands: parse input, call services, map results to status codes.",
        "Fat controllers with business logic become untestable and duplicated across transports.",
        ["thin controllers", "DTO in", "service call", "HTTP mapping"],
        "Validate DTOs, authorize, call services, return DTOs—no SQL in controllers.",
        "Very thin vs useful orchestration: keep orchestration minimal and explicit.",
        "If hard to unit test, logic is in the controller—extract services.",
        "@Post() create(@Body() dto: CreateOrderDto) {\n  return this.orders.create(dto);\n}",
        "1) Thin controllers. 2) Move logic to services. 3) Shared DTO validation. 4) Controller integration tests only for wiring.",
    ),
    "correlation ID": C(
        "Correlation IDs propagate a request identifier across services/logs so you can reconstruct a single transaction's path.",
        "Disconnected logs make multi-service incidents nearly impossible to triage.",
        ["generate at edge", "propagate headers", "include in logs", "trace linkage"],
        "Create/accept X-Request-Id, store in async local storage, inject into outbound calls and structured logs.",
        "IDs alone aren't distributed tracing spans, but they are a minimal must-have.",
        "If IDs change mid-flight, a client is overwriting—preserve inbound IDs when present.",
        "const id = req.headers['x-request-id'] ?? crypto.randomUUID();\nlogger.info({ requestId: id }, 'handling');",
        "1) Middleware generate/propagate. 2) ALS storage. 3) Outbound inject. 4) Log field standard. 5) Dashboards by id.",
    ),
    "distributed lock": C(
        "Distributed locks coordinate mutual exclusion across processes using Redis/etcd with TTLs and safe ownership tokens.",
        "Locks without TTL deadlock after crashes; non-token unlocks delete someone else's lock.",
        ["SET NX EX", "ownership token", "TTL heartbeat", "fencing tokens ideally"],
        "Acquire with NX+TTL+token, extend if needed, unlock only with token compare, and design for lock loss.",
        "Locks are hard to get perfectly correct; prefer DB uniqueness constraints when possible.",
        "If two holders run, TTLs expired—shorten critical sections or use fencing.",
        "SET lock:job:1 token NX EX 30\n-- unlock via Lua compare-and-del token",
        "1) Prefer DB constraints. 2) If Redis lock, token+TTL. 3) Keep critical section tiny. 4) Chaos-test expiry.",
    ),
    "distributed tracing": C(
        "Distributed tracing records spans across services (OpenTelemetry) to visualize latency and errors in a request graph.",
        "Metrics alone cannot show which downstream hop caused a slow request.",
        ["trace/span context", "W3C headers", "sampling", "baggage caution"],
        "Instrument frameworks, propagate context, export to a backend, and sample appropriately.",
        "High sampling costs money; too low misses rare bugs. Tail-based sampling helps.",
        "If traces broken, check header propagation and clock skew.",
        "// OTel Node auto-instrument Nest/HTTP and export OTLP",
        "1) Add OTel SDK. 2) Propagate headers. 3) Sample. 4) Link logs via trace_id. 5) Create service maps.",
    ),
    "dynamic module": C(
        "Nest dynamic modules configure providers at import time via forRoot/forRootAsync for reusable libraries.",
        "Hard-coded config in shared modules prevents reuse across environments.",
        ["forRoot/forRootAsync", "module exports", "injection tokens", "global modules sparingly"],
        "Expose register methods that accept config, provide tokens, and export services for importers.",
        "Dynamic modules are flexible but harder to follow—document tokens clearly.",
        "If config undefined, Async factory deps aren't imported—wire ConfigModule.",
        "static forRoot(options: Opts): DynamicModule {\n  return { module: FooModule, providers: [{ provide: OPTS, useValue: options }], exports: [FooService] };\n}",
        "1) Convert shared libs to forRootAsync. 2) Inject config tokens. 3) Document. 4) Test module compile.",
    ),
    "environment configuration": C(
        "Environment configuration injects 12-factor settings (DB URLs, secrets, feature flags) without baking them into images.",
        "Committed secrets and undocumented env vars cause breaches and 'works on my machine' failures.",
        ["12-factor env", "schema validation", "secrets vs config", "per-env overlays"],
        "Load env via ConfigModule, validate with zod/joi at boot, fail fast on missing required vars.",
        "Many envs increase matrix complexity; prefer same artifact, different config.",
        "If boot succeeds with wrong DB, validation is incomplete—require critical keys.",
        "const env = z.object({ DATABASE_URL: z.string().url() }).parse(process.env);",
        "1) Schema-validate env at boot. 2) Keep secrets in a vault. 3) Document vars. 4) Same image across envs.",
    ),
    "execution context": C(
        "Nest ExecutionContext wraps the current request handler info so guards/interceptors can introspect class/handler/protocol.",
        "Auth logic that assumes HTTP fails for GraphQL/RPC or can't read metadata reflectors.",
        ["switchToHttp", "getHandler/getClass", "reflector metadata", "multi-protocol"],
        "Use context.switchToHttp().getRequest() for HTTP, read roles via Reflector, keep guards protocol-aware.",
        "Abstraction helps multi-transport apps; pure HTTP apps can keep it simple.",
        "If request is undefined, wrong switch method for transport.",
        "const req = ctx.switchToHttp().getRequest();\nconst roles = this.reflector.get('roles', ctx.getHandler());",
        "1) Centralize guards using ExecutionContext. 2) Use Reflector. 3) Test HTTP+any other transports.",
    ),
    "graceful shutdown": C(
        "Graceful shutdown stops accepting new work, drains in-flight requests/jobs, then exits—critical for deploys/K8s.",
        "Hard kills mid-write cause partial transactions and connection resets for clients.",
        ["SIGTERM handling", "server.close", "drain timeouts", "stop consumers first"],
        "Listen for SIGTERM, stop health readiness, close HTTP server with timeout, flush telemetry, then exit.",
        "Long drains delay rollouts; too short cuts requests—align with LB idle timeouts.",
        "If pods get SIGKILL, drain exceeds terminationGracePeriodSeconds—tune both.",
        "process.on('SIGTERM', async () => {\n  await app.close();\n  process.exit(0);\n});",
        "1) Handle SIGTERM. 2) Fail readiness first. 3) Drain with timeout. 4) Align K8s grace. 5) Test rolling deploys.",
    ),
    "guard": C(
        "Nest guards determine whether a route can run (authn/authz), running after middleware and before pipes/interceptors.",
        "Auth checks duplicated in services are easy to miss on new endpoints.",
        ["CanActivate", "Reflector roles", "default deny", "throw Unauthorized/Forbidden"],
        "Implement CanActivate, read metadata, validate credentials/permissions, and register globally or per-route.",
        "Guards keep controllers clean; over-smart guards become mini-frameworks—keep focused.",
        "If open routes exist, enforce global auth with explicit @Public() opt-outs.",
        "@Injectable() class AuthGuard implements CanActivate {\n  canActivate(ctx: ExecutionContext) { /* verify JWT */ return true; }\n}",
        "1) Global AuthGuard. 2) Role metadata. 3) @Public exceptions. 4) Integration tests per role.",
    ),
    "hexagonal architecture": C(
        "Hexagonal (ports & adapters) isolates domain logic from delivery/persistence adapters via interfaces.",
        "Domain code that imports Nest/ORM details becomes untestable outside the framework.",
        ["ports", "adapters", "domain core", "dependency direction inward"],
        "Define ports in domain, implement adapters for DB/HTTP, inject via DI at composition root.",
        "Clear boundaries vs more indirection; apply where complexity justifies.",
        "If tests need DB for domain rules, boundary leaked—introduce ports.",
        "// domain/OrderService depends on OrderRepository port\n// infra/PrismaOrderRepository implements port",
        "1) Identify domain core. 2) Define ports. 3) Move ORM to adapters. 4) Test domain pure. 5) Wire in Nest module.",
    ),
    "idempotency": C(
        "Idempotency ensures repeating the same logical request (retries) does not apply side effects twice.",
        "Network retries on POST without keys double-charge payments and create duplicate rows.",
        ["Idempotency-Key", "dedupe store", "same response replay", "fingerprint requests"],
        "Require keys on mutating POSTs, store response/status by key+actor, and replay on retries.",
        "Storage cost vs safety; TTL keys carefully. PUT/DELETE are often naturally idempotent.",
        "If duplicates appear, keys missing or uniqueness not enforced atomically.",
        "UNIQUE(user_id, idempotency_key)\n-- return stored response when key exists",
        "1) Add Idempotency-Key on payments. 2) Persist outcomes. 3) Atomic insert. 4) Client retry policy. 5) Metrics.",
    ),
    "interceptor": C(
        "Nest interceptors wrap handler execution for cross-cutting concerns: logging, mapping, caching, timeouts.",
        "Duplicated try/catch mapping in every controller drifts.",
        ["RxJS map/tap", "pre/post handler", "transform DTOs", "error mapping carefully"],
        "Implement NestInterceptor, use next.handle().pipe(...), and register globally when broadly useful.",
        "Powerful but opaque if overused; prefer pipes for validation and filters for errors.",
        "If response shape wrong, check interceptor order.",
        "@Injectable() class TimingInterceptor {\n  intercept(ctx, next) {\n    const t = Date.now();\n    return next.handle().pipe(tap(() => console.log(Date.now()-t)));\n  }\n}",
        "1) Add logging/transform interceptors. 2) Keep them focused. 3) Document order. 4) Test.",
    ),
    "job queue": C(
        "Job queues persist background work (emails, image processing) with retries, concurrency, and delayed jobs.",
        "Doing slow work in HTTP requests times out and couples UX to downstream failures.",
        ["enqueue", "workers", "retries/backoff", "idempotent jobs"],
        "Enqueue from API after durable write, process in workers, retry with backoff, DLQ failures.",
        "Queues improve resilience but require ops (Redis/BullMQ). Sync may be fine for tiny tasks.",
        "If jobs stuck, check worker health, failed sets, and poison payloads.",
        "await queue.add('email', { userId }, { attempts: 5, backoff: { type: 'exponential', delay: 1000 } });",
        "1) Introduce queue. 2) Move slow tasks. 3) Idempotent workers. 4) DLQ alerts. 5) Dashboard lag.",
    ),
    "keep-alive": C(
        "HTTP keep-alive reuses TCP connections for multiple requests, reducing handshake latency.",
        "Disabled keep-alive under load spikes latency/CPU on TLS handshakes.",
        ["Connection: keep-alive", "agent pooling", "idle timeouts", "LB alignment"],
        "Enable keep-alive agents for outbound HTTP, tune idle timeouts vs LBs, and monitor connection churn.",
        "Too-long idle can hit middlebox timeouts; too-short loses benefits.",
        "If many SYN packets, agents aren't reusing—fix agent config.",
        "const agent = new https.Agent({ keepAlive: true, maxSockets: 64 });",
        "1) Enable agents. 2) Align timeouts. 3) Load-test. 4) Monitor churn.",
    ),
    "libuv thread pool": C(
        "libuv's threadpool (default 4) handles some Node fs/dns/crypto tasks off the JS thread.",
        "Saturating the pool makes fs-heavy apps appear 'blocked' even when the JS loop looks idle.",
        ["UV_THREADPOOL_SIZE", "fs/dns/crypto offload", "pool saturation", "native addons"],
        "Measure, increase threadpool judiciously, prefer async APIs, and move heavy CPU to dedicated workers.",
        "Bigger pools help until hardware saturates; not a fix for bad algorithms.",
        "If fs latency high with idle loop, pool may be saturated—profile.",
        "UV_THREADPOOL_SIZE=16 node dist/main.js",
        "1) Measure fs/crypto latency. 2) Tune pool. 3) Offload extreme CPU. 4) Document runtime env.",
    ),
    "load balancing": C(
        "Load balancers distribute traffic across instances for scale and availability with health checks.",
        "Uneven routing and failing health checks cause cascading overload on remaining nodes.",
        ["L4 vs L7", "health checks", "sticky sessions caution", "connection draining"],
        "Place LB in front, health-check readiness, drain on deploy, and keep services as stateless as possible.",
        "Sticky sessions ease stateful apps but hurt failover; prefer shared stores.",
        "If one node hot, check sticky cookies and unbalanced least-conn settings.",
        "# readiness fails during drain; LB removes instance before SIGTERM completes",
        "1) Stateless services. 2) Readiness probes. 3) Connection drain. 4) Test failover. 5) Watch per-node RPS.",
    ),
    "mass assignment": C(
        "Mass assignment occurs when clients set sensitive fields (role, balance) because APIs bind raw JSON into models.",
        "Without allowlists, attackers escalate privileges via extra JSON properties.",
        ["allowlist DTO fields", "forbid non-whitelisted", "separate write models", "never bind entities directly"],
        "Use DTOs with explicit fields, forbid unknowns, and map manually to domain updates.",
        "Strict DTOs add boilerplate but prevent an entire vulnerability class.",
        "Try posting role:admin; if accepted, fix whitelist immediately.",
        "ValidationPipe({ whitelist: true, forbidNonWhitelisted: true })",
        "1) DTO allowlists. 2) Forbid extras. 3) Security tests. 4) Review ORM entity binding.",
    ),
    "metrics": C(
        "Metrics are numeric time-series (counters/histograms/gauges) for RED/USE monitoring and alerting.",
        "Logs alone cannot efficiently compute p99 or error rates across fleets.",
        ["counter/histogram/gauge", "labels cardinality", "SLO burn alerts", "exemplars"],
        "Instrument request rate/errors/duration, keep label cardinality bounded, and alert on SLO burn.",
        "Too many labels explode TSDB cost; too few can't debug.",
        "If metrics missing, check exporter scrape configs and service discovery.",
        "http_request_duration_seconds_bucket{path=\"/orders\",status=\"200\"}",
        "1) Add RED metrics. 2) Bound labels. 3) SLO alerts. 4) Dashboard golden signals.",
    ),
    "middleware": C(
        "Middleware sits in the HTTP pipeline before routing finishes concerns like logging, CORS, and raw body parsing.",
        "Order mistakes break auth (parsing body after auth) or double-parse payloads.",
        ["order matters", "req/res/next", "Nest middleware vs Express", "keep thin"],
        "Register cross-cutting HTTP concerns early, call next, and prefer guards/pipes for Nest-specific logic.",
        "Middleware is flexible but less typed than Nest guards; use the right layer.",
        "If req.body empty, parser middleware missing or consumed earlier.",
        "consumer.apply(LoggerMiddleware).forRoutes('*');",
        "1) Map pipeline order. 2) Keep middleware thin. 3) Prefer guards for auth. 4) Test order-sensitive paths.",
    ),
    "modular monolith": C(
        "A modular monolith is a single deployable with strong internal module boundaries—often the best step before microservices.",
        "Microservices too early multiply ops cost without real team/scale need.",
        ["module boundaries", "no cross-DB joins secretly", "clear APIs", "extract later"],
        "Enforce module public APIs, separate schemas if needed, and forbid deep imports via lint.",
        "One deploy is simple; still requires discipline or it becomes a monolith ball of mud.",
        "If modules circularly import, boundaries are wrong—revisit context map.",
        "orders/ public API only; inventory/ cannot import orders/internal/*",
        "1) Define modules. 2) Lint boundaries. 3) Separate tables ownership. 4) Extract service only with evidence.",
    ),
    "module": C(
        "Nest modules group providers/controllers and control export/import visibility for DI encapsulation.",
        "Everything-in-AppModule recreates a global mess and circular DI pain.",
        ["imports/exports", "providers", "feature modules", "global modules sparingly"],
        "Create feature modules, export only public providers, import what you need, avoid circular imports.",
        "More modules clarify ownership but increase wiring; find a balance.",
        "If Nest can't resolve deps, check exports of the providing module.",
        "@Module({ imports: [DbModule], controllers: [OrdersController], providers: [OrdersService], exports: [OrdersService] })",
        "1) Split feature modules. 2) Export minimally. 3) Fix cycles. 4) Document public providers.",
    ),
    "multi-tenant SaaS": C(
        "Multi-tenant SaaS serves many customers with isolation via tenant_id, schemas, or separate databases.",
        "Missing tenant filters leak data across customers—the worst class of bug.",
        ["tenant context", "row-level filters", "isolation levels", "per-tenant limits"],
        "Resolve tenant per request, enforce filters in data layer, test cross-tenant access attempts, and isolate noisy neighbors.",
        "Shared DB is cheaper; separate DBs isolate better at higher cost.",
        " pen-test with another tenant's IDs; must 404/403.",
        "WHERE id = $1 AND tenant_id = $2",
        "1) Tenant context middleware. 2) Enforce in repo layer. 3) Automated cross-tenant tests. 4) Quotas. 5) Audit logs.",
    ),
    "notification service": C(
        "Notification services fan out email/SMS/push with templates, preferences, and delivery receipts.",
        "Sending directly from many services duplicates logic and ignores user preferences/unsubscribes.",
        ["channels", "templates", "preference center", "idempotent sends"],
        "Enqueue notification commands, render templates, respect prefs/unsub, and retry with provider webhooks.",
        "Central service adds latency/ops but prevents spam and inconsistency.",
        "If duplicates, idempotency keys missing on provider calls.",
        "await notify.enqueue({ userId, template: 'welcome', channel: 'email' });",
        "1) Centralize notifications. 2) Prefs/unsub. 3) Idempotent provider calls. 4) Webhook status. 5) Metrics per channel.",
    ),
    "object storage": C(
        "Object storage (S3-compatible) stores blobs by key with durability and cheap scale vs local disk.",
        "App servers storing files locally lose data on redeploy and don't scale horizontally.",
        ["buckets/keys", "presigned URLs", "content-type", "lifecycle policies"],
        "Upload via presigned URLs or server streams, store keys in DB, set lifecycle/encryption, and scan for malware if user content.",
        "Public buckets are dangerous; prefer private + presign. Egress costs can surprise.",
        "If 403 on get, check IAM and presign expiry.",
        "const url = await s3.getSignedUrl('putObject', { Bucket, Key, Expires: 900 });",
        "1) Private buckets. 2) Presigned upload. 3) Persist keys. 4) Lifecycle rules. 5) Virus scan if needed.",
    ),
    "optimistic locking": C(
        "Optimistic locking detects concurrent updates via version columns instead of holding long DB locks.",
        "Lost updates occur when two readers write stale copies last-write-wins.",
        ["version column", "compare-and-update", "retry on conflict", "409 responses"],
        "Include version in UPDATE ... WHERE version=old; increment; on 0 rows return conflict for client retry.",
        "Better concurrency than pessimistic locks for low contention; high contention needs different design.",
        "If silent overwrites happen, version not checked—fix SQL.",
        "UPDATE accounts SET bal=$1, version=version+1 WHERE id=$2 AND version=$3",
        "1) Add version columns. 2) Enforce in repo. 3) Return 409. 4) Client refresh/retry. 5) Test concurrent writers.",
    ),
    "pagination": C(
        "Pagination returns result windows via offset/limit or cursors/keyset for stable large lists.",
        "Huge unbounded lists time out and freeze UIs; offset deep pages get slow and inconsistent under inserts.",
        ["limit/offset", "keyset/cursor", "stable sort keys", "total count cost"],
        "Prefer keyset on indexed (created_at,id), return next cursor, and avoid counting every time if expensive.",
        "Offset is simple for admin UIs; cursors for feeds at scale.",
        "If duplicates/skips while scrolling, sort key unstable—add unique tiebreaker.",
        "SELECT * FROM items WHERE (created_at, id) < ($1, $2) ORDER BY created_at DESC, id DESC LIMIT 20",
        "1) Replace offset feeds with cursors. 2) Index sort keys. 3) Document cursor opacity. 4) Optional approx totals.",
    ),
    "password hashing": C(
        "Password hashing stores one-way salted hashes (Argon2/bcrypt) so breaches don't reveal raw passwords.",
        "Plaintext or fast hashes (MD5) make credential stuffing trivial after a leak.",
        ["Argon2id/bcrypt", "unique salt", "work factor", "never log passwords"],
        "Hash with Argon2id, tune memory/time, compare in constant time, and migrate legacy hashes on login.",
        "Higher work factors harden security but increase CPU—balance with UX and DoS protections.",
        "If login CPU spikes, attackers may be DoSing hashing—rate-limit and CAPTCHA.",
        "const hash = await argon2.hash(password, { type: argon2.argon2id });",
        "1) Argon2id. 2) Rate-limit auth. 3) Migrate old hashes. 4) Breach monitoring. 5) Forbid password logs.",
    ),
    "payment API": C(
        "Payment APIs must be idempotent, PCI-aware (usually via providers), and explicit about capture/refund states.",
        "Retries without idempotency double-charge; storing raw card data creates compliance nightmares.",
        ["idempotency keys", "provider tokens", "state machine", "webhooks reconciliation"],
        "Use a PSP, store tokens not PANs, idempotent create/capture, verify webhooks, and reconcile ledgers.",
        "Building your own card vault is almost never worth it—use Stripe-like providers.",
        "If money mismatches, reconcile provider events vs ledger by payment id.",
        "POST /v1/charges Idempotency-Key: ...\n# webhook: payment_intent.succeeded → mark paid",
        "1) Integrate PSP. 2) Idempotent charges. 3) Webhook verify. 4) Ledger entries. 5) Reconciliation job.",
    ),
    "pipe": C(
        "Nest pipes transform and validate input (ValidationPipe, ParseUUIDPipe) before handlers run.",
        "Manual parsing in every handler duplicates and misses edge cases.",
        ["transform", "validate", "throw BadRequest", "global pipes"],
        "Register ValidationPipe globally, use param pipes, and keep transformations explicit.",
        "Pipes are perfect for input; don't hide domain rules inside them.",
        "If validation skipped, pipe not global and route lacks DTO types.",
        "app.useGlobalPipes(new ValidationPipe({ whitelist: true, transform: true }));",
        "1) Global ValidationPipe. 2) Param pipes. 3) Structured errors. 4) Tests for invalid payloads.",
    ),
    "profiling": C(
        "Profiling samples CPU/heap to find hot functions and leaks instead of guessing.",
        "Optimizing without profiles wastes time on the wrong 90%.",
        ["CPU profiles", "heap snapshots", "flamegraphs", "prod continuous profiling"],
        "Capture under realistic load, open flamegraphs, fix top frames, and re-measure.",
        "Sampling overhead is usually small; still avoid leaving debug profilers always-on carelessly.",
        "If profiles empty, missing symbols/source maps—fix build flags.",
        "node --cpu-prof dist/main.js\n# or clinic flame / 0x",
        "1) Baseline latency. 2) Profile under load. 3) Fix top hotspots. 4) Automate periodic profiles in staging.",
    ),
    "provider and dependency injection": C(
        "Nest providers are injectable classes/values registered in modules; DI wires constructor dependencies automatically.",
        "Manual `new Service()` bypasses DI and makes testing/lifecycle hooks harder.",
        ["constructor injection", "tokens", "scopes", "testing overrides"],
        "Annotate @Injectable, register providers, inject via constructor, override in tests with custom providers.",
        "DI clarifies graphs but circular deps signal design smells.",
        "If undefined dependency, provider missing from module providers/exports.",
        "constructor(private readonly users: UsersService) {}",
        "1) Register providers. 2) Inject constructors. 3) Use tokens for interfaces. 4) Override in tests.",
    ),
    "provider scopes": C(
        "Nest provider scopes (DEFAULT singleton, REQUEST, TRANSIENT) control instance lifetime.",
        "Request-scoped providers bubble and can surprise performance if overused.",
        ["singleton default", "REQUEST scope", "TRANSIENT", "scope chain"],
        "Keep most services singleton; use REQUEST for request-bound context sparingly; understand scope propagation.",
        "Request scope solves context passing but hurts throughput—prefer ALS for request ids when possible.",
        "If memory grows per request, a request-scoped tree is retaining too much.",
        "@Injectable({ scope: Scope.REQUEST }) class TenantContext {}",
        "1) Default singleton. 2) Limit REQUEST scope. 3) Measure. 4) Prefer ALS for simple context.",
    ),
    "race condition": C(
        "Race conditions occur when concurrent operations interleave unsafely on shared state, yielding lost updates or duplicates.",
        "Check-then-act without transactions/constraints fails under concurrency.",
        ["read-modify-write", "unique constraints", "transactions", "optimistic versions"],
        "Enforce invariants in DB constraints/transactions, avoid TOCTOU, and test with parallel requests.",
        "App-level locks are fragile vs DB constraints; prefer DB as source of truth.",
        "Reproduce with parallel k6/ab; if fails, add constraint/transaction.",
        "BEGIN;\nSELECT ... FOR UPDATE;\nUPDATE ...;\nCOMMIT;",
        "1) Identify shared invariants. 2) Enforce in DB. 3) Concurrent tests. 4) Remove check-then-act.",
    ),
    "rate limiting": C(
        "Rate limiting caps request rates per key (IP/user/API key) to protect availability and control abuse.",
        "Unauthenticated expensive endpoints get DoSed or scraped.",
        ["token bucket/fixed window", "key choice", "429 + Retry-After", "distributed stores"],
        "Apply limits at edge/API gateway and app, return 429 with headers, and store counters in Redis for multi-node.",
        "Strict limits protect systems but can block NAT users sharing IPs—prefer user keys when authenticated.",
        "If limit not enforced across nodes, local memory store—move to Redis.",
        "@Throttle(100, 60) // 100 req / 60s\n// or nginx limit_req",
        "1) Identify expensive routes. 2) Redis-backed limits. 3) 429 headers. 4) Tune with product. 5) Monitor.",
    ),
    "resource ownership checks": C(
        "Ownership checks ensure the authenticated principal can act only on resources they own (or are shared with).",
        "AuthN without ownership checks lets users access /orders/{someoneElsesId}.",
        ["principal id", "resource tenant/owner", "404 vs 403 policy", "centralize checks"],
        "Load resource, compare owner/tenant to principal, deny consistently, and test IDOR attempts.",
        "404 obscures existence; 403 is clearer—pick a policy and stick to it.",
        "IDOR test: authenticate as A, access B's id—must fail.",
        "if (order.userId !== user.id) throw new ForbiddenException();",
        "1) Centralize ownership helper. 2) Use on all by-id routes. 3) IDOR tests. 4) Audit logs.",
    ),
    "response serialization": C(
        "Response serialization maps domain entities to public DTOs, hiding internal fields and shaping API contracts.",
        "Returning ORM entities leaks password hashes and internal columns.",
        ["class-transformer", "exclude secrets", "view DTOs", "consistent envelopes"],
        "Use interceptor/serializer to expose allowlisted fields; never return raw entities.",
        "Manual mapping is clear; automated exclude decorators can be forgotten—review carefully.",
        "If hash leaks, entity was returned—add serialization tests.",
        "@Exclude() passwordHash: string;\n@Expose() email: string;",
        "1) Response DTOs. 2) Global serializer. 3) Leak tests. 4) Document public fields.",
    ),
    "retry and dead-letter queue": C(
        "Retries re-attempt failed jobs with backoff; DLQs hold poison messages after exhaustion for human/automated review.",
        "Infinite retries without DLQ hot-loop CPU and block queues.",
        ["exponential backoff", "max attempts", "DLQ", "alert on depth"],
        "Configure attempts/backoff, ack only on success, route to DLQ, and page on DLQ growth.",
        "Retries help transient faults; non-idempotent handlers make retries dangerous.",
        "If DLQ fills, inspect payloads and fix consumer bugs before redrive.",
        "attempts: 5, backoff: exponential, removeOnFail: false // inspect failed set / DLQ",
        "1) Idempotent consumers. 2) Backoff retries. 3) DLQ. 4) Alerts. 5) Redrive runbook.",
    ),
    "retry with backoff": C(
        "Retry with backoff spaces attempts (often exponential + jitter) to let transient faults recover without stampedes.",
        "Immediate tight retries amplify outages and trip rate limits.",
        ["exponential backoff", "jitter", "max attempts", "idempotent ops"],
        "Retry only transient errors, add jittered delay, cap attempts, and bubble final failure.",
        "Backoff helps clients and servers; don't retry non-idempotent POSTs without keys.",
        "If you still stampede, missing jitter—add randomized delay.",
        "await retry(() => fetch(url), { retries: 5, factor: 2, minTimeout: 100, jitter: true });",
        "1) Classify transient errors. 2) Library with jitter. 3) Idempotency. 4) Metrics on retry counts.",
    ),
    "saga": C(
        "Sagas coordinate multi-step business processes across services with compensating actions when a step fails.",
        "Distributed transactions (2PC) are rarely practical; partial failures leave inconsistent states.",
        ["choreography vs orchestration", "compensations", "state machine", "idempotent steps"],
        "Model steps/compensations, persist saga state, and ensure each step can retry safely.",
        "Sagas add complexity; sometimes a modular monolith transaction is better.",
        "If stuck mid-saga, inspect state store and compensation failures.",
        "// orchestrator: ReserveStock → ChargeCard → CreateShipment; compensations reverse",
        "1) Decide choreography/orchestration. 2) Persist state. 3) Compensations. 4) Timeouts. 5) Dashboards.",
    ),
    "secrets management": C(
        "Secrets management stores credentials in a vault/manager with rotation and audited access—not in git or images.",
        "Leaked .env in repos and baked Docker secrets cause breaches.",
        ["vault/KMS", "short-lived credentials", "rotation", "least privilege"],
        "Inject secrets at runtime, rotate regularly, scope IAM tightly, and scan git history for leaks.",
        "Vault ops cost vs cloud secret managers convenience—pick what you'll actually operate.",
        "If secret leaked, rotate immediately and review access logs.",
        "# AWS SM / GCP Secret Manager / Vault KV; never COPY .env into Docker images",
        "1) Move secrets to manager. 2) Remove from git. 3) Rotate. 4) IAM least privilege. 5) Pre-commit secret scan.",
    ),
    "service boundary": C(
        "Service boundaries define ownership of data and behavior so teams can deploy independently with clear contracts.",
        "Random network splits without data ownership create distributed monoliths.",
        ["data ownership", "API contracts", "synchronous vs async", "avoid shared DB"],
        "Split by domain ownership, prohibit cross-service DB access, and communicate via APIs/events.",
        "More services increase isolation and ops cost; start coarse.",
        "If you need joins across services constantly, boundary is wrong.",
        "// orders service owns orders tables; inventory exposes ReserveStock API/events",
        "1) Map ownership. 2) Kill shared DB access. 3) Publish contracts. 4) Review sync coupling.",
    ),
    "session authentication": C(
        "Session authentication stores server-side session state referenced by an opaque cookie id.",
        "Client-side-only auth without revocation options complicates logout and theft response.",
        ["opaque session id", "server store", "cookie flags", "rotation on login"],
        "Create session on login, set HttpOnly Secure SameSite cookie, validate server-side, destroy on logout.",
        "Easy revocation vs sticky store scaling; Redis sessions are common.",
        "If sessions persist after logout, destroy server record and expire cookie.",
        "req.session.userId = user.id;\n// cookie: sid=...; HttpOnly; Secure; SameSite=Lax",
        "1) Server sessions. 2) Secure cookies. 3) CSRF defenses. 4) Redis store. 5) Rotate session ids.",
    ),
    "stateless API": C(
        "Stateless APIs keep authorization/state in the request (token/headers) so any instance can serve it.",
        "In-memory session affinity complicates horizontal scale and failover.",
        ["no server affinity", "bearer tokens/cookies to shared store", "horizontal scale", "shared caches"],
        "Externalize session/cache state, verify auth each request, and design handlers without local process memory requirements.",
        "Truly stateless simplifies scale; some state (WS) still needs sticky or shared pubsub.",
        "If only one node works for a user, you have sticky state—externalize it.",
        "// JWT or session id backed by Redis — any node can validate",
        "1) Externalize state. 2) Auth each request. 3) Remove sticky needs. 4) Test multi-instance locally.",
    ),
    "streamed upload": C(
        "Streamed uploads pipe request bodies directly to storage without buffering entire files in memory.",
        "Buffering multi-GB uploads crashes Node under concurrency.",
        ["multipart parsers streaming", "content-length limits", "virus scan async", "checksums"],
        "Use streaming multipart middleware, pipe to S3, enforce size limits, and process scans asynchronously.",
        "Streaming is efficient; error handling mid-stream needs cleanup of partial objects.",
        "If RSS spikes on upload, buffering remains—switch to true streaming APIs.",
        "await pipeline(req, fs.createWriteStream(tmp)); // or s3.upload({ Body: req })",
        "1) Stream to object storage. 2) Size caps. 3) Cleanup partials. 4) Async malware scan. 5) Load-test.",
    ),
    "structured logging": C(
        "Structured logging emits JSON fields (level, msg, requestId, userId) for queryable observability.",
        "String-only logs are hard to filter and correlate during incidents.",
        ["JSON logs", "levels", "PII redaction", "correlation ids"],
        "Use pino/winston JSON, include requestIds, redact secrets/PII, and ship to a log backend.",
        "Debug logs in prod explode cost; sample or raise levels carefully.",
        "If you can't filter by user, fields missing—standardize schema.",
        "logger.info({ requestId, userId, route }, 'order_created');",
        "1) JSON logger. 2) Field standard. 3) Redaction. 4) Ship to stack. 5) Dashboards/alerts.",
    ),
    "timeout": C(
        "Timeouts bound how long you wait on dependencies so failures surface instead of hanging forever.",
        "No timeouts exhaust connection pools as requests pile up waiting on dead deps.",
        ["client timeouts", "server deadlines", "cancellation", "deadline propagation"],
        "Set explicit timeouts on HTTP/DB calls, cancel work when possible, and map to 504/503 appropriately.",
        "Too aggressive timeouts false-fail; too long hold resources—align with SLOs.",
        "If pools exhaust, hung calls without timeouts—add them and circuit breakers.",
        "await fetch(url, { signal: AbortSignal.timeout(3000) });",
        "1) Default client timeouts. 2) Propagate deadlines. 3) Align with LB. 4) Alert on timeout rates.",
    ),
    "transaction boundary": C(
        "Transaction boundaries group DB operations that must commit or roll back together to preserve invariants.",
        "Multi-step writes without transactions leave partial state on mid-failure.",
        ["ACID unit", "keep transactions short", "avoid external I/O inside", "isolation levels"],
        "Open transaction, perform related writes, commit; never call payment providers inside holding DB locks.",
        "Wide transactions increase contention; chatty small transactions can break invariants—balance carefully.",
        "If partial rows remain after errors, missing transaction or catch swallowed rollback.",
        "await prisma.$transaction(async (tx) => {\n  await tx.order.create(...);\n  await tx.stock.update(...);\n});",
        "1) Identify invariants. 2) Wrap in transactions. 3) Keep short. 4) Outbox for external side effects. 5) Tests for mid-fail.",
    ),
    "unit test": C(
        "Unit tests verify pure logic and services with dependencies mocked/faked for fast feedback.",
        "No unit tests make refactors scary; over-mocking tests implementation not behavior.",
        ["arrange-act-assert", "mock boundaries", "fast suites", "deterministic"],
        "Test domain rules with fakes, avoid mocking everything, and keep tests readable.",
        "Unit speed vs integration confidence—use both deliberately.",
        "If tests break on renames only, you over-mocked—assert behavior.",
        "it('computes tax', () => expect(tax(100, 0.1)).toBe(10));",
        "1) Unit-test domain. 2) Mock IO boundaries. 3) Fast CI target. 4) Pair with API integration tests.",
    ),
    "worker threads": C(
        "worker_threads run JS in parallel threads sharing memory optionally via SharedArrayBuffer/MessageChannel.",
        "CPU-heavy work on the main thread blocks all request handling.",
        ["Worker", "message passing", "pool workers", "transferable buffers"],
        "Offload CPU tasks to a worker pool, pass data via postMessage, and return results to the request path carefully.",
        "Threads help CPU; IO-bound work usually doesn't need them. Pool sizing matters.",
        "If still blocked, work isn't offloaded or pool is size 1 under load.",
        "import { Worker } from 'node:worker_threads';\nconst result = await runInWorker(payload);",
        "1) Identify CPU hotspots. 2) Worker pool. 3) Benchmark. 4) Fallback timeout. 5) Monitor pool queue.",
    ),
}
