# High-quality Flutter/Dart interview knowledge cards.

def C(summary, problem, concepts, mechanics, tradeoffs, troubleshoot, example, integration):
    return {
        "summary": summary,
        "problem": problem,
        "concepts": concepts,
        "mechanics": mechanics,
        "tradeoffs": tradeoffs,
        "troubleshoot": troubleshoot,
        "example": example,
        "integration": integration,
    }


FLUTTER = {
    "_general": C(
        "Flutter interviews expect a solid model of widgets→elements→render objects, rebuild cost, and async BuildContext safety.",
        "Treating Flutter like a DOM framework misses constraints, keys, and the UI-thread isolate model.",
        ["immutable widgets", "Element identity", "rebuild vs relayout/repaint", "async gaps"],
        "Explain the pipeline for the symptom (build/layout/paint), propose a minimal repro, then a fix with a widget test.",
        "Prefer composition and framework APIs over fighting the engine with hacks.",
        "Use DevTools timeline and inspector before guessing.",
        "flutter run --profile\n# DevTools → Performance / Inspector",
        "1) Reproduce. 2) Identify pipeline stage. 3) Fix with keys/state/constraints. 4) Add widget test. 5) Verify in profile mode.",
    ),
    "APNs": C(
        "APNs (Apple Push Notification service) delivers remote notifications to iOS devices via device tokens and Apple's servers.",
        "Missing entitlements, wrong env (sandbox/prod), or expired certs/keys silently drop pushes.",
        ["device token", "auth key vs certs", "payload limits", "foreground presentation"],
        "Register for notifications, send token to backend, authenticate to APNs with key, handle foreground/background differently.",
        "Keys are easier to rotate than certs; still need correct bundle id/topic.",
        "If undelivered, check token env mismatch and apns-topic.",
        "// iOS: capability Push Notifications + background modes as needed\n// Backend: JWT ES256 to api.push.apple.com",
        "1) Enable capability. 2) Capture tokens. 3) Backend APNs auth. 4) Test sandbox+prod. 5) Handle permission UX.",
    ),
    "Android permissions": C(
        "Android permissions gate sensitive APIs; dangerous permissions require runtime requests on modern SDKs.",
        "Declaring only in manifest without runtime request fails on Android 6+.",
        ["normal vs dangerous", "runtime request", "shouldShowRequestRationale", "maxSdk/version quirks"],
        "Declare in AndroidManifest, request at use-time with permission_handler, and degrade gracefully on deny.",
        "Ask too early and users deny permanently; ask in context of the feature.",
        "If permanently denied, deep-link to settings; verify merged manifest.",
        "<uses-permission android:name=\"android.permission.CAMERA\" />\nawait Permission.camera.request();",
        "1) Inventory permissions. 2) Request in-context. 3) Handle denied. 4) Test across API levels. 5) Document why each is needed.",
    ),
    "AnimationController": C(
        "AnimationController drives ticker-based animations with duration, vsync, and status listeners—usually owned by State.",
        "Controllers without disposal leak tickers; creating them in build resets animations.",
        ["vsync/TickerProvider", "forward/reverse/repeat", "CurvedAnimation", "dispose"],
        "Create controller in initState with vsync: this, drive Tween/Animation, dispose in dispose().",
        "Explicit controllers give control vs implicit animations' simplicity.",
        "If assertion about ticker, missing SingleTickerProviderStateMixin or dispose.",
        "late final controller = AnimationController(vsync: this, duration: const Duration(ms: 300));\n@override void dispose(){ controller.dispose(); super.dispose(); }",
        "1) Mixin ticker provider. 2) Own controller in State. 3) Dispose. 4) Prefer ImplicitlyAnimated for simple cases.",
    ),
    "AppLifecycleState": C(
        "AppLifecycleState reports resumed/inactive/paused/detached/hidden so you can pause work and save state.",
        "Ignoring lifecycle wastes battery with timers/sockets in background and loses draft state.",
        ["WidgetsBindingObserver", "resumed vs paused", "save on inactive", "platform differences"],
        "Add observer in initState, handle didChangeAppLifecycleState, remove observer on dispose.",
        "Mobile OS may kill paused apps; persist critical state to disk, don't rely on memory.",
        "If observer never fires, not registered or removed too early.",
        "class _S extends State with WidgetsBindingObserver {\n  @override void didChangeAppLifecycleState(AppLifecycleState s) { /* persist */ }\n}",
        "1) Observe lifecycle. 2) Pause streams/timers. 3) Persist drafts. 4) Resume carefully. 5) Test backgrounding.",
    ),
    "BLoC/Cubit": C(
        "BLoC/Cubit separate events/state from UI: Cubit exposes functions; BLoC maps events to states via streams.",
        "setState sprawl across the tree makes business logic untestable and rebuilds chaotic.",
        ["events/states", "BlocProvider", "BlocBuilder/Listener", "pure reducers"],
        "Put logic in Cubit/Bloc, provide above subtree, rebuild with builders, navigate/side effects in listeners.",
        "BLoC ceremony helps large teams; Cubit is lighter for simple state. Don't Bloc everything.",
        "If UI misses states, check equality (Equatable) and buildWhen.",
        "class CounterCubit extends Cubit<int> {\n  CounterCubit(): super(0);\n  void inc() => emit(state+1);\n}",
        "1) Introduce Cubit for a feature. 2) Provide at route. 3) Test cubit pure. 4) Listeners for side effects. 5) Avoid UI logic in widgets.",
    ),
    "BuildContext": C(
        "BuildContext is a handle to a widget's location in the tree—used to find InheritedWidgets, navigate, and theme.",
        "Using a context across async gaps after dispose, or the wrong context for Provider/Navigator, causes crashes/lookups to fail.",
        ["element location", "dependOnInheritedWidget", "mounted check", "context from builder"],
        "Use context only when mounted; capture Navigator/Theme before await or check mounted after; prefer the context that can see the ancestor you need.",
        "Passing context deep is fine; storing it long-term is not. Element APIs are advanced.",
        "If 'deactivated widget' asserts, you used context after dispose—guard with mounted.",
        "await future;\nif (!mounted) return;\nNavigator.of(context).pop();",
        "1) Audit async methods. 2) mounted checks. 3) Correct lookup context. 4) Widget tests for async nav.",
    ),
    "BuildOwner": C(
        "BuildOwner schedules and manages the build pipeline for dirty Elements in the framework.",
        "Misunderstanding who marks dirty leads to wrong optimization attempts outside the framework.",
        ["dirty elements", "build scope", "global keys registration", "pipeline owner"],
        "Widgets call setState → element marks dirty → BuildOwner rebuilds in frame; you rarely touch BuildOwner directly.",
        "Framework internals help debugging; app code should stay at widget/state layer.",
        "If infinite rebuilds, something marks dirty every build—find the setState loop.",
        "// Prefer fixing setState loops over hacking BuildOwner",
        "1) Use DevTools rebuild profiler. 2) Fix dirty loops. 3) Keep custom RenderObjects rare. 4) Read framework only when needed.",
    ),
    "Cloud Firestore": C(
        "Cloud Firestore is a document/collection NoSQL DB with realtime listeners and offline persistence popular with Flutter apps.",
        "Chatty listeners and unbounded queries explode reads/cost; poor modeling makes queries impossible.",
        ["documents/collections", "queries/indexes", "snapshots", "security rules"],
        "Model for queries, add composite indexes, listen with streams, and enforce security rules—never trust client alone.",
        "Realtime convenience vs cost/vendor lock-in; sometimes REST+SQL is simpler.",
        "If missing index errors, create suggested composite index; audit read counts.",
        "FirebaseFirestore.instance.collection('todos').where('uid', isEqualTo: uid).snapshots();",
        "1) Design collections. 2) Rules. 3) Indexes. 4) Limit listeners. 5) Monitor usage.",
    ),
    "CocoaPods": C(
        "CocoaPods manages native iOS dependencies for Flutter plugins via the Podfile in ios/.",
        "Pod version conflicts and outdated repos break `pod install` and iOS builds.",
        ["Podfile", "pod install", "platform version", "use_frameworks quirks"],
        "Run flutter pub get, cd ios && pod install, keep platform version compatible with plugins.",
        "SwiftPM is emerging; many Flutter plugins still expect CocoaPods.",
        "If install fails, update repo, clear Pods/Podfile.lock carefully, check minimum iOS version.",
        "cd ios && pod repo update && pod install",
        "1) Pin iOS platform. 2) Commit Podfile.lock. 3) CI pod install. 4) Document plugin native requirements.",
    ),
    "Codemagic/GitHub Actions": C(
        "CI systems like Codemagic and GitHub Actions build, test, and sign Flutter apps on every change.",
        "Manual local releases drift signing configs and skip tests.",
        ["workflows", "caching", "signing secrets", "matrix devices"],
        "Run analyze/test, build IPA/AAB with secrets, cache Flutter/pub, and upload artifacts.",
        "Codemagic is Flutter-focused; GHA is flexible. Choose based on team familiarity and macOS minute costs.",
        "If signing fails in CI only, check provisioning secrets and keychain unlock steps.",
        "# GHA sketch\n- uses: subosito/flutter-action@v2\n- run: flutter test && flutter build appbundle",
        "1) Add CI workflow. 2) Cache deps. 3) Store signing secrets. 4) Gate merges on tests. 5) Automate store upload carefully.",
    ),
    "CustomPainter": C(
        "CustomPainter draws via Canvas in a paint method—ideal for charts, game sprites, and custom shapes.",
        "Heavy paint without shouldRepaint optimization janks scrolling; hit testing needs extra work.",
        ["paint(Canvas, Size)", "shouldRepaint", "HitTestBehavior", "repaint boundaries"],
        "Implement painter, wrap in CustomPaint, return true from shouldRepaint only when data changes.",
        "Painter is powerful but accessibility/semantics need manual Semantics; prefer widgets when possible.",
        "If always repainting, shouldRepaint always true—compare fields.",
        "class GridPainter extends CustomPainter {\n  @override void paint(Canvas c, Size s) { /* ... */ }\n  @override bool shouldRepaint(covariant GridPainter old) => false;\n}",
        "1) Prototype with CustomPaint. 2) Optimize shouldRepaint. 3) Add semantics. 4) Profile. 5) Extract package if reused.",
    ),
    "CustomScrollView and slivers": C(
        "Slivers are scrollable-area protocols; CustomScrollView composes slivers (lists, grids, app bars) in one scroll.",
        "Nested ListViews with their own scrolls fight; pinned headers need slivers.",
        ["SliverList/Grid", "SliverAppBar", "viewport", "lazy children"],
        "Compose slivers in CustomScrollView, use builders for laziness, and keep one primary scroll.",
        "Slivers are flexible but denser API than ListView; worth it for advanced scroll UI.",
        "If shrinkWrap perf issues, you forced unbounded work—use slivers instead.",
        "CustomScrollView(slivers: [\n  SliverAppBar(pinned: true, title: Text('Feed')),\n  SliverList.builder(itemBuilder: ...),\n]);",
        "1) Replace nested scrolls with slivers. 2) Lazy builders. 3) Pinned headers. 4) Test scroll performance.",
    ),
    "Dart FFI": C(
        "Dart FFI calls native C APIs from Dart without channels—useful for shared libraries and performance-critical code.",
        "Unsafe pointers and wrong ABI cause crashes outside Dart's usual safety.",
        ["DynamicLibrary", "lookup function", "arena/malloc", "native finalizers"],
        "Load library, bind signatures with ffi, manage memory carefully, and isolate heavy native work if needed.",
        "FFI is fast and direct but platform packaging and safety are harder than Pigeon/channels for simple APIs.",
        "If segfaults, audit lifetimes and struct sizes/alignment.",
        "final nativeAdd = lib.lookupFunction<Int32 Function(Int32, Int32), int Function(int, int)>('add');",
        "1) Identify C API need. 2) Bind via ffi. 3) Harden memory. 4) Test per ABI. 5) Document packaging.",
    ),
    "Dart type system": C(
        "Dart's type system is sound with null safety, generics, and strong inference guiding safe refactors.",
        "Dynamic sprawl and bang operators (!) hide null bugs until runtime.",
        ["static types", "null safety", "generics", "typedefs/records"],
        "Type APIs explicitly, prefer nullable modeling over !, and enable strict analysis options.",
        "Strictness slows some prototyping but pays off in large apps.",
        "If analyzer disagrees with runtime, you cast incorrectly—remove casts.",
        "analysis_options.yaml: analyzer: language: strict-casts: true",
        "1) Enable strict analysis. 2) Remove dynamic. 3) Model nulls. 4) Fix analyzer issues in CI.",
    ),
    "DevTools performance timeline": C(
        "DevTools Performance timeline shows UI/Raster thread frames to diagnose jank sources.",
        "Guessing optimizations without frames data wastes time.",
        ["UI vs Raster", "frame budget ~16ms", "rebuild shading", "shader compilation jank"],
        "Run profile mode, record interaction, inspect timeline, fix rebuilds/layout/shaders accordingly.",
        "Debug mode is not representative—always profile in profile/release.",
        "If UI thread long, reduce build; if raster, simplify effects/images.",
        "flutter run --profile\n# open DevTools → Performance → record",
        "1) Profile mode. 2) Record jank. 3) Attribute UI/Raster. 4) Fix. 5) Re-measure.",
    ),
    "Drift": C(
        "Drift (moor) is a reactive Dart ORM over SQLite with type-safe queries and streams of changes.",
        "Raw sqflite SQL strings drift from models and miss reactive UI updates.",
        ["tables/DAOs", "watch queries", "migrations", "transactions"],
        "Define tables, generate code, watch selects as streams, migrate schema versions carefully.",
        "Codegen improves safety but adds build_runner complexity.",
        "If stream not updating, query not watched or transaction isolation unexpected.",
        "@DriftDatabase(tables: [Todos]) class AppDb extends _$AppDb {}",
        "1) Add Drift. 2) Define tables. 3) Migrations. 4) watch() in UI. 5) Test DAO.",
    ),
    "Element tree": C(
        "The Element tree is Flutter's mutable realization of Widgets—holding State, managing mounts, and configuring RenderObjects.",
        "Confusing Widget rebuilds with Element remounts leads to wrong key/state diagnoses.",
        ["mount/update/unmount", "State attachment", "Widget vs Element vs RenderObject", "keys guide matching"],
        "Framework matches widgets to elements by runtimeType+key; updates reuse elements; type/key changes remount.",
        "You rarely create Elements manually; understanding them debugs keys/state bugs.",
        "If State resets, Element remounted—inspect keys/types in inspector.",
        "// Changing Key or widget type at a slot remounts Element/State",
        "1) Teach three trees. 2) Fix keys. 3) Use inspector. 4) Add tests for state retention.",
    ),
    "Expanded": C(
        "Expanded is a Flex child that forces a child to consume remaining space along the main axis (flex fit tight).",
        "Putting Expanded outside Row/Column/Flex throws; unbounded flex parents fail layout.",
        ["flex factor", "Fit.tight vs Flexible", "must be flex descendant", "min/max constraints"],
        "Wrap children in Expanded/Flexible inside Row/Column to distribute leftover space.",
        "Expanded is convenient; sometimes Align/SizedBox is clearer for fixed layouts.",
        "If 'Incorrect use of ParentDataWidget', Expanded isn't under Flex.",
        "Row(children: [Text('A'), Expanded(child: Text('grows'))]);",
        "1) Use Expanded for leftover space. 2) Prefer Flexible for not-forced fill. 3) Fix unbounded lists separately.",
    ),
    "FCM": C(
        "Firebase Cloud Messaging routes push notifications to Android/iOS/web clients with topics and device tokens.",
        "Missing platform setup (APNs key, google-services) means tokens never receive messages.",
        ["device tokens", "data vs notification payloads", "topics", "foreground handlers"],
        "Integrate firebase_messaging, collect tokens, handle background isolates, and send via FCM HTTP v1.",
        "FCM simplifies cross-platform push but ties you to Google infrastructure.",
        "If iOS silent fails, check APNs key in Firebase console and background modes.",
        "FirebaseMessaging.onMessage.listen(handle);\nawait FirebaseMessaging.instance.getToken();",
        "1) Platform setup. 2) Token pipeline. 3) Handlers. 4) Topic strategy. 5) Test killed/background/foreground.",
    ),
    "Firebase Auth": C(
        "Firebase Auth provides managed identity (email, social, anonymous) with ID tokens for securing backends.",
        "Rolling your own auth incorrectly stores passwords badly and breaks multi-platform sessions.",
        ["idToken", "auth state streams", "providers", "security rules linkage"],
        "Sign in via plugin, listen authStateChanges, attach tokens to API calls, and gate Firestore rules by uid.",
        "Fast to ship vs vendor lock-in and limited enterprise IdP needs.",
        "If rules deny, print token claims and compare uid paths.",
        "FirebaseAuth.instance.authStateChanges().listen((u) => /* update app state */);",
        "1) Enable providers. 2) Wire auth stream. 3) Secure rules/API. 4) Persist session. 5) Handle account linking.",
    ),
    "Flutter Web rendering": C(
        "Flutter web can render via CanvasKit/Skwasm or HTML backends with different perf and download costs.",
        "Shipping huge CanvasKit wasm without need hurts first load on slow networks.",
        ["CanvasKit vs HTML", "wasm size", "text/SEO limits", "Loader"],
        "Choose renderer for app needs, optimize asset sizes, and understand SEO/text selection differences vs DOM apps.",
        "Flutter web is great for app-like UIs; content sites often better as HTML frameworks.",
        "If first load huge, analyze CanvasKit size and deferred imports.",
        "flutter build web --web-renderer canvaskit",
        "1) Pick renderer. 2) Measure TTI. 3) Optimize assets. 4) Decide SEO strategy. 5) Test browsers.",
    ),
    "Flutter constraints model": C(
        "Flutter layout is constraints down, sizes up: parents pass BoxConstraints, children choose a size within them.",
        "Fighting constraints with unbounded children (ListView in Column without Expanded) causes overflow/assert.",
        ["tight/loose/unbounded", "constraints → size → position", "RenderBox", "force expand via Expanded"],
        "Read incoming constraints, size child, parent positions; use Expanded/SizedBox.expand intentionally.",
        "Model is consistent once learned; coming from CSS requires unlearning some habits.",
        "If yellow/black stripes, overflow—inspect constraints in DevTools.",
        "Column(children: [\n  Expanded(child: ListView(...)), // bounded height\n]);",
        "1) Learn constraints. 2) Fix unbounded scrollables. 3) Use Inspector. 4) Document layout patterns.",
    ),
    "Flutter desktop windowing": C(
        "Flutter desktop manages native windows/menus/multi-window with platform channels and windowing plugins.",
        "Mobile-first layouts break on large resizable windows without adaptive breakpoints.",
        ["window size", "menus/shortcuts", "multi-window", "platform differences"],
        "Handle resize, provide desktop navigation patterns, and test macOS/Windows/Linux targets.",
        "One codebase helps but desktop UX expectations differ—budget polish.",
        "If content clipped, missing responsive layout for wide windows.",
        "WidgetsBinding.instance.platformDispatcher.views; // multi-view awareness",
        "1) Enable desktop targets. 2) Adaptive layout. 3) Shortcuts/menus. 4) CI per OS. 5) Polish window states.",
    ),
    "Focus system": C(
        "Flutter's focus system manages keyboard/traversal focus via FocusNode/FocusScope for accessibility and shortcuts.",
        "Custom controls without focus nodes are unreachable via keyboard.",
        ["FocusNode", "FocusTraversalPolicy", "autofocus", "onKeyEvent"],
        "Attach Focus widgets/nodes, define traversal order, and show focus highlights.",
        "Framework defaults work for many Material widgets; custom painters need manual focus.",
        "If Tab skips controls, missing focus nodes or incorrect scopes.",
        "final node = FocusNode();\nFocus(focusNode: node, child: ...);",
        "1) Audit keyboard nav. 2) Add FocusNodes. 3) Visible indicators. 4) Tests with sendKeyEvent. 5) Dispose nodes.",
    ),
    "Form validation": C(
        "Flutter Form/FormField widgets collect validators and validate() before submit with a FormState key.",
        "Creating a new GlobalKey every build resets FormState and loses field state.",
        ["GlobalKey<FormState>", "validator", "autovalidateMode", "TextFormField"],
        "Keep one Form key in State, validate on submit, show errors, and keep field controllers disposed.",
        "Form widget is fine for simple forms; complex flows may use separate state management.",
        "If validators never run, you didn't call formKey.currentState?.validate().",
        "final formKey = GlobalKey<FormState>();\nif (formKey.currentState!.validate()) { /* submit */ }",
        "1) Stable Form key. 2) Validators. 3) Dispose controllers. 4) Widget tests. 5) Server-side validate too.",
    ),
    "Freezed": C(
        "Freezed generates immutable union/data classes with copyWith, equality, and pattern matching helpers.",
        "Hand-written ==/hashCode and mutable models cause subtle state bugs in BLoC/Cubit.",
        ["immutable unions", "code generation", "when/map", "json_serializable integration"],
        "Annotate classes, run build_runner, emit states as freezed unions, and switch exhaustively.",
        "Codegen DX is great; build times and generated noise are the cost.",
        "If equality always fails, forgot freezed annotation/codegen.",
        "@freezed class AuthState with _$AuthState {\n  const factory AuthState.loading() = _Loading;\n  const factory AuthState.ready(User u) = _Ready;\n}",
        "1) Add freezed. 2) Model states. 3) Generate. 4) Exhaustive switches. 5) CI codegen check.",
    ),
    "Future": C(
        "A Future represents a single async result in Dart—completed with a value or error.",
        "Unawaited futures hide errors; using BuildContext after await without mounted checks crashes.",
        ["async/await", "Future.wait", "error handling", "microtask scheduling"],
        "Await futures, handle errors with try/catch or catchError, and parallelize with Future.wait when independent.",
        "Futures are one-shot; Streams are for multi-event. Don't convert everything to streams.",
        "If errors disappear, you forgot await/catch—use unawaited_lints.",
        "final results = await Future.wait([loadA(), loadB()]);",
        "1) Lint unawaited futures. 2) mounted after await. 3) Parallelize carefully. 4) Surface errors to UI.",
    ),
    "GlobalKey": C(
        "GlobalKey uniquely identifies an element across the tree—used for FormState and rare reparenting cases.",
        "Creating GlobalKeys in build is expensive and resets state; overuse is a smell.",
        ["unique identity", "currentState", "costly lookups", "prefer LocalKey for lists"],
        "Store GlobalKey in State fields, access currentState sparingly, prefer ValueKey for list identity.",
        "Powerful but breaks encapsulation; avoid for routine list keys.",
        "If Form resets each rebuild, GlobalKey was recreated in build.",
        "final formKey = GlobalKey<FormState>(); // field on State, not in build",
        "1) Ban GlobalKey in build. 2) Use for Form/Scaffold rarely. 3) Prefer ValueKey. 4) Review PRs for misuse.",
    ),
    "Gradle/AGP compatibility": C(
        "Android builds require compatible Gradle, Android Gradle Plugin, Kotlin, and JDK versions with Flutter's templates.",
        "Random upgrades break builds with cryptic AGP/Gradle mismatch errors.",
        ["AGP version", "Gradle wrapper", "JDK", "Flutter migrate"],
        "Follow Flutter's supported matrix, upgrade via flutter create repair/docs, and change versions together.",
        "Staying current gets Play requirements; bleeding edge breaks plugins.",
        "If build fails after upgrade, read compatibility table and align wrapper+AGP+Kotlin.",
        "// android/build.gradle AGP version must match gradle-wrapper.properties",
        "1) Track Flutter Android upgrade guides. 2) Upgrade in lockstep. 3) CI on clean checkout. 4) Pin versions.",
    ),
    "Hero animation": C(
        "Hero widgets animate a shared-tag element between routes during Navigator transitions.",
        "Duplicate tags in one route or missing pairs cause jumps instead of flights.",
        ["tag uniqueness per route", "flight controller", "rect tween", "Material rect"],
        "Wrap shared visuals with matching Hero tags on both routes; keep tags unique within a route.",
        "Heroes delight but can conflict with complex custom transitions.",
        "If two heroes conflict, tags collide—make tags include ids.",
        "Hero(tag: 'avatar-$id', child: CircleAvatar(...))",
        "1) Identify shared elements. 2) Matching tags. 3) Unique per route. 4) Test transitions. 5) Disable if a11y prefers reduced motion.",
    ),
    "Impeller rendering": C(
        "Impeller is Flutter's modern renderer aiming for predictable performance by precompiling shaders (esp. iOS).",
        "Skia runtime shader compilation caused first-animation jank on iOS.",
        ["precompiled shaders", "Metal/Vulkan backends", "feature parity journey", "profile comparisons"],
        "Use current Flutter channels where Impeller is default/enabled, profile animations, and report gaps.",
        "Impeller improves jank but may lag some rare Skia effects—verify your app.",
        "If visual bugs, try disabling Impeller to compare and file issues.",
        "flutter run --enable-impeller  # or disable per docs when debugging",
        "1) Upgrade Flutter. 2) Profile animations. 3) Validate visuals. 4) Keep repros for engine bugs.",
    ),
    "InheritedWidget": C(
        "InheritedWidget efficiently broadcasts data downward; dependents rebuild when updateShouldNotify says so.",
        "Recreating inherited values every build without notification control causes broad rebuilds—or none when needed.",
        ["dependOnInheritedWidgetOfExactType", "updateShouldNotify", "of(context) pattern", "Provider built on this"],
        "Expose static of(context), call context.dependOn..., and implement updateShouldNotify by value compare.",
        "Low-level vs Provider/Riverpod convenience—know it to debug.",
        "If child doesn't rebuild, updateShouldNotify false or not dependent (used context incorrectly).",
        "static ThemeData of(BuildContext c) => c.dependOnInheritedWidgetOfExactType<_Theme>()!.data;",
        "1) Use for true ambient data. 2) Correct of(context). 3) Notify carefully. 4) Prefer community libs for app state.",
    ),
    "IntrinsicWidth/IntrinsicHeight": C(
        "Intrinsic widgets measure children's intrinsic dimensions—expensive because they may lay out children twice.",
        "Using intrinsics in deep trees tanks performance especially in lists.",
        ["intrinsic measurements", "costly layout", "alternatives: fixed sizes/Align", "debug flags"],
        "Avoid in hot paths; prefer explicit sizes, Expanded, or Align; profile if needed.",
        "Sometimes correct for menus; almost never inside each list row.",
        "If jank in layout phase, search for Intrinsics in tree.",
        "// Prefer sized widgets over IntrinsicWidth in ListView children",
        "1) Ban Intrinsics in lists via review. 2) Replace with constraints. 3) Profile layout. 4) Document exceptions.",
    ),
    "Key": C(
        "Keys (ValueKey/ObjectKey/UniqueKey/GlobalKey) tell Flutter which Element to match when reordering/updating widgets.",
        "Index-based identity loses State on reorder; UniqueKey every build remounts always.",
        ["local vs global keys", "ValueKey(id)", "Element matching", "State preservation"],
        "Assign ValueKey with stable business ids on list children that hold State.",
        "Keys solve identity; they are not for styling. Don't over-key static children.",
        "If form fields shuffle values after reorder, fix keys.",
        "ListView.builder(itemBuilder: (_, i) => TodoRow(key: ValueKey(todos[i].id), todo: todos[i]));",
        "1) Audit list keys. 2) Stable ids. 3) Widget tests reorder. 4) Reserve GlobalKey.",
    ),
    "LayoutBuilder": C(
        "LayoutBuilder rebuilds its builder with the parent's incoming BoxConstraints—enabling responsive branching.",
        "MediaQuery-only breakpoints ignore that a widget may live in a narrow sidebar.",
        ["constraints.maxWidth", "responsive branches", "avoid heavy work in builder", "nested builders cost"],
        "Branch UI on constraints, keep builders light, and combine with flexible layouts.",
        "Powerful for components; overusing nested LayoutBuilders adds rebuild noise.",
        "If always getting unbounded, parent passed unbounded constraints—wrap properly.",
        "LayoutBuilder(builder: (c, constraints) {\n  if (constraints.maxWidth < 600) return Mobile();\n  return Desktop();\n});",
        "1) Replace viewport-only assumptions. 2) Adaptive components. 3) Test in sidebars. 4) Keep builders cheap.",
    ),
    "ListView": C(
        "ListView lazily builds children in a scrollable viewport—default for vertical collections.",
        "ListView(children: hugeList) builds eagerly; shrinkWrap inside Column causes expensive layouts.",
        ["builder/separated", "itemExtent", "shrinkWrap caution", "primary scroll"],
        "Use builder constructors, provide keys, consider itemExtent for perf, avoid shrinkWrap when Expanded works.",
        "ListView is simple; CustomScrollView needed for mixed slivers.",
        "If jank on scroll, reduce item build cost and avoid shrinkWrap.",
        "ListView.builder(itemCount: n, itemBuilder: (_, i) => Item(key: ValueKey(ids[i]), index: i));",
        "1) Always builder for long lists. 2) Keys. 3) Expanded not shrinkWrap. 4) Profile. 5) itemExtent when uniform.",
    ),
    "MVVM": C(
        "MVVM structures Flutter apps with Views (widgets), ViewModels (state/commands), and Models (data).",
        "Fat widgets mixing IO and UI become untestable.",
        ["ViewModel state", "command methods", "binding via listening", "test VMs without UI"],
        "Put state in ChangeNotifier/Cubit ViewModels, inject repositories, and keep widgets declarative.",
        "MVVM clarity vs extra layers for tiny apps—scale the pattern to team size.",
        "If widgets call APIs directly, move to VM/repository.",
        "class LoginVm extends ChangeNotifier { /* state + submit() */ }",
        "1) Introduce VM for a screen. 2) Inject repos. 3) Unit-test VM. 4) Thin widgets. 5) Consistent folder layout.",
    ),
    "Material 3 theming": C(
        "Material 3 theming uses ColorScheme, TextTheme, and component themes for systematic styling.",
        "Hard-coded colors ignore dark mode and accessibility contrast.",
        ["ColorScheme.fromSeed", "ThemeData.useMaterial3", "component themes", "dynamic color optional"],
        "Define seed/scheme, apply Theme, prefer theme colors in widgets, and support dark/light.",
        "M3 defaults may differ from brand—override component themes rather than one-off colors.",
        "If dark mode breaks, missing ColorScheme roles—audit hard-coded Color(0x..).",
        "ThemeData(useMaterial3: true, colorScheme: ColorScheme.fromSeed(seedColor: Colors.teal));",
        "1) Adopt M3 ThemeData. 2) Map brand tokens. 3) Dark scheme. 4) Ban raw colors in widgets. 5) Contrast check.",
    ),
    "MethodChannel": C(
        "MethodChannel invokes platform methods (Android/iOS) with async results—classic Flutter platform interop.",
        "Missing native implementations or wrong channel names throw MissingPluginException.",
        ["channel name", "invokeMethod", "codecs", "main thread care on native"],
        "Define channel string, implement handlers natively, invoke from Dart, and handle errors.",
        "Channels are flexible; Pigeon adds type safety. Heavy traffic may need EventChannel/FFI.",
        "If MissingPluginException, plugin not registered or running on unsupported platform.",
        "const ch = MethodChannel('app.battery');\nfinal level = await ch.invokeMethod<int>('getBatteryLevel');",
        "1) Define API. 2) Implement native. 3) Dart invoke. 4) Tests/mocks. 5) Consider Pigeon if growing.",
    ),
    "Navigator 1.0": C(
        "Navigator 1.0 manages a stack of Routes with push/pop and imperative APIs many apps still use.",
        "Passing wrong context (below Navigator) fails; not awaiting results loses return values.",
        ["push/pop", "MaterialPageRoute", "onGenerateRoute", "result futures"],
        "Push routes with MaterialPageRoute/named routes, pop with results, and keep a clear routing table.",
        "1.0 is simple; complex deep links/web sync often need Router 2.0/go_router.",
        "If push fails, context lacks Navigator—use root navigator or correct context.",
        "final ok = await Navigator.of(context).push<bool>(MaterialPageRoute(builder: (_) => EditPage()));",
        "1) Centralize routes. 2) Type results. 3) Handle back. 4) Migrate to go_router when deep links demand.",
    ),
    "Pigeon": C(
        "Pigeon generates type-safe platform channel code from a Dart API definition for Flutter↔native.",
        "Hand-written channels drift types and codecs between platforms.",
        ["API IDL", "codegen", "HostApi/FlutterApi", "null safety"],
        "Define API, generate Dart/Kotlin/Swift, implement native hosts, call generated Dart APIs.",
        "Type safety vs setup cost; worth it as channel surface grows.",
        "If codegen mismatches, clean and regenerate; versions must align.",
        "// pigeons/api.dart → flutter pub run pigeon ...",
        "1) Write pigeon API. 2) Generate. 3) Implement hosts. 4) CI codegen. 5) Version carefully.",
    ),
    "Provider": C(
        "Provider exposes values/ChangeNotifiers via InheritedWidget wrappers with convenient read/watch APIs.",
        "Using Provider.of with listen:true indiscriminately rebuilds large subtrees.",
        ["ChangeNotifierProvider", "context.watch/read", "Consumer", "MultiProvider"],
        "Provide at subtree root, watch selectively, call notifyListeners on changes, dispose notifiers.",
        "Simple and popular; Riverpod addresses some test/compile-time issues. Don't provide everything globally.",
        "If rebuild storms, you watched too high—narrow Consumer/select.",
        "ChangeNotifierProvider(create: (_) => CartModel(), child: App());\ncontext.watch<CartModel>().count;",
        "1) Provide feature models. 2) watch narrowly. 3) read in callbacks. 4) Dispose. 5) Widget tests with overrides.",
    ),
    "R8/ProGuard": C(
        "R8 shrinks/obfuscates Android release builds; keep rules preserve reflection-needed classes (plugins).",
        "Missing keep rules crash release-only when Gson/reflection plugins break.",
        ["minifyEnabled", "proguard-rules.pro", "consumer rules", "mapping.txt"],
        "Enable minify for release, add plugin keep rules, save mapping for crash deobfuscation.",
        "Smaller apps vs fragile reflection; test release builds always.",
        "If release crash only, check mapping and missing keeps.",
        "minifyEnabled true\nproguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'",
        "1) Enable R8. 2) Add keeps. 3) Test release. 4) Upload mapping. 5) Monitor crashlytics.",
    ),
    "REST API integration": C(
        "Flutter REST integration uses http/dio clients, DTO parsing, auth headers, and resilient error mapping.",
        "Parsing JSON in UI isolates janks; ignoring non-2xx statuses mis-handles errors.",
        ["http client", "dto/json", "auth interceptors", "timeouts"],
        "Centralize client, parse with json_serializable, map errors, and optionally isolate heavy parses.",
        "dio features vs http simplicity—pick one and standardize.",
        "If UI janks on large JSON, move parse off UI isolate.",
        "final res = await http.get(uri, headers: headers);\nif (res.statusCode >= 400) throw ApiException(res.statusCode);",
        "1) API client module. 2) Typed DTOs. 3) Error mapping. 4) Auth refresh. 5) Widget/repo tests.",
    ),
    "RenderFlex overflow": C(
        "RenderFlex overflow (yellow/black stripes) means Row/Column children exceeded available space along main axis.",
        "Unbounded text or fixed widths in narrow layouts ignore constraints.",
        ["main axis overflow", "Flexible/Expanded", "softWrap/ellipsis", "Inspect constraints"],
        "Wrap with Flexible/Expanded, allow text to ellipsize, or scroll; never ignore overflow in production.",
        "Overflow is a layout bug, not a visual style—fix constraints.",
        "Use Inspector to see who forced oversized child.",
        "Row(children: [Icon(...), Expanded(child: Text(long, overflow: TextOverflow.ellipsis))]);",
        "1) Reproduce narrow sizes. 2) Fix flex/text. 3) Add golden/widget tests at small sizes. 4) Ban ignore overflow.",
    ),
    "RenderObject": C(
        "RenderObjects perform layout and painting; widgets configure them via Elements.",
        "App developers rarely need custom RenderObjects—mistakes break constraints contracts.",
        ["performLayout", "paint", "hitTest", "ParentData"],
        "Prefer composing widgets; write custom RenderBox only when existing render objects can't express the layout.",
        "Ultimate control vs maintenance cost and a11y complexity.",
        "If asserts in performLayout, constraints protocol violated.",
        "// Prefer CustomPainter/box widgets before custom RenderBox",
        "1) Exhaust widget options. 2) Study RenderBox docs. 3) Implement carefully. 4) Heavy tests. 5) Semantics.",
    ),
    "RepaintBoundary": C(
        "RepaintBoundary creates a separate display list layer so frequent repaints don't dirty siblings.",
        "Animating one subtree without boundaries can repaint large ancestors costlessly avoided.",
        ["layer separation", "toImage", "memory cost of layers", "profile first"],
        "Wrap chatty animations/complex static siblings strategically; don't wrap everything.",
        "More layers help repaint isolation but use memory/GPU bandwidth.",
        "If still janky, problem may be build/layout not paint—check timeline.",
        "RepaintBoundary(child: ComplicatedStaticHeader());",
        "1) Profile paints. 2) Boundary around static vs animated. 3) Re-measure. 4) Avoid excessive layers.",
    ),
    "Riverpod": C(
        "Riverpod is a compile-safe reactive caching/state toolkit that improves on Provider with no BuildContext for reads.",
        "Provider context lookup limitations and disposal bugs push teams to Riverpod.",
        ["ProviderContainer", "ref.watch/read", "family/autoDispose", "AsyncNotifier"],
        "Declare providers globally, watch in consumers, use autoDispose for ephemeral state, override in tests.",
        "Learning curve vs safety; still don't put all ephemeral UI flags in providers.",
        "If disposed provider errors, lifecycle mismatch—tune autoDispose.",
        "final counterProvider = StateProvider((ref) => 0);\nref.watch(counterProvider);",
        "1) Add Riverpod. 2) Migrate one feature. 3) autoDispose where needed. 4) Override in tests. 5) Document provider graph.",
    ),
    "Row and Column": C(
        "Row and Column are Flex widgets laying out children horizontally/vertically under incoming constraints.",
        "Placing unbounded scroll views inside them without Expanded causes layout exceptions.",
        ["main/cross axis", "Expanded/Flexible", "MainAxisSize", "alignment"],
        "Choose axis, align children, expand to fill leftover space, and respect constraints.",
        "Simple and ubiquitous; complex grids may need Wrap/GridView/CustomMultiChildLayout.",
        "Overflow? Check Expanded and text wrapping.",
        "Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [...]); ",
        "1) Standardize spacing. 2) Expanded patterns. 3) Test small screens. 4) Prefer Wrap when needed.",
    ),
    "SQLite/sqflite": C(
        "sqflite is a popular SQLite plugin for local relational storage on mobile.",
        "No migrations strategy corrupts upgrades; main-isolate heavy queries jank UI.",
        ["openDatabase", "migrations version", "transactions", "indexes"],
        "Open with version+onUpgrade, wrap multi-writes in transactions, index query columns, consider background isolates.",
        "SQL control vs Drift's codegen convenience.",
        "If upgrade crashes, onUpgrade incomplete—test migrations on copies.",
        "await db.execute('CREATE TABLE ...');\nawait db.transaction((txn) async { /* ... */ });",
        "1) Schema+migrations. 2) Indexes. 3) Transactions. 4) Offload heavy queries. 5) Backup strategy.",
    ),
    "SafeArea": C(
        "SafeArea pads children to avoid system OS intrusions (notches, status bar, home indicator).",
        "Content under notches looks broken and can be untappable.",
        ["MediaQuery.padding", "minimum vs maintainBottomViewPadding", "false edges", "immersive modes"],
        "Wrap top-level scaffolds/screens with SafeArea or use padded AppBars that handle insets.",
        "Sometimes intentional edge-to-edge design needs manual padding instead of SafeArea everywhere.",
        "If double padding, SafeArea + AppBar both applied—disable edges.",
        "SafeArea(child: Scaffold(body: ...));",
        "1) Apply SafeArea at screen roots. 2) Verify devices with notches. 3) Handle keyboards. 4) Edge-to-edge carefully.",
    ),
    "ScrollController": C(
        "ScrollController observes/drives scroll offset for infinite scroll, parallax, and scroll-to-index patterns.",
        "Sharing one controller across multiple scrollables or forgetting dispose leaks.",
        ["offset/position", "listeners", "animateTo", "PrimaryScrollController"],
        "Create controller in State, attach to one scrollable, listen for thresholds, dispose.",
        "Controller gives power; NotificationListener often enough for simple cases.",
        "If 'ScrollController attached to multiple', reuse bug—one controller per scrollable.",
        "controller.addListener(() {\n  if (controller.position.extentAfter < 200) loadMore();\n});",
        "1) Own controller in State. 2) Dispose. 3) Infinite scroll guards. 4) Tests with controller jumps.",
    ),
    "Semantics": C(
        "Semantics describe UI meaning for assistive technologies; Flutter merges a semantics tree parallel to widgets.",
        "Custom painted controls without semantics are invisible to TalkBack/VoiceOver.",
        ["Semantics widget", "labels/actions", "excludeSemantics", "MergeSemantics"],
        "Use semantic widgets (button/text), add Semantics for custom controls, and test with screen readers.",
        "Too many semantics nodes can confuse; merge thoughtfully.",
        "If unlabeled buttons, wrap with Semantics(button:true, label:...).",
        "Semantics(label: 'Delete item', button: true, onTap: onDelete, child: Icon(Icons.delete));",
        "1) Audit custom controls. 2) Labels/actions. 3) SR testing. 4) Keep Material semantics where possible.",
    ),
    "SharedPreferences": C(
        "SharedPreferences stores small key-value prefs locally (NSUserDefaults/SharedPreferences).",
        "Storing secrets or large blobs here is insecure/slow; async API misuse assumes sync availability.",
        ["async getInstance", "primitive types", "not encrypted", "migration"],
        "Await instance, read/write simple prefs, and use secure storage for tokens.",
        "Simple prefs vs need for typed DB—don't stretch it.",
        "If null unexpectedly, key mismatch or cleared app data.",
        "final p = await SharedPreferences.getInstance();\nawait p.setBool('dark', true);",
        "1) Prefs for UX flags only. 2) Secure tokens elsewhere. 3) Default values. 4) Document keys.",
    ),
    "State lifecycle": C(
        "StatefulWidget State mounts via initState, updates via didUpdateWidget, cleans in deactivate/dispose.",
        "Starting streams in build or skipping dispose leaks and duplicates subscriptions.",
        ["initState", "didChangeDependencies", "didUpdateWidget", "dispose"],
        "Init controllers/subscriptions in initState, respond to prop changes in didUpdateWidget, dispose all.",
        "Lifecycle mastery prevents leaks; prefer higher-level state managers for complex syncing.",
        "If double subscription, initState work incorrectly re-run—check keys remounting.",
        "@override void dispose(){ sub.cancel(); controller.dispose(); super.dispose(); }",
        "1) Audit dispose. 2) No side effects in build. 3) Tests for remount. 4) Document owned resources.",
    ),
    "StatelessWidget": C(
        "StatelessWidget describes UI from configuration (props) without local mutable State.",
        "Pushing ephemeral interaction state into parents unnecessarily creates rebuild churn.",
        ["immutable config", "build method", "const constructors", "when to go Stateful"],
        "Prefer const Stateless widgets; escalate to Stateful/Cubit when local mutable state appears.",
        "Stateless clarity vs needing State for animations/forms.",
        "If you need setState, it's no longer Stateless—migrate.",
        "class Label extends StatelessWidget {\n  const Label(this.text, {super.key});\n  final String text;\n  @override Widget build(BuildContext c) => Text(text);\n}",
        "1) Prefer const Stateless. 2) Elevate state intentionally. 3) Const all the way. 4) Lint unnecessary stateful.",
    ),
    "Stream": C(
        "Streams deliver asynchronous sequences of events—used for sockets, Firestore snapshots, and BLoC.",
        "Missing cancellation leaks; using single-subscription streams twice throws.",
        ["single vs broadcast", "StreamBuilder", "subscription.cancel", "asyncMap"],
        "Subscribe with StreamBuilder or listen+cancel, choose broadcast when multi-listen needed, handle errors.",
        "Streams are powerful; Futures suffice for one-shot. Backpressure rarely automatic—careful producers.",
        "If 'already listened', need broadcast or new instance per listener.",
        "StreamBuilder(stream: repo.watch(), builder: (c, snap) => ...)",
        "1) StreamBuilder for UI. 2) Cancel elsewhere. 3) Error UI. 4) Prefer broadcast for multi fans. 5) Test cancellation.",
    ),
    "ValueNotifier": C(
        "ValueNotifier is a ChangeNotifier holding a single value—lightweight reactive cell for small local state.",
        "Using full Provider/BLoC for a single boolean can be ceremony overkill.",
        ["value setter notifies", "ValueListenableBuilder", "dispose", "listenables"],
        "Create notifier, rebuild with ValueListenableBuilder, dispose with owner.",
        "Tiny and fast; not a full app architecture. Combine with larger patterns as needed.",
        "If UI not updating, you mutated fields inside value without reassigning value.",
        "final open = ValueNotifier(false);\nValueListenableBuilder(valueListenable: open, builder: ...);",
        "1) Use for local leaf state. 2) Dispose. 3) Escalate to Cubit when logic grows. 4) Prefer immutable value replaces.",
    ),
    "Wasm/SkWasm": C(
        "Skwasm is Flutter web's Wasm-oriented rendering path aiming for smaller/faster web engines than classic CanvasKit loading.",
        "Large Wasm downloads still hurt first load if not cached/deferred thoughtfully.",
        ["wasm gc/capabilities", "build flags", "browser support", "fallback"],
        "Build with current Flutter web Wasm options, test target browsers, measure load.",
        "Bleeding-edge perf vs compatibility—have fallbacks.",
        "If blank on older browsers, feature unsupported—detect and fallback.",
        "flutter build web --wasm  # per current Flutter docs/flags",
        "1) Evaluate Wasm builds. 2) Browser matrix. 3) Measure. 4) Fallback plan. 5) Cache aggressively.",
    ),
    "WebSocket": C(
        "WebSockets give Flutter apps bidirectional realtime channels for chat/presence.",
        "No reconnect/backoff drops users on mobile networks; parsing on UI isolate janks.",
        ["connect/auth", "heartbeat", "reconnect", "message codec"],
        "Connect with auth, heartbeat, exponential reconnect, and push events into a repository stream.",
        "Sockets are great for chat; SSE may suffice for server→client only.",
        "If battery drain, too-aggressive reconnect/ping—tune intervals.",
        "final ch = IOWebSocketChannel.connect(uri);\nch.stream.listen(onMsg);",
        "1) Repo-level socket. 2) Auth. 3) Reconnect+backoff. 4) Offline queue. 5) Profile parse cost.",
    ),
    "Widget": C(
        "Widgets are immutable configuration objects describing UI; Flutter rebuilds them cheaply compared to Elements/RenderObjects.",
        "Mutating widgets or heavy build methods without const causes avoidable work.",
        ["immutable config", "build()", "const constructors", "composition"],
        "Compose small widgets, use const, and keep build pure and light.",
        "Fine-grained widgets help rebuild control but too many layers hurt readability.",
        "If rebuild expensive, split widgets and add const.",
        "const Padding(padding: EdgeInsets.all(8), child: Text('Hi'));",
        "1) Const-friendly widgets. 2) Split builds. 3) Pure build. 4) Profile rebuilds.",
    ),
    "Widget tree": C(
        "The widget tree is the immutable configuration hierarchy Flutter diffs each build to update elements.",
        "Deep unnecessary subtrees and missing keys make diffs remount too much.",
        ["composition", "keys", "Builder for context", "devtools inspector"],
        "Keep trees intentional, key stateful lists, and inspect with Widget Inspector.",
        "Deeper trees vs fewer large builds—split when profiling says so.",
        "Inspector highlights rebuilds—use it when optimizing.",
        "// DevTools → Inspector → Track widget rebuilds",
        "1) Learn inspector. 2) Key lists. 3) Split heavy builds. 4) Avoid mega-build methods.",
    ),
    "adaptive UI": C(
        "Adaptive UI selects platform-appropriate patterns (Material vs Cupertino, navigation idioms) while sharing logic.",
        "Forcing Material everywhere on iOS feels foreign; duplicating entire apps is costly.",
        ["Theme platform", "adaptive widgets", "navigation idioms", "shared view models"],
        "Share VMs/repos, branch widgets via Theme.of.platform or adaptive constructors, test both targets.",
        "Adaptive takes effort; sometimes product chooses one design language deliberately.",
        "If iOS back gesture breaks, navigation adaptation incomplete.",
        "Theme.of(context).platform == TargetPlatform.iOS ? CupertinoButton(...) : ElevatedButton(...);",
        "1) Shared logic. 2) Adaptive widgets map. 3) Dual screenshots. 4) Platform QA checklist.",
    ),
    "async BuildContext safety": C(
        "After an await, the State may be disposed—using BuildContext then asserts/crashes unless mounted is checked.",
        "Fire-and-forget async in State without guards is a top Flutter crash source.",
        ["mounted", "capture navigators before await", "cancel on dispose", "use_build_context_synchronously lint"],
        "Await, then if (!mounted) return; before context use; or capture ScaffoldMessenger/Navigator before gap.",
        "Lint catches many cases; still design cancellation for long tasks.",
        "Enable use_build_context_synchronously and fix all hits.",
        "await repo.save();\nif (!mounted) return;\nScaffoldMessenger.of(context).showSnackBar(...);",
        "1) Enable lint. 2) mounted checks. 3) Cancel futures/subs on dispose. 4) Tests covering fast pop.",
    ),
    "background task execution": C(
        "Background tasks run work when UI is not foreground—constrained heavily by iOS/Android policies.",
        "Assuming infinite background CPU gets apps suspended/killed and store-rejected.",
        ["BGTaskScheduler/WorkManager", "constraints (network/charging)", "execution windows", "isolates"],
        "Use platform-supported schedulers, keep work short, persist progress, and test OS-kill scenarios.",
        "Push-driven work often more reliable than frequent polling background fetches.",
        "If never runs, missing native registration/permissions/Info.plist keys.",
        "// workmanager / flutter_background_fetch per platform setup docs",
        "1) Pick supported API. 2) Native setup. 3) Idempotent tasks. 4) Telemetry. 5) Store compliance review.",
    ),
    "build phase": C(
        "The build phase runs Widget.build to produce a new widget configuration for dirty elements.",
        "Side effects in build (HTTP, setState) create loops and unpredictable UI.",
        ["pure build", "setState schedules dirty", "const optimization", "rebuild scope"],
        "Keep build pure, trigger changes via events/setState outside build, and split widgets to limit rebuild scope.",
        "Rebuilds are normal; expensive builds are the problem.",
        "If infinite rebuild, setState during build—remove it.",
        "// Bad: build(){ setState((){}); }\n// Good: derive UI from state fields only",
        "1) Ban side effects in build. 2) Split widgets. 3) const. 4) Rebuild profiler.",
    ),
    "certificate pinning": C(
        "Certificate pinning trusts only specific certs/public keys for your API, mitigating rogue CAs/MITM on hostile networks.",
        "No pinning still relies on system CAs; pinning without rotation plan bricks apps when certs expire.",
        ["pin public key", "backup pins", "rotation", "debug overrides caution"],
        "Pin SPKI hashes in HTTP client, ship backup pins, and rotate ahead of expiry.",
        "Security vs operational risk—often for higher threat apps; consider at TLS terminator carefully.",
        "If prod suddenly fails TLS, pins outdated—roll emergency build with new pins.",
        "// dio HttpClientAdapter with SecurityContext / badCertificateCallback carefully pinned",
        "1) Decide threat model. 2) Pin+backup. 3) Rotation calendar. 4) Monitor TLS failures. 5) Emergency override process.",
    ),
    "code signing/provisioning": C(
        "iOS code signing binds apps to teams via certificates/profiles; Android uses keystores for package identity.",
        "Wrong profiles/expired certs fail install/TestFlight; lost Android upload keys are catastrophic.",
        ["Apple certs/profiles", "Android keystore", "CI secrets", "match/fastlane"],
        "Automate signing with fastlane match or store keys in CI secrets; back up Android keystores.",
        "Automation reduces pain; still need access control for signing material.",
        "If 'provisioning profile doesn't include signing certificate', regenerate profiles.",
        "fastlane match appstore\n# Android: keep upload keystore in secret manager",
        "1) Centralize signing. 2) Backup keys. 3) CI inject. 4) Rotate Apple certs deliberately. 5) Document restore.",
    ),
    "compositing": C(
        "Compositing combines layers (often GPU) into final frames; opacity/clip/transform can create layers.",
        "Accidental saveLayer/opacity over large areas burns GPU fill rate.",
        ["layers", "saveLayer cost", "RepaintBoundary", "raster thread"],
        "Reduce offscreen saves, prefer simpler effects, and profile raster jank.",
        "Pretty effects vs battery/GPU—measure on mid devices.",
        "If raster thread long, simplify blur/opacity/clips.",
        "// Avoid Opacity wrapping huge lists; prefer fading smaller subtrees",
        "1) Profile raster. 2) Reduce saveLayer. 3) Boundary wisely. 4) Test low-end Android.",
    ),
    "debug/profile/release modes": C(
        "Flutter has debug (asserts/JIT), profile (performance-like with tooling), and release (optimized AOT) modes.",
        "Judging jank in debug mode misleads—debug is slower by design.",
        ["asserts in debug", "profile for perf", "release for ship", "tree shaking"],
        "Develop in debug, measure in profile, ship release; never quote debug FPS as truth.",
        "Profile close to release but not identical; still verify release builds.",
        "If 'only release crashes', minify/strip issue—test release locally.",
        "flutter run --profile\nflutter build apk --release",
        "1) Educate team on modes. 2) Perf only in profile. 3) QA release builds. 4) Keep asserts for debug checks.",
    ),
    "deep linking": C(
        "Deep links open specific app routes from URLs (App Links/Universal Links/custom schemes).",
        "Misconfigured intent filters/apple-app-site-association breaks links into browser-only.",
        ["URI parsing", "verified links", "cold start vs warm", "go_router parsers"],
        "Claim domains, configure platform files, parse URIs into routes, and test install/referrer flows.",
        "Verified HTTPS links are better UX/security than custom schemes alone.",
        "If links open site not app, assetlinks/AASA or intent filters wrong.",
        "// Android intent-filter + assetlinks.json; iOS associated domains",
        "1) Domain verify. 2) Platform config. 3) Router parse. 4) Cold/warm tests. 5) Analytics on link opens.",
    ),
    "dependency injection": C(
        "DI supplies collaborators (repos/clients) to widgets/VMs instead of constructing globals everywhere.",
        "Singletons and `new` in widgets make testing and swapping environments painful.",
        ["constructor injection", "get_it/riverpod", "environments", "overrides in tests"],
        "Register implementations at startup, inject into VMs, override fakes in tests.",
        "Service locators are convenient but hide dependencies; constructor DI is clearer when practical.",
        "If wrong impl in tests, registration order/overrides missing.",
        "getIt.registerLazySingleton<Api>(() => Api(http));\nfinal api = getIt<Api>();",
        "1) Choose DI approach. 2) Register at boot. 3) Inject VMs. 4) Test overrides. 5) Env flavors.",
    ),
    "design tokens": C(
        "Design tokens are named raw values (color/space/type) shared between design and Flutter Theme.",
        "Magic numbers diverge from Figma and break dark theme consistency.",
        ["token naming", "ThemeExtension", "light/dark", "codegen from design"],
        "Map tokens into ThemeData/ThemeExtension and reference tokens in widgets only.",
        "Heavy token systems need discipline; start with color/space/type.",
        "If dark mode misses, token not mapped through ColorScheme/extension.",
        "Theme.of(context).extension<AppTokens>()!.spaceMd",
        "1) Extract tokens. 2) ThemeExtension. 3) Replace magic numbers. 4) Sync with design. 5) Contrast checks.",
    ),
    "event loop and microtask queue": C(
        "Dart's event loop runs microtasks before the next event events; UI frame callbacks interleave with events.",
        "Scheduling endless microtasks can starve frames similarly to JS.",
        ["microtask vs event queue", "scheduleMicrotask", "Future microtasks", "frame callbacks"],
        "Know await scheduling, use Future for yielding to events, and keep frame callbacks short.",
        "Same lessons as web event loops—apply to isolates' loops.",
        "If UI starves with tiny tasks, microtask storm—batch/yield.",
        "scheduleMicrotask(() => print('micro'));\nFuture(() => print('event'));",
        "1) Teach ordering. 2) Avoid microtask storms. 3) Profile frames. 4) Move CPU to isolates.",
    ),
    "extension methods": C(
        "Dart extensions add methods/getters to existing types without altering them—great for UI helpers.",
        "Overusing extensions hides where APIs live and can collide names.",
        ["extension on Type", "name conflicts", "static resolution", "no virtual dispatch"],
        "Create focused extensions (e.g., on BuildContext for theme), import deliberately.",
        "Nice DX vs discoverability—document team extensions.",
        "If extension missing, import not in scope.",
        "extension Fancy on BuildContext {\n  ThemeData get theme => Theme.of(this);\n}",
        "1) Add curated extensions. 2) Lint collisions. 3) Document. 4) Avoid business logic in extensions.",
    ),
    "federated plugin architecture": C(
        "Federated plugins split app-facing API, platform interface, and platform implementations into packages.",
        "Monolithic plugins make contributions and multi-platform support harder.",
        ["app-facing", "platform interface", "endorsed implementations", "federated stubs"],
        "Follow Flutter federated layout, implement platform interface, and endorse impls in pubspec.",
        "More packages to version; clearer ownership and testing.",
        "If wrong impl resolves, endorsements/pubspec miswired.",
        "// my_plugin, my_plugin_platform_interface, my_plugin_android/ios...",
        "1) Split plugin. 2) Platform interface. 3) CI per platform. 4) Versioning policy. 5) Example app.",
    ),
    "final and const": C(
        "final means single-assignment; const means compile-time constant canonicalized values—key for Flutter perf.",
        "Missing const on widgets forces rebuild work that could be reused.",
        ["final fields", "const constructors", "canonical instances", "constables"],
        "Prefer final fields, const widgets/constructors deeply when values are compile-time constant.",
        "Const is great; not everything can be const (depends on runtime).",
        "If analyzer suggests const, take it unless it harms readability badly.",
        "const EdgeInsets.all(8);\nfinal name = widget.user.name;",
        "1) Prefer final. 2) Const widgets. 3) Lint prefer_const. 4) Review hot paths.",
    ),
    "flavors and dart-define": C(
        "Flavors/schemas and --dart-define configure app ids, icons, and compile-time env (API URLs) per variant.",
        "Hard-coded prod URLs in debug cause accidents; manual switching is error-prone.",
        ["product flavors", "xcconfig schemes", "String.fromEnvironment", "entrypoints"],
        "Define flavors, pass dart-defines for env, and separate applicationIds/bundle ids.",
        "More flavors increase CI matrix cost—keep to needed envs.",
        "If wrong API hit, define not passed in IDE run config.",
        "flutter run --flavor staging --dart-define=API=https://stg.example.com",
        "1) Define flavors. 2) dart-define env. 3) IDE configs. 4) CI matrix. 5) Distinct app ids.",
    ),
    "foreground/background services": C(
        "Android foreground services run user-visible ongoing work; background services are heavily restricted post-O/12+.",
        "Starting background work illegally gets killed or Play policy strikes.",
        ["foreground notification", "types (location/media)", "exemptions", "iOS limitations"],
        "Use FGS with proper type/notification when required; prefer WorkManager for deferrable tasks.",
        "FGS UX cost (persistent notification) vs reliability.",
        "If killed immediately, missing notification/type or policy violation.",
        "// flutter_foreground_task / native FGS with type + notification channel",
        "1) Confirm need. 2) Correct FGS type. 3) Notification UX. 4) Play policy review. 5) Prefer deferred work when possible.",
    ),
    "frame lifecycle": C(
        "A Flutter frame walks build → layout → paint → composite on UI/raster threads targeting ~16ms.",
        "Work exceeding budget drops frames and feels janky.",
        ["SchedulerBinding", "frame callbacks", "UI vs raster", "vsync"],
        "Keep per-frame work small, defer heavy tasks, and profile timeline.",
        "Some jank is shader/IO—not always your Dart code.",
        "Attribute jank via DevTools before optimizing.",
        "SchedulerBinding.instance.addPostFrameCallback((_) {/* after first layout */});",
        "1) Understand phases. 2) Profile. 3) Cut build/layout/paint costs. 4) Defer non-critical work.",
    ),
    "garbage collection": C(
        "Dart GC reclaims unreachable objects; GC pauses can contribute to jank if allocation rates are huge.",
        "Allocating large temporary graphs every frame increases GC frequency.",
        ["generational GC", "allocation rate", "leak via listeners", "DevTools memory"],
        "Reduce per-frame allocations, cancel listeners, and inspect memory graphs for leaks.",
        "Don't micro-optimize allocations without profiles.",
        "If memory climbs across routes, leaked listeners/GlobalKeys/streams.",
        "// DevTools Memory → take heap snapshot, compare",
        "1) Snapshot before/after flows. 2) Fix leaks. 3) Reduce hot-path allocs. 4) Re-profile frames.",
    ),
    "generics": C(
        "Dart generics parameterize classes/functions for type-safe collections and APIs.",
        "Using dynamic lists loses safety and forces casts.",
        ["type parameters", "bounds", "reified generics vs Java erasure differences", "inference"],
        "Type public APIs, constrain parameters, and let inference work locally.",
        "Same tradeoffs as other languages—clarity over cleverness.",
        "If casts abound, introduce generics.",
        "T first<T>(List<T> items) => items.first;",
        "1) Generic repos/APIs. 2) Avoid dynamic. 3) Analyzer strictness. 4) Examples in docs.",
    ),
    "go_router": C(
        "go_router implements Router API with declarative routes, deep links, redirects, and nested navigation.",
        "Imperative Navigator-only apps struggle with web URLs and complex auth redirects.",
        ["routes/redirect", "ShellRoute", "refreshListenable", "typed routes optional"],
        "Declare route table, redirect for auth, nest shells, and parse deep links.",
        "Declarative routing helps; migration from Navigator 1.0 takes care for results/pop.",
        "If redirect loops, conditions overlap—add logging.",
        "GoRouter(routes: [GoRoute(path: '/', builder: ...)], redirect: (c,s) => auth ? null : '/login');",
        "1) Adopt go_router. 2) Auth redirect. 3) Deep link test. 4) Nested shells. 5) Analytics observer.",
    ),
    "golden test": C(
        "Golden tests screenshot widgets and compare against committed baseline images for visual regressions.",
        "Text/layout bugs escape behavior tests but get caught by goldens.",
        ["matchesGoldenFile", "platform font care", "CI determinism", "update intentionally"],
        "Pump widget, expect later matching golden, update with flag when intentional.",
        "Goldens flake across OS fonts if not controlled; use consistent CI images.",
        "If local/CI differ, font/rendering variance—standardize CI container.",
        "await expectLater(find.byType(MyWidget), matchesGoldenFile('goldens/my_widget.png'));",
        "1) Add goldens for key UI. 2) Lock CI fonts. 3) Review updates in PR. 4) Keep set small/high value.",
    ),
    "hit testing": C(
        "Hit testing determines which render object receives a pointer event by walking the hit test tree.",
        "Ignoring pointers incorrectly or deferring hits breaks taps on overlapping UIs.",
        ["HitTestBehavior", "IgnorePointer/AbsorbPointer", "Listener", "custom hitTest"],
        "Use IgnorePointer/AbsorbPointer intentionally, set behavior on listeners, and verify overlapping targets.",
        "Custom hit shapes need RenderBox.hitTest overrides—rare.",
        "If taps pass through, IgnorePointer or behavior translucent issues.",
        "IgnorePointer(ignoring: busy, child: button);",
        "1) Define overlay intent. 2) Absorb/Ignore correctly. 3) Widget tests taps. 4) Custom hits only if needed.",
    ),
    "http package": C(
        "The http package is Dart's simple HTTP client API for REST calls.",
        "Forgetting timeouts/headers and parsing without status checks causes hangs and silent failures.",
        ["Client", "Response", "headers", "closing clients"],
        "Create a shared Client, set timeouts via IOClient/adapters if needed, check status, close clients.",
        "http is minimal; dio adds interceptors—standardize one.",
        "If sockets leak, Client not closed.",
        "final client = http.Client();\ntry { final res = await client.get(url); } finally { client.close(); }",
        "1) Shared client. 2) Status checks. 3) Timeouts. 4) Interceptors/auth layer. 5) Tests with MockClient.",
    ),
    "image memory management": C(
        "Image memory can dominate Flutter RAM; cache width/height and eviction matter for galleries.",
        "Decoding full-res images into thumbnails OOMs on low-end devices.",
        ["cacheWidth/cacheHeight", "ResizeImage", "precacheImage", "ImageCache limits"],
        "Provide decode sizes for display size, clear caches on memory warnings if needed, and dispose controllers.",
        "Quality vs memory—decode near display pixel size.",
        "If OOM in gallery, missing cacheWidth—add it.",
        "Image.network(url, cacheWidth: (200 * devicePixelRatio).round());",
        "1) Decode near display size. 2) Limit cache. 3) Profile memory. 4) Paginate galleries. 5) Test low-end Android.",
    ),
    "implicit animations": C(
        "Implicit animations (AnimatedContainer/Opacity/etc.) tween property changes without manual controllers.",
        "Using explicit controllers for simple property changes adds boilerplate and leak risk.",
        ["AnimatedFoo widgets", "duration/curve", "state-driven props", "limits vs custom"],
        "Change target fields in state; implicit widgets animate to new values automatically.",
        "Simple UX wins; complex sequenced animations need AnimationController.",
        "If no animation, you replaced widget type/key remounting instead of updating props.",
        "AnimatedContainer(duration: Duration(ms: 200), color: selected ? Colors.teal : Colors.grey);",
        "1) Prefer implicit for simple. 2) Keep keys stable. 3) Escalate to explicit when sequencing. 4) Respect reduced motion.",
    ),
    "integration test": C(
        "integration_test drives the full app on device/emulator for end-to-end Flutter flows.",
        "Relying only on widget tests misses plugin/channel and performance issues.",
        ["integration_test package", "patrol optional", "firebase test lab", "determinism"],
        "Write integration tests for critical journeys, run on CI devices, reset state between tests.",
        "Slower/flakier than unit—keep suite thin.",
        "On flake, add explicit finds with timeouts and isolate shared state.",
        "IntegrationTestWidgetsFlutterBinding.ensureInitialized();\nawait tester.pumpWidget(MyApp());",
        "1) Critical path ITs. 2) Device CI. 3) Stable finders. 4) Quarantine flakes. 5) Keep widget tests majority.",
    ),
    "intl/ARB localization": C(
        "Flutter l10n uses ARB files and code generation (intl/flutter_gen) for translated strings and locales.",
        "Hard-coded English strings block markets and cause concatenation bugs for grammar.",
        ["ARB keys", "placeholders", "plural/select", "Locale resolution"],
        "Extract strings to ARB, generate localizations, and use AppLocalizations.of(context).",
        "Process overhead vs correctness for plurals/genders—worth it early.",
        "If missing strings, gen not run or locale not delegated.",
        "flutter gen-l10n\nText(AppLocalizations.of(context)!.helloWorld)",
        "1) Enable l10n. 2) ARB workflow. 3) CI gen. 4) Pseudo-locale QA. 5) RTL check.",
    ),
    "isolates": C(
        "Isolates are Dart's memory-isolated concurrency units—use for CPU-heavy work without blocking UI isolate.",
        "Heavy JSON parse/image work on UI isolate drops frames; await does not help CPU.",
        ["Isolate.run", "message passing", "no shared memory", "compute helper"],
        "Offload CPU with Isolate.run/compute, pass transferable-ish data, keep UI isolate free.",
        "Spawn cost exists—don't isolate tiny work. Prefer async IO which already frees UI.",
        "If still janky, work remains on UI or isolate messaging too large copies.",
        "final parsed = await Isolate.run(() => jsonDecode(bigJson));",
        "1) Profile UI isolate. 2) Isolate.run for CPU. 3) Measure. 4) Avoid for tiny tasks. 5) Error handling.",
    ),
    "json_serializable": C(
        "json_serializable generates fromJson/toJson for annotated Dart classes via build_runner.",
        "Hand-written JSON maps drift and throw on null/type mismatches late.",
        ["@JsonSerializable", "field rename", "null safety", "codegen"],
        "Annotate models, generate, parse at boundaries, and fail fast on schema mismatch.",
        "Codegen safety vs build_runner cost; freezed often pairs well.",
        "If field null errors, codegen outdated—rebuild.",
        "@JsonSerializable() class User { factory User.fromJson(Map<String,dynamic> j) => _$UserFromJson(j); }",
        "1) Add codegen. 2) Model DTOs. 3) CI generate. 4) Strict nulls. 5) Version API adapters.",
    ),
    "large Flutter app modularization": C(
        "Large Flutter apps split into packages/features with clear APIs to keep build times and ownership manageable.",
        "One giant lib/ with circular imports slows teams and analysis.",
        ["feature packages", "melos/pub workspaces", "public APIs", "dependency rules"],
        "Extract features into packages, enforce import boundaries, and use melos for scripts.",
        "More packages help scale; over-splitting early adds friction.",
        "If analyzer slow, modularize hot packages and reduce barrel exports.",
        "// packages/feature_auth, packages/feature_home, packages/design_system",
        "1) Identify features. 2) Extract packages. 3) Boundary lint. 4) Melos CI. 5) Keep shared slim.",
    ),
    "layout phase": C(
        "Layout assigns sizes/positions under constraints; expensive intrinsic/measuring layouts cause jank.",
        "shrinkWrap lists and Intrinsics force extra layout work.",
        ["performLayout", "constraints", "intrinsic cost", "relayout boundaries"],
        "Avoid shrinkWrap/intrinsics in hot paths, set itemExtent when possible, and profile layout.",
        "Correct layout vs cost—sometimes explicit sizes win.",
        "Timeline layout spikes → find shrinkWrap/Intrinsic.",
        "ListView.builder(itemExtent: 72, ...)",
        "1) Remove shrinkWrap where Expanded works. 2) itemExtent. 3) Ban Intrinsics in lists. 4) Profile.",
    ),
    "memory profiling": C(
        "Memory profiling uses DevTools heap snapshots/allocation tracing to find leaks and bloat.",
        "Ignoring memory causes OOM on low-end devices after long sessions.",
        ["heap snapshot", "diffing", "retaining paths", "ImageCache"],
        "Snapshot before/after flows, follow retainers, fix listeners/images/caches.",
        "Profiling overhead exists—use staging devices.",
        "If size climbs after pop routes, leaked elements/subscriptions.",
        "// DevTools Memory → Snapshot → Diff",
        "1) Baseline. 2) Diff journeys. 3) Fix retainers. 4) Automate smoke memory checks when possible.",
    ),
    "mixins": C(
        "Mixins reuse implementation across class hierarchies (`with`) without deep inheritance.",
        "Mixin hell and conflicting members create fragile classes.",
        ["with Mixin", "on constraints", "linearization", "prefer composition"],
        "Use mixins for cross-cutting State capabilities (TickerProvider), prefer composition for domain.",
        "Handy for Flutter State; overuse obscures behavior.",
        "If member conflict, rename/restructure.",
        "class _S extends State<W> with SingleTickerProviderStateMixin {}",
        "1) Limit mixins to framework patterns. 2) Compose domain. 3) Review conflicts. 4) Document mixin contracts.",
    ),
    "mocking": C(
        "Mocks/fakes replace dependencies in tests (mockito/mocktail) to assert interactions and stub responses.",
        "Over-mocking couples tests to implementation and misses integration bugs.",
        ["mocktail/mockito", "stubs vs fakes", "verify calls", "override DI"],
        "Fake repositories for VM tests, verify critical calls, and keep some integration tests unmocked.",
        "Mocks speed tests but can green-wash broken wiring.",
        "If tests pass but app fails, too many mocks—add integration coverage.",
        "when(() => api.load()).thenAnswer((_) async => sample);\nverify(() => api.load()).called(1);",
        "1) Fake repos. 2) mocktail. 3) Verify key interactions. 4) Balance with ITs. 5) Avoid mocking types you own unnecessarily.",
    ),
    "nested scrolling": C(
        "Nested scrolling coordinates parent/child scrollables (e.g., header + list) via NestedScrollView or custom physics.",
        "Competing scrollables steal gestures and produce sticky weirdness.",
        ["NestedScrollView", "PrimaryScrollController", "sliver coordination", "physics"],
        "Prefer CustomScrollView slivers or NestedScrollView; avoid shrinkWrap nested ListViews.",
        "NestedScrollView helps but is complex; slivers often simpler.",
        "If outer won't scroll, primary/controller conflict—align controllers.",
        "NestedScrollView(headerSliverBuilder: ..., body: ListView(...));",
        "1) Prefer single CustomScrollView. 2) Else NestedScrollView. 3) Test gestures. 4) Avoid nested shrinkWrap.",
    ),
    "offline-first mobile app": C(
        "Offline-first apps read/write a local source of truth and sync to network when available.",
        "Online-only mobile UX fails in tunnels/planes and feels fragile.",
        ["local DB", "outbox", "conflict policy", "connectivity signals"],
        "Persist locally first, enqueue mutations, sync with backoff, and show sync state honestly.",
        "Complexity vs UX—start with read-cache before full bidirectional sync.",
        "If duplicates after sync, missing idempotency keys.",
        "// write local → outbox row → worker POST with idempotency key → mark synced",
        "1) Local DB. 2) Outbox. 3) Sync worker. 4) Conflict policy. 5) UX for pending/failed.",
    ),
    "offline-first synchronization": C(
        "Sync protocols move local mutations to server and merge remote changes with clear conflict rules.",
        "Last-write-wins without vector clocks/versions silently drops user edits.",
        ["push/pull", "version vectors/etags", "CRDT optional", "idempotent upserts"],
        "Pull remote since cursor, push outbox with versions, resolve conflicts per domain rules.",
        "Perfect sync is hard; pick domain-appropriate conflicts (merge fields vs LWW).",
        "If data ping-pongs, clocks/versions wrong—add tests for concurrent edits.",
        "PUT /notes/{id} If-Match: \"etag\"",
        "1) Define conflict policy. 2) Version fields. 3) Cursor pull. 4) Outbox push. 5) Concurrent edit tests.",
    ),
    "package maintenance evaluation": C(
        "Evaluating Flutter packages checks maintenance, Flutter compatibility, issue health, and license fit.",
        "Adopting abandoned plugins blocks engine upgrades.",
        ["pub scores", "recent commits", "Flutter version support", "fork risk"],
        "Inspect pub.dev, repo activity, open critical issues, and prefer endorsed/popular maintained packages.",
        "Vendor vs write-your-own—estimate replacement cost before adopting.",
        "If plugin breaks on Flutter upgrade, check issues and be ready to fork/replace.",
        "// Checklist: last publish, open PRs, license, platforms supported, example runs",
        "1) Score candidates. 2) Spike upgrade. 3) Abstraction layer. 4) Monitor releases. 5) Exit plan.",
    ),
    "real-time chat app in Flutter": C(
        "Realtime chat in Flutter combines socket/stream repos, local cache, optimistic UI, and notification wakeups.",
        "Polling feels laggy; no local cache blanks the chat on reopen.",
        ["message stream", "optimistic send", "paging history", "push for wake"],
        "Persist messages, subscribe to room stream, reconcile acks, and virtualize long lists.",
        "Build vs buy (Stream/Sendbird)—time-to-market vs control.",
        "If duplicates, dedupe by server id; if reorder, sort stable timestamps.",
        "repo.watchMessages(roomId).listen(controller.add);\nawait repo.sendOptimistic(text);",
        "1) Message schema. 2) Local cache. 3) Socket stream. 4) Optimistic UI. 5) Push + pagination.",
    ),
    "rebuild optimization": C(
        "Rebuild optimization reduces work by splitting widgets, using const, selectors, and avoiding rebuilding huge subtrees.",
        "Mega build methods rebuild charts/lists on every keystroke.",
        ["const", "split widgets", "Selector/BlocSelector", "RepaintBoundary separate concern"],
        "Isolate frequently changing state, const static subtrees, and profile rebuilds before memo hacks.",
        "Readability vs micro-opts—measure first.",
        "DevTools rebuild highlights show hot widgets—split them.",
        "context.select<Cart,int>((c) => c.count); // rebuild only on count",
        "1) Profile rebuilds. 2) Split. 3) select/watch narrow. 4) const. 5) Re-measure.",
    ),
    "records and patterns": C(
        "Dart records and patterns enable concise multi-value returns and expressive switches/destructuring.",
        "Boilerplate classes for tiny tuples clutter APIs.",
        ["(a,b) records", "pattern switch", "destructuring", "exhaustiveness"],
        "Return records for small tuples, switch on sealed types with patterns, keep public domain models named when meaningful.",
        "Records are handy; named classes still better for evolving domain entities.",
        "If exhaustiveness fails, missing case—handle or use default carefully.",
        "final (user, token) = await login();\nswitch (state) { case Loading() => ...; case Ready(:final user) => ...; }",
        "1) Adopt records for tuples. 2) Pattern switches on unions. 3) Keep domain named. 4) Enable exhaustive lint.",
    ),
    "repository pattern": C(
        "Repositories abstract data sources (API/DB) behind interfaces consumed by VMs/use-cases.",
        "Widgets calling dio/Firebase directly scatter caching and error mapping.",
        ["interface + impl", "DTO mapping", "caching", "test fakes"],
        "Define repo interfaces, implement with remote/local, inject into VMs, fake in tests.",
        "Clear boundaries vs extra layer for tiny apps—use when multiple sources appear.",
        "If swapping API breaks UI, mapping leaked—keep DTOs inside repo.",
        "abstract class TodoRepo { Future<List<Todo>> list(); }\nclass ApiTodoRepo implements TodoRepo { /* dio */ }",
        "1) Repo interfaces. 2) Impl remote/local. 3) Inject. 4) Fake tests. 5) Map errors once.",
    ),
    "retry/backoff": C(
        "Client retry with exponential backoff+jitter handles transient mobile network failures.",
        "Immediate retries drain battery and hammer recovering servers.",
        ["idempotent methods", "jitter", "max attempts", "offline queue"],
        "Retry GETs and idempotent writes, honor Retry-After, and queue when offline.",
        "Retries improve resilience; non-idempotent POSTs need keys.",
        "If storms in logs, missing jitter/caps.",
        "await retry(() => client.get(url), maxAttempts: 5, delayFactor: Duration(ms: 200));",
        "1) Classify idempotent calls. 2) Backoff+jitter. 3) Honor Retry-After. 4) Metrics. 5) UX for final failure.",
    ),
    "sealed/base/interface/final class modifiers": C(
        "Dart class modifiers (sealed/base/interface/final) control where types can be implemented/extended for safer APIs.",
        "Open hierarchies allow unexpected subtypes that break switch exhaustiveness assumptions.",
        ["sealed exhaustiveness", "base restrict implements", "interface", "final"],
        "Mark state unions sealed, lock library types with base/final as needed, and switch exhaustively.",
        "Stricter APIs help large codebases; may constrain plugin authors—document.",
        "If outside subtype appears, modifier missing—tighten.",
        "sealed class Result {}\nfinal class Ok extends Result {}\nfinal class Err extends Result {}",
        "1) Seal state unions. 2) Exhaustive switches. 3) final leaf types. 4) Document intended extension points.",
    ),
    "secure token storage": C(
        "Secure token storage uses Keychain/Keystore-backed plugins (flutter_secure_storage) instead of plain prefs.",
        "Tokens in SharedPreferences are readable on rooted/jailbroken devices and backups sometimes.",
        ["Keychain/Keystore", "biometric optional", "rotation", "clear on logout"],
        "Store refresh tokens securely, short-lived access in memory when possible, wipe on logout.",
        "Secure storage still not perfect on compromised devices—pair with server revocation.",
        "If tokens vanish on upgrade, storage options/accessibility settings wrong.",
        "await storage.write(key: 'refresh', value: token);",
        "1) Secure storage plugin. 2) Memory for access token. 3) Logout wipe. 4) Jailbreak heuristics optional. 5) Revoke server-side.",
    ),
    "setState": C(
        "setState marks the Element dirty so Flutter rebuilds that State's widget subtree with new fields.",
        "Calling setState after dispose or for every tiny leaf without splitting causes crashes/jank.",
        ["schedule rebuild", "mutate fields then setState", "mounted", "scope rebuilds"],
        "Update fields and call setState, guard with mounted, and split widgets so setState scope stays small.",
        "Fine for local UI; escalate to app state libs when sharing across routes.",
        "If setState() called after dispose(), async gap—check mounted.",
        "setState(() => count++);",
        "1) Local state via setState. 2) mounted guards. 3) Split trees. 4) Move shared state up/out.",
    ),
    "setState after dispose": C(
        "setState after dispose happens when async callbacks complete after State unmount—framework asserts in debug.",
        "Missing mounted checks crash or spam logs when users navigate away quickly.",
        ["mounted flag", "cancel subscriptions", "Abort async", "use_build_context_synchronously"],
        "Track subscriptions, cancel in dispose, and check mounted before setState after awaits.",
        "Always a bug to ignore—fix ownership of async work.",
        "Reproduce by popping during in-flight request; add guards.",
        "await future;\nif (!mounted) return;\nsetState(() => data = x);",
        "1) Audit async State methods. 2) mounted checks. 3) Cancel subs. 4) Regression tests fast pop.",
    ),
    "sound null safety": C(
        "Sound null safety makes nullable types explicit so the analyzer proves null dereferences can't occur.",
        "Legacy `dynamic`/`!` abuse reintroduces null crashes.",
        ["T vs T?", "promotion", "late", "never bang casually"],
        "Model nullability honestly, promote with checks, avoid ! except when proven, prefer late only for definite assignment.",
        "Migration pain vs runtime crash reduction—worth it fully.",
        "If bang throws, the assumption was wrong—model nullable instead.",
        "String title;\nString? maybe;\nif (maybe != null) print(maybe.length);",
        "1) Full null safety. 2) Ban unnecessary !. 3) Strict lints. 4) Fix rather than bang.",
    ),
    "unit test": C(
        "Flutter unit tests verify pure Dart logic (VMs, parsers) quickly without rendering.",
        "Putting logic only in widgets forces slower widget tests for everything.",
        ["test package", "arrange-act-assert", "fakes", "fast CI"],
        "Extract logic to testable classes and assert outputs/errors with fakes.",
        "Unit vs widget/integration—pyramid with mostly unit.",
        "If needing WidgetsFlutterBinding for pure logic, logic not extracted yet.",
        "test('tax', () => expect(calcTax(100), 10));",
        "1) Extract logic. 2) Unit tests. 3) Fake repos. 4) Keep CI fast. 5) Widget tests for UI wiring.",
    ),
    "zones": C(
        "Zones provide overriding execution contexts for async error handling and forkable behaviors in Dart.",
        "Uncaught async errors outside runZonedGuarded escape to the console without reporting.",
        ["runZonedGuarded", "uncaught errors", "binding ensureInitialized order", "zone-local values"],
        "Wrap app startup in runZonedGuarded to report errors, careful with zone-crossing assumptions.",
        "Zones are powerful/low-level—prefer framework error hooks when enough.",
        "If errors missing in Crashlytics, zone/handler not installed early enough.",
        "runZonedGuarded(() => runApp(App()), (e, st) => report(e, st));",
        "1) Guard main. 2) Report to crash tool. 3) FlutterError.onError too. 4) Test intentional throws.",
    ),
}
