from .lib import K

FULLSTACK_TOPICS = {
    "BFF pattern": K(
        "The BFF pattern creates a backend tailored to a specific frontend so the client receives workflow-shaped data without overfetching or leaking service complexity.",
        "Without a BFF, complex clients either overfetch from generic services or duplicate orchestration, security, and error handling in the browser.",
        [
            "Client-specific aggregation",
            "Backend-owned auth and policy",
            "Overfetching reduction",
            "BFF duplication risk",
        ],
        "Place a BFF between the client and backend services to aggregate calls, enforce user-context policy, map service errors, and return UI-shaped DTOs.",
        "A BFF improves client simplicity and performance, but each frontend-specific backend adds ownership, testing, deployment, and versioning cost.",
        "When a BFF response is wrong, trace the user context, downstream service calls, DTO mapping, cache behavior, and whether mobile and web contracts diverged.",
        "BFF resolver: GET /dashboard composes profile, entitlements, notifications, and usage limits; returns one typed DashboardView with partial-error metadata. Evidence cue: The BFF pattern creates a backend tailored to a specific frontend so the client receives workflow-shaped data without overfetching or leaking service complexity.",
        "1) Identify client-specific orchestration 2) Define UI-shaped DTOs and auth policy 3) Add contract tests for BFF responses 4) Monitor downstream latency and partial failures.",
    ),
    "CDN cache": K(
        "A CDN cache stores static or cacheable responses near users to reduce latency and origin load.",
        "Poor CDN cache produces stale screens, hydration errors, unnecessary JavaScript, or slow first interactions that users experience as broken product behavior.",
        [
            "CDN cache render or cache boundary",
            "Freshness and invalidation rule",
            "Loading/error/retry state",
            "Bundle or latency budget",
        ],
        "Design CDN cache by choosing server versus client responsibility, defining cache keys and revalidation, handling loading/error states, and measuring payload or latency impact.",
        "CDN cache can improve speed and perceived responsiveness, but it increases invalidation, rollback, and mental-model complexity.",
        "If CDN cache misbehaves, check cache headers, query keys, revalidation tags, hydration warnings, service worker state, and mutation rollback paths.",
        "Cache-Control: public, s-maxage=60, stale-while-revalidate=300 on /products; purge CDN key product:{id} on admin update.",
        "1) Choose render and cache ownership 2) Define freshness and invalidation rules 3) Test loading, error, and rollback states 4) Monitor latency, payload, and stale data.",
    ),
    "CORS": K(
        "CORS is a browser mechanism that blocks cross-origin responses unless the server explicitly allowlists the requesting origin and credentials mode.",
        "CORS mistakes make browser requests fail even when curl or Postman succeeds, especially when cookies, custom headers, or multiple environments are involved.",
        [
            "Same-origin policy",
            "Preflight OPTIONS request",
            "Access-Control-Allow-Origin",
            "Credentials mode and cookies",
        ],
        "Handle CORS on the API by allowlisting exact frontend origins, allowed methods and headers, and credentials behavior; the browser enforces the response headers.",
        "A tight allowlist protects users but needs environment management; wildcard origins are simpler but unsafe with credentials and usually wrong for authenticated apps.",
        "Inspect the OPTIONS preflight, Access-Control-Allow-Origin, Allow-Credentials, requested headers, status code, and whether a proxy or CDN stripped headers.",
        "NestJS config: app.enableCors({ origin: ['https://app.example.com'], credentials: true, methods: ['GET','POST','PATCH'], allowedHeaders: ['Content-Type','Authorization','X-CSRF-Token'] }); Evidence cue: CORS is a browser mechanism that blocks cross-origin responses unless the server explicitly allowlists the requesting origin and credentials mode.",
        "1) List allowed app origins 2) Configure methods, headers, and credentials 3) Test preflight in a browser 4) Keep cookie and CSRF policy aligned.",
    ),
    "CSP and frontend headers": K(
        "CSP and related frontend security headers restrict which scripts, frames, resources, and browser behaviors a page may use.",
        "Misimplemented CSP and frontend headers can expose accounts, leak data across tenants, or let the frontend imply permissions the backend never enforced.",
        [
            "CSP and frontend headers trust boundary",
            "Cookie or token lifecycle",
            "Server-side policy enforcement",
            "Safe error and audit behavior",
        ],
        "Implement CSP and frontend headers with server-side validation, explicit browser security headers or cookie attributes, policy checks on every protected resource, and user-safe error responses.",
        "CSP and frontend headers hardening can add redirects, token refresh complexity, or stricter local setup, but it prevents high-impact account and data exposure.",
        "When CSP and frontend headers fails, inspect request headers, Set-Cookie attributes, CSRF token flow, backend guard decisions, tenant filters, and audit logs.",
        "Security flow for CSP and frontend headers: login sets HttpOnly SameSite cookie; mutating request sends CSRF header; API guard checks session, role, tenant, and audit event. Evidence cue: CSP and related frontend security headers restrict which scripts, frames, resources, and browser behaviors a page may use.",
        "1) Define browser credential policy 2) Enforce backend authorization 3) Add abuse-case API tests 4) Log decisions with correlation ids.",
    ),
    "CSRF": K(
        "CSRF is an attack where a browser is tricked into sending an authenticated state-changing request to a site using the user's cookies.",
        "Misimplemented CSRF can expose accounts, leak data across tenants, or let the frontend imply permissions the backend never enforced.",
        [
            "CSRF trust boundary",
            "Cookie or token lifecycle",
            "Server-side policy enforcement",
            "Safe error and audit behavior",
        ],
        "Implement CSRF with server-side validation, explicit browser security headers or cookie attributes, policy checks on every protected resource, and user-safe error responses.",
        "CSRF hardening can add redirects, token refresh complexity, or stricter local setup, but it prevents high-impact account and data exposure.",
        "When CSRF fails, inspect request headers, Set-Cookie attributes, CSRF token flow, backend guard decisions, tenant filters, and audit logs.",
        "Security flow for CSRF: login sets HttpOnly SameSite cookie; mutating request sends CSRF header; API guard checks session, role, tenant, and audit event. Evidence cue: CSRF is an attack where a browser is tricked into sending an authenticated state-changing request to a site using the user's cookies.",
        "1) Define browser credential policy 2) Enforce backend authorization 3) Add abuse-case API tests 4) Log decisions with correlation ids.",
    ),
    "Docker Compose full-stack environment": K(
        "A Docker Compose full-stack environment runs the frontend, API, database, cache, and workers together from versioned local configuration.",
        "Poor Docker Compose full-stack environment lets frontend, backend, and deployment assumptions drift until integration fails late in CI or production.",
        [
            "Docker Compose full-stack environment ownership boundary",
            "Typed schema and runtime validation",
            "Environment or rollout control",
            "Contract and integration test",
        ],
        "Use Docker Compose full-stack environment to publish contracts, validate inputs at runtime, run realistic local or CI services, seed deterministic data, and control rollout with explicit ownership.",
        "Docker Compose full-stack environment reduces drift, but shared packages or flags can create coupling and cleanup debt if ownership is unclear.",
        "If Docker Compose full-stack environment breaks, diff schema versions, generated clients, environment variables, feature flag targeting, service health, and test data setup.",
        "Integration artifact for Docker Compose full-stack environment: OpenAPI diff check, generated TypeScript client, provider contract test, seeded tenant data, and rollout flag cleanup ticket. Evidence cue: A Docker Compose full-stack environment runs the frontend, API, database, cache, and workers together from versioned local configuration.",
        "1) Publish the contract and owner 2) Validate at runtime boundaries 3) Run integration checks with seeded data 4) Clean up flags, clients, and docs after rollout.",
    ),
    "E2E test": K(
        "An E2E test exercises a user journey through the real frontend, backend, and persistence layers.",
        "Unclear E2E test causes teams to debug the wrong layer while users see failed saves, stale data, or confusing errors.",
        [
            "E2E test request path",
            "Backend authority",
            "Data and cache consistency",
            "Observability and rollback",
        ],
        "Trace E2E test from browser event to request, controller, service rule, persistence or dependency, response mapping, cache update, and UI feedback.",
        "E2E test is easiest as a thin vertical slice, but distributed ownership needs stronger contracts, tracing, and operational runbooks.",
        "When E2E test fails, isolate browser network, API logs, validation errors, database queries, cache keys, flags, and deployment version.",
        "Full-stack trace for E2E test: click Save -> typed request -> auth and validation -> domain service -> persistence/cache -> mapped response -> UI success or retry state. Evidence cue: An E2E test exercises a user journey through the real frontend, backend, and persistence layers.",
        "1) Draw the request path 2) Define authority and data contracts 3) Add contract and E2E smoke checks 4) Instrument logs, metrics, traces, and rollback.",
    ),
    "Next.js plus NestJS boundary": K(
        "The Next.js plus NestJS boundary separates rendering and route concerns in Next.js from API, validation, authorization, and domain logic in NestJS.",
        "Poor Next.js plus NestJS boundary produces stale screens, hydration errors, unnecessary JavaScript, or slow first interactions that users experience as broken product behavior.",
        [
            "Next.js plus NestJS boundary render or cache boundary",
            "Freshness and invalidation rule",
            "Loading/error/retry state",
            "Bundle or latency budget",
        ],
        "Design Next.js plus NestJS boundary by choosing server versus client responsibility, defining cache keys and revalidation, handling loading/error states, and measuring payload or latency impact.",
        "Next.js plus NestJS boundary can improve speed and perceived responsiveness, but it increases invalidation, rollback, and mental-model complexity.",
        "If Next.js plus NestJS boundary misbehaves, check cache headers, query keys, revalidation tags, hydration warnings, service worker state, and mutation rollback paths.",
        "Next RSC fetches BFF /api/dashboard; Nest owns authz + aggregation; no direct DB from React Server Components.",
        "1) Choose render and cache ownership 2) Define freshness and invalidation rules 3) Test loading, error, and rollback states 4) Monitor latency, payload, and stale data.",
    ),
    "OpenAPI-generated clients": K(
        "OpenAPI-generated clients turn an API schema into typed request functions so frontend and backend contracts drift less.",
        "Poor OpenAPI-generated clients lets frontend, backend, and deployment assumptions drift until integration fails late in CI or production.",
        [
            "OpenAPI-generated clients ownership boundary",
            "Typed schema and runtime validation",
            "Environment or rollout control",
            "Contract and integration test",
        ],
        "Use OpenAPI-generated clients to publish contracts, validate inputs at runtime, run realistic local or CI services, seed deterministic data, and control rollout with explicit ownership.",
        "OpenAPI-generated clients reduces drift, but shared packages or flags can create coupling and cleanup debt if ownership is unclear.",
        "If OpenAPI-generated clients breaks, diff schema versions, generated clients, environment variables, feature flag targeting, service health, and test data setup.",
        "Integration artifact for OpenAPI-generated clients: OpenAPI diff check, generated TypeScript client, provider contract test, seeded tenant data, and rollout flag cleanup ticket. Evidence cue: OpenAPI-generated clients turn an API schema into typed request functions so frontend and backend contracts drift less.",
        "1) Publish the contract and owner 2) Validate at runtime boundaries 3) Run integration checks with seeded data 4) Clean up flags, clients, and docs after rollout.",
    ),
    "RSC boundary": K(
        "The RSC boundary separates React Server Components, which run on the server, from Client Components that hydrate and handle browser interactivity.",
        "Poor RSC boundary produces stale screens, hydration errors, unnecessary JavaScript, or slow first interactions that users experience as broken product behavior.",
        [
            "RSC boundary render or cache boundary",
            "Freshness and invalidation rule",
            "Loading/error/retry state",
            "Bundle or latency budget",
        ],
        "Design RSC boundary by choosing server versus client responsibility, defining cache keys and revalidation, handling loading/error states, and measuring payload or latency impact.",
        "RSC boundary can improve speed and perceived responsiveness, but it increases invalidation, rollback, and mental-model complexity.",
        "If RSC boundary misbehaves, check cache headers, query keys, revalidation tags, hydration warnings, service worker state, and mutation rollback paths.",
        "Server Component lists products; Client Component owns add-to-cart mutation + optimistic UI; no secrets in client bundle.",
        "1) Choose render and cache ownership 2) Define freshness and invalidation rules 3) Test loading, error, and rollback states 4) Monitor latency, payload, and stale data.",
    ),
    "SSR": K(
        "SSR renders HTML on the server before sending it to the browser, improving first paint or SEO for suitable routes.",
        "Poor SSR produces stale screens, hydration errors, unnecessary JavaScript, or slow first interactions that users experience as broken product behavior.",
        [
            "SSR render or cache boundary",
            "Freshness and invalidation rule",
            "Loading/error/retry state",
            "Bundle or latency budget",
        ],
        "Design SSR by choosing server versus client responsibility, defining cache keys and revalidation, handling loading/error states, and measuring payload or latency impact.",
        "SSR can improve speed and perceived responsiveness, but it increases invalidation, rollback, and mental-model complexity.",
        "If SSR misbehaves, check cache headers, query keys, revalidation tags, hydration warnings, service worker state, and mutation rollback paths.",
        "Product page SSR for SEO/TTFB; personalize cart badge client-side after hydrate to avoid cache fragmentation.",
        "1) Choose render and cache ownership 2) Define freshness and invalidation rules 3) Test loading, error, and rollback states 4) Monitor latency, payload, and stale data.",
    ),
    "WebSocket end-to-end flow": K(
        "A WebSocket end-to-end flow keeps a persistent connection so the server can push real-time events to the browser.",
        "Weak WebSocket end-to-end flow lets UI status drift from committed backend state, especially around retries, jobs, webhooks, files, or rolling deploys.",
        [
            "WebSocket end-to-end flow state machine",
            "Idempotency or ordering rule",
            "Persistence and async boundary",
            "Reconciliation and audit trail",
        ],
        "Build WebSocket end-to-end flow with explicit states, idempotency keys where retries happen, transactional writes for local invariants, workers for slow tasks, and a response the UI can recover from.",
        "WebSocket end-to-end flow is simpler when synchronous, but asynchronous processing improves resilience and scale at the cost of status, ordering, and reconciliation logic.",
        "When WebSocket end-to-end flow is inconsistent, follow the correlation id through API logs, database rows, queue messages, webhook receipts, cache invalidation, and frontend state.",
        "State flow for WebSocket end-to-end flow: request accepted -> row pending -> worker processes -> status succeeded/failed -> UI subscribes or polls -> audit record stored. Evidence cue: A WebSocket end-to-end flow keeps a persistent connection so the server can push real-time events to the browser.",
        "1) Model states and idempotency 2) Implement transaction or worker boundary 3) Expose user-visible status 4) Reconcile failures with audit data.",
    ),
    "audit trail across frontend and backend": K(
        "An audit trail across frontend and backend records who did what, when, from which context, and which backend action resulted.",
        "Weak audit trail across frontend and backend lets UI status drift from committed backend state, especially around retries, jobs, webhooks, files, or rolling deploys.",
        [
            "audit trail across frontend and backend state machine",
            "Idempotency or ordering rule",
            "Persistence and async boundary",
            "Reconciliation and audit trail",
        ],
        "Build audit trail across frontend and backend with explicit states, idempotency keys where retries happen, transactional writes for local invariants, workers for slow tasks, and a response the UI can recover from.",
        "audit trail across frontend and backend is simpler when synchronous, but asynchronous processing improves resilience and scale at the cost of status, ordering, and reconciliation logic.",
        "When audit trail across frontend and backend is inconsistent, follow the correlation id through API logs, database rows, queue messages, webhook receipts, cache invalidation, and frontend state.",
        "State flow for audit trail across frontend and backend: request accepted -> row pending -> worker processes -> status succeeded/failed -> UI subscribes or polls -> audit record stored. Evidence cue: An audit trail across frontend and backend records who did what, when, from which context, and which backend action resulted.",
        "1) Model states and idempotency 2) Implement transaction or worker boundary 3) Expose user-visible status 4) Reconcile failures with audit data.",
    ),
    "authentication vs authorization across layers": K(
        "Authentication proves identity, while authorization decides what that identity may do at each frontend and backend boundary.",
        "Misimplemented authentication vs authorization across layers can expose accounts, leak data across tenants, or let the frontend imply permissions the backend never enforced.",
        [
            "authentication vs authorization across layers trust boundary",
            "Cookie or token lifecycle",
            "Server-side policy enforcement",
            "Safe error and audit behavior",
        ],
        "Implement authentication vs authorization across layers with server-side validation, explicit browser security headers or cookie attributes, policy checks on every protected resource, and user-safe error responses.",
        "authentication vs authorization across layers hardening can add redirects, token refresh complexity, or stricter local setup, but it prevents high-impact account and data exposure.",
        "When authentication vs authorization across layers fails, inspect request headers, Set-Cookie attributes, CSRF token flow, backend guard decisions, tenant filters, and audit logs.",
        "Security flow for authentication vs authorization across layers: login sets HttpOnly SameSite cookie; mutating request sends CSRF header; API guard checks session, role, tenant, and audit event. Evidence cue: Authentication proves identity, while authorization decides what that identity may do at each frontend and backend boundary.",
        "1) Define browser credential policy 2) Enforce backend authorization 3) Add abuse-case API tests 4) Log decisions with correlation ids.",
    ),
    "backward-compatible API change": K(
        "A backward-compatible API change lets old and new clients work during independent deploys by adding behavior before removing old fields.",
        "Poor backward-compatible API change lets frontend, backend, and deployment assumptions drift until integration fails late in CI or production.",
        [
            "backward-compatible API change ownership boundary",
            "Typed schema and runtime validation",
            "Environment or rollout control",
            "Contract and integration test",
        ],
        "Use backward-compatible API change to publish contracts, validate inputs at runtime, run realistic local or CI services, seed deterministic data, and control rollout with explicit ownership.",
        "backward-compatible API change reduces drift, but shared packages or flags can create coupling and cleanup debt if ownership is unclear.",
        "If backward-compatible API change breaks, diff schema versions, generated clients, environment variables, feature flag targeting, service health, and test data setup.",
        "Integration artifact for backward-compatible API change: OpenAPI diff check, generated TypeScript client, provider contract test, seeded tenant data, and rollout flag cleanup ticket. Evidence cue: A backward-compatible API change lets old and new clients work during independent deploys by adding behavior before removing old fields.",
        "1) Publish the contract and owner 2) Validate at runtime boundaries 3) Run integration checks with seeded data 4) Clean up flags, clients, and docs after rollout.",
    ),
    "browser cache": K(
        "The browser cache stores HTTP responses locally according to headers such as Cache-Control, ETag, and Last-Modified.",
        "Poor browser cache produces stale screens, hydration errors, unnecessary JavaScript, or slow first interactions that users experience as broken product behavior.",
        [
            "browser cache render or cache boundary",
            "Freshness and invalidation rule",
            "Loading/error/retry state",
            "Bundle or latency budget",
        ],
        "Design browser cache by choosing server versus client responsibility, defining cache keys and revalidation, handling loading/error states, and measuring payload or latency impact.",
        "browser cache can improve speed and perceived responsiveness, but it increases invalidation, rollback, and mental-model complexity.",
        "If browser cache misbehaves, check cache headers, query keys, revalidation tags, hydration warnings, service worker state, and mutation rollback paths.",
        "API GET /me Cache-Control: private, no-store; static /_next/static hashed assets immutable 1y.",
        "1) Choose render and cache ownership 2) Define freshness and invalidation rules 3) Test loading, error, and rollback states 4) Monitor latency, payload, and stale data.",
    ),
    "browser-to-database request path": K(
        "A browser-to-database request path traces a user action through HTTP, backend routing, service logic, persistence, and the returned UI state.",
        "Weak browser-to-database request path lets UI status drift from committed backend state, especially around retries, jobs, webhooks, files, or rolling deploys.",
        [
            "browser-to-database request path state machine",
            "Idempotency or ordering rule",
            "Persistence and async boundary",
            "Reconciliation and audit trail",
        ],
        "Build browser-to-database request path with explicit states, idempotency keys where retries happen, transactional writes for local invariants, workers for slow tasks, and a response the UI can recover from.",
        "browser-to-database request path is simpler when synchronous, but asynchronous processing improves resilience and scale at the cost of status, ordering, and reconciliation logic.",
        "When browser-to-database request path is inconsistent, follow the correlation id through API logs, database rows, queue messages, webhook receipts, cache invalidation, and frontend state.",
        "State flow for browser-to-database request path: request accepted -> row pending -> worker processes -> status succeeded/failed -> UI subscribes or polls -> audit record stored. Evidence cue: A browser-to-database request path traces a user action through HTTP, backend routing, service logic, persistence, and the returned UI state.",
        "1) Model states and idempotency 2) Implement transaction or worker boundary 3) Expose user-visible status 4) Reconcile failures with audit data.",
    ),
    "client validation": K(
        "Client validation gives immediate feedback in the browser but cannot replace server-side validation at trust boundaries.",
        "Unclear client validation causes teams to debug the wrong layer while users see failed saves, stale data, or confusing errors.",
        [
            "client validation request path",
            "Backend authority",
            "Data and cache consistency",
            "Observability and rollback",
        ],
        "Trace client validation from browser event to request, controller, service rule, persistence or dependency, response mapping, cache update, and UI feedback.",
        "client validation is easiest as a thin vertical slice, but distributed ownership needs stronger contracts, tracing, and operational runbooks.",
        "When client validation fails, isolate browser network, API logs, validation errors, database queries, cache keys, flags, and deployment version.",
        "Full-stack trace for client validation: click Save -> typed request -> auth and validation -> domain service -> persistence/cache -> mapped response -> UI success or retry state. Evidence cue: Client validation gives immediate feedback in the browser but cannot replace server-side validation at trust boundaries.",
        "1) Draw the request path 2) Define authority and data contracts 3) Add contract and E2E smoke checks 4) Instrument logs, metrics, traces, and rollback.",
    ),
    "contract test": K(
        "A contract test verifies that a provider and consumer still agree on request and response shapes without running a full E2E stack.",
        "Poor contract test lets frontend, backend, and deployment assumptions drift until integration fails late in CI or production.",
        [
            "contract test ownership boundary",
            "Typed schema and runtime validation",
            "Environment or rollout control",
            "Contract and integration test",
        ],
        "Use contract test to publish contracts, validate inputs at runtime, run realistic local or CI services, seed deterministic data, and control rollout with explicit ownership.",
        "contract test reduces drift, but shared packages or flags can create coupling and cleanup debt if ownership is unclear.",
        "If contract test breaks, diff schema versions, generated clients, environment variables, feature flag targeting, service health, and test data setup.",
        "Integration artifact for contract test: OpenAPI diff check, generated TypeScript client, provider contract test, seeded tenant data, and rollout flag cleanup ticket. Evidence cue: A contract test verifies that a provider and consumer still agree on request and response shapes without running a full E2E stack.",
        "1) Publish the contract and owner 2) Validate at runtime boundaries 3) Run integration checks with seeded data 4) Clean up flags, clients, and docs after rollout.",
    ),
    "direct-to-object-storage upload": K(
        "Direct-to-object-storage upload lets the browser send files to S3-like storage using a short-lived signed URL from the backend.",
        "Weak direct-to-object-storage upload lets UI status drift from committed backend state, especially around retries, jobs, webhooks, files, or rolling deploys.",
        [
            "direct-to-object-storage upload state machine",
            "Idempotency or ordering rule",
            "Persistence and async boundary",
            "Reconciliation and audit trail",
        ],
        "Build direct-to-object-storage upload with explicit states, idempotency keys where retries happen, transactional writes for local invariants, workers for slow tasks, and a response the UI can recover from.",
        "direct-to-object-storage upload is simpler when synchronous, but asynchronous processing improves resilience and scale at the cost of status, ordering, and reconciliation logic.",
        "When direct-to-object-storage upload is inconsistent, follow the correlation id through API logs, database rows, queue messages, webhook receipts, cache invalidation, and frontend state.",
        "State flow for direct-to-object-storage upload: request accepted -> row pending -> worker processes -> status succeeded/failed -> UI subscribes or polls -> audit record stored. Evidence cue: Direct-to-object-storage upload lets the browser send files to S3-like storage using a short-lived signed URL from the backend.",
        "1) Model states and idempotency 2) Implement transaction or worker boundary 3) Expose user-visible status 4) Reconcile failures with audit data.",
    ),
    "ecommerce checkout flow": K(
        "An ecommerce checkout flow coordinates cart, pricing, inventory, payment, order creation, confirmation, and failure recovery.",
        "Weak ecommerce checkout flow lets UI status drift from committed backend state, especially around retries, jobs, webhooks, files, or rolling deploys.",
        [
            "ecommerce checkout flow state machine",
            "Idempotency or ordering rule",
            "Persistence and async boundary",
            "Reconciliation and audit trail",
        ],
        "Build ecommerce checkout flow with explicit states, idempotency keys where retries happen, transactional writes for local invariants, workers for slow tasks, and a response the UI can recover from.",
        "ecommerce checkout flow is simpler when synchronous, but asynchronous processing improves resilience and scale at the cost of status, ordering, and reconciliation logic.",
        "When ecommerce checkout flow is inconsistent, follow the correlation id through API logs, database rows, queue messages, webhook receipts, cache invalidation, and frontend state.",
        "State flow for ecommerce checkout flow: request accepted -> row pending -> worker processes -> status succeeded/failed -> UI subscribes or polls -> audit record stored. Evidence cue: An ecommerce checkout flow coordinates cart, pricing, inventory, payment, order creation, confirmation, and failure recovery.",
        "1) Model states and idempotency 2) Implement transaction or worker boundary 3) Expose user-visible status 4) Reconcile failures with audit data.",
    ),
    "end-to-end correlation ID": K(
        "An end-to-end correlation ID is a request identifier propagated through browser, API, logs, traces, queues, and downstream calls.",
        "Unclear end-to-end correlation ID causes teams to debug the wrong layer while users see failed saves, stale data, or confusing errors.",
        [
            "end-to-end correlation ID request path",
            "Backend authority",
            "Data and cache consistency",
            "Observability and rollback",
        ],
        "Trace end-to-end correlation ID from browser event to request, controller, service rule, persistence or dependency, response mapping, cache update, and UI feedback.",
        "end-to-end correlation ID is easiest as a thin vertical slice, but distributed ownership needs stronger contracts, tracing, and operational runbooks.",
        "When end-to-end correlation ID fails, isolate browser network, API logs, validation errors, database queries, cache keys, flags, and deployment version.",
        "Full-stack trace for end-to-end correlation ID: click Save -> typed request -> auth and validation -> domain service -> persistence/cache -> mapped response -> UI success or retry state. Evidence cue: An end-to-end correlation ID is a request identifier propagated through browser, API, logs, traces, queues, and downstream calls.",
        "1) Draw the request path 2) Define authority and data contracts 3) Add contract and E2E smoke checks 4) Instrument logs, metrics, traces, and rollback.",
    ),
    "feature flag": K(
        "A feature flag controls exposure of behavior at runtime so teams can release, target, test, or roll back without redeploying.",
        "Poor feature flag lets frontend, backend, and deployment assumptions drift until integration fails late in CI or production.",
        [
            "feature flag ownership boundary",
            "Typed schema and runtime validation",
            "Environment or rollout control",
            "Contract and integration test",
        ],
        "Use feature flag to publish contracts, validate inputs at runtime, run realistic local or CI services, seed deterministic data, and control rollout with explicit ownership.",
        "feature flag reduces drift, but shared packages or flags can create coupling and cleanup debt if ownership is unclear.",
        "If feature flag breaks, diff schema versions, generated clients, environment variables, feature flag targeting, service health, and test data setup.",
        "Integration artifact for feature flag: OpenAPI diff check, generated TypeScript client, provider contract test, seeded tenant data, and rollout flag cleanup ticket. Evidence cue: A feature flag controls exposure of behavior at runtime so teams can release, target, test, or roll back without redeploying.",
        "1) Publish the contract and owner 2) Validate at runtime boundaries 3) Run integration checks with seeded data 4) Clean up flags, clients, and docs after rollout.",
    ),
    "file-processing pipeline": K(
        "A file-processing pipeline accepts uploads, stores metadata, runs asynchronous processing, and reports status or errors back to users.",
        "Weak file-processing pipeline lets UI status drift from committed backend state, especially around retries, jobs, webhooks, files, or rolling deploys.",
        [
            "file-processing pipeline state machine",
            "Idempotency or ordering rule",
            "Persistence and async boundary",
            "Reconciliation and audit trail",
        ],
        "Build file-processing pipeline with explicit states, idempotency keys where retries happen, transactional writes for local invariants, workers for slow tasks, and a response the UI can recover from.",
        "file-processing pipeline is simpler when synchronous, but asynchronous processing improves resilience and scale at the cost of status, ordering, and reconciliation logic.",
        "When file-processing pipeline is inconsistent, follow the correlation id through API logs, database rows, queue messages, webhook receipts, cache invalidation, and frontend state.",
        "State flow for file-processing pipeline: request accepted -> row pending -> worker processes -> status succeeded/failed -> UI subscribes or polls -> audit record stored. Evidence cue: A file-processing pipeline accepts uploads, stores metadata, runs asynchronous processing, and reports status or errors back to users.",
        "1) Model states and idempotency 2) Implement transaction or worker boundary 3) Expose user-visible status 4) Reconcile failures with audit data.",
    ),
    "full-stack error model": K(
        "A full-stack error model defines consistent backend error codes, HTTP status, user-safe messages, logging, and frontend presentation.",
        "Unclear full-stack error model causes teams to debug the wrong layer while users see failed saves, stale data, or confusing errors.",
        [
            "full-stack error model request path",
            "Backend authority",
            "Data and cache consistency",
            "Observability and rollback",
        ],
        "Trace full-stack error model from browser event to request, controller, service rule, persistence or dependency, response mapping, cache update, and UI feedback.",
        "full-stack error model is easiest as a thin vertical slice, but distributed ownership needs stronger contracts, tracing, and operational runbooks.",
        "When full-stack error model fails, isolate browser network, API logs, validation errors, database queries, cache keys, flags, and deployment version.",
        "Full-stack trace for full-stack error model: click Save -> typed request -> auth and validation -> domain service -> persistence/cache -> mapped response -> UI success or retry state. Evidence cue: A full-stack error model defines consistent backend error codes, HTTP status, user-safe messages, logging, and frontend presentation.",
        "1) Draw the request path 2) Define authority and data contracts 3) Add contract and E2E smoke checks 4) Instrument logs, metrics, traces, and rollback.",
    ),
    "full-stack performance budget": K(
        "A full-stack performance budget allocates latency and resource targets across browser, network, API, database, cache, and dependencies.",
        "Unclear full-stack performance budget causes teams to debug the wrong layer while users see failed saves, stale data, or confusing errors.",
        [
            "full-stack performance budget request path",
            "Backend authority",
            "Data and cache consistency",
            "Observability and rollback",
        ],
        "Trace full-stack performance budget from browser event to request, controller, service rule, persistence or dependency, response mapping, cache update, and UI feedback.",
        "full-stack performance budget is easiest as a thin vertical slice, but distributed ownership needs stronger contracts, tracing, and operational runbooks.",
        "When full-stack performance budget fails, isolate browser network, API logs, validation errors, database queries, cache keys, flags, and deployment version.",
        "Full-stack trace for full-stack performance budget: click Save -> typed request -> auth and validation -> domain service -> persistence/cache -> mapped response -> UI success or retry state. Evidence cue: A full-stack performance budget allocates latency and resource targets across browser, network, API, database, cache, and dependencies.",
        "1) Draw the request path 2) Define authority and data contracts 3) Add contract and E2E smoke checks 4) Instrument logs, metrics, traces, and rollback.",
    ),
    "hydration": K(
        "Hydration attaches client-side React behavior to server-rendered HTML so the page becomes interactive.",
        "Poor hydration produces stale screens, hydration errors, unnecessary JavaScript, or slow first interactions that users experience as broken product behavior.",
        [
            "SSR HTML + client attach",
            "Mismatch causes warnings/errors",
            "Keep nondeterministic values client-only",
            "Progressive enhancement",
        ],
        "Design hydration by choosing server versus client responsibility, defining cache keys and revalidation, handling loading/error states, and measuring payload or latency impact.",
        "hydration can improve speed and perceived responsiveness, but it increases invalidation, rollback, and mental-model complexity.",
        "If hydration misbehaves, check cache headers, query keys, revalidation tags, hydration warnings, service worker state, and mutation rollback paths.",
        "Avoid Date.now() in SSR markup; render relative time only after mount; fix text mismatch that throws hydration warnings.",
        "1) Choose render and cache ownership 2) Define freshness and invalidation rules 3) Test loading, error, and rollback states 4) Monitor latency, payload, and stale data.",
    ),
    "modular monolith full stack": K(
        "A modular monolith full stack keeps one deployable application while enforcing internal module boundaries across UI, domain, and data.",
        "Poor modular monolith full stack lets frontend, backend, and deployment assumptions drift until integration fails late in CI or production.",
        [
            "modular monolith full stack ownership boundary",
            "Typed schema and runtime validation",
            "Environment or rollout control",
            "Contract and integration test",
        ],
        "Use modular monolith full stack to publish contracts, validate inputs at runtime, run realistic local or CI services, seed deterministic data, and control rollout with explicit ownership.",
        "modular monolith full stack reduces drift, but shared packages or flags can create coupling and cleanup debt if ownership is unclear.",
        "If modular monolith full stack breaks, diff schema versions, generated clients, environment variables, feature flag targeting, service health, and test data setup.",
        "Integration artifact for modular monolith full stack: OpenAPI diff check, generated TypeScript client, provider contract test, seeded tenant data, and rollout flag cleanup ticket. Evidence cue: A modular monolith full stack keeps one deployable application while enforcing internal module boundaries across UI, domain, and data.",
        "1) Publish the contract and owner 2) Validate at runtime boundaries 3) Run integration checks with seeded data 4) Clean up flags, clients, and docs after rollout.",
    ),
    "multi-layer invalidation": K(
        "Multi-layer invalidation clears or refreshes stale data across browser cache, CDN, server cache, query cache, and database-derived views.",
        "Poor multi-layer invalidation produces stale screens, hydration errors, unnecessary JavaScript, or slow first interactions that users experience as broken product behavior.",
        [
            "multi-layer invalidation render or cache boundary",
            "Freshness and invalidation rule",
            "Loading/error/retry state",
            "Bundle or latency budget",
        ],
        "Design multi-layer invalidation by choosing server versus client responsibility, defining cache keys and revalidation, handling loading/error states, and measuring payload or latency impact.",
        "multi-layer invalidation can improve speed and perceived responsiveness, but it increases invalidation, rollback, and mental-model complexity.",
        "If multi-layer invalidation misbehaves, check cache headers, query keys, revalidation tags, hydration warnings, service worker state, and mutation rollback paths.",
        "On price update: write DB \u2192 bust Redis product:{id} \u2192 purge CDN \u2192 invalidate React Query key [\"product\", id].",
        "1) Choose render and cache ownership 2) Define freshness and invalidation rules 3) Test loading, error, and rollback states 4) Monitor latency, payload, and stale data.",
    ),
    "multi-tenant full-stack app": K(
        "A multi-tenant full-stack app serves multiple customer organizations while isolating data, configuration, branding, and permissions.",
        "Misimplemented multi-tenant full-stack app can expose accounts, leak data across tenants, or let the frontend imply permissions the backend never enforced.",
        [
            "multi-tenant full-stack app trust boundary",
            "Cookie or token lifecycle",
            "Server-side policy enforcement",
            "Safe error and audit behavior",
        ],
        "Implement multi-tenant full-stack app with server-side validation, explicit browser security headers or cookie attributes, policy checks on every protected resource, and user-safe error responses.",
        "multi-tenant full-stack app hardening can add redirects, token refresh complexity, or stricter local setup, but it prevents high-impact account and data exposure.",
        "When multi-tenant full-stack app fails, inspect request headers, Set-Cookie attributes, CSRF token flow, backend guard decisions, tenant filters, and audit logs.",
        "Security flow for multi-tenant full-stack app: login sets HttpOnly SameSite cookie; mutating request sends CSRF header; API guard checks session, role, tenant, and audit event. Evidence cue: A multi-tenant full-stack app serves multiple customer organizations while isolating data, configuration, branding, and permissions.",
        "1) Define browser credential policy 2) Enforce backend authorization 3) Add abuse-case API tests 4) Log decisions with correlation ids.",
    ),
    "offline-capable web app": K(
        "An offline-capable web app uses local storage, service workers, sync queues, and conflict handling so users can work without a network.",
        "Poor offline-capable web app produces stale screens, hydration errors, unnecessary JavaScript, or slow first interactions that users experience as broken product behavior.",
        [
            "offline-capable web app render or cache boundary",
            "Freshness and invalidation rule",
            "Loading/error/retry state",
            "Bundle or latency budget",
        ],
        "Design offline-capable web app by choosing server versus client responsibility, defining cache keys and revalidation, handling loading/error states, and measuring payload or latency impact.",
        "offline-capable web app can improve speed and perceived responsiveness, but it increases invalidation, rollback, and mental-model complexity.",
        "If offline-capable web app misbehaves, check cache headers, query keys, revalidation tags, hydration warnings, service worker state, and mutation rollback paths.",
        "Service worker caches shell; IndexedDB queues create-order; sync on online with idempotency key; conflict UI if server rejects.",
        "1) Choose render and cache ownership 2) Define freshness and invalidation rules 3) Test loading, error, and rollback states 4) Monitor latency, payload, and stale data.",
    ),
    "optimistic update": K(
        "An optimistic update changes UI state before the server confirms success, then reconciles or rolls back based on the response.",
        "Poor optimistic update produces stale screens, hydration errors, unnecessary JavaScript, or slow first interactions that users experience as broken product behavior.",
        [
            "optimistic update render or cache boundary",
            "Freshness and invalidation rule",
            "Loading/error/retry state",
            "Bundle or latency budget",
        ],
        "Design optimistic update by choosing server versus client responsibility, defining cache keys and revalidation, handling loading/error states, and measuring payload or latency impact.",
        "optimistic update can improve speed and perceived responsiveness, but it increases invalidation, rollback, and mental-model complexity.",
        "If optimistic update misbehaves, check cache headers, query keys, revalidation tags, hydration warnings, service worker state, and mutation rollback paths.",
        "onMutate cancels queries, snapshots cart, patches UI; onError rollback snapshot; onSettled invalidate [\"cart\"].",
        "1) Choose render and cache ownership 2) Define freshness and invalidation rules 3) Test loading, error, and rollback states 4) Monitor latency, payload, and stale data.",
    ),
    "presence system": K(
        "A presence system shows which users are online, active, idle, or viewing the same resource in near real time.",
        "Weak presence system lets UI status drift from committed backend state, especially around retries, jobs, webhooks, files, or rolling deploys.",
        [
            "presence system state machine",
            "Idempotency or ordering rule",
            "Persistence and async boundary",
            "Reconciliation and audit trail",
        ],
        "Build presence system with explicit states, idempotency keys where retries happen, transactional writes for local invariants, workers for slow tasks, and a response the UI can recover from.",
        "presence system is simpler when synchronous, but asynchronous processing improves resilience and scale at the cost of status, ordering, and reconciliation logic.",
        "When presence system is inconsistent, follow the correlation id through API logs, database rows, queue messages, webhook receipts, cache invalidation, and frontend state.",
        "State flow for presence system: request accepted -> row pending -> worker processes -> status succeeded/failed -> UI subscribes or polls -> audit record stored. Evidence cue: A presence system shows which users are online, active, idle, or viewing the same resource in near real time.",
        "1) Model states and idempotency 2) Implement transaction or worker boundary 3) Expose user-visible status 4) Reconcile failures with audit data.",
    ),
    "real-time dashboard": K(
        "A real-time dashboard streams or polls fresh metrics and renders them with latency, ordering, and error handling in mind.",
        "Weak real-time dashboard lets UI status drift from committed backend state, especially around retries, jobs, webhooks, files, or rolling deploys.",
        [
            "real-time dashboard state machine",
            "Idempotency or ordering rule",
            "Persistence and async boundary",
            "Reconciliation and audit trail",
        ],
        "Build real-time dashboard with explicit states, idempotency keys where retries happen, transactional writes for local invariants, workers for slow tasks, and a response the UI can recover from.",
        "real-time dashboard is simpler when synchronous, but asynchronous processing improves resilience and scale at the cost of status, ordering, and reconciliation logic.",
        "When real-time dashboard is inconsistent, follow the correlation id through API logs, database rows, queue messages, webhook receipts, cache invalidation, and frontend state.",
        "State flow for real-time dashboard: request accepted -> row pending -> worker processes -> status succeeded/failed -> UI subscribes or polls -> audit record stored. Evidence cue: A real-time dashboard streams or polls fresh metrics and renders them with latency, ordering, and error handling in mind.",
        "1) Model states and idempotency 2) Implement transaction or worker boundary 3) Expose user-visible status 4) Reconcile failures with audit data.",
    ),
    "refresh-token flow": K(
        "A refresh-token flow exchanges a long-lived refresh credential for short-lived access tokens while managing rotation and revocation.",
        "Unclear refresh-token flow causes teams to debug the wrong layer while users see failed saves, stale data, or confusing errors.",
        [
            "refresh-token flow request path",
            "Backend authority",
            "Data and cache consistency",
            "Observability and rollback",
        ],
        "Trace refresh-token flow from browser event to request, controller, service rule, persistence or dependency, response mapping, cache update, and UI feedback.",
        "refresh-token flow is easiest as a thin vertical slice, but distributed ownership needs stronger contracts, tracing, and operational runbooks.",
        "When refresh-token flow fails, isolate browser network, API logs, validation errors, database queries, cache keys, flags, and deployment version.",
        "Full-stack trace for refresh-token flow: click Save -> typed request -> auth and validation -> domain service -> persistence/cache -> mapped response -> UI success or retry state. Evidence cue: A refresh-token flow exchanges a long-lived refresh credential for short-lived access tokens while managing rotation and revocation.",
        "1) Draw the request path 2) Define authority and data contracts 3) Add contract and E2E smoke checks 4) Instrument logs, metrics, traces, and rollback.",
    ),
    "secure cookie session": K(
        "A secure cookie session stores the session identifier in a cookie protected with HttpOnly, Secure, SameSite, and server-side validation.",
        "Misimplemented secure cookie session can expose accounts, leak data across tenants, or let the frontend imply permissions the backend never enforced.",
        [
            "secure cookie session trust boundary",
            "Cookie or token lifecycle",
            "Server-side policy enforcement",
            "Safe error and audit behavior",
        ],
        "Implement secure cookie session with server-side validation, explicit browser security headers or cookie attributes, policy checks on every protected resource, and user-safe error responses.",
        "secure cookie session hardening can add redirects, token refresh complexity, or stricter local setup, but it prevents high-impact account and data exposure.",
        "When secure cookie session fails, inspect request headers, Set-Cookie attributes, CSRF token flow, backend guard decisions, tenant filters, and audit logs.",
        "Security flow for secure cookie session: login sets HttpOnly SameSite cookie; mutating request sends CSRF header; API guard checks session, role, tenant, and audit event. Evidence cue: A secure cookie session stores the session identifier in a cookie protected with HttpOnly, Secure, SameSite, and server-side validation.",
        "1) Define browser credential policy 2) Enforce backend authorization 3) Add abuse-case API tests 4) Log decisions with correlation ids.",
    ),
    "server state": K(
        "Server state is remote data owned by the backend that the frontend caches, invalidates, refetches, and reconciles.",
        "Poor server state produces stale screens, hydration errors, unnecessary JavaScript, or slow first interactions that users experience as broken product behavior.",
        [
            "server state render or cache boundary",
            "Freshness and invalidation rule",
            "Loading/error/retry state",
            "Bundle or latency budget",
        ],
        "Design server state by choosing server versus client responsibility, defining cache keys and revalidation, handling loading/error states, and measuring payload or latency impact.",
        "server state can improve speed and perceived responsiveness, but it increases invalidation, rollback, and mental-model complexity.",
        "If server state misbehaves, check cache headers, query keys, revalidation tags, hydration warnings, service worker state, and mutation rollback paths.",
        "TanStack Query: queryKey [\"orders\", filters], staleTime 30s, mutation invalidates list; do not mirror server list in Zustand.",
        "1) Choose render and cache ownership 2) Define freshness and invalidation rules 3) Test loading, error, and rollback states 4) Monitor latency, payload, and stale data.",
    ),
    "shared API types": K(
        "Shared API types are common request and response definitions used by frontend and backend to reduce compile-time drift.",
        "Poor shared API types lets frontend, backend, and deployment assumptions drift until integration fails late in CI or production.",
        [
            "shared API types ownership boundary",
            "Typed schema and runtime validation",
            "Environment or rollout control",
            "Contract and integration test",
        ],
        "Use shared API types to publish contracts, validate inputs at runtime, run realistic local or CI services, seed deterministic data, and control rollout with explicit ownership.",
        "shared API types reduces drift, but shared packages or flags can create coupling and cleanup debt if ownership is unclear.",
        "If shared API types breaks, diff schema versions, generated clients, environment variables, feature flag targeting, service health, and test data setup.",
        "Integration artifact for shared API types: OpenAPI diff check, generated TypeScript client, provider contract test, seeded tenant data, and rollout flag cleanup ticket. Evidence cue: Shared API types are common request and response definitions used by frontend and backend to reduce compile-time drift.",
        "1) Publish the contract and owner 2) Validate at runtime boundaries 3) Run integration checks with seeded data 4) Clean up flags, clients, and docs after rollout.",
    ),
    "shared packages": K(
        "Shared packages are reusable modules in a workspace or monorepo, such as validation schemas, UI components, or utilities.",
        "Poor shared packages lets frontend, backend, and deployment assumptions drift until integration fails late in CI or production.",
        [
            "shared packages ownership boundary",
            "Typed schema and runtime validation",
            "Environment or rollout control",
            "Contract and integration test",
        ],
        "Use shared packages to publish contracts, validate inputs at runtime, run realistic local or CI services, seed deterministic data, and control rollout with explicit ownership.",
        "shared packages reduces drift, but shared packages or flags can create coupling and cleanup debt if ownership is unclear.",
        "If shared packages breaks, diff schema versions, generated clients, environment variables, feature flag targeting, service health, and test data setup.",
        "Integration artifact for shared packages: OpenAPI diff check, generated TypeScript client, provider contract test, seeded tenant data, and rollout flag cleanup ticket. Evidence cue: Shared packages are reusable modules in a workspace or monorepo, such as validation schemas, UI components, or utilities.",
        "1) Publish the contract and owner 2) Validate at runtime boundaries 3) Run integration checks with seeded data 4) Clean up flags, clients, and docs after rollout.",
    ),
    "subscription SaaS": K(
        "Subscription SaaS combines account tenancy, billing plans, entitlements, invoices, trials, renewals, and cancellation flows.",
        "Unclear subscription SaaS causes teams to debug the wrong layer while users see failed saves, stale data, or confusing errors.",
        [
            "subscription SaaS request path",
            "Backend authority",
            "Data and cache consistency",
            "Observability and rollback",
        ],
        "Trace subscription SaaS from browser event to request, controller, service rule, persistence or dependency, response mapping, cache update, and UI feedback.",
        "subscription SaaS is easiest as a thin vertical slice, but distributed ownership needs stronger contracts, tracing, and operational runbooks.",
        "When subscription SaaS fails, isolate browser network, API logs, validation errors, database queries, cache keys, flags, and deployment version.",
        "Full-stack trace for subscription SaaS: click Save -> typed request -> auth and validation -> domain service -> persistence/cache -> mapped response -> UI success or retry state. Evidence cue: Subscription SaaS combines account tenancy, billing plans, entitlements, invoices, trials, renewals, and cancellation flows.",
        "1) Draw the request path 2) Define authority and data contracts 3) Add contract and E2E smoke checks 4) Instrument logs, metrics, traces, and rollback.",
    ),
    "test data management": K(
        "Test data management creates deterministic users, tenants, records, and cleanup rules so full-stack tests are reliable.",
        "Poor test data management lets frontend, backend, and deployment assumptions drift until integration fails late in CI or production.",
        [
            "test data management ownership boundary",
            "Typed schema and runtime validation",
            "Environment or rollout control",
            "Contract and integration test",
        ],
        "Use test data management to publish contracts, validate inputs at runtime, run realistic local or CI services, seed deterministic data, and control rollout with explicit ownership.",
        "test data management reduces drift, but shared packages or flags can create coupling and cleanup debt if ownership is unclear.",
        "If test data management breaks, diff schema versions, generated clients, environment variables, feature flag targeting, service health, and test data setup.",
        "Integration artifact for test data management: OpenAPI diff check, generated TypeScript client, provider contract test, seeded tenant data, and rollout flag cleanup ticket. Evidence cue: Test data management creates deterministic users, tenants, records, and cleanup rules so full-stack tests are reliable.",
        "1) Publish the contract and owner 2) Validate at runtime boundaries 3) Run integration checks with seeded data 4) Clean up flags, clients, and docs after rollout.",
    ),
    "transactional workflow": K(
        "A transactional workflow coordinates multiple state changes so critical business invariants are committed or rolled back correctly.",
        "Weak transactional workflow lets UI status drift from committed backend state, especially around retries, jobs, webhooks, files, or rolling deploys.",
        [
            "transactional workflow state machine",
            "Idempotency or ordering rule",
            "Persistence and async boundary",
            "Reconciliation and audit trail",
        ],
        "Build transactional workflow with explicit states, idempotency keys where retries happen, transactional writes for local invariants, workers for slow tasks, and a response the UI can recover from.",
        "transactional workflow is simpler when synchronous, but asynchronous processing improves resilience and scale at the cost of status, ordering, and reconciliation logic.",
        "When transactional workflow is inconsistent, follow the correlation id through API logs, database rows, queue messages, webhook receipts, cache invalidation, and frontend state.",
        "State flow for transactional workflow: request accepted -> row pending -> worker processes -> status succeeded/failed -> UI subscribes or polls -> audit record stored. Evidence cue: A transactional workflow coordinates multiple state changes so critical business invariants are committed or rolled back correctly.",
        "1) Model states and idempotency 2) Implement transaction or worker boundary 3) Expose user-visible status 4) Reconcile failures with audit data.",
    ),
    "waterfall request chain": K(
        "A waterfall request chain happens when the frontend waits for sequential dependent requests, increasing latency and fragility.",
        "Unclear waterfall request chain causes teams to debug the wrong layer while users see failed saves, stale data, or confusing errors.",
        [
            "waterfall request chain request path",
            "Backend authority",
            "Data and cache consistency",
            "Observability and rollback",
        ],
        "Trace waterfall request chain from browser event to request, controller, service rule, persistence or dependency, response mapping, cache update, and UI feedback.",
        "waterfall request chain is easiest as a thin vertical slice, but distributed ownership needs stronger contracts, tracing, and operational runbooks.",
        "When waterfall request chain fails, isolate browser network, API logs, validation errors, database queries, cache keys, flags, and deployment version.",
        "Full-stack trace for waterfall request chain: click Save -> typed request -> auth and validation -> domain service -> persistence/cache -> mapped response -> UI success or retry state. Evidence cue: A waterfall request chain happens when the frontend waits for sequential dependent requests, increasing latency and fragility.",
        "1) Draw the request path 2) Define authority and data contracts 3) Add contract and E2E smoke checks 4) Instrument logs, metrics, traces, and rollback.",
    ),
    "zero-downtime database migration": K(
        "A zero-downtime database migration changes schema and code in compatible phases so old and new app versions run during rollout.",
        "Weak zero-downtime database migration lets UI status drift from committed backend state, especially around retries, jobs, webhooks, files, or rolling deploys.",
        [
            "zero-downtime database migration state machine",
            "Idempotency or ordering rule",
            "Persistence and async boundary",
            "Reconciliation and audit trail",
        ],
        "Build zero-downtime database migration with explicit states, idempotency keys where retries happen, transactional writes for local invariants, workers for slow tasks, and a response the UI can recover from.",
        "zero-downtime database migration is simpler when synchronous, but asynchronous processing improves resilience and scale at the cost of status, ordering, and reconciliation logic.",
        "When zero-downtime database migration is inconsistent, follow the correlation id through API logs, database rows, queue messages, webhook receipts, cache invalidation, and frontend state.",
        "State flow for zero-downtime database migration: request accepted -> row pending -> worker processes -> status succeeded/failed -> UI subscribes or polls -> audit record stored. Evidence cue: A zero-downtime database migration changes schema and code in compatible phases so old and new app versions run during rollout.",
        "1) Model states and idempotency 2) Implement transaction or worker boundary 3) Expose user-visible status 4) Reconcile failures with audit data.",
    ),
}

