from .lib import K

PM_TOPICS = {
    "Agile values": K(
        "Agile values prioritize individuals and interactions, working software, customer collaboration, and responding to change over heavier process artifacts.",
        "When Agile values becomes ceremony rather than outcome management, teams report activity while value, blockers, and quality risks stay hidden.",
        [
            "Agile values role in Scrum flow",
            "Sprint Goal or product outcome",
            "Ready and done criteria",
            "Inspect-and-adapt feedback",
        ],
        "Use Agile values to clarify goal, order the right work, expose blockers, inspect the increment, and adapt the backlog or team process.",
        "Agile values gives cadence and transparency, but teams should avoid cargo-cult Scrum when flow-based work or urgent interrupts dominate.",
        "If Agile values is ineffective, inspect WIP, carryover, unclear acceptance criteria, unplanned work, dependencies, and whether retrospectives create actions.",
        "Scrum board artifact: Agile values column or note ties each story to Sprint Goal, acceptance criteria, blocker owner, demo status, and carryover reason. Evidence cue: Agile values prioritize individuals and interactions, working software, customer collaboration, and responding to change over heavier process artifacts.",
        "1) Clarify goal and ready criteria 2) Make blockers visible daily 3) Review increment with stakeholders 4) Turn retro learning into one action.",
    ),
    "DORA-style delivery metrics": K(
        "DORA-style delivery metrics measure delivery performance through deployment frequency, lead time for changes, change failure rate, and recovery time.",
        "Misused DORA-style delivery metrics creates false precision or local optimization instead of better delivery decisions.",
        [
            "DORA-style delivery metrics metric definition",
            "Decision the metric supports",
            "Trend over snapshot",
            "Gaming and misuse risk",
        ],
        "Apply DORA-style delivery metrics by defining the measurement, collecting it consistently, reviewing trends with context, and tying actions to bottlenecks or prioritization choices.",
        "DORA-style delivery metrics improves transparency, but it should not be used as an individual scorecard or compared across teams without context.",
        "If DORA-style delivery metrics worsens, inspect WIP, batch size, queues, blocked time, rework, release approvals, and whether the measurement changed.",
        "Metric review: DORA-style delivery metrics trend, target, context note, suspected bottleneck, action owner, due date, and next review. Evidence cue: DORA-style delivery metrics measure delivery performance through deployment frequency, lead time for changes, change failure rate, and recovery time.",
        "1) Define metric and decision 2) Collect consistent trend data 3) Review with blockers and outcomes 4) Change WIP, scope, or process based on evidence.",
    ),
    "Daily Scrum": K(
        "The Daily Scrum is a short Scrum event for developers to inspect progress toward the Sprint Goal and adapt the day plan.",
        "When Daily Scrum becomes ceremony rather than outcome management, teams report activity while value, blockers, and quality risks stay hidden.",
        [
            "Daily Scrum role in Scrum flow",
            "Sprint Goal or product outcome",
            "Ready and done criteria",
            "Inspect-and-adapt feedback",
        ],
        "Use Daily Scrum to clarify goal, order the right work, expose blockers, inspect the increment, and adapt the backlog or team process.",
        "Daily Scrum gives cadence and transparency, but teams should avoid cargo-cult Scrum when flow-based work or urgent interrupts dominate.",
        "If Daily Scrum is ineffective, inspect WIP, carryover, unclear acceptance criteria, unplanned work, dependencies, and whether retrospectives create actions.",
        "Scrum board artifact: Daily Scrum column or note ties each story to Sprint Goal, acceptance criteria, blocker owner, demo status, and carryover reason. Evidence cue: The Daily Scrum is a short Scrum event for developers to inspect progress toward the Sprint Goal and adapt the day plan.",
        "1) Clarify goal and ready criteria 2) Make blockers visible daily 3) Review increment with stakeholders 4) Turn retro learning into one action.",
    ),
    "Definition of Done": K(
        "Definition of Done is the shared quality checklist an increment must satisfy before the team can call work complete.",
        "When Definition of Done becomes ceremony rather than outcome management, teams report activity while value, blockers, and quality risks stay hidden.",
        [
            "Definition of Done role in Scrum flow",
            "Sprint Goal or product outcome",
            "Ready and done criteria",
            "Inspect-and-adapt feedback",
        ],
        "Use Definition of Done to clarify goal, order the right work, expose blockers, inspect the increment, and adapt the backlog or team process.",
        "Definition of Done gives cadence and transparency, but teams should avoid cargo-cult Scrum when flow-based work or urgent interrupts dominate.",
        "If Definition of Done is ineffective, inspect WIP, carryover, unclear acceptance criteria, unplanned work, dependencies, and whether retrospectives create actions.",
        "Scrum board artifact: Definition of Done column or note ties each story to Sprint Goal, acceptance criteria, blocker owner, demo status, and carryover reason. Evidence cue: Definition of Done is the shared quality checklist an increment must satisfy before the team can call work complete.",
        "1) Clarify goal and ready criteria 2) Make blockers visible daily 3) Review increment with stakeholders 4) Turn retro learning into one action.",
    ),
    "Jira workflow": K(
        "A Jira workflow models the states and transitions work items follow from intake to completion.",
        "Unclear Jira workflow causes activity without alignment on why the work exists, who decides, and what outcome counts as success.",
        [
            "Jira workflow objective",
            "Scope and success criteria",
            "Owner and governance",
            "Risk and decision log",
        ],
        "Use Jira workflow to define objective, scope, stakeholders, assumptions, milestones, quality bar, risks, and decision cadence.",
        "Jira workflow should be lightweight for small efforts and more traceable for client, regulated, or cross-team projects.",
        "If Jira workflow feels ambiguous, review the charter, backlog readiness, RAID log, decision log, and whether stakeholders agree on success.",
        "Board columns: To Do \u2192 In Progress \u2192 In Review \u2192 Done; WIP limit 3 In Progress; blocked flag requires comment + owner.",
        "1) Define objective and scope 2) Assign owners and cadence 3) Track risks and decisions 4) Review outcome against acceptance criteria.",
    ),
    "MoSCoW": K(
        "MoSCoW prioritization classifies scope as Must, Should, Could, or Won't for a given timebox.",
        "Misused MoSCoW creates false precision or local optimization instead of better delivery decisions.",
        [
            "MoSCoW metric definition",
            "Decision the metric supports",
            "Trend over snapshot",
            "Gaming and misuse risk",
        ],
        "Apply MoSCoW by defining the measurement, collecting it consistently, reviewing trends with context, and tying actions to bottlenecks or prioritization choices.",
        "MoSCoW improves transparency, but it should not be used as an individual scorecard or compared across teams without context.",
        "If MoSCoW worsens, inspect WIP, batch size, queues, blocked time, rework, release approvals, and whether the measurement changed.",
        "Metric review: MoSCoW trend, target, context note, suspected bottleneck, action owner, due date, and next review. Evidence cue: MoSCoW prioritization classifies scope as Must, Should, Could, or Won't for a given timebox.",
        "1) Define metric and decision 2) Collect consistent trend data 3) Review with blockers and outcomes 4) Change WIP, scope, or process based on evidence.",
    ),
    "PMP": K(
        "PMP refers to PMI's Project Management Professional framework and certification for predictive, agile, and hybrid project practices.",
        "Unclear PMP causes activity without alignment on why the work exists, who decides, and what outcome counts as success.",
        [
            "PMP objective",
            "Scope and success criteria",
            "Owner and governance",
            "Risk and decision log",
        ],
        "Use PMP to define objective, scope, stakeholders, assumptions, milestones, quality bar, risks, and decision cadence.",
        "PMP should be lightweight for small efforts and more traceable for client, regulated, or cross-team projects.",
        "If PMP feels ambiguous, review the charter, backlog readiness, RAID log, decision log, and whether stakeholders agree on success.",
        "Triple constraint talk track: scope/time/cost trade-off options with quality/risk callouts \u2014 not process trivia memorization.",
        "1) Define objective and scope 2) Assign owners and cadence 3) Track risks and decisions 4) Review outcome against acceptance criteria.",
    ),
    "Product Backlog": K(
        "The Product Backlog is the ordered, evolving list of product work managed to maximize value.",
        "When Product Backlog becomes ceremony rather than outcome management, teams report activity while value, blockers, and quality risks stay hidden.",
        [
            "Product Backlog role in Scrum flow",
            "Sprint Goal or product outcome",
            "Ready and done criteria",
            "Inspect-and-adapt feedback",
        ],
        "Use Product Backlog to clarify goal, order the right work, expose blockers, inspect the increment, and adapt the backlog or team process.",
        "Product Backlog gives cadence and transparency, but teams should avoid cargo-cult Scrum when flow-based work or urgent interrupts dominate.",
        "If Product Backlog is ineffective, inspect WIP, carryover, unclear acceptance criteria, unplanned work, dependencies, and whether retrospectives create actions.",
        "Scrum board artifact: Product Backlog column or note ties each story to Sprint Goal, acceptance criteria, blocker owner, demo status, and carryover reason. Evidence cue: The Product Backlog is the ordered, evolving list of product work managed to maximize value.",
        "1) Clarify goal and ready criteria 2) Make blockers visible daily 3) Review increment with stakeholders 4) Turn retro learning into one action.",
    ),
    "Product Owner": K(
        "The Product Owner is accountable in Scrum for maximizing product value through backlog ordering and stakeholder alignment.",
        "When Product Owner becomes ceremony rather than outcome management, teams report activity while value, blockers, and quality risks stay hidden.",
        [
            "Product Owner role in Scrum flow",
            "Sprint Goal or product outcome",
            "Ready and done criteria",
            "Inspect-and-adapt feedback",
        ],
        "Use Product Owner to clarify goal, order the right work, expose blockers, inspect the increment, and adapt the backlog or team process.",
        "Product Owner gives cadence and transparency, but teams should avoid cargo-cult Scrum when flow-based work or urgent interrupts dominate.",
        "If Product Owner is ineffective, inspect WIP, carryover, unclear acceptance criteria, unplanned work, dependencies, and whether retrospectives create actions.",
        "Scrum board artifact: Product Owner column or note ties each story to Sprint Goal, acceptance criteria, blocker owner, demo status, and carryover reason. Evidence cue: The Product Owner is accountable in Scrum for maximizing product value through backlog ordering and stakeholder alignment.",
        "1) Clarify goal and ready criteria 2) Make blockers visible daily 3) Review increment with stakeholders 4) Turn retro learning into one action.",
    ),
    "RAID log": K(
        "A RAID log tracks Risks, Assumptions, Issues, and Dependencies with owners and actions.",
        "Unmanaged RAID log becomes a late surprise that forces rushed scope cuts, missed dates, or production instability.",
        [
            "RAID log owner",
            "Probability and impact",
            "Trigger and response plan",
            "Escalation threshold",
        ],
        "Capture RAID log with description, owner, impact, trigger, mitigation, due date, contingency, and current status; review until closed.",
        "RAID log tracking prevents surprises, but stale registers create false comfort; keep entries few, owned, and decision-oriented.",
        "If RAID log is not improving delivery, check whether owners can act, triggers are measurable, mitigation has dates, and escalation reaches a decision maker.",
        "RAID row: RAID log = payment sandbox approval delayed; impact checkout testing blocked; owner vendor manager; mitigation daily vendor check; escalate Friday. Evidence cue: A RAID log tracks Risks, Assumptions, Issues, and Dependencies with owners and actions.",
        "1) Log owner, impact, trigger, and mitigation 2) Review on delivery cadence 3) Escalate with options before tolerance is exceeded 4) Close with outcome and lesson.",
    ),
    "STAR interview response": K(
        "A STAR interview response structures an example as Situation, Task, Action, and Result.",
        "Unclear STAR interview response causes activity without alignment on why the work exists, who decides, and what outcome counts as success.",
        [
            "STAR interview response objective",
            "Scope and success criteria",
            "Owner and governance",
            "Risk and decision log",
        ],
        "Use STAR interview response to define objective, scope, stakeholders, assumptions, milestones, quality bar, risks, and decision cadence.",
        "STAR interview response should be lightweight for small efforts and more traceable for client, regulated, or cross-team projects.",
        "If STAR interview response feels ambiguous, review the charter, backlog readiness, RAID log, decision log, and whether stakeholders agree on success.",
        "STAR card: Situation (checkout delay) \u2192 Task (recover date) \u2192 Action (cut scope + daily RAID) \u2192 Result (shipped MVP, +0 escaped S1).",
        "1) Define objective and scope 2) Assign owners and cadence 3) Track risks and decisions 4) Review outcome against acceptance criteria.",
    ),
    "Scrum Master": K(
        "The Scrum Master is accountable for Scrum effectiveness by coaching the team, removing impediments, and improving how Scrum is used.",
        "When Scrum Master becomes ceremony rather than outcome management, teams report activity while value, blockers, and quality risks stay hidden.",
        [
            "Scrum Master role in Scrum flow",
            "Sprint Goal or product outcome",
            "Ready and done criteria",
            "Inspect-and-adapt feedback",
        ],
        "Use Scrum Master to clarify goal, order the right work, expose blockers, inspect the increment, and adapt the backlog or team process.",
        "Scrum Master gives cadence and transparency, but teams should avoid cargo-cult Scrum when flow-based work or urgent interrupts dominate.",
        "If Scrum Master is ineffective, inspect WIP, carryover, unclear acceptance criteria, unplanned work, dependencies, and whether retrospectives create actions.",
        "Scrum board artifact: Scrum Master column or note ties each story to Sprint Goal, acceptance criteria, blocker owner, demo status, and carryover reason. Evidence cue: The Scrum Master is accountable for Scrum effectiveness by coaching the team, removing impediments, and improving how Scrum is used.",
        "1) Clarify goal and ready criteria 2) Make blockers visible daily 3) Review increment with stakeholders 4) Turn retro learning into one action.",
    ),
    "Sprint": K(
        "A Sprint is a fixed-length Scrum timebox for creating a usable increment toward a Sprint Goal.",
        "When Sprint becomes ceremony rather than outcome management, teams report activity while value, blockers, and quality risks stay hidden.",
        [
            "Sprint role in Scrum flow",
            "Sprint Goal or product outcome",
            "Ready and done criteria",
            "Inspect-and-adapt feedback",
        ],
        "Use Sprint to clarify goal, order the right work, expose blockers, inspect the increment, and adapt the backlog or team process.",
        "Sprint gives cadence and transparency, but teams should avoid cargo-cult Scrum when flow-based work or urgent interrupts dominate.",
        "If Sprint is ineffective, inspect WIP, carryover, unclear acceptance criteria, unplanned work, dependencies, and whether retrospectives create actions.",
        "Scrum board artifact: Sprint column or note ties each story to Sprint Goal, acceptance criteria, blocker owner, demo status, and carryover reason. Evidence cue: A Sprint is a fixed-length Scrum timebox for creating a usable increment toward a Sprint Goal.",
        "1) Clarify goal and ready criteria 2) Make blockers visible daily 3) Review increment with stakeholders 4) Turn retro learning into one action.",
    ),
    "Sprint Goal": K(
        "A Sprint Goal is the single objective that gives the Sprint coherence and guides tradeoffs.",
        "When Sprint Goal becomes ceremony rather than outcome management, teams report activity while value, blockers, and quality risks stay hidden.",
        [
            "Sprint Goal role in Scrum flow",
            "Sprint Goal or product outcome",
            "Ready and done criteria",
            "Inspect-and-adapt feedback",
        ],
        "Use Sprint Goal to clarify goal, order the right work, expose blockers, inspect the increment, and adapt the backlog or team process.",
        "Sprint Goal gives cadence and transparency, but teams should avoid cargo-cult Scrum when flow-based work or urgent interrupts dominate.",
        "If Sprint Goal is ineffective, inspect WIP, carryover, unclear acceptance criteria, unplanned work, dependencies, and whether retrospectives create actions.",
        "Scrum board artifact: Sprint Goal column or note ties each story to Sprint Goal, acceptance criteria, blocker owner, demo status, and carryover reason. Evidence cue: A Sprint Goal is the single objective that gives the Sprint coherence and guides tradeoffs.",
        "1) Clarify goal and ready criteria 2) Make blockers visible daily 3) Review increment with stakeholders 4) Turn retro learning into one action.",
    ),
    "Sprint Review": K(
        "The Sprint Review is a Scrum event where the team inspects the increment with stakeholders and adapts the Product Backlog.",
        "When Sprint Review becomes ceremony rather than outcome management, teams report activity while value, blockers, and quality risks stay hidden.",
        [
            "Sprint Review role in Scrum flow",
            "Sprint Goal or product outcome",
            "Ready and done criteria",
            "Inspect-and-adapt feedback",
        ],
        "Use Sprint Review to clarify goal, order the right work, expose blockers, inspect the increment, and adapt the backlog or team process.",
        "Sprint Review gives cadence and transparency, but teams should avoid cargo-cult Scrum when flow-based work or urgent interrupts dominate.",
        "If Sprint Review is ineffective, inspect WIP, carryover, unclear acceptance criteria, unplanned work, dependencies, and whether retrospectives create actions.",
        "Scrum board artifact: Sprint Review column or note ties each story to Sprint Goal, acceptance criteria, blocker owner, demo status, and carryover reason. Evidence cue: The Sprint Review is a Scrum event where the team inspects the increment with stakeholders and adapts the Product Backlog.",
        "1) Clarify goal and ready criteria 2) Make blockers visible daily 3) Review increment with stakeholders 4) Turn retro learning into one action.",
    ),
    "WIP limit": K(
        "A WIP limit caps work in progress to expose bottlenecks and improve flow.",
        "Misused WIP limit creates false precision or local optimization instead of better delivery decisions.",
        [
            "WIP limit metric definition",
            "Decision the metric supports",
            "Trend over snapshot",
            "Gaming and misuse risk",
        ],
        "Apply WIP limit by defining the measurement, collecting it consistently, reviewing trends with context, and tying actions to bottlenecks or prioritization choices.",
        "WIP limit improves transparency, but it should not be used as an individual scorecard or compared across teams without context.",
        "If WIP limit worsens, inspect WIP, batch size, queues, blocked time, rework, release approvals, and whether the measurement changed.",
        "Metric review: WIP limit trend, target, context note, suspected bottleneck, action owner, due date, and next review. Evidence cue: A WIP limit caps work in progress to expose bottlenecks and improve flow.",
        "1) Define metric and decision 2) Collect consistent trend data 3) Review with blockers and outcomes 4) Change WIP, scope, or process based on evidence.",
    ),
    "acceptance criteria": K(
        "Acceptance criteria are testable conditions that define when a user story satisfies the intended behavior.",
        "Unclear acceptance criteria causes activity without alignment on why the work exists, who decides, and what outcome counts as success.",
        [
            "acceptance criteria objective",
            "Scope and success criteria",
            "Owner and governance",
            "Risk and decision log",
        ],
        "Use acceptance criteria to define objective, scope, stakeholders, assumptions, milestones, quality bar, risks, and decision cadence.",
        "acceptance criteria should be lightweight for small efforts and more traceable for client, regulated, or cross-team projects.",
        "If acceptance criteria feels ambiguous, review the charter, backlog readiness, RAID log, decision log, and whether stakeholders agree on success.",
        "Story AC: Given saved card; When pay; Then charge tokenized card, show receipt, emit audit event; no raw PAN stored.",
        "1) Define objective and scope 2) Assign owners and cadence 3) Track risks and decisions 4) Review outcome against acceptance criteria.",
    ),
    "budget baseline": K(
        "A budget baseline is the approved cost plan used to compare actual and forecasted project spending.",
        "Poor budget baseline lets scope, date, cost, and quality move independently without an explicit sponsor decision.",
        [
            "budget baseline baseline",
            "Constraint and assumption log",
            "Forecast variance",
            "Approval or tradeoff decision",
        ],
        "Manage budget baseline by decomposing work, identifying constraints, tracking actuals against baseline, forecasting variance, and documenting approved tradeoffs.",
        "budget baseline gives control and predictability, but rigid baselines can fight discovery unless change control is lightweight and transparent.",
        "If budget baseline slips, inspect the critical path, dependency waits, capacity assumptions, estimation range, and whether scope was accepted without a baseline update.",
        "Change note: budget baseline impact from adding SSO is +2 weeks unless reporting export moves out; sponsor decides date move or scope swap by Tuesday. Evidence cue: A budget baseline is the approved cost plan used to compare actual and forecasted project spending.",
        "1) Set baseline and assumptions 2) Track actuals and variance 3) Model options for scope/date/cost 4) Approve and communicate the new baseline.",
    ),
    "burndown": K(
        "A burndown chart shows remaining work over time within a Sprint or release.",
        "When burndown becomes ceremony rather than outcome management, teams report activity while value, blockers, and quality risks stay hidden.",
        [
            "burndown role in Scrum flow",
            "Sprint Goal or product outcome",
            "Ready and done criteria",
            "Inspect-and-adapt feedback",
        ],
        "Use burndown to clarify goal, order the right work, expose blockers, inspect the increment, and adapt the backlog or team process.",
        "burndown gives cadence and transparency, but teams should avoid cargo-cult Scrum when flow-based work or urgent interrupts dominate.",
        "If burndown is ineffective, inspect WIP, carryover, unclear acceptance criteria, unplanned work, dependencies, and whether retrospectives create actions.",
        "Scrum board artifact: burndown column or note ties each story to Sprint Goal, acceptance criteria, blocker owner, demo status, and carryover reason. Evidence cue: A burndown chart shows remaining work over time within a Sprint or release.",
        "1) Clarify goal and ready criteria 2) Make blockers visible daily 3) Review increment with stakeholders 4) Turn retro learning into one action.",
    ),
    "business requirement": K(
        "A business requirement describes the outcome or capability the organization needs, before solution details.",
        "Unclear business requirement causes activity without alignment on why the work exists, who decides, and what outcome counts as success.",
        [
            "business requirement objective",
            "Scope and success criteria",
            "Owner and governance",
            "Risk and decision log",
        ],
        "Use business requirement to define objective, scope, stakeholders, assumptions, milestones, quality bar, risks, and decision cadence.",
        "business requirement should be lightweight for small efforts and more traceable for client, regulated, or cross-team projects.",
        "If business requirement feels ambiguous, review the charter, backlog readiness, RAID log, decision log, and whether stakeholders agree on success.",
        "BRD slice: objective, actors, in/out scope, success metric, constraints, open questions \u2014 linked to backlog epics.",
        "1) Define objective and scope 2) Assign owners and cadence 3) Track risks and decisions 4) Review outcome against acceptance criteria.",
    ),
    "capacity planning": K(
        "Capacity planning estimates available team effort after considering people, calendars, skills, and operational load.",
        "Poor capacity planning lets scope, date, cost, and quality move independently without an explicit sponsor decision.",
        [
            "capacity planning baseline",
            "Constraint and assumption log",
            "Forecast variance",
            "Approval or tradeoff decision",
        ],
        "Manage capacity planning by decomposing work, identifying constraints, tracking actuals against baseline, forecasting variance, and documenting approved tradeoffs.",
        "capacity planning gives control and predictability, but rigid baselines can fight discovery unless change control is lightweight and transparent.",
        "If capacity planning slips, inspect the critical path, dependency waits, capacity assumptions, estimation range, and whether scope was accepted without a baseline update.",
        "Change note: capacity planning impact from adding SSO is +2 weeks unless reporting export moves out; sponsor decides date move or scope swap by Tuesday. Evidence cue: Capacity planning estimates available team effort after considering people, calendars, skills, and operational load.",
        "1) Set baseline and assumptions 2) Track actuals and variance 3) Model options for scope/date/cost 4) Approve and communicate the new baseline.",
    ),
    "change control": K(
        "Change control is the process for evaluating, approving, and communicating scope or baseline changes.",
        "Poor change control lets scope, date, cost, and quality move independently without an explicit sponsor decision.",
        [
            "change control baseline",
            "Constraint and assumption log",
            "Forecast variance",
            "Approval or tradeoff decision",
        ],
        "Manage change control by decomposing work, identifying constraints, tracking actuals against baseline, forecasting variance, and documenting approved tradeoffs.",
        "change control gives control and predictability, but rigid baselines can fight discovery unless change control is lightweight and transparent.",
        "If change control slips, inspect the critical path, dependency waits, capacity assumptions, estimation range, and whether scope was accepted without a baseline update.",
        "Change note: change control impact from adding SSO is +2 weeks unless reporting export moves out; sponsor decides date move or scope swap by Tuesday. Evidence cue: Change control is the process for evaluating, approving, and communicating scope or baseline changes.",
        "1) Set baseline and assumptions 2) Track actuals and variance 3) Model options for scope/date/cost 4) Approve and communicate the new baseline.",
    ),
    "client expectation management": K(
        "Client expectation management aligns promised outcomes, constraints, timing, risks, and communication before surprises erode trust.",
        "Weak client expectation management creates rework because sponsors, clients, vendors, and teams operate from different assumptions.",
        [
            "client expectation management audience map",
            "Decision rights and RACI",
            "Communication cadence",
            "Escalation path",
        ],
        "Run client expectation management by mapping influence and needs, choosing communication channels, recording decisions, confirming owners, and closing loops after meetings.",
        "client expectation management builds trust through transparency, but excessive updates become noise; tune detail to audience, risk, and decision needs.",
        "If client expectation management breaks down, separate facts from preferences, restate constraints, identify the decision owner, and offer options with impact.",
        "Status note: client expectation management audience gets RAG, milestone forecast, blocker, owner, RAID change, decision needed, and next communication date. Evidence cue: Client expectation management aligns promised outcomes, constraints, timing, risks, and communication before surprises erode trust.",
        "1) Map stakeholder needs 2) Publish concise status 3) Record decisions and owners 4) Escalate unresolved tradeoffs.",
    ),
    "conflict resolution": K(
        "Conflict resolution identifies the real disagreement, separates facts from positions, and guides stakeholders toward an agreed decision.",
        "Weak conflict resolution creates rework because sponsors, clients, vendors, and teams operate from different assumptions.",
        [
            "conflict resolution audience map",
            "Decision rights and RACI",
            "Communication cadence",
            "Escalation path",
        ],
        "Run conflict resolution by mapping influence and needs, choosing communication channels, recording decisions, confirming owners, and closing loops after meetings.",
        "conflict resolution builds trust through transparency, but excessive updates become noise; tune detail to audience, risk, and decision needs.",
        "If conflict resolution breaks down, separate facts from preferences, restate constraints, identify the decision owner, and offer options with impact.",
        "Status note: conflict resolution audience gets RAG, milestone forecast, blocker, owner, RAID change, decision needed, and next communication date. Evidence cue: Conflict resolution identifies the real disagreement, separates facts from positions, and guides stakeholders toward an agreed decision.",
        "1) Map stakeholder needs 2) Publish concise status 3) Record decisions and owners 4) Escalate unresolved tradeoffs.",
    ),
    "critical path": K(
        "The critical path is the sequence of dependent tasks that determines the earliest possible project finish date.",
        "Poor critical path lets scope, date, cost, and quality move independently without an explicit sponsor decision.",
        [
            "critical path baseline",
            "Constraint and assumption log",
            "Forecast variance",
            "Approval or tradeoff decision",
        ],
        "Manage critical path by decomposing work, identifying constraints, tracking actuals against baseline, forecasting variance, and documenting approved tradeoffs.",
        "critical path gives control and predictability, but rigid baselines can fight discovery unless change control is lightweight and transparent.",
        "If critical path slips, inspect the critical path, dependency waits, capacity assumptions, estimation range, and whether scope was accepted without a baseline update.",
        "Change note: critical path impact from adding SSO is +2 weeks unless reporting export moves out; sponsor decides date move or scope swap by Tuesday. Evidence cue: The critical path is the sequence of dependent tasks that determines the earliest possible project finish date.",
        "1) Set baseline and assumptions 2) Track actuals and variance 3) Model options for scope/date/cost 4) Approve and communicate the new baseline.",
    ),
    "cycle time": K(
        "Cycle time measures how long work takes from active start to completion.",
        "Misused cycle time creates false precision or local optimization instead of better delivery decisions.",
        [
            "cycle time metric definition",
            "Decision the metric supports",
            "Trend over snapshot",
            "Gaming and misuse risk",
        ],
        "Apply cycle time by defining the measurement, collecting it consistently, reviewing trends with context, and tying actions to bottlenecks or prioritization choices.",
        "cycle time improves transparency, but it should not be used as an individual scorecard or compared across teams without context.",
        "If cycle time worsens, inspect WIP, batch size, queues, blocked time, rework, release approvals, and whether the measurement changed.",
        "Metric review: cycle time trend, target, context note, suspected bottleneck, action owner, due date, and next review. Evidence cue: Cycle time measures how long work takes from active start to completion.",
        "1) Define metric and decision 2) Collect consistent trend data 3) Review with blockers and outcomes 4) Change WIP, scope, or process based on evidence.",
    ),
    "dependency": K(
        "A dependency is work, a decision, resource, or external party that another item needs before it can finish.",
        "Unmanaged dependency becomes a late surprise that forces rushed scope cuts, missed dates, or production instability.",
        [
            "dependency owner",
            "Probability and impact",
            "Trigger and response plan",
            "Escalation threshold",
        ],
        "Capture dependency with description, owner, impact, trigger, mitigation, due date, contingency, and current status; review until closed.",
        "dependency tracking prevents surprises, but stale registers create false comfort; keep entries few, owned, and decision-oriented.",
        "If dependency is not improving delivery, check whether owners can act, triggers are measurable, mitigation has dates, and escalation reaches a decision maker.",
        "RAID row: dependency = payment sandbox approval delayed; impact checkout testing blocked; owner vendor manager; mitigation daily vendor check; escalate Friday. Evidence cue: A dependency is work, a decision, resource, or external party that another item needs before it can finish.",
        "1) Log owner, impact, trigger, and mitigation 2) Review on delivery cadence 3) Escalate with options before tolerance is exceeded 4) Close with outcome and lesson.",
    ),
    "distributed team management": K(
        "Distributed team management coordinates people across locations, time zones, and communication norms.",
        "Weak distributed team management creates rework because sponsors, clients, vendors, and teams operate from different assumptions.",
        [
            "distributed team management audience map",
            "Decision rights and RACI",
            "Communication cadence",
            "Escalation path",
        ],
        "Run distributed team management by mapping influence and needs, choosing communication channels, recording decisions, confirming owners, and closing loops after meetings.",
        "distributed team management builds trust through transparency, but excessive updates become noise; tune detail to audience, risk, and decision needs.",
        "If distributed team management breaks down, separate facts from preferences, restate constraints, identify the decision owner, and offer options with impact.",
        "Status note: distributed team management audience gets RAG, milestone forecast, blocker, owner, RAID change, decision needed, and next communication date. Evidence cue: Distributed team management coordinates people across locations, time zones, and communication norms.",
        "1) Map stakeholder needs 2) Publish concise status 3) Record decisions and owners 4) Escalate unresolved tradeoffs.",
    ),
    "earned value concepts": K(
        "Earned value concepts compare planned value, earned value, and actual cost to assess project cost and schedule performance.",
        "Poor earned value concepts lets scope, date, cost, and quality move independently without an explicit sponsor decision.",
        [
            "earned value concepts baseline",
            "Constraint and assumption log",
            "Forecast variance",
            "Approval or tradeoff decision",
        ],
        "Manage earned value concepts by decomposing work, identifying constraints, tracking actuals against baseline, forecasting variance, and documenting approved tradeoffs.",
        "earned value concepts gives control and predictability, but rigid baselines can fight discovery unless change control is lightweight and transparent.",
        "If earned value concepts slips, inspect the critical path, dependency waits, capacity assumptions, estimation range, and whether scope was accepted without a baseline update.",
        "Change note: earned value concepts impact from adding SSO is +2 weeks unless reporting export moves out; sponsor decides date move or scope swap by Tuesday. Evidence cue: Earned value concepts compare planned value, earned value, and actual cost to assess project cost and schedule performance.",
        "1) Set baseline and assumptions 2) Track actuals and variance 3) Model options for scope/date/cost 4) Approve and communicate the new baseline.",
    ),
    "escalation": K(
        "Escalation raises a blocked risk, issue, or decision to the level that can resolve it.",
        "Unmanaged escalation becomes a late surprise that forces rushed scope cuts, missed dates, or production instability.",
        [
            "escalation owner",
            "Probability and impact",
            "Trigger and response plan",
            "Escalation threshold",
        ],
        "Capture escalation with description, owner, impact, trigger, mitigation, due date, contingency, and current status; review until closed.",
        "escalation tracking prevents surprises, but stale registers create false comfort; keep entries few, owned, and decision-oriented.",
        "If escalation is not improving delivery, check whether owners can act, triggers are measurable, mitigation has dates, and escalation reaches a decision maker.",
        "RAID row: escalation = payment sandbox approval delayed; impact checkout testing blocked; owner vendor manager; mitigation daily vendor check; escalate Friday. Evidence cue: Escalation raises a blocked risk, issue, or decision to the level that can resolve it.",
        "1) Log owner, impact, trigger, and mitigation 2) Review on delivery cadence 3) Escalate with options before tolerance is exceeded 4) Close with outcome and lesson.",
    ),
    "expectation management": K(
        "Expectation management keeps stakeholders aligned on what will happen, by when, under which assumptions, and with what risks.",
        "Weak expectation management creates rework because sponsors, clients, vendors, and teams operate from different assumptions.",
        [
            "expectation management audience map",
            "Decision rights and RACI",
            "Communication cadence",
            "Escalation path",
        ],
        "Run expectation management by mapping influence and needs, choosing communication channels, recording decisions, confirming owners, and closing loops after meetings.",
        "expectation management builds trust through transparency, but excessive updates become noise; tune detail to audience, risk, and decision needs.",
        "If expectation management breaks down, separate facts from preferences, restate constraints, identify the decision owner, and offer options with impact.",
        "Status note: expectation management audience gets RAG, milestone forecast, blocker, owner, RAID change, decision needed, and next communication date. Evidence cue: Expectation management keeps stakeholders aligned on what will happen, by when, under which assumptions, and with what risks.",
        "1) Map stakeholder needs 2) Publish concise status 3) Record decisions and owners 4) Escalate unresolved tradeoffs.",
    ),
    "incident management": K(
        "Incident management coordinates response, communication, mitigation, and learning when production service is degraded.",
        "Unmanaged incident management becomes a late surprise that forces rushed scope cuts, missed dates, or production instability.",
        [
            "incident management owner",
            "Probability and impact",
            "Trigger and response plan",
            "Escalation threshold",
        ],
        "Capture incident management with description, owner, impact, trigger, mitigation, due date, contingency, and current status; review until closed.",
        "incident management tracking prevents surprises, but stale registers create false comfort; keep entries few, owned, and decision-oriented.",
        "If incident management is not improving delivery, check whether owners can act, triggers are measurable, mitigation has dates, and escalation reaches a decision maker.",
        "RAID row: incident management = payment sandbox approval delayed; impact checkout testing blocked; owner vendor manager; mitigation daily vendor check; escalate Friday. Evidence cue: Incident management coordinates response, communication, mitigation, and learning when production service is degraded.",
        "1) Log owner, impact, trigger, and mitigation 2) Review on delivery cadence 3) Escalate with options before tolerance is exceeded 4) Close with outcome and lesson.",
    ),
    "lead time": K(
        "Lead time measures elapsed time from request or commitment to delivery.",
        "Misused lead time creates false precision or local optimization instead of better delivery decisions.",
        [
            "lead time metric definition",
            "Decision the metric supports",
            "Trend over snapshot",
            "Gaming and misuse risk",
        ],
        "Apply lead time by defining the measurement, collecting it consistently, reviewing trends with context, and tying actions to bottlenecks or prioritization choices.",
        "lead time improves transparency, but it should not be used as an individual scorecard or compared across teams without context.",
        "If lead time worsens, inspect WIP, batch size, queues, blocked time, rework, release approvals, and whether the measurement changed.",
        "Metric review: lead time trend, target, context note, suspected bottleneck, action owner, due date, and next review. Evidence cue: Lead time measures elapsed time from request or commitment to delivery.",
        "1) Define metric and decision 2) Collect consistent trend data 3) Review with blockers and outcomes 4) Change WIP, scope, or process based on evidence.",
    ),
    "milestone": K(
        "A milestone is a significant checkpoint or decision point in a project schedule.",
        "Poor milestone lets scope, date, cost, and quality move independently without an explicit sponsor decision.",
        [
            "milestone baseline",
            "Constraint and assumption log",
            "Forecast variance",
            "Approval or tradeoff decision",
        ],
        "Manage milestone by decomposing work, identifying constraints, tracking actuals against baseline, forecasting variance, and documenting approved tradeoffs.",
        "milestone gives control and predictability, but rigid baselines can fight discovery unless change control is lightweight and transparent.",
        "If milestone slips, inspect the critical path, dependency waits, capacity assumptions, estimation range, and whether scope was accepted without a baseline update.",
        "Change note: milestone impact from adding SSO is +2 weeks unless reporting export moves out; sponsor decides date move or scope swap by Tuesday. Evidence cue: A milestone is a significant checkpoint or decision point in a project schedule.",
        "1) Set baseline and assumptions 2) Track actuals and variance 3) Model options for scope/date/cost 4) Approve and communicate the new baseline.",
    ),
    "mitigation": K(
        "Mitigation is a planned action that reduces the probability or impact of a risk before it happens.",
        "Unmanaged mitigation becomes a late surprise that forces rushed scope cuts, missed dates, or production instability.",
        [
            "mitigation owner",
            "Probability and impact",
            "Trigger and response plan",
            "Escalation threshold",
        ],
        "Capture mitigation with description, owner, impact, trigger, mitigation, due date, contingency, and current status; review until closed.",
        "mitigation tracking prevents surprises, but stale registers create false comfort; keep entries few, owned, and decision-oriented.",
        "If mitigation is not improving delivery, check whether owners can act, triggers are measurable, mitigation has dates, and escalation reaches a decision maker.",
        "RAID row: mitigation = payment sandbox approval delayed; impact checkout testing blocked; owner vendor manager; mitigation daily vendor check; escalate Friday. Evidence cue: Mitigation is a planned action that reduces the probability or impact of a risk before it happens.",
        "1) Log owner, impact, trigger, and mitigation 2) Review on delivery cadence 3) Escalate with options before tolerance is exceeded 4) Close with outcome and lesson.",
    ),
    "multi-team dependency management": K(
        "Multi-team dependency management coordinates sequencing, ownership, and integration points across teams.",
        "Unmanaged multi-team dependency management becomes a late surprise that forces rushed scope cuts, missed dates, or production instability.",
        [
            "multi-team dependency management owner",
            "Probability and impact",
            "Trigger and response plan",
            "Escalation threshold",
        ],
        "Capture multi-team dependency management with description, owner, impact, trigger, mitigation, due date, contingency, and current status; review until closed.",
        "multi-team dependency management tracking prevents surprises, but stale registers create false comfort; keep entries few, owned, and decision-oriented.",
        "If multi-team dependency management is not improving delivery, check whether owners can act, triggers are measurable, mitigation has dates, and escalation reaches a decision maker.",
        "RAID row: multi-team dependency management = payment sandbox approval delayed; impact checkout testing blocked; owner vendor manager; mitigation daily vendor check; escalate Friday. Evidence cue: Multi-team dependency management coordinates sequencing, ownership, and integration points across teams.",
        "1) Log owner, impact, trigger, and mitigation 2) Review on delivery cadence 3) Escalate with options before tolerance is exceeded 4) Close with outcome and lesson.",
    ),
    "project": K(
        "A project is temporary work undertaken to create a unique product, service, or result.",
        "Unclear project causes activity without alignment on why the work exists, who decides, and what outcome counts as success.",
        [
            "project objective",
            "Scope and success criteria",
            "Owner and governance",
            "Risk and decision log",
        ],
        "Use project to define objective, scope, stakeholders, assumptions, milestones, quality bar, risks, and decision cadence.",
        "project should be lightweight for small efforts and more traceable for client, regulated, or cross-team projects.",
        "If project feels ambiguous, review the charter, backlog readiness, RAID log, decision log, and whether stakeholders agree on success.",
        "Charter blurb: deliver billing v2 by Nov 30; MVP = invoices + card pay; out = multi-currency; sponsor = CFO; risk = PSP approval.",
        "1) Define objective and scope 2) Assign owners and cadence 3) Track risks and decisions 4) Review outcome against acceptance criteria.",
    ),
    "project charter": K(
        "A project charter authorizes the project and records objectives, scope, stakeholders, assumptions, and success criteria.",
        "Unclear project charter causes activity without alignment on why the work exists, who decides, and what outcome counts as success.",
        [
            "project charter objective",
            "Scope and success criteria",
            "Owner and governance",
            "Risk and decision log",
        ],
        "Use project charter to define objective, scope, stakeholders, assumptions, milestones, quality bar, risks, and decision cadence.",
        "project charter should be lightweight for small efforts and more traceable for client, regulated, or cross-team projects.",
        "If project charter feels ambiguous, review the charter, backlog readiness, RAID log, decision log, and whether stakeholders agree on success.",
        "Charter fields: purpose, success criteria, scope in/out, milestones, budget band, sponsor, core team, major risks.",
        "1) Define objective and scope 2) Assign owners and cadence 3) Track risks and decisions 4) Review outcome against acceptance criteria.",
    ),
    "project initiation": K(
        "Project initiation clarifies why the work should start, who sponsors it, and what outcome justifies investment.",
        "Unclear project initiation causes activity without alignment on why the work exists, who decides, and what outcome counts as success.",
        [
            "project initiation objective",
            "Scope and success criteria",
            "Owner and governance",
            "Risk and decision log",
        ],
        "Use project initiation to define objective, scope, stakeholders, assumptions, milestones, quality bar, risks, and decision cadence.",
        "project initiation should be lightweight for small efforts and more traceable for client, regulated, or cross-team projects.",
        "If project initiation feels ambiguous, review the charter, backlog readiness, RAID log, decision log, and whether stakeholders agree on success.",
        "Initiation checklist: charter approved, stakeholders mapped, kickoff held, RAID started, environments requested.",
        "1) Define objective and scope 2) Assign owners and cadence 3) Track risks and decisions 4) Review outcome against acceptance criteria.",
    ),
    "project management": K(
        "Project management applies planning, coordination, risk control, and stakeholder communication to deliver outcomes.",
        "Unclear project management causes activity without alignment on why the work exists, who decides, and what outcome counts as success.",
        [
            "project management objective",
            "Scope and success criteria",
            "Owner and governance",
            "Risk and decision log",
        ],
        "Use project management to define objective, scope, stakeholders, assumptions, milestones, quality bar, risks, and decision cadence.",
        "project management should be lightweight for small efforts and more traceable for client, regulated, or cross-team projects.",
        "If project management feels ambiguous, review the charter, backlog readiness, RAID log, decision log, and whether stakeholders agree on success.",
        "Weekly cadence: status RAG, RAID review, dependency sync, decision log \u2014 artifacts over heroics.",
        "1) Define objective and scope 2) Assign owners and cadence 3) Track risks and decisions 4) Review outcome against acceptance criteria.",
    ),
    "project status report": K(
        "A project status report summarizes progress, forecast, risks, blockers, decisions, and next steps for stakeholders.",
        "Weak project status report creates rework because sponsors, clients, vendors, and teams operate from different assumptions.",
        [
            "project status report audience map",
            "Decision rights and RACI",
            "Communication cadence",
            "Escalation path",
        ],
        "Run project status report by mapping influence and needs, choosing communication channels, recording decisions, confirming owners, and closing loops after meetings.",
        "project status report builds trust through transparency, but excessive updates become noise; tune detail to audience, risk, and decision needs.",
        "If project status report breaks down, separate facts from preferences, restate constraints, identify the decision owner, and offer options with impact.",
        "Status note: project status report audience gets RAG, milestone forecast, blocker, owner, RAID change, decision needed, and next communication date. Evidence cue: A project status report summarizes progress, forecast, risks, blockers, decisions, and next steps for stakeholders.",
        "1) Map stakeholder needs 2) Publish concise status 3) Record decisions and owners 4) Escalate unresolved tradeoffs.",
    ),
    "quality assurance": K(
        "Quality assurance defines preventive practices that help teams build quality into the delivery process.",
        "Unclear quality assurance causes activity without alignment on why the work exists, who decides, and what outcome counts as success.",
        [
            "quality assurance objective",
            "Scope and success criteria",
            "Owner and governance",
            "Risk and decision log",
        ],
        "Use quality assurance to define objective, scope, stakeholders, assumptions, milestones, quality bar, risks, and decision cadence.",
        "quality assurance should be lightweight for small efforts and more traceable for client, regulated, or cross-team projects.",
        "If quality assurance feels ambiguous, review the charter, backlog readiness, RAID log, decision log, and whether stakeholders agree on success.",
        "DoD includes: AC met, tests updated, a11y smoke, monitoring/alert owner, rollback note.",
        "1) Define objective and scope 2) Assign owners and cadence 3) Track risks and decisions 4) Review outcome against acceptance criteria.",
    ),
    "quality gate": K(
        "A quality gate is a go/no-go checkpoint based on tests, reviews, criteria, or approvals.",
        "Unclear quality gate causes activity without alignment on why the work exists, who decides, and what outcome counts as success.",
        [
            "quality gate objective",
            "Scope and success criteria",
            "Owner and governance",
            "Risk and decision log",
        ],
        "Use quality gate to define objective, scope, stakeholders, assumptions, milestones, quality bar, risks, and decision cadence.",
        "quality gate should be lightweight for small efforts and more traceable for client, regulated, or cross-team projects.",
        "If quality gate feels ambiguous, review the charter, backlog readiness, RAID log, decision log, and whether stakeholders agree on success.",
        "Release gate: smoke green, no open S1, perf p95 budget OK, security checklist signed, residual risk accepted by sponsor.",
        "1) Define objective and scope 2) Assign owners and cadence 3) Track risks and decisions 4) Review outcome against acceptance criteria.",
    ),
    "release plan": K(
        "A release plan sequences scope, dates, environments, dependencies, communications, and rollback readiness for launch.",
        "Poor release plan lets scope, date, cost, and quality move independently without an explicit sponsor decision.",
        [
            "release plan baseline",
            "Constraint and assumption log",
            "Forecast variance",
            "Approval or tradeoff decision",
        ],
        "Manage release plan by decomposing work, identifying constraints, tracking actuals against baseline, forecasting variance, and documenting approved tradeoffs.",
        "release plan gives control and predictability, but rigid baselines can fight discovery unless change control is lightweight and transparent.",
        "If release plan slips, inspect the critical path, dependency waits, capacity assumptions, estimation range, and whether scope was accepted without a baseline update.",
        "Change note: release plan impact from adding SSO is +2 weeks unless reporting export moves out; sponsor decides date move or scope swap by Tuesday. Evidence cue: A release plan sequences scope, dates, environments, dependencies, communications, and rollback readiness for launch.",
        "1) Set baseline and assumptions 2) Track actuals and variance 3) Model options for scope/date/cost 4) Approve and communicate the new baseline.",
    ),
    "resource leveling": K(
        "Resource leveling adjusts schedule or scope to resolve over-allocation of people or equipment.",
        "Poor resource leveling lets scope, date, cost, and quality move independently without an explicit sponsor decision.",
        [
            "resource leveling baseline",
            "Constraint and assumption log",
            "Forecast variance",
            "Approval or tradeoff decision",
        ],
        "Manage resource leveling by decomposing work, identifying constraints, tracking actuals against baseline, forecasting variance, and documenting approved tradeoffs.",
        "resource leveling gives control and predictability, but rigid baselines can fight discovery unless change control is lightweight and transparent.",
        "If resource leveling slips, inspect the critical path, dependency waits, capacity assumptions, estimation range, and whether scope was accepted without a baseline update.",
        "Change note: resource leveling impact from adding SSO is +2 weeks unless reporting export moves out; sponsor decides date move or scope swap by Tuesday. Evidence cue: Resource leveling adjusts schedule or scope to resolve over-allocation of people or equipment.",
        "1) Set baseline and assumptions 2) Track actuals and variance 3) Model options for scope/date/cost 4) Approve and communicate the new baseline.",
    ),
    "risk probability/impact": K(
        "Risk probability/impact estimates how likely a risk is and how severe its effect would be.",
        "Unmanaged risk probability/impact becomes a late surprise that forces rushed scope cuts, missed dates, or production instability.",
        [
            "risk probability/impact owner",
            "Probability and impact",
            "Trigger and response plan",
            "Escalation threshold",
        ],
        "Capture risk probability/impact with description, owner, impact, trigger, mitigation, due date, contingency, and current status; review until closed.",
        "risk probability/impact tracking prevents surprises, but stale registers create false comfort; keep entries few, owned, and decision-oriented.",
        "If risk probability/impact is not improving delivery, check whether owners can act, triggers are measurable, mitigation has dates, and escalation reaches a decision maker.",
        "RAID row: risk probability/impact = payment sandbox approval delayed; impact checkout testing blocked; owner vendor manager; mitigation daily vendor check; escalate Friday. Evidence cue: Risk probability/impact estimates how likely a risk is and how severe its effect would be.",
        "1) Log owner, impact, trigger, and mitigation 2) Review on delivery cadence 3) Escalate with options before tolerance is exceeded 4) Close with outcome and lesson.",
    ),
    "risk register": K(
        "A risk register records identified risks with probability, impact, owner, response, trigger, and status.",
        "Unmanaged risk register becomes a late surprise that forces rushed scope cuts, missed dates, or production instability.",
        [
            "risk register owner",
            "Probability and impact",
            "Trigger and response plan",
            "Escalation threshold",
        ],
        "Capture risk register with description, owner, impact, trigger, mitigation, due date, contingency, and current status; review until closed.",
        "risk register tracking prevents surprises, but stale registers create false comfort; keep entries few, owned, and decision-oriented.",
        "If risk register is not improving delivery, check whether owners can act, triggers are measurable, mitigation has dates, and escalation reaches a decision maker.",
        "RAID row: risk register = payment sandbox approval delayed; impact checkout testing blocked; owner vendor manager; mitigation daily vendor check; escalate Friday. Evidence cue: A risk register records identified risks with probability, impact, owner, response, trigger, and status.",
        "1) Log owner, impact, trigger, and mitigation 2) Review on delivery cadence 3) Escalate with options before tolerance is exceeded 4) Close with outcome and lesson.",
    ),
    "scope baseline": K(
        "A scope baseline is the approved definition of deliverables and boundaries used to control change.",
        "Poor scope baseline lets scope, date, cost, and quality move independently without an explicit sponsor decision.",
        [
            "scope baseline baseline",
            "Constraint and assumption log",
            "Forecast variance",
            "Approval or tradeoff decision",
        ],
        "Manage scope baseline by decomposing work, identifying constraints, tracking actuals against baseline, forecasting variance, and documenting approved tradeoffs.",
        "scope baseline gives control and predictability, but rigid baselines can fight discovery unless change control is lightweight and transparent.",
        "If scope baseline slips, inspect the critical path, dependency waits, capacity assumptions, estimation range, and whether scope was accepted without a baseline update.",
        "Change note: scope baseline impact from adding SSO is +2 weeks unless reporting export moves out; sponsor decides date move or scope swap by Tuesday. Evidence cue: A scope baseline is the approved definition of deliverables and boundaries used to control change.",
        "1) Set baseline and assumptions 2) Track actuals and variance 3) Model options for scope/date/cost 4) Approve and communicate the new baseline.",
    ),
    "scope creep": K(
        "Scope creep is uncontrolled expansion of work without matching changes to time, budget, or tradeoffs.",
        "Poor scope creep lets scope, date, cost, and quality move independently without an explicit sponsor decision.",
        [
            "scope creep baseline",
            "Constraint and assumption log",
            "Forecast variance",
            "Approval or tradeoff decision",
        ],
        "Manage scope creep by decomposing work, identifying constraints, tracking actuals against baseline, forecasting variance, and documenting approved tradeoffs.",
        "scope creep gives control and predictability, but rigid baselines can fight discovery unless change control is lightweight and transparent.",
        "If scope creep slips, inspect the critical path, dependency waits, capacity assumptions, estimation range, and whether scope was accepted without a baseline update.",
        "Change note: scope creep impact from adding SSO is +2 weeks unless reporting export moves out; sponsor decides date move or scope swap by Tuesday. Evidence cue: Scope creep is uncontrolled expansion of work without matching changes to time, budget, or tradeoffs.",
        "1) Set baseline and assumptions 2) Track actuals and variance 3) Model options for scope/date/cost 4) Approve and communicate the new baseline.",
    ),
    "servant leadership": K(
        "Servant leadership focuses leaders on enabling the team through clarity, trust, coaching, and impediment removal.",
        "Unclear servant leadership causes activity without alignment on why the work exists, who decides, and what outcome counts as success.",
        [
            "servant leadership objective",
            "Scope and success criteria",
            "Owner and governance",
            "Risk and decision log",
        ],
        "Use servant leadership to define objective, scope, stakeholders, assumptions, milestones, quality bar, risks, and decision cadence.",
        "servant leadership should be lightweight for small efforts and more traceable for client, regulated, or cross-team projects.",
        "If servant leadership feels ambiguous, review the charter, backlog readiness, RAID log, decision log, and whether stakeholders agree on success.",
        "Standup facilitation: remove blocker for engineer X same day; protect focus time; surface risk without blame.",
        "1) Define objective and scope 2) Assign owners and cadence 3) Track risks and decisions 4) Review outcome against acceptance criteria.",
    ),
    "stakeholder mapping": K(
        "Stakeholder mapping identifies people or groups by influence, interest, needs, and communication approach.",
        "Weak stakeholder mapping creates rework because sponsors, clients, vendors, and teams operate from different assumptions.",
        [
            "stakeholder mapping audience map",
            "Decision rights and RACI",
            "Communication cadence",
            "Escalation path",
        ],
        "Run stakeholder mapping by mapping influence and needs, choosing communication channels, recording decisions, confirming owners, and closing loops after meetings.",
        "stakeholder mapping builds trust through transparency, but excessive updates become noise; tune detail to audience, risk, and decision needs.",
        "If stakeholder mapping breaks down, separate facts from preferences, restate constraints, identify the decision owner, and offer options with impact.",
        "Status note: stakeholder mapping audience gets RAG, milestone forecast, blocker, owner, RAID change, decision needed, and next communication date. Evidence cue: Stakeholder mapping identifies people or groups by influence, interest, needs, and communication approach.",
        "1) Map stakeholder needs 2) Publish concise status 3) Record decisions and owners 4) Escalate unresolved tradeoffs.",
    ),
    "steering committee": K(
        "A steering committee is a governance group that provides direction, resolves escalations, and approves major tradeoffs.",
        "Weak steering committee creates rework because sponsors, clients, vendors, and teams operate from different assumptions.",
        [
            "steering committee audience map",
            "Decision rights and RACI",
            "Communication cadence",
            "Escalation path",
        ],
        "Run steering committee by mapping influence and needs, choosing communication channels, recording decisions, confirming owners, and closing loops after meetings.",
        "steering committee builds trust through transparency, but excessive updates become noise; tune detail to audience, risk, and decision needs.",
        "If steering committee breaks down, separate facts from preferences, restate constraints, identify the decision owner, and offer options with impact.",
        "Status note: steering committee audience gets RAG, milestone forecast, blocker, owner, RAID change, decision needed, and next communication date. Evidence cue: A steering committee is a governance group that provides direction, resolves escalations, and approves major tradeoffs.",
        "1) Map stakeholder needs 2) Publish concise status 3) Record decisions and owners 4) Escalate unresolved tradeoffs.",
    ),
    "story points": K(
        "Story points are a relative estimate of effort, complexity, and uncertainty for backlog items, used for team capacity planning rather than productivity comparison.",
        "When story points are treated as hours or individual targets, teams inflate estimates and lose the planning signal.",
        [
            "Relative sizing",
            "Complexity and uncertainty",
            "Team-local calibration",
            "Capacity planning not productivity scoring",
        ],
        "Estimate by comparing backlog items to known reference stories, discussing complexity and uncertainty, and using recent team velocity only for team-level forecasting.",
        "Story points are fast for relative planning, but they hide calendar constraints and should be paired with capacity, dependencies, and risk.",
        "If point estimates become political, stop cross-team comparisons, recalibrate with examples, and inspect whether stories are too large or acceptance criteria are unclear.",
        "Planning poker calibration: text-only copy change = 1, add saved payment method = 5, new fraud-provider integration = 13 because dependency and uncertainty dominate. Evidence cue: Story points are a relative estimate of effort, complexity, and uncertainty for backlog items, used for team capacity planning rather than productivity comparison.",
        "1) Agree reference stories 2) Estimate as a team 3) Forecast with recent velocity and capacity 4) Review misses in retro.",
    ),
    "technical debt": K(
        "Technical debt is the future cost of shortcuts in code, architecture, tests, or operations that slow change or increase risk.",
        "Unclear technical debt causes activity without alignment on why the work exists, who decides, and what outcome counts as success.",
        [
            "technical debt objective",
            "Scope and success criteria",
            "Owner and governance",
            "Risk and decision log",
        ],
        "Use technical debt to define objective, scope, stakeholders, assumptions, milestones, quality bar, risks, and decision cadence.",
        "technical debt should be lightweight for small efforts and more traceable for client, regulated, or cross-team projects.",
        "If technical debt feels ambiguous, review the charter, backlog readiness, RAID log, decision log, and whether stakeholders agree on success.",
        "Debt ticket: \"Remove dual pricing tables\"; cost now 2d / cost later 2w each release; schedule 20% capacity next sprint.",
        "1) Define objective and scope 2) Assign owners and cadence 3) Track risks and decisions 4) Review outcome against acceptance criteria.",
    ),
    "three-point estimation": K(
        "Three-point estimation uses optimistic, most likely, and pessimistic estimates to express uncertainty.",
        "Misused three-point estimation creates false precision or local optimization instead of better delivery decisions.",
        [
            "three-point estimation metric definition",
            "Decision the metric supports",
            "Trend over snapshot",
            "Gaming and misuse risk",
        ],
        "Apply three-point estimation by defining the measurement, collecting it consistently, reviewing trends with context, and tying actions to bottlenecks or prioritization choices.",
        "three-point estimation improves transparency, but it should not be used as an individual scorecard or compared across teams without context.",
        "If three-point estimation worsens, inspect WIP, batch size, queues, blocked time, rework, release approvals, and whether the measurement changed.",
        "Metric review: three-point estimation trend, target, context note, suspected bottleneck, action owner, due date, and next review. Evidence cue: Three-point estimation uses optimistic, most likely, and pessimistic estimates to express uncertainty.",
        "1) Define metric and decision 2) Collect consistent trend data 3) Review with blockers and outcomes 4) Change WIP, scope, or process based on evidence.",
    ),
    "throughput": K(
        "Throughput measures how many work items a team completes in a period.",
        "Misused throughput creates false precision or local optimization instead of better delivery decisions.",
        [
            "throughput metric definition",
            "Decision the metric supports",
            "Trend over snapshot",
            "Gaming and misuse risk",
        ],
        "Apply throughput by defining the measurement, collecting it consistently, reviewing trends with context, and tying actions to bottlenecks or prioritization choices.",
        "throughput improves transparency, but it should not be used as an individual scorecard or compared across teams without context.",
        "If throughput worsens, inspect WIP, batch size, queues, blocked time, rework, release approvals, and whether the measurement changed.",
        "Metric review: throughput trend, target, context note, suspected bottleneck, action owner, due date, and next review. Evidence cue: Throughput measures how many work items a team completes in a period.",
        "1) Define metric and decision 2) Collect consistent trend data 3) Review with blockers and outcomes 4) Change WIP, scope, or process based on evidence.",
    ),
    "value vs effort": K(
        "Value vs effort prioritization compares expected benefit against delivery cost to choose work deliberately.",
        "Misused value vs effort creates false precision or local optimization instead of better delivery decisions.",
        [
            "value vs effort metric definition",
            "Decision the metric supports",
            "Trend over snapshot",
            "Gaming and misuse risk",
        ],
        "Apply value vs effort by defining the measurement, collecting it consistently, reviewing trends with context, and tying actions to bottlenecks or prioritization choices.",
        "value vs effort improves transparency, but it should not be used as an individual scorecard or compared across teams without context.",
        "If value vs effort worsens, inspect WIP, batch size, queues, blocked time, rework, release approvals, and whether the measurement changed.",
        "Metric review: value vs effort trend, target, context note, suspected bottleneck, action owner, due date, and next review. Evidence cue: Value vs effort prioritization compares expected benefit against delivery cost to choose work deliberately.",
        "1) Define metric and decision 2) Collect consistent trend data 3) Review with blockers and outcomes 4) Change WIP, scope, or process based on evidence.",
    ),
    "velocity": K(
        "Velocity is the amount of estimated work a Scrum team completes in a Sprint, useful for that team's forecasting.",
        "When velocity becomes ceremony rather than outcome management, teams report activity while value, blockers, and quality risks stay hidden.",
        [
            "velocity role in Scrum flow",
            "Sprint Goal or product outcome",
            "Ready and done criteria",
            "Inspect-and-adapt feedback",
        ],
        "Use velocity to clarify goal, order the right work, expose blockers, inspect the increment, and adapt the backlog or team process.",
        "velocity gives cadence and transparency, but teams should avoid cargo-cult Scrum when flow-based work or urgent interrupts dominate.",
        "If velocity is ineffective, inspect WIP, carryover, unclear acceptance criteria, unplanned work, dependencies, and whether retrospectives create actions.",
        "Scrum board artifact: velocity column or note ties each story to Sprint Goal, acceptance criteria, blocker owner, demo status, and carryover reason. Evidence cue: Velocity is the amount of estimated work a Scrum team completes in a Sprint, useful for that team's forecasting.",
        "1) Clarify goal and ready criteria 2) Make blockers visible daily 3) Review increment with stakeholders 4) Turn retro learning into one action.",
    ),
    "vendor management": K(
        "Vendor management coordinates third-party scope, contracts, performance, risks, and communication.",
        "Weak vendor management creates rework because sponsors, clients, vendors, and teams operate from different assumptions.",
        [
            "vendor management audience map",
            "Decision rights and RACI",
            "Communication cadence",
            "Escalation path",
        ],
        "Run vendor management by mapping influence and needs, choosing communication channels, recording decisions, confirming owners, and closing loops after meetings.",
        "vendor management builds trust through transparency, but excessive updates become noise; tune detail to audience, risk, and decision needs.",
        "If vendor management breaks down, separate facts from preferences, restate constraints, identify the decision owner, and offer options with impact.",
        "Status note: vendor management audience gets RAG, milestone forecast, blocker, owner, RAID change, decision needed, and next communication date. Evidence cue: Vendor management coordinates third-party scope, contracts, performance, risks, and communication.",
        "1) Map stakeholder needs 2) Publish concise status 3) Record decisions and owners 4) Escalate unresolved tradeoffs.",
    ),
    "work breakdown structure": K(
        "A work breakdown structure decomposes project deliverables into smaller manageable work packages.",
        "Poor work breakdown structure lets scope, date, cost, and quality move independently without an explicit sponsor decision.",
        [
            "work breakdown structure baseline",
            "Constraint and assumption log",
            "Forecast variance",
            "Approval or tradeoff decision",
        ],
        "Manage work breakdown structure by decomposing work, identifying constraints, tracking actuals against baseline, forecasting variance, and documenting approved tradeoffs.",
        "work breakdown structure gives control and predictability, but rigid baselines can fight discovery unless change control is lightweight and transparent.",
        "If work breakdown structure slips, inspect the critical path, dependency waits, capacity assumptions, estimation range, and whether scope was accepted without a baseline update.",
        "Change note: work breakdown structure impact from adding SSO is +2 weeks unless reporting export moves out; sponsor decides date move or scope swap by Tuesday. Evidence cue: A work breakdown structure decomposes project deliverables into smaller manageable work packages.",
        "1) Set baseline and assumptions 2) Track actuals and variance 3) Model options for scope/date/cost 4) Approve and communicate the new baseline.",
    ),
}

