from .lib import K

UIUX_TOPICS = {
    "A/B test": K(
        "An A/B test compares two or more design variants with live users to measure which one improves a predefined product metric.",
        "A/B tests that start from visual preference can overfit clicks, miss trust damage, or stop before the result is stable.",
        [
            "Hypothesis before variants",
            "Primary metric and guardrails",
            "Random assignment",
            "Minimum sample and duration",
        ],
        "Write the hypothesis, define the audience and allocation, instrument the primary conversion plus guardrails, run to the planned sample, and decide before peeking at noisy results.",
        "Experiments give production evidence, but they need traffic, analytics quality, and ethical guardrails for manipulative variants.",
        "If results look surprising, check event instrumentation, sample ratio mismatch, segment imbalance, seasonality, and whether users were exposed to both variants.",
        "Experiment brief: Variant B shortens signup copy; primary metric activation within 24h; guardrails unsubscribe rate and support tickets; stop after 14 days or planned sample. Evidence cue: An A/B test compares two or more design variants with live users to measure which one improves a predefined product metric.",
        "1) Write hypothesis and decision rule 2) Instrument primary and guardrail metrics 3) Run with stable allocation 4) Ship, iterate, or stop based on result.",
    ),
    "AI-assisted design": K(
        "AI-assisted design uses AI tools to draft, critique, or vary design work while a human designer remains responsible for judgment, ethics, and validation.",
        "Weak AI-assisted design makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "AI-assisted design task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply AI-assisted design by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "AI-assisted design benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around AI-assisted design, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Prompt brief: \"Generate 3 checkout error states using our tokens\"; designer keeps one, rewrites copy, runs contrast check, and discards generic stock layouts.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "Auto Layout": K(
        "Auto Layout is Figma behavior that lets frames and components resize predictably from padding, spacing, direction, and constraints.",
        "Poor Auto Layout makes components break with long labels, translated text, or different screen widths.",
        [
            "Direction and gap",
            "Padding and hug/fill behavior",
            "Constraints for resizing",
            "Nested frames for responsive components",
        ],
        "Set direction, gap, padding, hug/fill rules, min/max widths, and nested frames so the component resizes from content rather than manual pixel nudges.",
        "Auto Layout speeds responsive work, but deeply nested frames can confuse contributors and should be named clearly.",
        "If a component collapses, inspect hug/fill settings, absolute positioning, fixed widths, text wrapping, and nested frame constraints.",
        "Figma button: horizontal Auto Layout, 12px left/right padding, 8px icon gap, label hugs contents, container min-height 44px, loading spinner variant keeps width stable. Evidence cue: Auto Layout is Figma behavior that lets frames and components resize predictably from padding, spacing, direction, and constraints.",
        "1) Set padding, gap, and direction 2) Define hug/fill behavior for content 3) Test long text and responsive widths 4) Document component resizing rules.",
    ),
    "Jobs To Be Done": K(
        "Jobs To Be Done frames user needs as progress a person is trying to make in a situation, not as demographic traits.",
        "Without a clear Jobs To Be Done, teams can ship attractive screens that do not improve the behavior or outcome the product needs.",
        [
            "Jobs To Be Done outcome definition",
            "Baseline and segment",
            "Primary metric with guardrails",
            "Decision rule",
        ],
        "Translate Jobs To Be Done into a hypothesis, baseline the current behavior, instrument the relevant flow, and compare results with qualitative feedback.",
        "Jobs To Be Done focuses decisions, but narrow metrics can encourage dark patterns or local optimization unless guardrails are included.",
        "If Jobs To Be Done moves unexpectedly, check event naming, funnel step definitions, segment mix, attribution windows, and whether the design changed user intent or merely clicks.",
        "Product decision note: Jobs To Be Done hypothesis, target segment, primary metric, guardrails, baseline, experiment window, and ship/iterate/stop rule. Evidence cue: Jobs To Be Done frames user needs as progress a person is trying to make in a situation, not as demographic traits.",
        "1) Define the outcome and baseline 2) Instrument the behavior 3) Add guardrails 4) Review result and decision.",
    ),
    "UI design": K(
        "UI design is the craft of arranging visual and interactive interface elements so users can understand and operate a product.",
        "Weak UI design makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "UI design task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply UI design by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "UI design benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around UI design, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Screen spec: Orders list with sticky filters, empty state illustration, row density 48px, primary CTA \"Create order\" top-right, and truncated IDs with tooltip.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "UX writing": K(
        "UX writing is product copy for labels, instructions, empty states, errors, and confirmations that helps users complete tasks clearly.",
        "Weak UX writing makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "UX writing task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply UX writing by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "UX writing benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around UX writing, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Error rewrite: Bad \"Error occurred\" \u2192 Good \"Payment failed \u2014 card declined. Try another card or contact your bank.\" CTA: \"Try another card\".",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "WCAG": K(
        "WCAG is the W3C accessibility standard of testable success criteria organized around perceivable, operable, understandable, and robust experiences.",
        "Weak WCAG can block users with low vision, motor constraints, keyboard-only workflows, or assistive technology from completing a task.",
        [
            "WCAG success criterion",
            "Accessible name/role/state",
            "Keyboard and pointer operability",
            "Manual assistive-technology evidence",
        ],
        "Evaluate WCAG at component and journey level: inspect semantics, measure target or contrast values, keyboard through the flow, and confirm error/status announcements when relevant.",
        "Accessibility constraints can challenge brand or density preferences, but they usually improve clarity, error recovery, and usability for all users.",
        "When WCAG fails, check token values, component semantics, focus management, disabled-state contrast, viewport size, and whether the issue repeats across the design system.",
        "Accessibility audit: verify WCAG on login and checkout with keyboard-only navigation, visible focus, label association, and documented WCAG criterion. Evidence cue: WCAG is the W3C accessibility standard of testable success criteria organized around perceivable, operable, understandable, and robust experiences.",
        "1) Map WCAG to WCAG or platform guidance 2) Fix the source component or token 3) Test keyboard, screen reader, and pointer behavior 4) Track defects by user impact.",
    ),
    "affinity mapping": K(
        "Affinity mapping groups observations, quotes, or ideas into themes so teams can see patterns after research or ideation.",
        "Without a sound affinity mapping method, teams mistake anecdotes or biased prompts for evidence and design around the loudest internal opinion.",
        [
            "affinity mapping research objective",
            "Participant screening",
            "Neutral task or prompt design",
            "Synthesis into design decisions",
        ],
        "Use affinity mapping by writing the research question, choosing representative participants, running a neutral script or task, capturing observations, and synthesizing patterns into product decisions.",
        "affinity mapping gives depth and context, but it may not estimate frequency; pair it with analytics or survey data when scale matters.",
        "If affinity mapping findings conflict, review recruiting, moderator wording, task realism, prototype fidelity, and whether outliers were over-weighted.",
        "Research artifact: affinity mapping plan with objective, participant criteria, task/script, note grid, severity tags, clips/quotes, and decision recommendations. Evidence cue: Affinity mapping groups observations, quotes, or ideas into themes so teams can see patterns after research or ideation.",
        "1) Write the research decision 2) Recruit the right participant mix 3) Run sessions with neutral prompts 4) Synthesize findings into design changes.",
    ),
    "card sorting": K(
        "Card sorting is a research method where participants group and label content to inform information architecture.",
        "Without a sound card sorting method, teams mistake anecdotes or biased prompts for evidence and design around the loudest internal opinion.",
        [
            "card sorting research objective",
            "Participant screening",
            "Neutral task or prompt design",
            "Synthesis into design decisions",
        ],
        "Use card sorting by writing the research question, choosing representative participants, running a neutral script or task, capturing observations, and synthesizing patterns into product decisions.",
        "card sorting gives depth and context, but it may not estimate frequency; pair it with analytics or survey data when scale matters.",
        "If card sorting findings conflict, review recruiting, moderator wording, task realism, prototype fidelity, and whether outliers were over-weighted.",
        "Research artifact: card sorting plan with objective, participant criteria, task/script, note grid, severity tags, clips/quotes, and decision recommendations. Evidence cue: Card sorting is a research method where participants group and label content to inform information architecture.",
        "1) Write the research decision 2) Recruit the right participant mix 3) Run sessions with neutral prompts 4) Synthesize findings into design changes.",
    ),
    "case study": K(
        "A UX case study is a structured story of a design project, showing problem, role, process, tradeoffs, evidence, and outcome.",
        "Weak case study makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "case study task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply case study by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "case study benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around case study, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Portfolio outline: context \u2192 problem \u2192 constraints \u2192 2 rejected options \u2192 final flow \u2192 usability finding \u2192 metric (+12% activation) \u2192 what I would redo.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "color contrast": K(
        "Color contrast is the luminance difference between foreground and background colors, critical for readability and accessibility.",
        "Weak color contrast can block users with low vision, motor constraints, keyboard-only workflows, or assistive technology from completing a task.",
        [
            "color contrast success criterion",
            "Accessible name/role/state",
            "Keyboard and pointer operability",
            "Manual assistive-technology evidence",
        ],
        "Evaluate color contrast at component and journey level: inspect semantics, measure target or contrast values, keyboard through the flow, and confirm error/status announcements when relevant.",
        "Accessibility constraints can challenge brand or density preferences, but they usually improve clarity, error recovery, and usability for all users.",
        "When color contrast fails, check token values, component semantics, focus management, disabled-state contrast, viewport size, and whether the issue repeats across the design system.",
        "Accessibility audit: verify color contrast on login and checkout with keyboard-only navigation, visible focus, label association, and documented WCAG criterion. Evidence cue: Color contrast is the luminance difference between foreground and background colors, critical for readability and accessibility.",
        "1) Map color contrast to WCAG or platform guidance 2) Fix the source component or token 3) Test keyboard, screen reader, and pointer behavior 4) Track defects by user impact.",
    ),
    "component": K(
        "A design component is a reusable UI building block with defined structure, states, and behavior.",
        "Poor component causes implementation drift: teams rebuild patterns, miss states, and ship inconsistent accessibility or responsive behavior.",
        [
            "component usage rules",
            "State and variant matrix",
            "Token and constraint mapping",
            "Engineering acceptance notes",
        ],
        "Document component with named variants, state coverage, content limits, responsive behavior, tokens, accessibility requirements, and examples of correct and incorrect use.",
        "A strong component speeds delivery after setup, but excessive governance can block necessary product-specific learning.",
        "If component drifts in code, compare the Figma component, token export, Storybook implementation, state matrix, and open handoff questions.",
        "Component artifact: component spec lists default/hover/focus/disabled/loading states, variant props, token names, responsive constraints, and do/don't examples. Evidence cue: A design component is a reusable UI building block with defined structure, states, and behavior.",
        "1) Define variants and states 2) Attach tokens and constraints 3) Review with engineering 4) Publish usage and deprecation notes.",
    ),
    "component library": K(
        "A component library is a shared catalog of reusable UI components, guidelines, and implementation references.",
        "Poor component library causes implementation drift: teams rebuild patterns, miss states, and ship inconsistent accessibility or responsive behavior.",
        [
            "component library usage rules",
            "State and variant matrix",
            "Token and constraint mapping",
            "Engineering acceptance notes",
        ],
        "Document component library with named variants, state coverage, content limits, responsive behavior, tokens, accessibility requirements, and examples of correct and incorrect use.",
        "A strong component library speeds delivery after setup, but excessive governance can block necessary product-specific learning.",
        "If component library drifts in code, compare the Figma component, token export, Storybook implementation, state matrix, and open handoff questions.",
        "Component artifact: component library spec lists default/hover/focus/disabled/loading states, variant props, token names, responsive constraints, and do/don't examples. Evidence cue: A component library is a shared catalog of reusable UI components, guidelines, and implementation references.",
        "1) Define variants and states 2) Attach tokens and constraints 3) Review with engineering 4) Publish usage and deprecation notes.",
    ),
    "contextual inquiry": K(
        "Contextual inquiry is field research where the researcher observes and interviews users in the environment where work happens.",
        "Without a sound contextual inquiry method, teams mistake anecdotes or biased prompts for evidence and design around the loudest internal opinion.",
        [
            "contextual inquiry research objective",
            "Participant screening",
            "Neutral task or prompt design",
            "Synthesis into design decisions",
        ],
        "Use contextual inquiry by writing the research question, choosing representative participants, running a neutral script or task, capturing observations, and synthesizing patterns into product decisions.",
        "contextual inquiry gives depth and context, but it may not estimate frequency; pair it with analytics or survey data when scale matters.",
        "If contextual inquiry findings conflict, review recruiting, moderator wording, task realism, prototype fidelity, and whether outliers were over-weighted.",
        "Research artifact: contextual inquiry plan with objective, participant criteria, task/script, note grid, severity tags, clips/quotes, and decision recommendations. Evidence cue: Contextual inquiry is field research where the researcher observes and interviews users in the environment where work happens.",
        "1) Write the research decision 2) Recruit the right participant mix 3) Run sessions with neutral prompts 4) Synthesize findings into design changes.",
    ),
    "customer journey map": K(
        "A customer journey map visualizes the steps, touchpoints, emotions, pain points, and opportunities across a user relationship with a product or service.",
        "Without a sound customer journey map method, teams mistake anecdotes or biased prompts for evidence and design around the loudest internal opinion.",
        [
            "customer journey map research objective",
            "Participant screening",
            "Neutral task or prompt design",
            "Synthesis into design decisions",
        ],
        "Use customer journey map by writing the research question, choosing representative participants, running a neutral script or task, capturing observations, and synthesizing patterns into product decisions.",
        "customer journey map gives depth and context, but it may not estimate frequency; pair it with analytics or survey data when scale matters.",
        "If customer journey map findings conflict, review recruiting, moderator wording, task realism, prototype fidelity, and whether outliers were over-weighted.",
        "Research artifact: customer journey map plan with objective, participant criteria, task/script, note grid, severity tags, clips/quotes, and decision recommendations. Evidence cue: A customer journey map visualizes the steps, touchpoints, emotions, pain points, and opportunities across a user relationship with a product or service.",
        "1) Write the research decision 2) Recruit the right participant mix 3) Run sessions with neutral prompts 4) Synthesize findings into design changes.",
    ),
    "dark pattern": K(
        "A dark pattern is a deceptive interface choice that manipulates users into actions they did not freely intend.",
        "Dark patterns can lift a local metric while increasing complaints, chargebacks, churn, regulatory exposure, and loss of user trust.",
        [
            "Deceptive choice architecture",
            "Consent and transparency",
            "Short-term conversion vs trust",
            "Legal and brand risk",
        ],
        "Identify the deceptive mechanism, restate the business goal, design an honest alternative, and measure conversion with trust guardrails.",
        "Transparent flows may reduce accidental conversions, but they build durable consent and reduce support and legal risk.",
        "If stakeholders push for deception, show the exact user harm, comparable compliant patterns, complaint data, and guardrail metrics beyond click-through rate.",
        "Cancellation review: remove hidden opt-out, show plan value honestly, offer pause as an equal option, and track completed cancellations, saves, complaints, and refunds. Evidence cue: A dark pattern is a deceptive interface choice that manipulates users into actions they did not freely intend.",
        "1) Name the deceptive mechanism 2) Propose an ethical alternative 3) Add trust and complaint guardrails 4) Document the decision with legal/product review.",
    ),
    "design critique": K(
        "Design critique is a structured review of design work against goals, constraints, evidence, and principles.",
        "Weak design critique makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "design critique task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply design critique by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "design critique benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around design critique, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Critique agenda (30m): goal restated 2m \u2192 silent review 5m \u2192 feedback against heuristics 15m \u2192 actions owned in tickets 8m.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "design rationale": K(
        "Design rationale documents why a design decision was made, including alternatives, constraints, evidence, and tradeoffs.",
        "Weak design rationale makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "design rationale task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply design rationale by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "design rationale benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around design rationale, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "ADR-D: Chose multi-step signup over single page because mobile validation errors overwhelmed users in test; link usability notes + metric.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "design token": K(
        "Design tokens are named, reusable design decisions like color, spacing, typography, radius, and motion stored as data for Figma and code.",
        "Without design tokens, Figma colors and code values drift, dark mode becomes a repainting exercise, and accessibility fixes must be repeated component by component.",
        [
            "Primitive vs semantic tokens",
            "Role-based naming",
            "Theme and mode remapping",
            "Export to CSS variables or platform constants",
        ],
        "Define primitives such as blue-600, map semantic roles such as color.action.primary, publish modes for themes, and export the token package to CSS variables or native constants.",
        "Token systems improve consistency and theming, but over-nesting aliases makes debugging hard and can slow small experiments.",
        "If a color or spacing value differs between design and code, trace the semantic token, generated CSS variable, component override, and theme mode before changing raw values.",
        "Token JSON: {\"color\":{\"action\":{\"primary\":{\"value\":\"{color.blue.600}\"}}},\"space\":{\"400\":{\"value\":\"16px\"}}}; CSS uses var(--color-action-primary). Evidence cue: Design tokens are named, reusable design decisions like color, spacing, typography, radius, and motion stored as data for Figma and code.",
        "1) Name primitive and semantic token layers 2) Export tokens from Figma or source JSON 3) Consume CSS variables in components 4) Audit hard-coded values during review.",
    ),
    "designer-PM collaboration": K(
        "Designer-PM collaboration aligns user needs, product strategy, scope, metrics, and delivery constraints before design work hardens.",
        "Weak designer-PM collaboration makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "designer-PM collaboration task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply designer-PM collaboration by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "designer-PM collaboration benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around designer-PM collaboration, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Kickoff one-pager: outcome, user, constraints, non-goals, success metric, open questions \u2014 signed by PM + design before UI polish.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "designer-engineer handoff": K(
        "Designer-engineer handoff translates design intent into buildable specifications, states, assets, tokens, and open questions.",
        "Poor designer-engineer handoff causes implementation drift: teams rebuild patterns, miss states, and ship inconsistent accessibility or responsive behavior.",
        [
            "designer-engineer handoff usage rules",
            "State and variant matrix",
            "Token and constraint mapping",
            "Engineering acceptance notes",
        ],
        "Document designer-engineer handoff with named variants, state coverage, content limits, responsive behavior, tokens, accessibility requirements, and examples of correct and incorrect use.",
        "A strong designer-engineer handoff speeds delivery after setup, but excessive governance can block necessary product-specific learning.",
        "If designer-engineer handoff drifts in code, compare the Figma component, token export, Storybook implementation, state matrix, and open handoff questions.",
        "Component artifact: designer-engineer handoff spec lists default/hover/focus/disabled/loading states, variant props, token names, responsive constraints, and do/don't examples. Evidence cue: Designer-engineer handoff translates design intent into buildable specifications, states, assets, tokens, and open questions.",
        "1) Define variants and states 2) Attach tokens and constraints 3) Review with engineering 4) Publish usage and deprecation notes.",
    ),
    "developer handoff": K(
        "Developer handoff is the package of design specs, behavior notes, assets, and decisions engineers need to implement accurately.",
        "Poor developer handoff causes implementation drift: teams rebuild patterns, miss states, and ship inconsistent accessibility or responsive behavior.",
        [
            "developer handoff usage rules",
            "State and variant matrix",
            "Token and constraint mapping",
            "Engineering acceptance notes",
        ],
        "Document developer handoff with named variants, state coverage, content limits, responsive behavior, tokens, accessibility requirements, and examples of correct and incorrect use.",
        "A strong developer handoff speeds delivery after setup, but excessive governance can block necessary product-specific learning.",
        "If developer handoff drifts in code, compare the Figma component, token export, Storybook implementation, state matrix, and open handoff questions.",
        "Component artifact: developer handoff spec lists default/hover/focus/disabled/loading states, variant props, token names, responsive constraints, and do/don't examples. Evidence cue: Developer handoff is the package of design specs, behavior notes, assets, and decisions engineers need to implement accurately.",
        "1) Define variants and states 2) Attach tokens and constraints 3) Review with engineering 4) Publish usage and deprecation notes.",
    ),
    "error prevention": K(
        "Error prevention designs constraints, defaults, confirmations, and validation to stop users from making costly mistakes.",
        "Weak error prevention makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "error prevention task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply error prevention by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "error prevention benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around error prevention, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Destructive pattern: Delete project requires typing name; default action is Archive; Undo toast 10s for recoverable deletes.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "feedback and system status": K(
        "Feedback and system status means the UI visibly communicates what happened, what is happening, and what the user can do next.",
        "Weak feedback and system status makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "feedback and system status task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply feedback and system status by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "feedback and system status benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around feedback and system status, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Save flow: button \u2192 Saving\u2026 (disabled) \u2192 Saved \u2713 inline; on failure show field-level message + retry without clearing inputs.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "funnel analysis": K(
        "Funnel analysis measures how users move through a sequence of steps and where they drop off.",
        "Without a clear funnel analysis, teams can ship attractive screens that do not improve the behavior or outcome the product needs.",
        [
            "funnel analysis outcome definition",
            "Baseline and segment",
            "Primary metric with guardrails",
            "Decision rule",
        ],
        "Translate funnel analysis into a hypothesis, baseline the current behavior, instrument the relevant flow, and compare results with qualitative feedback.",
        "funnel analysis focuses decisions, but narrow metrics can encourage dark patterns or local optimization unless guardrails are included.",
        "If funnel analysis moves unexpectedly, check event naming, funnel step definitions, segment mix, attribution windows, and whether the design changed user intent or merely clicks.",
        "Product decision note: funnel analysis hypothesis, target segment, primary metric, guardrails, baseline, experiment window, and ship/iterate/stop rule. Evidence cue: Funnel analysis measures how users move through a sequence of steps and where they drop off.",
        "1) Define the outcome and baseline 2) Instrument the behavior 3) Add guardrails 4) Review result and decision.",
    ),
    "gesture": K(
        "A gesture is a touch or pointer interaction such as tap, swipe, drag, pinch, or long press that triggers product behavior.",
        "Weak gesture makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "gesture task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply gesture by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "gesture benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around gesture, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Archive: swipe left reveals Archive + Undo toast; overflow menu also has Archive for discoverability and a11y.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "governance": K(
        "Design system governance defines how components, tokens, contribution rules, ownership, and deprecations are managed over time.",
        "Poor governance causes implementation drift: teams rebuild patterns, miss states, and ship inconsistent accessibility or responsive behavior.",
        [
            "governance usage rules",
            "State and variant matrix",
            "Token and constraint mapping",
            "Engineering acceptance notes",
        ],
        "Document governance with named variants, state coverage, content limits, responsive behavior, tokens, accessibility requirements, and examples of correct and incorrect use.",
        "A strong governance speeds delivery after setup, but excessive governance can block necessary product-specific learning.",
        "If governance drifts in code, compare the Figma component, token export, Storybook implementation, state matrix, and open handoff questions.",
        "Component artifact: governance spec lists default/hover/focus/disabled/loading states, variant props, token names, responsive constraints, and do/don't examples. Evidence cue: Design system governance defines how components, tokens, contribution rules, ownership, and deprecations are managed over time.",
        "1) Define variants and states 2) Attach tokens and constraints 3) Review with engineering 4) Publish usage and deprecation notes.",
    ),
    "grid system": K(
        "A grid system is a layout structure of columns, gutters, and margins that helps align content consistently across screens.",
        "Weak grid system makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "grid system task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply grid system by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "grid system benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around grid system, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Layout: mobile 4-col gutter 16; tablet 8-col gutter 24; desktop 12-col max 1200; full-bleed hero is documented exception.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "information architecture": K(
        "Information architecture organizes content and navigation so users can find, understand, and complete tasks.",
        "Weak information architecture makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "information architecture task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply information architecture by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "information architecture benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around information architecture, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Tree-test result: \"Invoices\" found under Billing 80%; rename \"Statements\" \u2192 \"Invoices\" and collapse duplicate Finance entry points.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "interaction design": K(
        "Interaction design defines how users act on an interface and how the system responds across states and time.",
        "Weak interaction design makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "interaction design task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply interaction design by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "interaction design benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around interaction design, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Invite modal: focus trap, Esc closes, role select with keyboard, success returns focus to Invite button, error announced on role field.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "keyboard accessibility": K(
        "Keyboard accessibility means every interactive task can be reached, understood, and completed with keyboard input alone.",
        "Weak keyboard accessibility can block users with low vision, motor constraints, keyboard-only workflows, or assistive technology from completing a task.",
        [
            "keyboard accessibility success criterion",
            "Accessible name/role/state",
            "Keyboard and pointer operability",
            "Manual assistive-technology evidence",
        ],
        "Evaluate keyboard accessibility at component and journey level: inspect semantics, measure target or contrast values, keyboard through the flow, and confirm error/status announcements when relevant.",
        "Accessibility constraints can challenge brand or density preferences, but they usually improve clarity, error recovery, and usability for all users.",
        "When keyboard accessibility fails, check token values, component semantics, focus management, disabled-state contrast, viewport size, and whether the issue repeats across the design system.",
        "Accessibility audit: verify keyboard accessibility on login and checkout with keyboard-only navigation, visible focus, label association, and documented WCAG criterion. Evidence cue: Keyboard accessibility means every interactive task can be reached, understood, and completed with keyboard input alone.",
        "1) Map keyboard accessibility to WCAG or platform guidance 2) Fix the source component or token 3) Test keyboard, screen reader, and pointer behavior 4) Track defects by user impact.",
    ),
    "low-fidelity wireframe": K(
        "A low-fidelity wireframe is a rough layout that explores structure, priority, and flow before visual polish.",
        "Weak low-fidelity wireframe makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "low-fidelity wireframe task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply low-fidelity wireframe by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "low-fidelity wireframe benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around low-fidelity wireframe, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Grayscale wire: header / filters / results / primary CTA only; annotate \"sort TBD\" rather than inventing chrome.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "moderated test": K(
        "A moderated test is a usability session where a facilitator observes a participant performing tasks and asks neutral follow-up questions.",
        "Without a sound moderated test method, teams mistake anecdotes or biased prompts for evidence and design around the loudest internal opinion.",
        [
            "moderated test research objective",
            "Participant screening",
            "Neutral task or prompt design",
            "Synthesis into design decisions",
        ],
        "Use moderated test by writing the research question, choosing representative participants, running a neutral script or task, capturing observations, and synthesizing patterns into product decisions.",
        "moderated test gives depth and context, but it may not estimate frequency; pair it with analytics or survey data when scale matters.",
        "If moderated test findings conflict, review recruiting, moderator wording, task realism, prototype fidelity, and whether outliers were over-weighted.",
        "Research artifact: moderated test plan with objective, participant criteria, task/script, note grid, severity tags, clips/quotes, and decision recommendations. Evidence cue: A moderated test is a usability session where a facilitator observes a participant performing tasks and asks neutral follow-up questions.",
        "1) Write the research decision 2) Recruit the right participant mix 3) Run sessions with neutral prompts 4) Synthesize findings into design changes.",
    ),
    "persona": K(
        "A persona is a research-based archetype that summarizes user goals, behaviors, context, and needs for design alignment.",
        "Without a sound persona method, teams mistake anecdotes or biased prompts for evidence and design around the loudest internal opinion.",
        [
            "persona research objective",
            "Participant screening",
            "Neutral task or prompt design",
            "Synthesis into design decisions",
        ],
        "Use persona by writing the research question, choosing representative participants, running a neutral script or task, capturing observations, and synthesizing patterns into product decisions.",
        "persona gives depth and context, but it may not estimate frequency; pair it with analytics or survey data when scale matters.",
        "If persona findings conflict, review recruiting, moderator wording, task realism, prototype fidelity, and whether outliers were over-weighted.",
        "Research artifact: persona plan with objective, participant criteria, task/script, note grid, severity tags, clips/quotes, and decision recommendations. Evidence cue: A persona is a research-based archetype that summarizes user goals, behaviors, context, and needs for design alignment.",
        "1) Write the research decision 2) Recruit the right participant mix 3) Run sessions with neutral prompts 4) Synthesize findings into design changes.",
    ),
    "product metric": K(
        "A product metric is a quantified signal of user or business behavior used to judge whether a product change worked.",
        "Without a clear product metric, teams can ship attractive screens that do not improve the behavior or outcome the product needs.",
        [
            "product metric outcome definition",
            "Baseline and segment",
            "Primary metric with guardrails",
            "Decision rule",
        ],
        "Translate product metric into a hypothesis, baseline the current behavior, instrument the relevant flow, and compare results with qualitative feedback.",
        "product metric focuses decisions, but narrow metrics can encourage dark patterns or local optimization unless guardrails are included.",
        "If product metric moves unexpectedly, check event naming, funnel step definitions, segment mix, attribution windows, and whether the design changed user intent or merely clicks.",
        "Product decision note: product metric hypothesis, target segment, primary metric, guardrails, baseline, experiment window, and ship/iterate/stop rule. Evidence cue: A product metric is a quantified signal of user or business behavior used to judge whether a product change worked.",
        "1) Define the outcome and baseline 2) Instrument the behavior 3) Add guardrails 4) Review result and decision.",
    ),
    "product thinking": K(
        "Product thinking connects user problems, business goals, constraints, and measurable outcomes before choosing features.",
        "Without a clear product thinking, teams can ship attractive screens that do not improve the behavior or outcome the product needs.",
        [
            "product thinking outcome definition",
            "Baseline and segment",
            "Primary metric with guardrails",
            "Decision rule",
        ],
        "Translate product thinking into a hypothesis, baseline the current behavior, instrument the relevant flow, and compare results with qualitative feedback.",
        "product thinking focuses decisions, but narrow metrics can encourage dark patterns or local optimization unless guardrails are included.",
        "If product thinking moves unexpectedly, check event naming, funnel step definitions, segment mix, attribution windows, and whether the design changed user intent or merely clicks.",
        "Product decision note: product thinking hypothesis, target segment, primary metric, guardrails, baseline, experiment window, and ship/iterate/stop rule. Evidence cue: Product thinking connects user problems, business goals, constraints, and measurable outcomes before choosing features.",
        "1) Define the outcome and baseline 2) Instrument the behavior 3) Add guardrails 4) Review result and decision.",
    ),
    "prototype": K(
        "A prototype is an interactive or simulated version of a design used to test flow, behavior, and assumptions before build.",
        "Weak prototype makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "prototype task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply prototype by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "prototype benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around prototype, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Figma prototype task: invite teammate with view-only; success = correct role set in <2 minutes without facilitator help.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "qualitative research": K(
        "Qualitative research explores why users behave or feel a certain way through interviews, observation, and open-ended tasks.",
        "Without a sound qualitative research method, teams mistake anecdotes or biased prompts for evidence and design around the loudest internal opinion.",
        [
            "qualitative research research objective",
            "Participant screening",
            "Neutral task or prompt design",
            "Synthesis into design decisions",
        ],
        "Use qualitative research by writing the research question, choosing representative participants, running a neutral script or task, capturing observations, and synthesizing patterns into product decisions.",
        "qualitative research gives depth and context, but it may not estimate frequency; pair it with analytics or survey data when scale matters.",
        "If qualitative research findings conflict, review recruiting, moderator wording, task realism, prototype fidelity, and whether outliers were over-weighted.",
        "Research artifact: qualitative research plan with objective, participant criteria, task/script, note grid, severity tags, clips/quotes, and decision recommendations. Evidence cue: Qualitative research explores why users behave or feel a certain way through interviews, observation, and open-ended tasks.",
        "1) Write the research decision 2) Recruit the right participant mix 3) Run sessions with neutral prompts 4) Synthesize findings into design changes.",
    ),
    "research bias": K(
        "Research bias is systematic distortion in recruiting, questions, interpretation, or analysis that makes findings less trustworthy.",
        "Without a sound research bias method, teams mistake anecdotes or biased prompts for evidence and design around the loudest internal opinion.",
        [
            "research bias research objective",
            "Participant screening",
            "Neutral task or prompt design",
            "Synthesis into design decisions",
        ],
        "Use research bias by writing the research question, choosing representative participants, running a neutral script or task, capturing observations, and synthesizing patterns into product decisions.",
        "research bias gives depth and context, but it may not estimate frequency; pair it with analytics or survey data when scale matters.",
        "If research bias findings conflict, review recruiting, moderator wording, task realism, prototype fidelity, and whether outliers were over-weighted.",
        "Research artifact: research bias plan with objective, participant criteria, task/script, note grid, severity tags, clips/quotes, and decision recommendations. Evidence cue: Research bias is systematic distortion in recruiting, questions, interpretation, or analysis that makes findings less trustworthy.",
        "1) Write the research decision 2) Recruit the right participant mix 3) Run sessions with neutral prompts 4) Synthesize findings into design changes.",
    ),
    "research plan": K(
        "A research plan defines the objective, method, participants, script or tasks, success criteria, timeline, and synthesis approach.",
        "Without a sound research plan method, teams mistake anecdotes or biased prompts for evidence and design around the loudest internal opinion.",
        [
            "research plan research objective",
            "Participant screening",
            "Neutral task or prompt design",
            "Synthesis into design decisions",
        ],
        "Use research plan by writing the research question, choosing representative participants, running a neutral script or task, capturing observations, and synthesizing patterns into product decisions.",
        "research plan gives depth and context, but it may not estimate frequency; pair it with analytics or survey data when scale matters.",
        "If research plan findings conflict, review recruiting, moderator wording, task realism, prototype fidelity, and whether outliers were over-weighted.",
        "Research artifact: research plan plan with objective, participant criteria, task/script, note grid, severity tags, clips/quotes, and decision recommendations. Evidence cue: A research plan defines the objective, method, participants, script or tasks, success criteria, timeline, and synthesis approach.",
        "1) Write the research decision 2) Recruit the right participant mix 3) Run sessions with neutral prompts 4) Synthesize findings into design changes.",
    ),
    "responsive design": K(
        "Responsive design adapts layout, content priority, and interaction patterns across screen sizes and input modes.",
        "Weak responsive design makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "responsive design task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply responsive design by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "responsive design benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around responsive design, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Nav pattern: bottom bar on <768px, side nav desktop; wide tables collapse to card list with key fields first.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "spacing system": K(
        "A spacing system is a consistent scale for margins, padding, gaps, and layout rhythm.",
        "Weak spacing system makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "spacing system task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply spacing system by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "spacing system benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around spacing system, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Scale 4/8/12/16/24/32/48; stack gaps use space.400 (16); ban 13px one-offs in component PRs.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "target size": K(
        "Target size is the physical or CSS pixel area available for activating an interactive control.",
        "Weak target size can block users with low vision, motor constraints, keyboard-only workflows, or assistive technology from completing a task.",
        [
            "target size success criterion",
            "Accessible name/role/state",
            "Keyboard and pointer operability",
            "Manual assistive-technology evidence",
        ],
        "Evaluate target size at component and journey level: inspect semantics, measure target or contrast values, keyboard through the flow, and confirm error/status announcements when relevant.",
        "Accessibility constraints can challenge brand or density preferences, but they usually improve clarity, error recovery, and usability for all users.",
        "When target size fails, check token values, component semantics, focus management, disabled-state contrast, viewport size, and whether the issue repeats across the design system.",
        "Accessibility audit: verify target size on login and checkout with keyboard-only navigation, visible focus, label association, and documented WCAG criterion. Evidence cue: Target size is the physical or CSS pixel area available for activating an interactive control.",
        "1) Map target size to WCAG or platform guidance 2) Fix the source component or token 3) Test keyboard, screen reader, and pointer behavior 4) Track defects by user impact.",
    ),
    "task success": K(
        "Task success measures whether users can complete a defined task correctly, efficiently, and with acceptable confidence.",
        "Without a sound task success method, teams mistake anecdotes or biased prompts for evidence and design around the loudest internal opinion.",
        [
            "task success research objective",
            "Participant screening",
            "Neutral task or prompt design",
            "Synthesis into design decisions",
        ],
        "Use task success by writing the research question, choosing representative participants, running a neutral script or task, capturing observations, and synthesizing patterns into product decisions.",
        "task success gives depth and context, but it may not estimate frequency; pair it with analytics or survey data when scale matters.",
        "If task success findings conflict, review recruiting, moderator wording, task realism, prototype fidelity, and whether outliers were over-weighted.",
        "Research artifact: task success plan with objective, participant criteria, task/script, note grid, severity tags, clips/quotes, and decision recommendations. Evidence cue: Task success measures whether users can complete a defined task correctly, efficiently, and with acceptable confidence.",
        "1) Write the research decision 2) Recruit the right participant mix 3) Run sessions with neutral prompts 4) Synthesize findings into design changes.",
    ),
    "touch target": K(
        "A touch target is the tappable area of a mobile or touch interface control, including any invisible hit area.",
        "Weak touch target can block users with low vision, motor constraints, keyboard-only workflows, or assistive technology from completing a task.",
        [
            "touch target success criterion",
            "Accessible name/role/state",
            "Keyboard and pointer operability",
            "Manual assistive-technology evidence",
        ],
        "Evaluate touch target at component and journey level: inspect semantics, measure target or contrast values, keyboard through the flow, and confirm error/status announcements when relevant.",
        "Accessibility constraints can challenge brand or density preferences, but they usually improve clarity, error recovery, and usability for all users.",
        "When touch target fails, check token values, component semantics, focus management, disabled-state contrast, viewport size, and whether the issue repeats across the design system.",
        "Accessibility audit: verify touch target on login and checkout with keyboard-only navigation, visible focus, label association, and documented WCAG criterion. Evidence cue: A touch target is the tappable area of a mobile or touch interface control, including any invisible hit area.",
        "1) Map touch target to WCAG or platform guidance 2) Fix the source component or token 3) Test keyboard, screen reader, and pointer behavior 4) Track defects by user impact.",
    ),
    "typography hierarchy": K(
        "Typography hierarchy uses type size, weight, spacing, and style to show content priority and relationships.",
        "Weak typography hierarchy makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "typography hierarchy task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply typography hierarchy by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "typography hierarchy benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around typography hierarchy, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Text styles: Display 32/40, Title 24/32, Body 16/24, Label 14/20, Caption 12/16 \u2014 body measure ~60ch.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "usability heuristic": K(
        "A usability heuristic is a broad rule of thumb, such as visibility of system status or error prevention, used to inspect an interface.",
        "Without a sound usability heuristic method, teams mistake anecdotes or biased prompts for evidence and design around the loudest internal opinion.",
        [
            "usability heuristic research objective",
            "Participant screening",
            "Neutral task or prompt design",
            "Synthesis into design decisions",
        ],
        "Use usability heuristic by writing the research question, choosing representative participants, running a neutral script or task, capturing observations, and synthesizing patterns into product decisions.",
        "usability heuristic gives depth and context, but it may not estimate frequency; pair it with analytics or survey data when scale matters.",
        "If usability heuristic findings conflict, review recruiting, moderator wording, task realism, prototype fidelity, and whether outliers were over-weighted.",
        "Research artifact: usability heuristic plan with objective, participant criteria, task/script, note grid, severity tags, clips/quotes, and decision recommendations. Evidence cue: A usability heuristic is a broad rule of thumb, such as visibility of system status or error prevention, used to inspect an interface.",
        "1) Write the research decision 2) Recruit the right participant mix 3) Run sessions with neutral prompts 4) Synthesize findings into design changes.",
    ),
    "usability testing": K(
        "Usability testing observes representative users attempting realistic tasks to find friction and validate design decisions.",
        "Without a sound usability testing method, teams mistake anecdotes or biased prompts for evidence and design around the loudest internal opinion.",
        [
            "usability testing research objective",
            "Participant screening",
            "Neutral task or prompt design",
            "Synthesis into design decisions",
        ],
        "Use usability testing by writing the research question, choosing representative participants, running a neutral script or task, capturing observations, and synthesizing patterns into product decisions.",
        "usability testing gives depth and context, but it may not estimate frequency; pair it with analytics or survey data when scale matters.",
        "If usability testing findings conflict, review recruiting, moderator wording, task realism, prototype fidelity, and whether outliers were over-weighted.",
        "Research artifact: usability testing plan with objective, participant criteria, task/script, note grid, severity tags, clips/quotes, and decision recommendations. Evidence cue: Usability testing observes representative users attempting realistic tasks to find friction and validate design decisions.",
        "1) Write the research decision 2) Recruit the right participant mix 3) Run sessions with neutral prompts 4) Synthesize findings into design changes.",
    ),
    "user flow": K(
        "A user flow maps the steps a user takes from entry point to goal, including decisions and system states.",
        "Weak user flow makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "user flow task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply user flow by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "user flow benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around user flow, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Flow: Start trial \u2192 verify email \u2192 create workspace \u2192 invite \u2192 first project; branches for expired link and existing account.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "user interview": K(
        "A user interview is a research conversation used to understand motivations, context, pain points, and decision-making.",
        "Without a sound user interview method, teams mistake anecdotes or biased prompts for evidence and design around the loudest internal opinion.",
        [
            "user interview research objective",
            "Participant screening",
            "Neutral task or prompt design",
            "Synthesis into design decisions",
        ],
        "Use user interview by writing the research question, choosing representative participants, running a neutral script or task, capturing observations, and synthesizing patterns into product decisions.",
        "user interview gives depth and context, but it may not estimate frequency; pair it with analytics or survey data when scale matters.",
        "If user interview findings conflict, review recruiting, moderator wording, task realism, prototype fidelity, and whether outliers were over-weighted.",
        "Research artifact: user interview plan with objective, participant criteria, task/script, note grid, severity tags, clips/quotes, and decision recommendations. Evidence cue: A user interview is a research conversation used to understand motivations, context, pain points, and decision-making.",
        "1) Write the research decision 2) Recruit the right participant mix 3) Run sessions with neutral prompts 4) Synthesize findings into design changes.",
    ),
    "user outcome": K(
        "A user outcome is the meaningful result a user wants after using the product, independent of a particular feature.",
        "Without a clear user outcome, teams can ship attractive screens that do not improve the behavior or outcome the product needs.",
        [
            "user outcome outcome definition",
            "Baseline and segment",
            "Primary metric with guardrails",
            "Decision rule",
        ],
        "Translate user outcome into a hypothesis, baseline the current behavior, instrument the relevant flow, and compare results with qualitative feedback.",
        "user outcome focuses decisions, but narrow metrics can encourage dark patterns or local optimization unless guardrails are included.",
        "If user outcome moves unexpectedly, check event naming, funnel step definitions, segment mix, attribution windows, and whether the design changed user intent or merely clicks.",
        "Product decision note: user outcome hypothesis, target segment, primary metric, guardrails, baseline, experiment window, and ship/iterate/stop rule. Evidence cue: A user outcome is the meaningful result a user wants after using the product, independent of a particular feature.",
        "1) Define the outcome and baseline 2) Instrument the behavior 3) Add guardrails 4) Review result and decision.",
    ),
    "user-centered design": K(
        "User-centered design is an iterative process that bases decisions on user needs, context, feedback, and usability evidence.",
        "Weak user-centered design makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "user-centered design task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply user-centered design by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "user-centered design benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around user-centered design, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Loop card: problem statement + 5 interview quotes \u2192 prototype \u2192 5-user test \u2192 ship MVP \u2192 activation dashboard review.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "variables": K(
        "Figma variables store reusable values such as color, spacing, strings, or modes that can drive consistent design behavior.",
        "Poor variables causes implementation drift: teams rebuild patterns, miss states, and ship inconsistent accessibility or responsive behavior.",
        [
            "variables usage rules",
            "State and variant matrix",
            "Token and constraint mapping",
            "Engineering acceptance notes",
        ],
        "Document variables with named variants, state coverage, content limits, responsive behavior, tokens, accessibility requirements, and examples of correct and incorrect use.",
        "A strong variables speeds delivery after setup, but excessive governance can block necessary product-specific learning.",
        "If variables drifts in code, compare the Figma component, token export, Storybook implementation, state matrix, and open handoff questions.",
        "Component artifact: variables spec lists default/hover/focus/disabled/loading states, variant props, token names, responsive constraints, and do/don't examples. Evidence cue: Figma variables store reusable values such as color, spacing, strings, or modes that can drive consistent design behavior.",
        "1) Define variants and states 2) Attach tokens and constraints 3) Review with engineering 4) Publish usage and deprecation notes.",
    ),
    "variant": K(
        "A variant is a named state or option of a component, such as size, intent, selected, disabled, or loading.",
        "Poor variant causes implementation drift: teams rebuild patterns, miss states, and ship inconsistent accessibility or responsive behavior.",
        [
            "variant usage rules",
            "State and variant matrix",
            "Token and constraint mapping",
            "Engineering acceptance notes",
        ],
        "Document variant with named variants, state coverage, content limits, responsive behavior, tokens, accessibility requirements, and examples of correct and incorrect use.",
        "A strong variant speeds delivery after setup, but excessive governance can block necessary product-specific learning.",
        "If variant drifts in code, compare the Figma component, token export, Storybook implementation, state matrix, and open handoff questions.",
        "Component artifact: variant spec lists default/hover/focus/disabled/loading states, variant props, token names, responsive constraints, and do/don't examples. Evidence cue: A variant is a named state or option of a component, such as size, intent, selected, disabled, or loading.",
        "1) Define variants and states 2) Attach tokens and constraints 3) Review with engineering 4) Publish usage and deprecation notes.",
    ),
    "visual hierarchy": K(
        "Visual hierarchy directs attention by using size, contrast, position, spacing, and grouping.",
        "Weak visual hierarchy makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "visual hierarchy task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply visual hierarchy by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "visual hierarchy benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around visual hierarchy, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Before/after: reduce 4 equal buttons to 1 primary + text links; increase title weight; add 24px separation above CTA.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
    "whiteboard challenge": K(
        "A whiteboard challenge is a timed design exercise used to evaluate problem framing, collaboration, and reasoning under constraints.",
        "Weak whiteboard challenge makes the next action, hierarchy, or recovery path unclear, increasing hesitation and avoidable errors.",
        [
            "whiteboard challenge task model",
            "Information or visual priority",
            "State and recovery design",
            "Validation through critique or test",
        ],
        "Apply whiteboard challenge by mapping the user flow, defining hierarchy and copy, designing empty/loading/error/success states, and testing the riskiest interaction.",
        "whiteboard challenge benefits from fast low-fidelity exploration, but complex interactions need prototype fidelity high enough to reveal timing and state problems.",
        "If users hesitate around whiteboard challenge, inspect labels, grouping, visual weight, affordances, spacing, error text, and whether the primary action matches the user goal.",
        "Timed script: clarify users/goals \u2192 assumptions \u2192 happy flow \u2192 2 edge cases \u2192 success metric \u2192 summarize trade-off in 2 minutes.",
        "1) Map the target task 2) Sketch or prototype key states 3) Review hierarchy and accessibility 4) Validate the risky step.",
    ),
}

