#!/usr/bin/env python3
"""Expand AI track catalogs: tools, prompt recipes, failure issues, topics, interviews, decisions."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATE = "2026-09-16"


def write_json(path: Path, data: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def topic_mdx(
    *,
    tid: str,
    title: str,
    title_bn: str,
    description: str,
    description_bn: str,
    category: str,
    difficulty: str,
    minutes: int,
    prerequisites: list[str],
    related: list[str],
    tags: list[str],
    sources: list[str],
    body: str,
    track: str = "ai-framework",
) -> str:
    prereq = "\n".join(f'  - "{p}"' for p in prerequisites) or "[]"
    if prerequisites:
        prereq_block = "prerequisites:\n" + "\n".join(f'  - "{p}"' for p in prerequisites)
    else:
        prereq_block = "prerequisites: []"
    related_block = "\n".join(f'  - "{r}"' for r in related)
    tags_block = "\n".join(f'  - "{t}"' for t in tags)
    sources_block = "\n".join(f'  - "{s}"' for s in sources)
    return f"""---
id: {tid}
title: "{title}"
titleBn: "{title_bn}"
description: "{description}"
descriptionBn: "{description_bn}"
track: {track}
category: {category}
difficulty: {difficulty}
estimatedMinutes: {minutes}
{prereq_block}
unlocks: []
related:
{related_block}
careers:
  - "software-engineer"
tags:
{tags_block}
status: published
translationStatus: partial
createdAt: "{DATE}"
updatedAt: "{DATE}"
lastVerified: "{DATE}"
sources:
{sources_block}
contributors:
  - name: "Dev Turning Point"
---

import Callout from '../../../components/content/Callout.astro';

{body}
"""


TOOLS = [
    {
        "id": "AI-TOOL-OPENAI-CODEX",
        "name": "OpenAI Codex / coding agents",
        "category": "coding-agents",
        "description": "OpenAI coding-agent surfaces that assist with repository tasks via model APIs and agent workflows.",
        "bestFor": ["API-driven coding assistance", "Teams already on OpenAI platform"],
        "notIdealFor": ["Offline-only environments", "Unreviewed production commits"],
        "prerequisites": ["AI-LLM-FUNDAMENTALS", "AI-PROMPT-ENGINEERING"],
        "officialUrl": "https://platform.openai.com/",
        "docsUrl": "https://platform.openai.com/docs",
        "languageEcosystem": ["multi-language"],
        "localOrCloud": "cloud",
        "openSourceStatus": "proprietary",
        "costModelSummary": "Usage-based API / product tiers; verify current pricing on OpenAI.",
        "securityNotes": ["Do not paste secrets", "Verify packages and APIs before install"],
        "relatedTopicIds": ["AI-CODING-AGENTS-CURSOR", "AI-PROMPT-ENGINEERING"],
        "relatedProjectIds": ["PBL-AI-B-002"],
    },
    {
        "id": "AI-TOOL-GITHUB-COPILOT",
        "name": "GitHub Copilot",
        "category": "coding-agents",
        "description": "IDE-integrated coding assistant tightly coupled with GitHub workflows and PR review features.",
        "bestFor": ["Inline completion in IDEs", "GitHub-centric teams"],
        "notIdealFor": ["Deep multi-file agent workflows without human verification"],
        "prerequisites": ["AI-PROMPT-ENGINEERING"],
        "officialUrl": "https://github.com/features/copilot",
        "docsUrl": "https://docs.github.com/en/copilot",
        "languageEcosystem": ["multi-language"],
        "localOrCloud": "cloud",
        "openSourceStatus": "proprietary",
        "costModelSummary": "Subscription tiers; org policies may apply.",
        "securityNotes": ["Respect org content exclusion policies", "Review suggested code for authz bugs"],
        "relatedTopicIds": ["AI-CODING-AGENTS-CURSOR"],
        "relatedProjectIds": ["PBL-AI-B-002"],
    },
    {
        "id": "AI-TOOL-CLAUDE-CODE",
        "name": "Claude Code",
        "category": "coding-agents",
        "description": "Anthropic coding agent for terminal/repo workflows with strong reasoning models.",
        "bestFor": ["CLI-centric agent loops", "Anthropic-stack teams"],
        "notIdealFor": ["Blind autonomous production changes"],
        "prerequisites": ["AI-LLM-FUNDAMENTALS"],
        "officialUrl": "https://www.anthropic.com/",
        "docsUrl": "https://docs.anthropic.com/",
        "languageEcosystem": ["multi-language"],
        "localOrCloud": "cloud",
        "openSourceStatus": "proprietary",
        "costModelSummary": "Anthropic API / product usage; confirm current plans.",
        "securityNotes": ["Least-privilege tool access", "Human review of diffs"],
        "relatedTopicIds": ["AI-CODING-AGENTS-CURSOR", "AI-TOOL-CALLING"],
        "relatedProjectIds": ["PBL-AI-B-002"],
    },
    {
        "id": "AI-TOOL-OPENAI",
        "name": "OpenAI API",
        "category": "model-providers",
        "description": "Hosted models, embeddings, structured outputs, and tool calling via OpenAI platform APIs.",
        "bestFor": ["Chat/completions with schemas", "Embeddings for RAG prototypes"],
        "notIdealFor": ["Fully air-gapped deployments without alternatives"],
        "prerequisites": ["AI-LLM-FUNDAMENTALS"],
        "officialUrl": "https://platform.openai.com/",
        "docsUrl": "https://platform.openai.com/docs",
        "languageEcosystem": ["Python", "TypeScript", "HTTP"],
        "localOrCloud": "cloud",
        "openSourceStatus": "proprietary",
        "costModelSummary": "Per-token / usage billing; warn before paid calls.",
        "securityNotes": ["Never expose API keys in frontend", "Log redaction for prompts"],
        "relatedTopicIds": ["AI-LLM-FUNDAMENTALS", "AI-STRUCTURED-OUTPUTS"],
        "relatedProjectIds": ["PBL-AI-B-001", "PBL-AI-B-003"],
    },
    {
        "id": "AI-TOOL-ANTHROPIC",
        "name": "Anthropic API",
        "category": "model-providers",
        "description": "Claude models with tool use, long context, and safety-oriented guidance.",
        "bestFor": ["Tool-using assistants", "Long-document reasoning"],
        "notIdealFor": ["Local-only inference"],
        "prerequisites": ["AI-LLM-FUNDAMENTALS"],
        "officialUrl": "https://www.anthropic.com/",
        "docsUrl": "https://docs.anthropic.com/",
        "languageEcosystem": ["Python", "TypeScript", "HTTP"],
        "localOrCloud": "cloud",
        "openSourceStatus": "proprietary",
        "costModelSummary": "Usage-based; confirm pricing before production.",
        "securityNotes": ["Treat tool results as untrusted input", "Key management via server env"],
        "relatedTopicIds": ["AI-TOOL-CALLING", "AI-SECURITY-OWASP"],
        "relatedProjectIds": ["PBL-AI-I-002"],
    },
    {
        "id": "AI-TOOL-GEMINI",
        "name": "Google Gemini API",
        "category": "model-providers",
        "description": "Google Gemini developer APIs for multimodal and generative applications.",
        "bestFor": ["Multimodal prototypes", "Google Cloud adjacent stacks"],
        "notIdealFor": ["Vendor-neutral local-only requirements"],
        "prerequisites": ["AI-LLM-FUNDAMENTALS", "AI-MULTIMODAL"],
        "officialUrl": "https://ai.google.dev/",
        "docsUrl": "https://ai.google.dev/gemini-api/docs",
        "languageEcosystem": ["Python", "TypeScript", "HTTP"],
        "localOrCloud": "cloud",
        "openSourceStatus": "proprietary",
        "costModelSummary": "Google AI / Cloud billing depending on product surface.",
        "securityNotes": ["Review data residency options", "Validate multimodal inputs"],
        "relatedTopicIds": ["AI-MULTIMODAL"],
        "relatedProjectIds": ["PBL-AI-I-003"],
    },
    {
        "id": "AI-TOOL-VERCEL-AI-SDK",
        "name": "Vercel AI SDK",
        "category": "application-frameworks",
        "description": "TypeScript SDK for streaming UI, providers, and tooling around LLM apps on the web.",
        "bestFor": ["Next.js/React streaming chat UIs", "Multi-provider TypeScript apps"],
        "notIdealFor": ["Heavy Python data-science pipelines"],
        "prerequisites": ["AI-LLM-FUNDAMENTALS"],
        "officialUrl": "https://sdk.vercel.ai/",
        "docsUrl": "https://sdk.vercel.ai/docs",
        "languageEcosystem": ["TypeScript"],
        "localOrCloud": "both",
        "openSourceStatus": "open-source",
        "costModelSummary": "SDK free; model/provider costs separate.",
        "securityNotes": ["Keep keys server-side", "Validate tool calls"],
        "relatedTopicIds": ["AI-FRAMEWORKS-LANDSCAPE"],
        "relatedProjectIds": ["PBL-AI-B-003"],
    },
    {
        "id": "AI-TOOL-LANGCHAIN",
        "name": "LangChain",
        "category": "application-frameworks",
        "description": "Composable building blocks for LLM apps (chains, retrievers, tools) across Python/JS.",
        "bestFor": ["Rapid RAG prototypes", "Integrating many connectors"],
        "notIdealFor": ["Understanding AI fundamentals before APIs", "Ultra-minimal single-call apps"],
        "prerequisites": ["AI-LLM-FUNDAMENTALS", "AI-PROMPT-ENGINEERING"],
        "officialUrl": "https://www.langchain.com/",
        "docsUrl": "https://python.langchain.com/docs/",
        "languageEcosystem": ["Python", "TypeScript"],
        "localOrCloud": "both",
        "openSourceStatus": "open-source",
        "costModelSummary": "Open-source core; hosted LangSmith optional.",
        "securityNotes": ["Abstraction can hide data flows—trace them", "Pin versions"],
        "relatedTopicIds": ["AI-FRAMEWORKS-LANDSCAPE", "AI-RAG-FUNDAMENTALS"],
        "relatedProjectIds": ["PBL-AI-I-001"],
    },
    {
        "id": "AI-TOOL-LANGGRAPH",
        "name": "LangGraph",
        "category": "application-frameworks",
        "description": "Graph/stateful orchestration for multi-step agents with durable workflows.",
        "bestFor": ["Stateful agents", "Human-in-the-loop checkpoints"],
        "notIdealFor": ["One-shot classification APIs"],
        "prerequisites": ["AI-TOOL-CALLING", "AI-AGENTS-OVERVIEW"],
        "officialUrl": "https://www.langchain.com/langgraph",
        "docsUrl": "https://langchain-ai.github.io/langgraph/",
        "languageEcosystem": ["Python", "TypeScript"],
        "localOrCloud": "both",
        "openSourceStatus": "open-source",
        "costModelSummary": "Open-source; infra/hosting separate.",
        "securityNotes": ["Bound tool permissions", "Persist state carefully across tenants"],
        "relatedTopicIds": ["AI-AGENTS-OVERVIEW", "AI-MCP-INTRO"],
        "relatedProjectIds": ["PBL-AI-A-001"],
    },
    {
        "id": "AI-TOOL-LLAMAINDEX",
        "name": "LlamaIndex",
        "category": "application-frameworks",
        "description": "Data framework focused on indexing, retrieval, and RAG pipelines.",
        "bestFor": ["Document ingestion + retrieval apps", "Query engines over private data"],
        "notIdealFor": ["Pure frontend streaming without retrieval"],
        "prerequisites": ["AI-RAG-FUNDAMENTALS"],
        "officialUrl": "https://www.llamaindex.ai/",
        "docsUrl": "https://docs.llamaindex.ai/",
        "languageEcosystem": ["Python", "TypeScript"],
        "localOrCloud": "both",
        "openSourceStatus": "open-source",
        "costModelSummary": "Open-source core; cloud offerings optional.",
        "securityNotes": ["Tenant isolation in indexes", "Sanitize ingested documents"],
        "relatedTopicIds": ["AI-RAG-FUNDAMENTALS", "AI-VECTOR-DATABASES"],
        "relatedProjectIds": ["PBL-AI-I-001"],
    },
    {
        "id": "AI-TOOL-PYTORCH",
        "name": "PyTorch",
        "category": "ml-open-models",
        "description": "Deep learning framework for research and production training/inference stacks.",
        "bestFor": ["Training/custom models", "Research-to-prod ML pipelines"],
        "notIdealFor": ["Simple hosted chat wrappers"],
        "prerequisites": ["AI-FUNDAMENTALS-OVERVIEW"],
        "officialUrl": "https://pytorch.org/",
        "docsUrl": "https://pytorch.org/docs/",
        "languageEcosystem": ["Python"],
        "localOrCloud": "both",
        "openSourceStatus": "open-source",
        "costModelSummary": "Open-source; GPU infra costs apply.",
        "securityNotes": ["Validate model artifacts", "Pin CUDA/driver stacks"],
        "relatedTopicIds": ["AI-OPEN-MODELS"],
        "relatedProjectIds": ["PBL-AI-A-002"],
    },
    {
        "id": "AI-TOOL-HF-TRANSFORMERS",
        "name": "Hugging Face Transformers",
        "category": "ml-open-models",
        "description": "Library and Hub ecosystem for loading and running transformer models.",
        "bestFor": ["Open-model experimentation", "Standard NLP/multimodal pipelines"],
        "notIdealFor": ["Managed SaaS chat without ops ownership"],
        "prerequisites": ["AI-OPEN-MODELS"],
        "officialUrl": "https://huggingface.co/",
        "docsUrl": "https://huggingface.co/docs/transformers",
        "languageEcosystem": ["Python"],
        "localOrCloud": "both",
        "openSourceStatus": "open-source",
        "costModelSummary": "Library free; Hub/Inference endpoints may bill.",
        "securityNotes": ["Review model licenses", "Scan downloaded weights/sources"],
        "relatedTopicIds": ["AI-OPEN-MODELS"],
        "relatedProjectIds": ["PBL-AI-A-002"],
    },
    {
        "id": "AI-TOOL-HF-PEFT",
        "name": "Hugging Face PEFT",
        "category": "ml-open-models",
        "description": "Parameter-efficient fine-tuning (LoRA/PEFT) utilities for adapting models.",
        "bestFor": ["LoRA adapters", "Cost-aware fine-tuning experiments"],
        "notIdealFor": ["First-line RAG when retrieval suffices"],
        "prerequisites": ["AI-OPEN-MODELS"],
        "officialUrl": "https://huggingface.co/docs/peft",
        "docsUrl": "https://huggingface.co/docs/peft",
        "languageEcosystem": ["Python"],
        "localOrCloud": "both",
        "openSourceStatus": "open-source",
        "costModelSummary": "Open-source; training compute billed separately.",
        "securityNotes": ["Govern training data rights", "Evaluate for leakage"],
        "relatedTopicIds": ["AI-FINE-TUNING-BASICS"],
        "relatedProjectIds": ["PBL-AI-A-002"],
    },
    {
        "id": "AI-TOOL-OLLAMA",
        "name": "Ollama",
        "category": "ml-open-models",
        "description": "Local model runner for downloading and serving open models on developer machines.",
        "bestFor": ["Low/no-cost local experiments", "Privacy-sensitive prototypes"],
        "notIdealFor": ["High-QPS multi-tenant production without a serving stack"],
        "prerequisites": ["AI-OPEN-MODELS"],
        "officialUrl": "https://ollama.com/",
        "docsUrl": "https://github.com/ollama/ollama",
        "languageEcosystem": ["CLI", "HTTP"],
        "localOrCloud": "local",
        "openSourceStatus": "open-source",
        "costModelSummary": "Free software; hardware costs on you.",
        "securityNotes": ["Models stay local but still need output validation", "Do not grant shell tools lightly"],
        "relatedTopicIds": ["AI-OPEN-MODELS"],
        "relatedProjectIds": ["PBL-AI-A-002", "PBL-AI-B-001"],
    },
    {
        "id": "AI-TOOL-VLLM",
        "name": "vLLM",
        "category": "ml-open-models",
        "description": "High-throughput open-model serving engine for production-ish inference.",
        "bestFor": ["Self-hosted model APIs", "Batch/throughput-oriented serving"],
        "notIdealFor": ["Laptop-only learning without GPUs"],
        "prerequisites": ["AI-OPEN-MODELS", "AI-MODEL-SERVING"],
        "officialUrl": "https://github.com/vllm-project/vllm",
        "docsUrl": "https://docs.vllm.ai/",
        "languageEcosystem": ["Python"],
        "localOrCloud": "both",
        "openSourceStatus": "open-source",
        "costModelSummary": "Open-source; GPU cluster costs dominate.",
        "securityNotes": ["Auth front the serving API", "Resource quotas against unbounded consumption"],
        "relatedTopicIds": ["AI-MODEL-SERVING"],
        "relatedProjectIds": ["PBL-AI-A-002"],
    },
    {
        "id": "AI-TOOL-PGVECTOR",
        "name": "pgvector",
        "category": "retrieval",
        "description": "PostgreSQL extension for vector similarity search alongside relational data.",
        "bestFor": ["RAG with existing Postgres", "Strong transactional co-location"],
        "notIdealFor": ["Billion-scale ANN without careful ops"],
        "prerequisites": ["AI-EMBEDDINGS", "AI-RAG-FUNDAMENTALS"],
        "officialUrl": "https://github.com/pgvector/pgvector",
        "docsUrl": "https://github.com/pgvector/pgvector",
        "languageEcosystem": ["SQL", "PostgreSQL"],
        "localOrCloud": "both",
        "openSourceStatus": "open-source",
        "costModelSummary": "Extension free; Postgres hosting costs apply.",
        "securityNotes": ["Row-level security for tenants", "Index/embedding freshness"],
        "relatedTopicIds": ["AI-VECTOR-DATABASES", "AI-RAG-FUNDAMENTALS"],
        "relatedProjectIds": ["PBL-AI-I-001", "PBL-AI-A-003"],
    },
    {
        "id": "AI-TOOL-PINECONE",
        "name": "Pinecone",
        "category": "retrieval",
        "description": "Managed vector database service for similarity search at scale.",
        "bestFor": ["Managed vector ops", "Teams avoiding self-host ANN"],
        "notIdealFor": ["Strict all-data-in-Postgres constraints"],
        "prerequisites": ["AI-VECTOR-DATABASES"],
        "officialUrl": "https://www.pinecone.io/",
        "docsUrl": "https://docs.pinecone.io/",
        "languageEcosystem": ["Python", "TypeScript"],
        "localOrCloud": "cloud",
        "openSourceStatus": "proprietary",
        "costModelSummary": "Hosted billing; warn before paid usage.",
        "securityNotes": ["Namespace isolation", "API key rotation"],
        "relatedTopicIds": ["AI-VECTOR-DATABASES"],
        "relatedProjectIds": ["PBL-AI-I-001"],
    },
    {
        "id": "AI-TOOL-WEAVIATE",
        "name": "Weaviate",
        "category": "retrieval",
        "description": "Open-source vector database with hybrid search and modular vectorizers.",
        "bestFor": ["Hybrid search stacks", "Self-host or cloud Weaviate"],
        "notIdealFor": ["Tiny demos where Postgres+pgvector is enough"],
        "prerequisites": ["AI-VECTOR-DATABASES"],
        "officialUrl": "https://weaviate.io/",
        "docsUrl": "https://weaviate.io/developers/weaviate",
        "languageEcosystem": ["Python", "TypeScript", "Go"],
        "localOrCloud": "both",
        "openSourceStatus": "open-source",
        "costModelSummary": "OSS + optional cloud.",
        "securityNotes": ["Auth modules", "Multi-tenant class design"],
        "relatedTopicIds": ["AI-VECTOR-DATABASES"],
        "relatedProjectIds": ["PBL-AI-I-001"],
    },
    {
        "id": "AI-TOOL-QDRANT",
        "name": "Qdrant",
        "category": "retrieval",
        "description": "Vector similarity engine with filtering and payload storage.",
        "bestFor": ["Filtered ANN", "Rust-backed self-host search"],
        "notIdealFor": ["When relational joins dominate every query"],
        "prerequisites": ["AI-VECTOR-DATABASES"],
        "officialUrl": "https://qdrant.tech/",
        "docsUrl": "https://qdrant.tech/documentation/",
        "languageEcosystem": ["Python", "TypeScript", "Rust"],
        "localOrCloud": "both",
        "openSourceStatus": "open-source",
        "costModelSummary": "OSS + cloud options.",
        "securityNotes": ["API keys", "Collection isolation"],
        "relatedTopicIds": ["AI-VECTOR-DATABASES"],
        "relatedProjectIds": ["PBL-AI-I-001"],
    },
    {
        "id": "AI-TOOL-CHROMA",
        "name": "Chroma",
        "category": "retrieval",
        "description": "Developer-friendly embedding database popular for local RAG prototypes.",
        "bestFor": ["Local RAG notebooks", "Fast prototyping"],
        "notIdealFor": ["Hard multi-tenant production without extra controls"],
        "prerequisites": ["AI-EMBEDDINGS"],
        "officialUrl": "https://www.trychroma.com/",
        "docsUrl": "https://docs.trychroma.com/",
        "languageEcosystem": ["Python", "TypeScript"],
        "localOrCloud": "both",
        "openSourceStatus": "open-source",
        "costModelSummary": "OSS; hosted tiers optional.",
        "securityNotes": ["Do not treat local demo stores as production isolation"],
        "relatedTopicIds": ["AI-VECTOR-DATABASES", "AI-RAG-FUNDAMENTALS"],
        "relatedProjectIds": ["PBL-AI-I-001"],
    },
    {
        "id": "AI-TOOL-FAISS",
        "name": "FAISS",
        "category": "retrieval",
        "description": "Facebook AI Similarity Search library for efficient vector indexes.",
        "bestFor": ["Custom ANN research", "Offline index experiments"],
        "notIdealFor": ["Turnkey multi-user SaaS without a service layer"],
        "prerequisites": ["AI-EMBEDDINGS"],
        "officialUrl": "https://github.com/facebookresearch/faiss",
        "docsUrl": "https://github.com/facebookresearch/faiss/wiki",
        "languageEcosystem": ["Python", "C++"],
        "localOrCloud": "local",
        "openSourceStatus": "open-source",
        "costModelSummary": "Open-source; your hardware.",
        "securityNotes": ["Index files may contain sensitive embeddings"],
        "relatedTopicIds": ["AI-VECTOR-DATABASES"],
        "relatedProjectIds": ["PBL-AI-A-002"],
    },
    {
        "id": "AI-TOOL-LANGSMITH",
        "name": "LangSmith",
        "category": "evaluation-observability",
        "description": "Tracing, datasets, and evaluation tooling for LLM applications.",
        "bestFor": ["Trace debugging", "Eval datasets for RAG/agents"],
        "notIdealFor": ["Offline-only classrooms without accounts"],
        "prerequisites": ["AI-EVALUATION-BASICS"],
        "officialUrl": "https://www.langchain.com/langsmith",
        "docsUrl": "https://docs.smith.langchain.com/",
        "languageEcosystem": ["Python", "TypeScript"],
        "localOrCloud": "cloud",
        "openSourceStatus": "proprietary",
        "costModelSummary": "Hosted product tiers; warn before paid usage.",
        "securityNotes": ["Prompt logs may contain PII", "Control retention"],
        "relatedTopicIds": ["AI-EVALUATION-BASICS", "AI-LLMOPS"],
        "relatedProjectIds": ["PBL-AI-I-001", "PBL-AI-A-001"],
    },
    {
        "id": "AI-TOOL-MLFLOW",
        "name": "MLflow",
        "category": "evaluation-observability",
        "description": "Open experiment tracking and model lifecycle tooling adaptable to LLMOps.",
        "bestFor": ["Experiment tracking", "Model registry habits"],
        "notIdealFor": ["Pure chat UI without offline experiments"],
        "prerequisites": ["AI-EVALUATION-BASICS"],
        "officialUrl": "https://mlflow.org/",
        "docsUrl": "https://mlflow.org/docs/latest/index.html",
        "languageEcosystem": ["Python"],
        "localOrCloud": "both",
        "openSourceStatus": "open-source",
        "costModelSummary": "OSS; hosting optional.",
        "securityNotes": ["Artifact stores hold sensitive data"],
        "relatedTopicIds": ["AI-LLMOPS"],
        "relatedProjectIds": ["PBL-AI-A-002"],
    },
    {
        "id": "AI-TOOL-OPENAI-EVALS",
        "name": "OpenAI evaluation tooling",
        "category": "evaluation-observability",
        "description": "OpenAI-oriented evaluation patterns and tooling for measuring model/task quality.",
        "bestFor": ["Prompt/regression evals on OpenAI models"],
        "notIdealFor": ["Vendor-neutral open-model-only labs without adapters"],
        "prerequisites": ["AI-EVALUATION-BASICS"],
        "officialUrl": "https://platform.openai.com/docs",
        "docsUrl": "https://platform.openai.com/docs/guides/evals",
        "languageEcosystem": ["Python", "HTTP"],
        "localOrCloud": "cloud",
        "openSourceStatus": "mixed",
        "costModelSummary": "Eval runs consume API usage.",
        "securityNotes": ["Dataset privacy", "Do not leak customer data into shared evals"],
        "relatedTopicIds": ["AI-EVALUATION-BASICS"],
        "relatedProjectIds": ["PBL-AI-B-001"],
    },
    {
        "id": "AI-TOOL-MCP",
        "name": "Model Context Protocol (MCP)",
        "category": "protocol",
        "description": "Open protocol connecting LLM apps to tools and data sources with negotiated capabilities.",
        "bestFor": ["Standardizing tool integrations", "IDE/agent tool ecosystems"],
        "notIdealFor": ["Replacing application authz"],
        "prerequisites": ["AI-TOOL-CALLING", "AI-AGENTS-OVERVIEW"],
        "officialUrl": "https://modelcontextprotocol.io/",
        "docsUrl": "https://modelcontextprotocol.io/specification/2026-07-28",
        "languageEcosystem": ["TypeScript", "Python", "multi"],
        "localOrCloud": "both",
        "openSourceStatus": "protocol",
        "costModelSummary": "Protocol free; servers/tools may have costs.",
        "securityNotes": ["Least privilege tools", "Treat tool outputs as untrusted", "Spec version: 2026-07-28"],
        "relatedTopicIds": ["AI-MCP-INTRO", "AI-SECURITY-OWASP"],
        "relatedProjectIds": ["PBL-AI-A-001"],
    },
    {
        "id": "AI-TOOL-FASTAPI",
        "name": "FastAPI",
        "category": "backend",
        "description": "Python web framework commonly used to expose AI services with typed schemas.",
        "bestFor": ["AI backend APIs", "OpenAPI-first services"],
        "notIdealFor": ["Static marketing sites"],
        "prerequisites": ["AI-LLM-FUNDAMENTALS"],
        "officialUrl": "https://fastapi.tiangolo.com/",
        "docsUrl": "https://fastapi.tiangolo.com/",
        "languageEcosystem": ["Python"],
        "localOrCloud": "both",
        "openSourceStatus": "open-source",
        "costModelSummary": "Open-source; hosting separate.",
        "securityNotes": ["Authn/z on every route", "Never return raw model output into HTML without encoding"],
        "relatedTopicIds": ["AI-ASSISTED-BACKEND"],
        "relatedProjectIds": ["PBL-AI-I-002", "PBL-AI-A-003"],
    },
]

for t in TOOLS:
    t["lastVerified"] = DATE
    t["status"] = "published"


def recipe(
    rid: str,
    title: str,
    track: str,
    task_type: str,
    difficulty: str,
    when: str,
    when_not: str,
    inputs: list[str],
    template: str,
    bad: str,
    improved: str,
    expected: str,
    verify: list[str],
    failures: list[str],
    privacy: list[str],
    tools: list[str],
    topics: list[str],
    projects: list[str],
) -> dict:
    return {
        "id": rid,
        "title": title,
        "track": track,
        "taskType": task_type,
        "difficulty": difficulty,
        "whenToUse": when,
        "whenNotToUse": when_not,
        "requiredInputs": inputs,
        "promptTemplate": template,
        "badPrompt": bad,
        "improvedPrompt": improved,
        "expectedOutput": expected,
        "verificationChecklist": verify,
        "failureModes": failures,
        "privacySecurityNotes": privacy,
        "relatedTools": tools,
        "relatedTopics": topics,
        "relatedProjects": projects,
        "lastVerified": DATE,
        "status": "published",
    }


GOAL_TMPL = """GOAL:
{goal}

CONTEXT:
{context}

INPUT:
{inp}

CONSTRAINTS:
{constraints}

OUTPUT:
{output}

ACCEPTANCE:
{acceptance}

VERIFICATION:
{verification}"""

RECIPES = [
    recipe(
        "PROMPT-PLAN-FEATURE",
        "Plan a feature",
        "ai-framework",
        "planning",
        "beginner",
        "You need a bounded implementation plan before coding.",
        "The change is a one-line typo fix.",
        ["Requirement", "Repo map"],
        GOAL_TMPL.format(
            goal="Produce a milestone plan for {{feature}} without writing code yet.",
            context="Stack: {{stack}}. Non-goals: {{nongoals}}.",
            inp="Relevant files/paths: {{paths}}.",
            constraints="- No file edits\n- Call out risks\n- Prefer smallest slice first",
            output="Milestones, files touched, tests, risks",
            acceptance="A junior can implement milestone 1 without guessing scope.",
            verification="List assumptions and files that justify each milestone.",
        ),
        "Add the feature somehow.",
        "GOAL: Plan checkout coupon feature only.\nCONTEXT: Next.js + Nest; no payment provider change.\nCONSTRAINTS: Read-only; 3 milestones max.\nOUTPUT: milestones + tests.\nVERIFICATION: cite files.",
        "A short milestone plan with risks and tests.",
        ["No code changes", "Milestones are ordered", "Non-goals explicit"],
        ["Scope creep into redesign", "Invented APIs"],
        ["Do not paste customer PII"],
        ["AI-TOOL-CURSOR"],
        ["AI-PROMPT-ENGINEERING", "AI-CODING-AGENTS-CURSOR"],
        ["PBL-AI-B-002"],
    ),
    recipe(
        "PROMPT-IMPLEMENT-MILESTONE",
        "Implement one milestone",
        "ai-framework",
        "implementation",
        "beginner",
        "You already have a plan and want a single slice.",
        "You ask for the entire product in one shot.",
        ["Milestone text", "Acceptance criteria"],
        GOAL_TMPL.format(
            goal="Implement ONLY milestone {{milestoneId}}: {{milestoneTitle}}.",
            context="Follow existing patterns in {{paths}}.",
            inp="Acceptance: {{acceptance}}.",
            constraints="- No unrelated refactors\n- No new deps unless justified and verified\n- Keep diff reviewable",
            output="Code changes + how to test",
            acceptance="Milestone validation checklist passes.",
            verification="Commands to run + expected evidence.",
        ),
        "Build everything in the plan now.",
        "Implement only M01 auth middleware; do not touch UI; no new packages; show test command.",
        "A small diff with test steps.",
        ["Diff limited to milestone", "Dependencies verified", "Tests listed"],
        ["Silent dependency upgrades", "Overbroad refactor"],
        ["No secrets in prompts"],
        ["AI-TOOL-CURSOR"],
        ["AI-CODING-AGENTS-CURSOR"],
        ["PBL-AI-B-002"],
    ),
    recipe(
        "PROMPT-DEBUG-BUG",
        "Debug a bug",
        "ai-framework",
        "debugging",
        "intermediate",
        "You have reproducible symptoms and need a hypothesis loop.",
        "You only have a vague “it feels slow.”",
        ["Symptoms", "Reproduction steps", "Logs"],
        GOAL_TMPL.format(
            goal="Debug {{bug}} with hypotheses, not random rewrites.",
            context="Observed: {{symptoms}}. Environment: {{env}}.",
            inp="Repro steps: {{repro}}. Logs: {{logs}}.",
            constraints="- Propose <=3 hypotheses\n- Ask for one experiment at a time\n- No massive rewrites first",
            output="Hypotheses, experiment, expected evidence",
            acceptance="Root cause linked to evidence.",
            verification="Which log/test proves it.",
        ),
        "Fix whatever is wrong.",
        "Hypothesize why 500 on /checkout when cart empty; propose one experiment; no rewrite.",
        "Ordered hypotheses with evidence plan.",
        ["Hypotheses falsifiable", "No drive-by refactors"],
        ["Fabricated stack traces", "Fixing symptoms only"],
        ["Redact tokens from logs"],
        ["AI-TOOL-CURSOR"],
        ["AI-CODING-AGENTS-CURSOR", "AI-SECURITY-OWASP"],
        ["PBL-AI-B-002"],
    ),
    recipe(
        "PROMPT-SAFE-REFACTOR",
        "Refactor safely",
        "ai-framework",
        "refactor",
        "intermediate",
        "Behavior must stay identical while structure improves.",
        "You are mid-feature and lack tests.",
        ["Target files", "Invariant tests"],
        GOAL_TMPL.format(
            goal="Refactor {{target}} with zero behavior change.",
            context="Tests that must stay green: {{tests}}.",
            inp="Smell: {{smell}}.",
            constraints="- No API changes\n- Keep commits semantic\n- Stop if tests fail",
            output="Plan + incremental steps",
            acceptance="Same tests pass; diff is structural.",
            verification="Run listed tests yourself.",
        ),
        "Clean up the whole repo style.",
        "Extract validation helper in auth module only; keep public API; run unit tests.",
        "Incremental refactor plan.",
        ["Behavior preserved", "Scope bounded"],
        ["Mixing features into refactor"],
        ["Do not include production data dumps"],
        ["AI-TOOL-CURSOR"],
        ["AI-CODING-AGENTS-CURSOR"],
        ["PBL-AI-B-002"],
    ),
    recipe(
        "PROMPT-REVIEW-DIFF",
        "Review branch/diff",
        "ai-framework",
        "code-review",
        "intermediate",
        "Before merge, need risk-focused review.",
        "Diff is empty.",
        ["Diff or PR URL", "Acceptance criteria"],
        GOAL_TMPL.format(
            goal="Review this diff for correctness, security, and scope.",
            context="Acceptance: {{acceptance}}.",
            inp="{{diff}}",
            constraints="- Cite file:line\n- Separate blocking vs nit\n- Flag invented APIs/deps",
            output="Findings table + residual risks",
            acceptance="Blocking issues actionable.",
            verification="Each finding cites evidence.",
        ),
        "LGTM",
        "Review for authz gaps and new dependencies; blocking vs nit; cite paths.",
        "Structured review notes.",
        ["Findings cited", "Secrets checked"],
        ["Rubber-stamp approval"],
        ["Do not paste secrets from .env"],
        ["AI-TOOL-CURSOR"],
        ["AI-SECURITY-OWASP", "AI-CODING-AGENTS-CURSOR"],
        ["PBL-AI-B-002"],
    ),
    recipe(
        "PROMPT-GENERATE-TESTS",
        "Generate tests",
        "ai-framework",
        "testing",
        "intermediate",
        "You need regression tests for a known behavior.",
        "You want tests that merely assert mocks without behavior.",
        ["Function/module under test", "Failure cases"],
        GOAL_TMPL.format(
            goal="Write tests for {{unit}} covering happy + failure paths.",
            context="Framework: {{testFramework}}.",
            inp="Behaviors: {{behaviors}}.",
            constraints="- Prefer real behavior over overmocked units\n- Name tests by behavior",
            output="Test code + how to run",
            acceptance="Fails if bug reintroduced.",
            verification="Run tests; show output.",
        ),
        "Add some tests.",
        "Add Vitest cases for empty cart 400 and success 200; no snapshot-only asserts.",
        "Focused regression tests.",
        ["Failure path covered", "Command provided"],
        ["Tests pass for wrong reason", "Overmocking"],
        ["No production PII in fixtures"],
        ["AI-TOOL-CURSOR"],
        ["AI-ASSISTED-QA"],
        ["PBL-AI-B-001"],
    ),
    recipe(
        "PROMPT-SECURITY-REVIEW",
        "Security review",
        "ai-framework",
        "security",
        "advanced",
        "Authn/z, injection, secrets, and AI-specific risks need review.",
        "Cosmetic UI polish only.",
        ["Diff", "Trust boundaries"],
        GOAL_TMPL.format(
            goal="Security review of {{surface}} using OWASP GenAI + classic web risks.",
            context="Trust boundaries: {{boundaries}}.",
            inp="{{diff}}",
            constraints="- Check authn/z, injection, secrets, prompt injection, tool over-permission",
            output="Findings with severity",
            acceptance="Blocking issues listed with fix direction.",
            verification="Cite OWASP themes where relevant.",
        ),
        "Is this secure?",
        "Review for prompt injection, tool agency, XSS from model HTML, and missing authz on /admin.",
        "Severity-ranked security findings.",
        ["OWASP themes mapped", "Evidence cited"],
        ["False confidence", "Ignoring tool permissions"],
        ["Never paste live credentials"],
        ["AI-TOOL-CURSOR"],
        ["AI-SECURITY-OWASP"],
        ["PBL-AI-A-003"],
    ),
    recipe(
        "PROMPT-DB-MIGRATION-REVIEW",
        "DB migration review",
        "database",
        "database",
        "advanced",
        "Before applying a migration in shared environments.",
        "Toy local schema with no data.",
        ["Migration SQL", "Rollback plan"],
        GOAL_TMPL.format(
            goal="Review migration {{name}} for safety and rollback.",
            context="DB: {{engine}}. Table sizes if known: {{sizes}}.",
            inp="{{sql}}",
            constraints="- Flag locks, destructive drops, missing rollback",
            output="Risks + safer sequence",
            acceptance="Rollback path exists or explicitly impossible with reason.",
            verification="EXPLAIN/lock notes where relevant.",
        ),
        "Ship the migration.",
        "Review ALTER for ACCESS EXCLUSIVE locks; propose expand/contract; require rollback notes.",
        "Migration risk review.",
        ["Lock risks noted", "Rollback addressed"],
        ["Destructive SQL unnoticed"],
        ["No prod dumps in prompt"],
        ["AI-TOOL-CURSOR"],
        ["AI-ASSISTED-DATABASE"],
        [],
    ),
    recipe(
        "PROMPT-SQL-EXPLAIN",
        "SQL/EXPLAIN analysis",
        "database",
        "database",
        "intermediate",
        "Query is slow or suspicious.",
        "No EXPLAIN output available and you invent one.",
        ["Query", "EXPLAIN plan"],
        GOAL_TMPL.format(
            goal="Interpret EXPLAIN for {{queryPurpose}}.",
            context="Engine: {{engine}}.",
            inp="SQL + EXPLAIN: {{explain}}",
            constraints="- Do not invent plans\n- Propose indexes carefully",
            output="Bottleneck + next experiment",
            acceptance="Advice tied to actual plan nodes.",
            verification="Cite plan lines.",
        ),
        "Make it fast.",
        "Given this EXPLAIN ANALYZE, identify seq scan cause and propose one index experiment.",
        "Plan-grounded tuning advice.",
        ["Uses real EXPLAIN", "One experiment"],
        ["Fabricated plans"],
        ["Mask tenant data in samples"],
        ["AI-TOOL-CURSOR"],
        ["AI-ASSISTED-DATABASE"],
        [],
    ),
    recipe(
        "PROMPT-FLUTTER-BUG",
        "Flutter bug/build analysis",
        "mobile-flutter",
        "mobile",
        "intermediate",
        "Build/runtime Flutter errors need structured triage.",
        "You only say “app crashed.”",
        ["Error log", "Flutter/Dart versions"],
        GOAL_TMPL.format(
            goal="Diagnose Flutter issue: {{summary}}.",
            context="Versions: {{versions}}. Platform: {{platform}}.",
            inp="Logs: {{logs}}",
            constraints="- Separate build vs runtime\n- Prefer official Flutter docs over guesses",
            output="Root cause hypotheses + commands",
            acceptance="Next command is concrete.",
            verification="Expected log signature.",
        ),
        "Fix Flutter.",
        "Analyze Gradle/Xcode failure from this log; propose one command; no random dependency bumps.",
        "Flutter triage notes.",
        ["Platform identified", "Command listed"],
        ["Hallucinated Flutter APIs"],
        ["No signing secrets in prompt"],
        ["AI-TOOL-CURSOR"],
        ["AI-ASSISTED-FLUTTER"],
        [],
    ),
    recipe(
        "PROMPT-FRONTEND-FIGMA",
        "Frontend from screenshot/Figma",
        "frontend",
        "frontend",
        "intermediate",
        "Implement UI matching design within design-system constraints.",
        "No design reference and you invent branding.",
        ["Screenshot/Figma link", "Design tokens"],
        GOAL_TMPL.format(
            goal="Implement UI for {{screen}} matching design.",
            context="Tokens/components: {{system}}.",
            inp="Reference: {{reference}}",
            constraints="- Reuse existing components\n- a11y labels\n- No new CSS framework",
            output="Component structure + a11y notes",
            acceptance="Visual + keyboard checks listed.",
            verification="Manual checklist.",
        ),
        "Make it pretty like the screenshot.",
        "Build pricing section using existing Button/Stack; match spacing tokens; include focus states.",
        "Component plan with a11y.",
        ["Tokens reused", "a11y included"],
        ["Invented design system"],
        ["Do not upload confidential client screenshots to public models if policy forbids"],
        ["AI-TOOL-CURSOR"],
        ["AI-ASSISTED-FRONTEND"],
        [],
    ),
    recipe(
        "PROMPT-A11Y-REVIEW",
        "Accessibility review",
        "frontend",
        "accessibility",
        "intermediate",
        "Need WCAG-oriented review of a UI change.",
        "Pure backend SQL change.",
        ["Component code or URL", "Target level"],
        GOAL_TMPL.format(
            goal="a11y review of {{surface}} targeting {{level}}.",
            context="Framework: {{framework}}.",
            inp="{{codeOrUrl}}",
            constraints="- Name, roles, keyboard, contrast notes\n- Prefer native semantics",
            output="Issues + fixes",
            acceptance="Blocking a11y issues listed.",
            verification="Suggest axe/keyboard checks.",
        ),
        "Is a11y fine?",
        "Review icon button names, dialog focus trap, and contrast on muted text.",
        "a11y findings.",
        ["Keyboard path covered", "Names checked"],
        ["ARIA overuse"],
        [],
        ["AI-TOOL-CURSOR"],
        ["AI-ASSISTED-FRONTEND", "AI-ASSISTED-UIUX"],
        [],
    ),
    recipe(
        "PROMPT-BACKEND-API-DESIGN",
        "Backend API design",
        "backend",
        "backend",
        "intermediate",
        "Design endpoints before coding.",
        "You already have a frozen contract.",
        ["Resources", "Auth model"],
        GOAL_TMPL.format(
            goal="Design REST/JSON API for {{resource}}.",
            context="Auth: {{auth}}. Idempotency needs: {{idem}}.",
            inp="Use cases: {{usecases}}",
            constraints="- Explicit status codes\n- Validation\n- No security theater",
            output="Endpoints, schemas, error model",
            acceptance="Client can integrate from the contract.",
            verification="List threat notes (authz).",
        ),
        "Make an API.",
        "Design /orders with idempotency-key, 409 conflicts, and role checks; no GraphQL unless justified.",
        "API contract draft.",
        ["Authz specified", "Errors specified"],
        ["Missing authz"],
        ["No real customer payloads"],
        ["AI-TOOL-CURSOR", "AI-TOOL-FASTAPI"],
        ["AI-ASSISTED-BACKEND"],
        [],
    ),
    recipe(
        "PROMPT-DEVOPS-IAC",
        "DevOps/IaC change",
        "devops",
        "devops",
        "advanced",
        "Infrastructure change needs blast-radius thinking.",
        "Cosmetic README edit.",
        ["IaC diff", "Environment"],
        GOAL_TMPL.format(
            goal="Review/propose IaC change for {{goal}}.",
            context="Env: {{env}}. Tool: {{tool}}.",
            inp="{{diff}}",
            constraints="- No destructive defaults\n- Require plan output\n- Secrets via secret store",
            output="Change plan + rollback",
            acceptance="Rollback stated.",
            verification="Plan/apply commands.",
        ),
        "Update infra.",
        "Add S3 bucket with block public access; show terraform plan expectations; no delete of prod state.",
        "IaC plan with rollback.",
        ["Blast radius clear", "Secrets not plaintext"],
        ["Destructive apply", "Fake commands"],
        ["No cloud keys in prompt"],
        ["AI-TOOL-CURSOR"],
        ["AI-ASSISTED-DEVOPS"],
        [],
    ),
    recipe(
        "PROMPT-CICD-CHANGE",
        "CI/CD change",
        "devops",
        "ci-cd",
        "intermediate",
        "Pipeline must stay safe and reproducible.",
        "Local-only scripts with no CI.",
        ["Workflow file", "Required checks"],
        GOAL_TMPL.format(
            goal="Adjust CI for {{goal}}.",
            context="Platform: {{ci}}.",
            inp="{{workflow}}",
            constraints="- Pin actions\n- No secrets in logs\n- Fail on lint/test",
            output="Patched workflow + rationale",
            acceptance="Required checks still gate merge.",
            verification="List jobs/steps.",
        ),
        "Fix CI somehow.",
        "Add typecheck job; pin action SHAs; do not print secrets; keep cache keys stable.",
        "CI patch proposal.",
        ["Pins present", "Secrets safe"],
        ["Unpinned actions"],
        [],
        ["AI-TOOL-CURSOR"],
        ["AI-ASSISTED-DEVOPS"],
        [],
    ),
    recipe(
        "PROMPT-INCIDENT-ANALYSIS",
        "Production incident analysis",
        "devops",
        "incident",
        "advanced",
        "You have timelines/metrics and need structured incident reasoning.",
        "No data and you invent root cause.",
        ["Timeline", "Metrics/logs"],
        GOAL_TMPL.format(
            goal="Analyze incident {{id}}.",
            context="SLO impact: {{slo}}.",
            inp="Timeline/logs: {{data}}",
            constraints="- Separate facts vs hypotheses\n- No blame language\n- Propose next probe",
            output="Facts, hypotheses, actions",
            acceptance="Next action is safe and specific.",
            verification="Cite timestamps/metrics.",
        ),
        "Why did prod die?",
        "Using this timeline, list facts vs hypotheses for elevated 5xx; propose one safe probe.",
        "Incident analysis notes.",
        ["Facts separated", "Safe next step"],
        ["Fabricated causes"],
        ["Redact customer data"],
        ["AI-TOOL-CURSOR"],
        ["AI-ASSISTED-DEVOPS"],
        [],
    ),
    recipe(
        "PROMPT-QA-TEST-PLAN",
        "QA test plan",
        "qa",
        "qa",
        "intermediate",
        "Need risk-based coverage for a release.",
        "You want infinite exhaustive testing with no priority.",
        ["Feature scope", "Risks"],
        GOAL_TMPL.format(
            goal="Draft risk-based test plan for {{feature}}.",
            context="Platforms: {{platforms}}.",
            inp="Risks: {{risks}}",
            constraints="- Prioritize by risk\n- Include negative cases\n- No fake pass claims",
            output="Cases + environments",
            acceptance="Highest risks covered first.",
            verification="Traceability to risks.",
        ),
        "Test everything.",
        "Plan checkout tests by payment failure, concurrency, and a11y; map to risks.",
        "Prioritized test plan.",
        ["Risks mapped", "Negative cases"],
        ["Checkbox theater"],
        [],
        ["AI-TOOL-CURSOR"],
        ["AI-ASSISTED-QA"],
        [],
    ),
    recipe(
        "PROMPT-PLAYWRIGHT-GEN",
        "Playwright generation",
        "qa",
        "qa-automation",
        "intermediate",
        "Automate a stable user journey.",
        "Highly flaky visual animations as first target.",
        ["User journey", "Selectors strategy"],
        GOAL_TMPL.format(
            goal="Generate Playwright test for {{journey}}.",
            context="App URL pattern: {{url}}.",
            inp="Steps: {{steps}}",
            constraints="- Prefer role/text selectors\n- Assert outcomes not implementation\n- Avoid sleeps",
            output="Test code + run command",
            acceptance="Fails if journey breaks.",
            verification="Run locally.",
        ),
        "Write Playwright magic.",
        "E2E login→add-to-cart→checkout success; use getByRole; no networkidle sleeps.",
        "Playwright test draft.",
        ["Stable selectors", "Outcome asserts"],
        ["Brittle CSS selectors"],
        ["No prod credentials"],
        ["AI-TOOL-CURSOR"],
        ["AI-ASSISTED-QA"],
        [],
    ),
    recipe(
        "PROMPT-UX-CRITIQUE",
        "UX critique",
        "uiux",
        "ux",
        "intermediate",
        "Critique a flow with heuristics—not invented user quotes.",
        "You need fabricated personas as “research.”",
        ["Flow description/screens", "Task goal"],
        GOAL_TMPL.format(
            goal="Heuristic critique of {{flow}} for task {{task}}.",
            context="Users: {{audience}} (assumptions labeled).",
            inp="{{screens}}",
            constraints="- No invented interview quotes\n- Separate observation vs recommendation",
            output="Issues + severity + redesign ideas",
            acceptance="Assumptions labeled.",
            verification="Each issue points to UI evidence.",
        ),
        "Users hate this.",
        "Critique onboarding for clarity and error recovery; label assumptions; no fake quotes.",
        "Heuristic critique.",
        ["Assumptions labeled", "No fake research"],
        ["Fabricated user research"],
        [],
        ["AI-TOOL-CURSOR"],
        ["AI-ASSISTED-UIUX"],
        [],
    ),
    recipe(
        "PROMPT-UX-RESEARCH-PLAN",
        "UX research-plan drafting",
        "uiux",
        "ux-research",
        "intermediate",
        "Structure a real research plan the human will execute.",
        "Asking the model to invent study results.",
        ["Research question", "Constraints"],
        GOAL_TMPL.format(
            goal="Draft research plan for {{question}}.",
            context="Constraints: {{constraints}}.",
            inp="Decisions to inform: {{decisions}}",
            constraints="- Do not invent findings\n- Methods must match question",
            output="Participants, script outline, analysis plan",
            acceptance="Human can run sessions from the plan.",
            verification="Success criteria for research quality—not product outcome claims.",
        ),
        "Tell me what users want.",
        "Plan 5 usability tests for save-invoice; do not invent results; include script and notes grid.",
        "Executable research plan.",
        ["No fabricated findings", "Method fits question"],
        ["Fake insights"],
        ["Privacy for participants"],
        ["AI-TOOL-CURSOR"],
        ["AI-ASSISTED-UIUX"],
        [],
    ),
    recipe(
        "PROMPT-PM-REQUIREMENTS",
        "Project requirement decomposition",
        "project-management",
        "pm",
        "beginner",
        "Turn a fuzzy brief into testable requirements.",
        "You need fake stakeholder approvals.",
        ["Brief", "Constraints"],
        GOAL_TMPL.format(
            goal="Decompose {{brief}} into requirements and risks.",
            context="Constraints: {{constraints}}.",
            inp="Stakeholders (roles only): {{roles}}",
            constraints="- No invented approvals/dates as facts\n- Mark assumptions",
            output="Must/Should/Could + risks + open questions",
            acceptance="Open questions are explicit.",
            verification="Each must-have is testable.",
        ),
        "Write the PRD as if approved.",
        "Decompose POS offline-mode brief; label assumptions; list risks; no fake sign-offs.",
        "Requirement breakdown.",
        ["Assumptions labeled", "Testable musts"],
        ["Fabricated approvals"],
        [],
        ["AI-TOOL-CURSOR"],
        ["AI-ASSISTED-PM"],
        ["PBL-AI-A-003"],
    ),
    recipe(
        "PROMPT-JIRA-BACKLOG",
        "Jira backlog drafting",
        "project-management",
        "pm",
        "beginner",
        "Draft stories from agreed requirements.",
        "Inventing velocity or commitments.",
        ["Requirements", "Definition of done"],
        GOAL_TMPL.format(
            goal="Draft backlog for {{epic}}.",
            context="DoD: {{dod}}.",
            inp="Requirements: {{reqs}}",
            constraints="- INVEST-ish stories\n- No fake estimates as facts\n- Acceptance criteria testable",
            output="Stories + AC + dependencies",
            acceptance="Dev can start story 1.",
            verification="AC checkable.",
        ),
        "Fill Jira with 40 points.",
        "Draft 5 stories for invoice export; AC only; mark estimate as TBD.",
        "Backlog draft.",
        ["AC present", "Estimates not faked as facts"],
        ["Fake commitments"],
        [],
        ["AI-TOOL-CURSOR"],
        ["AI-ASSISTED-PM"],
        [],
    ),
    recipe(
        "PROMPT-ADR-RESEARCH",
        "Architecture decision research",
        "ai-framework",
        "architecture",
        "advanced",
        "Compare options with criteria before committing.",
        "Popularity contests without criteria.",
        ["Problem", "Constraints"],
        GOAL_TMPL.format(
            goal="ADR research for {{decision}}.",
            context="Constraints: {{constraints}}.",
            inp="Options: {{options}}",
            constraints="- Criteria first\n- Cite official docs\n- Include reject reasons",
            output="ADR draft",
            acceptance="Decision reversible notes included.",
            verification="Links to official sources.",
        ),
        "Which is best?",
        "Compare pgvector vs managed vector DB for multi-tenant RAG; criteria: tenancy, ops, cost, lock-in.",
        "ADR draft with criteria.",
        ["Criteria explicit", "Sources official"],
        ["Vendor trivia"],
        [],
        ["AI-TOOL-CURSOR"],
        ["AI-FRAMEWORKS-LANDSCAPE", "AI-VECTOR-DATABASES"],
        ["PBL-AI-I-001"],
    ),
    recipe(
        "PROMPT-DOCS-GENERATION",
        "Documentation generation",
        "ai-framework",
        "documentation",
        "beginner",
        "Document what the code actually does.",
        "Inventing features that are not implemented.",
        ["Code paths", "Audience"],
        GOAL_TMPL.format(
            goal="Document {{component}} for {{audience}}.",
            context="Only describe existing behavior.",
            inp="Paths: {{paths}}",
            constraints="- No aspirational features\n- Mark unknowns",
            output="README section + examples",
            acceptance="Another eng can run it.",
            verification="Commands tested by human.",
        ),
        "Write amazing docs for the future vision.",
        "Document current auth middleware only; include run/test commands; mark unknowns.",
        "Accurate docs draft.",
        ["Matches code", "Commands listed"],
        ["Doc/code drift"],
        [],
        ["AI-TOOL-CURSOR"],
        ["AI-PROMPT-ENGINEERING"],
        [],
    ),
]


ISSUES = [
    ("issue-ai-hallucinated-api", "Hallucinated API/method", "Agent invents methods not in official SDK docs.", "Verify against official docs before use."),
    ("issue-ai-deprecated-api", "Deprecated API suggested", "Model recommends APIs marked deprecated.", "Check current docs/changelog; prefer supported APIs."),
    ("issue-ai-fake-command", "Fake CLI command", "Suggested shell command does not exist.", "Run --help / man; never trust unseen commands in prod."),
    ("issue-ai-fabricated-source", "Fabricated source/citation", "Model invents URLs or paper titles.", "Open every citation; discard unverifiable claims."),
    ("issue-ai-fabricated-test-result", "Fabricated test result claim", "Agent claims tests passed without running them.", "Require command output evidence."),
    ("issue-ai-overbroad-refactor", "Overbroad refactor", "Agent rewrites unrelated modules in a small task.", "Bound scope; reject drive-by changes."),
    ("issue-ai-duplicate-logic", "Duplicate existing logic", "Agent reimplements helpers already in repo.", "Search codebase first; reuse modules."),
    ("issue-ai-insecure-auth", "Insecure authentication suggestion", "Agent stores tokens insecurely or skips authn.", "Follow secure session/token patterns; security review."),
    ("issue-ai-missing-authz", "Missing authorization", "Endpoints protected only by obscurity.", "Explicit authz checks per resource."),
    ("issue-ai-destructive-sql", "Destructive SQL", "DROP/TRUNCATE without expand-contract.", "Require review + backups; reject silent data loss."),
    ("issue-ai-unsafe-shell", "Unsafe shell command", "rm -rf, curl|bash, or prod mutations.", "Deny high-risk tools; human approval gates."),
    ("issue-ai-prompt-injection-direct", "Direct prompt injection", "User text overrides system instructions.", "Separate untrusted input; harden instructions; monitor."),
    ("issue-ai-indirect-prompt-injection", "Indirect prompt injection", "Retrieved docs contain attacker instructions.", "Treat retrieved text as data; cite-only modes."),
    ("issue-ai-retrieval-poisoning", "Retrieval poisoning", "Poisoned corpus skews RAG answers.", "Govern ingestion; integrity checks; evals."),
    ("issue-ai-cross-tenant-rag", "Cross-tenant RAG leak", "Embeddings/search cross customer boundaries.", "Filter by tenant before retrieval; test isolation."),
    ("issue-ai-mcp-overpermission", "MCP/tool over-permission", "MCP server exposes shell/DB with broad rights.", "Least privilege; approve tools consciously."),
    ("issue-ai-improper-output-handling", "Improper model output handling", "Raw model HTML/SQL executed unsafely.", "Validate/encode; never eval untrusted output."),
    ("issue-ai-leaked-secrets", "Leaked secrets in prompts/logs", "API keys appear in chat logs or commits.", "Secret scanning; redaction; rotate keys."),
    ("issue-ai-runaway-loop", "Runaway agent loop", "Agent retries endlessly spending tokens.", "Max steps/budgets; circuit breakers."),
    ("issue-ai-excessive-cost", "Excessive API cost", "Unbounded prompts/retries (OWASP unbounded consumption).", "Token budgets; caching; rate limits."),
    ("issue-ai-stale-embeddings", "Stale embeddings", "Index not refreshed after docs change.", "Reindex pipeline; freshness metrics."),
    ("issue-ai-malformed-structured", "Malformed structured output", "JSON/schema violations break parsers.", "Use schema-constrained decoding + validation."),
    ("issue-ai-provider-outage", "Model/provider outage", "Upstream 5xx/timeouts cascade.", "Timeouts, fallbacks, graceful degradation."),
    ("issue-ai-incorrect-citation", "Incorrect citation mapping", "Answer cites wrong chunk IDs.", "Enforce citation=retrieved span checks."),
    ("issue-ai-ungrounded-answer", "Ungrounded answer", "Fluent answer without retrieval support.", "Refuse when retrieval empty; eval groundedness."),
]


def main() -> None:
    tools_dir = ROOT / "src/content/ai-tools"
    for t in TOOLS:
        write_json(tools_dir / f"{t['id'].lower().replace('_', '-')}.json".replace("ai-tool-", ""), t)
        # clearer filenames
    # rewrite with readable names
    for t in TOOLS:
        slug = t["id"].removeprefix("AI-TOOL-").lower().replace("_", "-")
        write_json(tools_dir / f"{slug}.json", t)

    recipes_dir = ROOT / "src/content/prompt-recipes"
    for r in RECIPES:
        slug = r["id"].removeprefix("PROMPT-").lower().replace("_", "-")
        write_json(recipes_dir / f"{slug}.json", r)

    issues_dir = ROOT / "src/content/issues"
    for iid, title, cause, solution in ISSUES:
        write_json(
            issues_dir / f"{iid}.json",
            {
                "id": iid,
                "title": title,
                "technology": "AI / GenAI",
                "platform": "Any",
                "symptoms": [cause],
                "cause": cause,
                "solution": solution,
                "status": "VERIFIED",
                "relatedTopics": ["AI-SECURITY-OWASP", "AI-CODING-AGENTS-CURSOR"],
                "sources": ["OWASP-LLM-TOP10-2025"],
                "lastVerified": DATE,
            },
        )

    # Decision guides data
    decisions = [
        {
            "id": "direct-sdk-vs-framework",
            "title": "Direct provider SDK vs AI framework",
            "problem": "You need to call a model from an app and wonder whether to adopt LangChain/LlamaIndex/etc. first.",
            "criteria": ["Orchestration complexity", "Team familiarity", "Debuggability", "Lock-in"],
            "tradeOffs": "Frameworks accelerate connectors; direct SDKs keep control and clearer data flow.",
            "complexity": "Low for direct SDK; medium+ for frameworks.",
            "lockIn": "Framework abstractions and vendor-specific helpers can increase switching cost.",
            "security": "Either path needs output validation and secret hygiene; frameworks can hide tool surfaces.",
            "cost": "Framework OSS is free; complexity cost dominates early.",
            "exampleScenarios": [
                "Single structured extraction call → direct SDK",
                "Many retrievers/tools evolving weekly → framework may help",
            ],
            "references": ["OPENAI-API-DOCS", "LANGCHAIN-DOCS", "VERCEL-AI-SDK-DOCS"],
            "lastVerified": DATE,
        },
        {
            "id": "langchain-vs-langgraph",
            "title": "LangChain vs LangGraph",
            "problem": "Choosing between chains/composables and stateful graph orchestration.",
            "criteria": ["Need for durable state", "Human-in-the-loop", "Branching workflows"],
            "tradeOffs": "LangChain helps compose; LangGraph models stateful agent graphs.",
            "complexity": "LangGraph higher upfront.",
            "lockIn": "Graph state shapes become core architecture.",
            "security": "Stateful agents amplify excessive agency risks.",
            "cost": "Infra for persistence/checkpoints.",
            "exampleScenarios": ["FAQ RAG → LangChain/retriever path", "Ops agent with approvals → LangGraph"],
            "references": ["LANGCHAIN-DOCS", "LANGGRAPH-DOCS"],
            "lastVerified": DATE,
        },
        {
            "id": "langchain-vs-llamaindex",
            "title": "LangChain vs LlamaIndex",
            "problem": "Picking a data/RAG-centric vs general orchestration framework.",
            "criteria": ["Indexing needs", "Query engine features", "Team stack"],
            "tradeOffs": "LlamaIndex strong on data indexes; LangChain broad integrations.",
            "complexity": "Similar mid-level.",
            "lockIn": "Index formats and abstractions.",
            "security": "Ingestion pipelines are trust boundaries.",
            "cost": "Similar OSS; hosting varies.",
            "exampleScenarios": ["Document knowledge base → LlamaIndex", "Mixed tools+RAG → either, criteria-based"],
            "references": ["LANGCHAIN-DOCS", "LLAMAINDEX-DOCS"],
            "lastVerified": DATE,
        },
        {
            "id": "vercel-ai-sdk-vs-direct",
            "title": "Vercel AI SDK vs direct SDK",
            "problem": "TypeScript app needs streaming chat UI.",
            "criteria": ["UI streaming helpers", "Provider switching", "Bundle/runtime constraints"],
            "tradeOffs": "AI SDK speeds UI patterns; direct SDK maximizes control.",
            "complexity": "AI SDK lower for Next.js chat.",
            "lockIn": "Helper APIs; providers still swappable.",
            "security": "Keep keys on server routes.",
            "cost": "SDK free; tokens billed by provider.",
            "exampleScenarios": ["Next.js assistant UI → AI SDK", "Minimal worker script → direct"],
            "references": ["VERCEL-AI-SDK-DOCS", "OPENAI-API-DOCS"],
            "lastVerified": DATE,
        },
        {
            "id": "pgvector-vs-dedicated",
            "title": "pgvector vs dedicated vector database",
            "problem": "Where to store embeddings for RAG.",
            "criteria": ["Scale", "Ops skill", "Transactional joins", "Tenancy"],
            "tradeOffs": "pgvector co-locates with SQL; dedicated engines optimize ANN ops.",
            "complexity": "pgvector lower if Postgres already owned.",
            "lockIn": "Managed vector vendors vs Postgres extension.",
            "security": "Row-level security vs namespace isolation models.",
            "cost": "Often cheaper to start on Postgres; scale may shift economics.",
            "exampleScenarios": ["SaaS with Postgres → pgvector first", "Billion vectors → evaluate dedicated"],
            "references": ["PGVECTOR-DOCS", "PINECONE-DOCS", "QDRANT-DOCS"],
            "lastVerified": DATE,
        },
        {
            "id": "hosted-vs-local",
            "title": "Hosted vs local/open model",
            "problem": "Privacy, cost, and quality trade-offs for inference.",
            "criteria": ["Data sensitivity", "Latency", "Ops capacity", "Quality bar"],
            "tradeOffs": "Hosted quality/ops ease vs local control/privacy.",
            "complexity": "Local/serving higher ops.",
            "lockIn": "Provider APIs vs self-host stack.",
            "security": "Data leaves boundary on hosted; local still needs output controls.",
            "cost": "Tokens vs GPUs.",
            "exampleScenarios": ["Homework labs → Ollama", "Peak SaaS traffic → hosted or vLLM"],
            "references": ["OLLAMA-DOCS", "VLLM-DOCS", "OPENAI-API-DOCS"],
            "lastVerified": DATE,
        },
        {
            "id": "rag-vs-finetune",
            "title": "RAG vs fine-tuning",
            "problem": "Knowledge freshness vs behavioral specialization.",
            "criteria": ["Doc churn", "Style/format needs", "Eval budget"],
            "tradeOffs": "RAG grounds facts; fine-tune shapes behavior—not a substitute for retrieval of changing docs.",
            "complexity": "Fine-tune higher data/ops cost.",
            "lockIn": "Adapter/base model choices.",
            "security": "Training data rights; retrieval poisoning for RAG.",
            "cost": "Fine-tune compute; RAG embedding+store.",
            "exampleScenarios": ["Policy PDFs that change weekly → RAG", "Consistent extraction style → maybe light tune + schemas"],
            "references": ["OWASP-LLM-TOP10-2025", "HF-PEFT-DOCS", "LLAMAINDEX-DOCS"],
            "lastVerified": DATE,
        },
        {
            "id": "workflow-vs-agent",
            "title": "Deterministic workflow vs agent",
            "problem": "When to let a model choose tools dynamically.",
            "criteria": ["Branch predictability", "Audit needs", "Failure cost"],
            "tradeOffs": "Deterministic workflows are testable; agents handle open-ended tasks with higher variance.",
            "complexity": "Agents harder to eval.",
            "lockIn": "Tool schemas and memory stores.",
            "security": "Excessive agency risk rises with agents.",
            "cost": "Agents can loop tokens.",
            "exampleScenarios": ["Invoice status machine → workflow", "Ops triage with many tools → constrained agent"],
            "references": ["LANGGRAPH-DOCS", "OWASP-LLM-TOP10-2025"],
            "lastVerified": DATE,
        },
        {
            "id": "langgraph-vs-app-workflow",
            "title": "LangGraph vs ordinary application workflow",
            "problem": "Whether graph agent framework beats explicit app code.",
            "criteria": ["State durability", "Team ownership", "Debugging"],
            "tradeOffs": "App workflows are transparent; LangGraph helps complex agent graphs.",
            "complexity": "Prefer simplest that meets needs.",
            "lockIn": "Framework state APIs.",
            "security": "Same tool permission rules either way.",
            "cost": "Engineering time vs infra.",
            "exampleScenarios": ["CRUD + one model call → app workflow", "Multi-actor agent with HITL → LangGraph"],
            "references": ["LANGGRAPH-DOCS"],
            "lastVerified": DATE,
        },
        {
            "id": "ollama-vs-vllm",
            "title": "Ollama vs vLLM",
            "problem": "Local DX versus production-ish serving.",
            "criteria": ["Throughput", "Ops maturity", "Hardware"],
            "tradeOffs": "Ollama great for local DX; vLLM targets high-throughput serving.",
            "complexity": "vLLM higher.",
            "lockIn": "Serving APIs differ.",
            "security": "Both need API auth when exposed.",
            "cost": "GPU sizing dominates.",
            "exampleScenarios": ["Laptop learning → Ollama", "Team GPU box API → vLLM"],
            "references": ["OLLAMA-DOCS", "VLLM-DOCS"],
            "lastVerified": DATE,
        },
        {
            "id": "mcp-vs-custom",
            "title": "MCP vs custom integrations",
            "problem": "Standardize tool access vs bespoke adapters.",
            "criteria": ["Ecosystem reuse", "Security review surface", "Protocol fit"],
            "tradeOffs": "MCP standardizes; custom may be thinner for one integration.",
            "complexity": "MCP adds protocol concepts.",
            "lockIn": "Protocol versions (verify current MCP spec).",
            "security": "Tool permission model critical either way.",
            "cost": "Engineering vs shared servers.",
            "exampleScenarios": ["Many IDE tools → MCP", "One internal HTTP tool → custom may suffice"],
            "references": ["MCP-SPEC-2026-07-28", "CURSOR-DOCS-MCP"],
            "lastVerified": DATE,
        },
        {
            "id": "cursor-vs-other-agents",
            "title": "Cursor vs other coding agents by use case",
            "problem": "Choosing an AI coding environment for repo work.",
            "criteria": ["Repo context", "Rules/skills", "MCP", "Team workflow"],
            "tradeOffs": "Cursor emphasizes Agent + rules/skills/MCP; others optimize IDE completion or CLI loops.",
            "complexity": "All require human verification.",
            "lockIn": "Editor/subscription ecosystems.",
            "security": "Permissions and MCP least privilege.",
            "cost": "Subscriptions + model usage.",
            "exampleScenarios": ["Unfamiliar repo change with rules → Cursor", "Inline completion in JetBrains → Copilot-like tools"],
            "references": ["CURSOR-DOCS-RULES", "CURSOR-DOCS-SKILLS", "CURSOR-DOCS-MCP"],
            "lastVerified": DATE,
        },
    ]
    write_json(ROOT / "src/data/ai/decision-guides.json", decisions)

    # Additional topics
    topics = [
        (
            "AI-FUNDAMENTALS-OVERVIEW",
            "AI vs ML vs Deep Learning vs Generative AI",
            "AI, ML, Deep Learning এবং Generative AI",
            "Clarify overlapping terms so you pick the right learning path.",
            "সঠিক লার্নিং পথ বেছে নিতে পরিভাষা পরিষ্কার করুন।",
            "fundamentals",
            "beginner",
            35,
            [],
            ["AI-LLM-FUNDAMENTALS"],
            ["fundamentals", "ml"],
            ["OPENAI-API-DOCS", "OWASP-LLM-TOP10-2025"],
            """
<Callout type="mental-model">
AI is the broad goal; ML learns from data; deep learning uses neural nets; generative AI samples new content (text, images, etc.).
</Callout>

## Distinctions that matter at work

- **Classical ML** — tabular prediction, ranking, anomaly detection with explicit features.
- **Deep learning** — representation learning for vision/speech/text.
- **LLMs / generative AI** — sequence models producing tokens/media; need grounding and verification.

## Skill graph note

Do not jump to LangChain before you can explain tokens, evaluation, and failure modes.
""",
        ),
        (
            "AI-EMBEDDINGS",
            "Embeddings and semantic similarity",
            "Embeddings এবং semantic similarity",
            "Vector representations for search, clustering, and RAG retrieval.",
            "Search, clustering এবং RAG retrieval-এর জন্য vector representation।",
            "retrieval",
            "intermediate",
            40,
            ["AI-LLM-FUNDAMENTALS"],
            ["AI-VECTOR-DATABASES", "AI-RAG-FUNDAMENTALS"],
            ["embeddings", "rag"],
            ["OPENAI-API-DOCS", "PGVECTOR-DOCS"],
            """
## Mental model

Embeddings map text (or other modalities) into vectors so similar meanings are nearby. Similarity search is not the same as factual correctness.

## Practice

- Normalize chunking strategy before blaming the vector DB.
- Evaluate retrieval separately from generation (hit rate / recall@k).
""",
        ),
        (
            "AI-VECTOR-DATABASES",
            "Vector databases and pgvector",
            "Vector databases এবং pgvector",
            "When to keep vectors in Postgres versus a dedicated ANN store.",
            "Postgres-এ vector রাখা বনাম dedicated ANN store।",
            "retrieval",
            "intermediate",
            40,
            ["AI-EMBEDDINGS"],
            ["AI-RAG-FUNDAMENTALS"],
            ["pgvector", "vector-db"],
            ["PGVECTOR-DOCS", "QDRANT-DOCS", "PINECONE-DOCS"],
            """
## Decision sketch

Start with **pgvector** if you already operate PostgreSQL and need joins + tenancy filters. Move to dedicated engines when ANN scale/ops demands it—see decision guides.
""",
        ),
        (
            "AI-FRAMEWORKS-LANDSCAPE",
            "AI framework landscape",
            "AI framework landscape",
            "Problem → tool map across SDKs, LangChain, LangGraph, LlamaIndex, and Vercel AI SDK.",
            "SDK, LangChain, LangGraph, LlamaIndex, Vercel AI SDK—সমস্যা → টুল মানচিত্র।",
            "frameworks",
            "intermediate",
            45,
            ["AI-LLM-FUNDAMENTALS"],
            ["AI-RAG-FUNDAMENTALS", "AI-AGENTS-OVERVIEW"],
            ["frameworks"],
            ["LANGCHAIN-DOCS", "LANGGRAPH-DOCS", "LLAMAINDEX-DOCS", "VERCEL-AI-SDK-DOCS"],
            """
<Callout type="warning">
Frameworks are optional accelerators. Direct provider SDKs are enough for many production features.
</Callout>

See `/ai/decisions` for structured comparisons.
""",
        ),
        (
            "AI-FINE-TUNING-BASICS",
            "Fine-tuning / LoRA / PEFT basics",
            "Fine-tuning / LoRA / PEFT basics",
            "When adapters help—and when RAG + schemas are safer.",
            "কখন adapter কাজে লাগে—এবং কখন RAG + schema নিরাপদ।",
            "training",
            "advanced",
            45,
            ["AI-OPEN-MODELS"],
            ["AI-EVALUATION-BASICS"],
            ["lora", "peft"],
            ["HF-PEFT-DOCS", "OWASP-LLM-TOP10-2025"],
            """
Fine-tuning does not magically add private facts without data. Prefer RAG for changing knowledge; use PEFT when you need behavioral specialization with eval gates.
""",
        ),
        (
            "AI-MODEL-SERVING",
            "Model serving (Ollama vs vLLM)",
            "Model serving (Ollama vs vLLM)",
            "Serve open models locally for learning or with throughput-oriented engines.",
            "শেখার জন্য locally বা throughput-oriented engine দিয়ে open model serve।",
            "serving",
            "advanced",
            40,
            ["AI-OPEN-MODELS"],
            ["AI-EVALUATION-BASICS"],
            ["vllm", "ollama"],
            ["OLLAMA-DOCS", "VLLM-DOCS"],
            """
Ollama optimizes local DX. vLLM targets higher-throughput self-hosted APIs. Always put auth and quotas in front of any exposed endpoint.
""",
        ),
        (
            "AI-LLMOPS",
            "Observability / LLMOps",
            "Observability / LLMOps",
            "Traces, datasets, cost/latency metrics, and regression evals for AI features.",
            "AI ফিচারের জন্য trace, dataset, cost/latency এবং regression eval।",
            "ops",
            "advanced",
            40,
            ["AI-EVALUATION-BASICS"],
            ["AI-SECURITY-OWASP"],
            ["llmops", "tracing"],
            ["LANGSMITH-DOCS", "MLFLOW-DOCS", "OWASP-LLM-TOP10-2025"],
            """
Log prompts carefully (PII!). Track groundedness/eval scores alongside latency and spend. Unbounded retries are a security and cost issue.
""",
        ),
        (
            "AI-COST-LATENCY",
            "Cost and performance for AI features",
            "AI ফিচারের cost এবং performance",
            "Token budgets, caching, and latency budgets as first-class product constraints.",
            "Token budget, caching এবং latency—প্রোডাক্ট কনস্ট্রেইন্ট।",
            "ops",
            "intermediate",
            30,
            ["AI-LLM-FUNDAMENTALS"],
            ["AI-LLMOPS"],
            ["cost", "latency"],
            ["OPENAI-API-DOCS", "OWASP-LLM-TOP10-2025"],
            """
Measure p95 latency and cost per successful task. Cache embeddings/retrieval. Cap agent steps (OWASP unbounded consumption).
""",
        ),
        (
            "AI-PRODUCT-UX",
            "AI product UX",
            "AI product UX",
            "Streaming, citations, uncertainty, and human control in AI UIs.",
            "AI UI-তে streaming, citation, uncertainty এবং human control।",
            "product",
            "intermediate",
            30,
            ["AI-PROMPT-ENGINEERING"],
            ["AI-SECURITY-OWASP"],
            ["ux", "product"],
            ["OWASP-LLM-TOP10-2025", "VERCEL-AI-SDK-DOCS"],
            """
Show sources, allow edit/override, and never hide that output can be wrong. Loading and partial streaming states matter.
""",
        ),
        (
            "AI-CURSOR-SAFE-LAB",
            "Lab: Safely change an unfamiliar repository using Cursor",
            "Lab: Cursor দিয়ে অপরিচিত repository নিরাপদে পরিবর্তন",
            "Guided 11-step workflow from inspect to semantic commit.",
            "inspect থেকে semantic commit পর্যন্ত ১১ ধাপের guided workflow।",
            "coding-agents",
            "intermediate",
            60,
            ["AI-CODING-AGENTS-CURSOR"],
            ["AI-PROMPT-ENGINEERING", "AI-SECURITY-OWASP"],
            ["cursor", "lab"],
            ["CURSOR-DOCS-RULES", "CURSOR-DOCS-SKILLS", "CURSOR-DOCS-MCP", "OWASP-LLM-TOP10-2025"],
            """
## Required workflow

1. Inspect repository structure and manifests.
2. Map architecture and trust boundaries.
3. Define requirement + non-goals.
4. Create a plan (no code yet).
5. Implement one small slice.
6. Run tests/lint/typecheck yourself.
7. Review the diff for scope and invented deps.
8. Security/edge-case check (authz, injection, secrets).
9. Manual acceptance test.
10. Semantic commit with evidence.
11. Retrospective: what the agent got wrong.

Pair with project **PBL-AI-B-002** and the verify playbook at `/ai/verify`.
""",
        ),
        (
            "AI-ASSISTED-FRONTEND",
            "Using AI safely in Frontend",
            "Frontend-এ নিরাপদে AI ব্যবহার",
            "Components, Figma/screenshot implementation, a11y, tests, perf, security.",
            "Component, Figma/screenshot, a11y, test, perf, security।",
            "cross-track",
            "intermediate",
            35,
            ["AI-CODING-AGENTS-CURSOR"],
            ["AI-PROMPT-ENGINEERING"],
            ["frontend", "ai"],
            ["CURSOR-DOCS-RULES", "OWASP-LLM-TOP10-2025"],
            """
## Workflows

- Generate components against **existing** design-system primitives.
- Implement from screenshot/Figma with token constraints.
- Always run a11y checks; prefer semantic HTML.
- Add regression tests for interactions.
- Review for XSS from markdown/HTML model output.
""",
            "frontend",
        ),
        (
            "AI-ASSISTED-BACKEND",
            "Using AI safely in Backend",
            "Backend-এ নিরাপদে AI ব্যবহার",
            "API design, auth review, SQL, concurrency, tests, observability.",
            "API design, auth, SQL, concurrency, test, observability।",
            "cross-track",
            "intermediate",
            35,
            ["AI-CODING-AGENTS-CURSOR"],
            ["AI-SECURITY-OWASP"],
            ["backend", "ai"],
            ["OWASP-LLM-TOP10-2025", "OPENAI-API-DOCS"],
            """
## Workflows

- Design contracts before codegen.
- Force authn/z review on every endpoint suggestion.
- Treat SQL as hostile until parameterized.
- Demand concurrency/idempotency notes for payments/jobs.
- Require metrics/logging for new paths.
""",
            "backend",
        ),
        (
            "AI-ASSISTED-FLUTTER",
            "Using AI safely in Flutter",
            "Flutter-এ নিরাপদে AI ব্যবহার",
            "Widgets/layout, state, Android/iOS config, build debugging, tests.",
            "Widget/layout, state, Android/iOS config, build debug, test।",
            "cross-track",
            "intermediate",
            35,
            ["AI-CODING-AGENTS-CURSOR"],
            ["AI-PROMPT-ENGINEERING"],
            ["flutter", "ai"],
            ["CURSOR-DOCS-RULES", "OWASP-LLM-TOP10-2025"],
            """
## Workflows

- Prefer existing state patterns over inventing new architectures.
- Verify platform channel / permission changes carefully.
- Paste real build logs for triage; reject invented Flutter APIs.
- Add widget/integration tests for critical flows.
""",
            "mobile-flutter",
        ),
        (
            "AI-ASSISTED-FULLSTACK",
            "Using AI safely in Fullstack",
            "Fullstack-এ নিরাপদে AI ব্যবহার",
            "Contracts, E2E, migrations, deployment, integration boundaries.",
            "Contract, E2E, migration, deployment, integration।",
            "cross-track",
            "intermediate",
            35,
            ["AI-CODING-AGENTS-CURSOR"],
            ["AI-ASSISTED-FRONTEND", "AI-ASSISTED-BACKEND"],
            ["fullstack", "ai"],
            ["OWASP-LLM-TOP10-2025"],
            """
Keep FE/BE contracts explicit. Generate E2E only for stable journeys. Migrations need rollback notes. Never let the agent “also redeploy prod.”
""",
            "fullstack",
        ),
        (
            "AI-ASSISTED-DEVOPS",
            "Using AI safely in DevOps",
            "DevOps-এ নিরাপদে AI ব্যবহার",
            "IaC, Helm/YAML, CI, incidents, dangerous command verification.",
            "IaC, Helm/YAML, CI, incident, dangerous command verification।",
            "cross-track",
            "advanced",
            40,
            ["AI-CODING-AGENTS-CURSOR"],
            ["AI-SECURITY-OWASP"],
            ["devops", "ai"],
            ["OWASP-LLM-TOP10-2025", "CURSOR-DOCS-MCP"],
            """
## Hard rules

- Never run unverified destructive commands.
- Pin actions/images; require plan before apply.
- Incident analysis must separate facts vs hypotheses.
- MCP servers that can mutate infra need least privilege.
""",
            "devops",
        ),
        (
            "AI-ASSISTED-DATABASE",
            "Using AI safely in Database engineering",
            "Database engineering-এ নিরাপদে AI",
            "SQL, EXPLAIN, indexes, migrations, backups, destructive-query safety.",
            "SQL, EXPLAIN, index, migration, backup, destructive-query safety।",
            "cross-track",
            "advanced",
            40,
            ["AI-CODING-AGENTS-CURSOR"],
            ["AI-SECURITY-OWASP"],
            ["database", "ai"],
            ["OWASP-LLM-TOP10-2025", "PGVECTOR-DOCS"],
            """
Refuse destructive SQL without expand/contract. Ground tuning in real EXPLAIN. For AI features, isolate tenant filters before vector search.
""",
            "database",
        ),
        (
            "AI-ASSISTED-QA",
            "Using AI safely in QA",
            "QA-এ নিরাপদে AI ব্যবহার",
            "Test design, automation, failure reproduction, reviewing generated tests.",
            "Test design, automation, failure reproduction, generated test review।",
            "cross-track",
            "intermediate",
            35,
            ["AI-CODING-AGENTS-CURSOR"],
            ["AI-PROMPT-ENGINEERING"],
            ["qa", "ai"],
            ["OWASP-LLM-TOP10-2025"],
            """
AI can draft cases; humans own risk priority. Reject tests that pass for the wrong reason. Prefer outcome assertions over brittle selectors.
""",
            "qa",
        ),
        (
            "AI-ASSISTED-UIUX",
            "Using AI safely in UI/UX",
            "UI/UX-এ নিরাপদে AI ব্যবহার",
            "Research-plan assistance, synthesis structure, UX writing, a11y, design-system docs.",
            "Research-plan, synthesis, UX writing, a11y, design-system docs।",
            "cross-track",
            "intermediate",
            35,
            ["AI-PROMPT-ENGINEERING"],
            ["AI-PRODUCT-UX"],
            ["uiux", "ai"],
            ["OWASP-LLM-TOP10-2025"],
            """
<Callout type="warning">
Never fabricate user research quotes, usability findings, or stakeholder approvals.
</Callout>

Use AI to structure plans and critiques; you run real research.
""",
            "uiux",
        ),
        (
            "AI-ASSISTED-PM",
            "Using AI safely in Project Management",
            "Project Management-এ নিরাপদে AI",
            "Requirements, risks, stories, status drafts, scenario analysis—without fake outcomes.",
            "Requirement, risk, story, status draft—নাটকীয় outcome ছাড়া।",
            "cross-track",
            "intermediate",
            35,
            ["AI-PROMPT-ENGINEERING"],
            ["AI-SECURITY-OWASP"],
            ["pm", "ai"],
            ["OWASP-LLM-TOP10-2025"],
            """
<Callout type="warning">
Never fabricate stakeholder approval, estimate evidence, or project outcomes.
</Callout>

AI drafts; humans own commitments.
""",
            "project-management",
        ),
        (
            "AI-RESEARCH-GOVERNANCE",
            "AI research governance and freshness",
            "AI research governance এবং freshness",
            "How this site keeps educational AI content static, cited, and dated.",
            "শিক্ষামূলক AI কন্টেন্ট কীভাবে static, cited এবং dated রাখা হয়।",
            "governance",
            "beginner",
            25,
            [],
            ["AI-FUNDAMENTALS-OVERVIEW"],
            ["governance", "sources"],
            ["OWASP-LLM-TOP10-2025", "MCP-SPEC-2026-07-28", "CURSOR-DOCS-RULES"],
            """
This website does **not** call model APIs at runtime for lessons. Content is Git-reviewed. Prefer official docs; record `lastVerified`. Job-market notes use “Observed in Bangladesh job listings reviewed…” wording—not universal claims.
""",
        ),
    ]

    for spec in topics:
        if len(spec) == 13:
            tid, title, title_bn, desc, desc_bn, cat, diff, mins, prereq, related, tags, sources, body = spec
            track = "ai-framework"
        else:
            tid, title, title_bn, desc, desc_bn, cat, diff, mins, prereq, related, tags, sources, body, track = spec
        slug = tid.lower().replace("_", "-")
        # keep files under ai-framework folder for curriculum simplicity; cross-track topics still set track field
        folder = ROOT / "src/content/topics" / ("ai-framework" if track == "ai-framework" else track)
        # For cross-track assisted topics, put under each track folder
        if track != "ai-framework":
            folder = ROOT / "src/content/topics" / track
        path = folder / f"{slug}.mdx"
        path.parent.mkdir(parents=True, exist_ok=True)
        # Fix Callout import depth for non-ai-framework tracks (topics/<track>/file.mdx is same depth)
        content = topic_mdx(
            tid=tid,
            title=title,
            title_bn=title_bn,
            description=desc,
            description_bn=desc_bn,
            category=cat,
            difficulty=diff,
            minutes=mins,
            prerequisites=prereq,
            related=related,
            tags=tags,
            sources=sources,
            body=body.strip(),
            track=track,
        )
        path.write_text(content, encoding="utf-8")

    # Interview bank (canonical, moderate size, high signal)
    questions = []
    beginner = [
        ("AI vs ML vs generative AI", "Definition", "What is the difference between AI, ML, and generative AI in practical engineering terms?"),
        ("tokens", "Fundamentals", "What is a token, and why do cost and context limits usually track tokens rather than characters?"),
        ("context window", "Fundamentals", "What happens when a prompt exceeds the model context window, and how should systems handle it?"),
        ("hallucination", "Failure modes", "Why can an LLM sound confident while being wrong, and what product controls reduce harm?"),
        ("temperature", "Fundamentals", "How does temperature affect output variability for structured extraction tasks?"),
        ("prompt structure", "Prompting", "Why include GOAL, CONSTRAINTS, ACCEPTANCE, and VERIFICATION sections in engineering prompts?"),
        ("API keys", "Security", "Where should model API keys live in a web app, and why must they never ship in frontend bundles?"),
        ("structured outputs", "APIs", "What problem do schema-constrained structured outputs solve versus free-form chat text?"),
        ("coding agent evidence", "Verification", "An agent says tests passed. What evidence is required before you merge?"),
        ("RAG motivation", "RAG", "Why use retrieval-augmented generation instead of stuffing an entire corpus into the prompt?"),
    ]
    intermediate = [
        ("embeddings", "Retrieval", "What is an embedding, and why is nearest-neighbor search not sufficient for factual correctness?"),
        ("chunking", "RAG", "How does chunking strategy affect recall and citation quality in RAG?"),
        ("hybrid search", "RAG", "When would you combine keyword search with vector search?"),
        ("tool calling", "Tools", "How does tool/function calling differ from putting instructions only in natural language?"),
        ("MCP", "Protocols", "What problem does the Model Context Protocol address for tool integrations?"),
        ("eval datasets", "Evaluation", "How would you build a small offline evaluation set for a RAG assistant?"),
        ("prompt injection", "Security", "Explain direct vs indirect prompt injection with a concrete example."),
        ("pgvector choice", "Architecture", "When is pgvector a reasonable default versus a dedicated vector database?"),
        ("agent vs workflow", "Agents", "When should you prefer a deterministic workflow over an open-ended agent?"),
        ("cost controls", "Ops", "List practical controls against unbounded token consumption in production."),
        ("Cursor rules", "Coding agents", "How do AGENTS.md and `.cursor/rules` differ in Cursor’s current docs model?"),
        ("output handling", "Security", "Why is improper output handling dangerous when rendering model HTML or executing model SQL?"),
    ]
    advanced = [
        ("multi-tenant RAG", "System design", "Design tenant isolation for a multi-tenant RAG copilot and list failure tests."),
        ("agent failure", "Agents", "How do you detect and stop runaway tool-calling loops in a stateful agent?"),
        ("RAG quality", "Evaluation", "Which metrics would you track separately for retrieval quality vs answer groundedness?"),
        ("framework trade-off", "Architecture", "Compare adopting LangGraph versus an ordinary application workflow for an approval-gated ops agent."),
        ("supply chain", "Security", "How does OWASP LLM supply-chain risk show up when agents propose dependencies?"),
        ("fine-tune vs RAG", "Architecture", "Argue when LoRA/PEFT is justified versus improving retrieval and prompts."),
        ("observability", "LLMOps", "Design a tracing + eval regression gate for an AI feature release."),
        ("MCP permissions", "Security", "How would you threat-model an MCP server that can run shell commands?"),
        ("incident", "Production", "Provider latency spikes 10×. What graceful degradation options should a copilot expose?"),
        ("cross-tenant leak", "Security", "Describe a test that would catch cross-tenant vector retrieval leaks."),
        ("vLLM vs Ollama", "Serving", "When would you move from Ollama to vLLM for self-hosted inference?"),
        ("AI system design", "System design", "Design a citation-first internal knowledge assistant with evals, authz, and cost budgets."),
    ]

    def add(level: str, items: list[tuple[str, str, str]], prefix: str) -> None:
        for i, (topic, qtype, question) in enumerate(items, 1):
            qid = f"{prefix}-{i:04d}"
            short = "Ground answers in mechanisms, trade-offs, and verification—not vendor trivia."
            answer = (
                f"Explain {topic} with a precise mental model, a failure mode, and how you would verify behavior in a real system. "
                f"Prefer official docs and measurable checks over slogans."
            )
            questions.append(
                {
                    "id": qid,
                    "level": level,
                    "category": topic.title() if len(topic) < 40 else qtype,
                    "topic": topic,
                    "questionType": qtype,
                    "question": question,
                    "shortAnswer": short,
                    "answer": answer,
                    "example": "Prefer: cite official docs + a failing test/eval case that proves the claim.",
                    "integrationProcedure": "1) State the mechanism. 2) Give a concrete failure. 3) Describe verification (test, eval, EXPLAIN, or threat model).",
                }
            )

    add("Beginner", beginner, "AI-B")
    add("Intermediate", intermediate, "AI-I")
    add("Advanced", advanced, "AI-A")
    write_json(ROOT / "src/data/interviews/bank/ai-framework.json", questions)

    # Sources append
    sources_path = ROOT / "src/data/source-registry/sources.json"
    sources = json.loads(sources_path.read_text(encoding="utf-8"))
    existing = {s["id"] for s in sources}
    extra_sources = [
        ("VERCEL-AI-SDK-DOCS", "Vercel AI SDK Docs", "https://sdk.vercel.ai/docs", "Vercel", "official-docs"),
        ("GEMINI-API-DOCS", "Google Gemini API Docs", "https://ai.google.dev/gemini-api/docs", "Google", "official-docs"),
        ("PYTORCH-DOCS", "PyTorch Documentation", "https://pytorch.org/docs/", "PyTorch", "official-docs"),
        ("HF-TRANSFORMERS-DOCS", "Hugging Face Transformers Docs", "https://huggingface.co/docs/transformers", "Hugging Face", "official-docs"),
        ("HF-PEFT-DOCS", "Hugging Face PEFT Docs", "https://huggingface.co/docs/peft", "Hugging Face", "official-docs"),
        ("VLLM-DOCS", "vLLM Documentation", "https://docs.vllm.ai/", "vLLM", "official-docs"),
        ("PINECONE-DOCS", "Pinecone Documentation", "https://docs.pinecone.io/", "Pinecone", "official-docs"),
        ("WEAVIATE-DOCS", "Weaviate Documentation", "https://weaviate.io/developers/weaviate", "Weaviate", "official-docs"),
        ("QDRANT-DOCS", "Qdrant Documentation", "https://qdrant.tech/documentation/", "Qdrant", "official-docs"),
        ("CHROMA-DOCS", "Chroma Documentation", "https://docs.trychroma.com/", "Chroma", "official-docs"),
        ("FAISS-WIKI", "FAISS Wiki", "https://github.com/facebookresearch/faiss/wiki", "Facebook Research", "github"),
        ("LANGSMITH-DOCS", "LangSmith Documentation", "https://docs.smith.langchain.com/", "LangChain", "official-docs"),
        ("MLFLOW-DOCS", "MLflow Documentation", "https://mlflow.org/docs/latest/index.html", "MLflow", "official-docs"),
        ("FASTAPI-DOCS", "FastAPI Documentation", "https://fastapi.tiangolo.com/", "FastAPI", "official-docs"),
        ("GITHUB-COPILOT-DOCS", "GitHub Copilot Documentation", "https://docs.github.com/en/copilot", "GitHub", "official-docs"),
        ("CURSOR-DOCS-AGENT", "Cursor Docs — Agent", "https://cursor.com/docs/agent/overview", "Cursor", "official-docs"),
    ]
    for sid, title, url, publisher, stype in extra_sources:
        if sid not in existing:
            sources.append(
                {
                    "id": sid,
                    "title": title,
                    "url": url,
                    "publisher": publisher,
                    "sourceType": stype,
                    "accessedDate": DATE,
                    "authorityTier": "S1",
                }
            )
    write_json(sources_path, sources)

    print(
        f"Wrote tools={len(TOOLS)} recipes={len(RECIPES)+2} issues={len(ISSUES)} "
        f"topics={len(topics)} interviews={len(questions)} decisions={len(decisions)}"
    )


if __name__ == "__main__":
    main()
